### ISSUE TITLE
Small issues with FileChooser of Freeform fin 'Export shape to CSV'

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1020]
When trying to export the fin shape of a Freeform fin to CSV by going into the Freeform editor into the 'Shape' tab and clicking 'Export CSV', the JFileChooser has some beauty mistakes that should be resolved:

- the startup directory is just the home directory of your computer. In other JFileChoosers in OR (e.g. when saving your design), OR checks what the last used directory was and sets that as the startup directory for the JFileChooser
- the file format is just 'All Files'; also when you have saved the file, you have no file format. It should have 'Comma Separated Files (*.csv)' as file format, just as with exporting simulation data to CSV

**Comment by hcraigmiller** [comment]
Anomaly found. 

Although, when imported into a spreadsheet, the data is correct and correctly displayed, **the saved file does not have the .csv extension**. It should have _Comma Separated Files_ (*.csv) as file format.

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]
