### ISSUE TITLE
Integrate scaling with edit window

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1045]
At present, the scale function is accessed through through a dropdown from the "Edit" menu button.  It would make more sense for it to be an option in the Edit popup window.

**Comment by SiboVG** [comment]
@JoePfeiffer do you still want this issue to be open, now that scaling is more accessible through the context menu?

**Comment by JoePfeiffer** [comment]
Looks good.  Hmmm, the context menu is now so complete there's a temptation to move the "move up" and "move down" buttons into it and get rid of the column of buttons between the component tree and the "add new component" frame....
