### ISSUE TITLE
Feature Request: Calculate Force Differential between stages (Drag Separation Force)

### ISSUE THREAD

**Issue by andrewrbrown** [openrocket/openrocket#1048]
This may already exist through a script, but I can't figure it out.  It would be very nice if OpenRocket can calculate the force between stages, say a sustainer and an upper payload or nosecone, to determine if drag separation is an issue.

**Comment by JoePfeiffer** [comment]
This has been suggested again as #1225; there's been more discussion on that incarnation so I'm closing this one.
