### ISSUE TITLE
No warning when saving rocket with OR-only features in Rocksim format

### ISSUE THREAD

**Issue by soupwizard** [openrocket/openrocket#105]
From a comment on the Rocketry Forum: user saved rocket but after reopening, the following was noticed:
1. Have to open up Stage and un-check the Override Center of Gravity each time after opening rocket file again.
2. Add a mass component to the tube coupler (haven't found this problem anywhere else), then save and close the file, it omits this mass when file is re-opened. 
3. OR doesn't save "Deploys at" for either the payload parachute or the booster chute when file is saved and reopened. 

These (and possibly others) are caused by using .ork format file features but saving in .rkt Rocksim format.

Possible Fix: popup warning dialog when saving in Rocksim format when using OR only features (or maybe always, warning that "there may be features not saved").

Link to original comment on TRF: http://www.rocketryforum.com/showthread.php?55333-OpenRocket-Problems

**Comment by neilweinstock** [comment]
This has been fixed for a long time, closing.
