### ISSUE TITLE
Add explicit support for JL Chute Release

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1053]
The JLCR is very popular and widely used, but you have to jump through some non-obvious hoops to model it correctly in OR: https://www.rocketryforum.com/threads/help-with-open-rocket.169117/post-2196377

It would be very very nice indeed if there were explicit support for the JLCR.  This would also support cable cutters I would guess, so it's not necessarily specific to the JLCR (although even if it were, it would still be worth it).

I don't yet have an idea exactly what this would look like, just wanted to log the request.

**Comment by JoePfeiffer** [comment]
Superseded by #1864
