### ISSUE TITLE
Bug: Clicking Rocket Optimization with no components causes exception

### ISSUE THREAD

**Issue by WardBenjamin** [openrocket/openrocket#1058]
---------- Bug report ----------

I was exploring the software and clocked "Rocket Optimization" under the Tools menu, with no components added to the rocket.

---------- Exception stack trace ----------
java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.populateSimulations(GeneralOptimizationDialog.java:923)
	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.<init>(GeneralOptimizationDialog.java:364)
	at net.sf.openrocket.gui.main.BasicFrame$20.actionPerformed(BasicFrame.java:719)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------- Thread information ----------
Thread[AWT-EventQueue-0,6,main]

---------- System information ----------
OpenRocket version: 20-11-alpha-16
OpenRocket source: default
OpenRocket location: C:\Users\blward\Workspace\PRJ\OpenRocket\swing\build\jar\.\OpenRocket.jar
JOGL version: 2.4.0-rc-20200306
Current default locale: en_US
System properties:
  awt.toolkit=sun.awt.windows.WToolkit
  file.encoding=Cp1252
  file.separator=\
  java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
  java.awt.printerjob=sun.awt.windows.WPrinterJob
  java.class.path=.\OpenRocket.jar
  java.class.version=55.0
  java.home=C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot
  java.io.tmpdir=C:\Users\blward\AppData\Local\Temp\
  java.library.path=C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Python38\Scripts\;C:\Program Files\Python38\;C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Python37-32\Scripts\;C:\Program Files (x86)\Python37-32\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MATLAB\R2018b\runtime\win64;C:\Program Files\MATLAB\R2018b\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Calibre2\;C:\Users\Public\frc2019\roborio\bin;C:\Users\Public\frc2019\frccode;C:\Users\Public\wpilib\2020\roborio\bin;C:\Users\Public\wpilib\2020\frccode;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\blward\AppData\Local\Microsoft\WindowsApps;C:\Users\blward\.dotnet\tools;C:\Users\Public\frc2019\roborio\bin;C:\Users\Public\frc2019\frccode;C:\Users\Public\wpilib\2020\roborio\bin;C:\Users\Public\wpilib\2020\frccode;C:\Users\blward\.dotnet\tools;C:\Users\blward\AppData\Local\Microsoft\WindowsApps;C:\Users\blward\AppData\Roaming\npm;.
  java.runtime.name=OpenJDK Runtime Environment
  java.runtime.version=11.0.5+10
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=11
  java.util.Arrays.useLegacyMergeSort=true
  java.vendor=AdoptOpenJDK
  java.vendor.url=https://adoptopenjdk.net/
  java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-build/issues
  java.vendor.version=AdoptOpenJDK
  java.version=11.0.5
  java.version.date=2019-10-15
  java.vm.compressedOopsMode=Zero based
  java.vm.info=mixed mode
  java.vm.name=OpenJDK 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=11
  java.vm.vendor=AdoptOpenJDK
  java.vm.version=11.0.5+10
  jdk.debug=release
  jnlp.jogamp.tmp.cache.root=jln6403214582748230701
  line.separator=\u000d\u000a
  os.arch=amd64
  os.name=Windows 10
  os.version=10.0
  path.separator=;
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.library.path=C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin
  sun.cpu.endian=little
  sun.cpu.isalist=amd64
  sun.desktop=windows
  sun.io.unicode.encoding=UnicodeLittle
  sun.java.command=.\OpenRocket.jar
  sun.java.launcher=SUN_STANDARD
  sun.jnu.encoding=Cp1252
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=
  sun.stderr.encoding=cp437
  sun.stdout.encoding=cp437
  user.country=US
  user.dir=C:\Users\blward\Workspace\PRJ\OpenRocket\swing\build\jar
  user.home=C:\Users\blward
  user.language=en
  user.name=blward
  user.script=
  user.timezone=America/New_York
  user.variant=
---------- Error log ----------
   1      0.003 INFO   (SwingStartup.java:61) Starting up OpenRocket version 20-11-alpha-16
   2      0.003 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0.005 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0.196 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0.319 INFO   (SwingStartup.java:133) Registering exception handler
   6      0.326 INFO   (SwingStartup.java:139) Loading databases
   7      1.531 INFO   (TranslatorProvider.java:49) Using default locale en_US
   8      1.555 INFO   (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
   9      1.557 INFO   (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
  10      1.557 INFO   (MotorDatabaseLoader.java:87) Starting reading serialized motor database
  11      1.561 INFO   (SwingStartup.java:155) Update check disabled
  12      1.561 INFO   (SwingStartup.java:160) Setting best LAF
  13      1.562 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  14      1.562 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  15      1.585 DEBUG  (MotorDatabaseLoader.java:105) Reading motors from file datafiles/thrustcurves/thrustcurves.ser
  16      1.805 INFO   (SwingStartup.java:172) Opening main application window
  17      1.823 INFO   (BasicFrame.java:1576) New action initiated
  19      1.874 DEBUG  (BasicFrame.java:173) Instantiating new BasicFrame
  20      1.898 DEBUG  (ComponentPresetDatabaseLoader.java:59) Time to load presets: 341ms 1622 loaded from 1 files
  21      1.938 INFO   (MotorDatabaseLoader.java:93) Ending reading serialized motor database, motorCount=1870
  22      1.942 INFO   (MotorDatabaseLoader.java:68) Starting reading user-defined motors
  23      1.944 INFO   (MotorDatabaseLoader.java:78) Ending reading user-defined motors, motorCount=1870
  25      2.001 DEBUG  (Icons.java:24) Starting to load icons
  26      2.051 DEBUG  (Icons.java:94) Icons loaded
  28      2.053 DEBUG  (BasicFrame.java:196) Constructing the BasicFrame UI
  35      0.000 VBOSE  (-) ===== 9 VBOSE lines removed =====
  35      2.825 VBOSE  (DoubleModel.java:897) DoubleModel[MotorRowFilter:MaximumLength] adding listener (total 2): net.sf.openrocket.gui.dialogs.motor.thrustcurve.MotorFilterPanel$11@160e22
  36      2.907 VBOSE  (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
  37      3.219 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@659b192a, current number of listeners is 7
  38      3.239 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@3510ed94, current number of listeners is 8
  39      3.244 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.RecoveryConfigurationPanel$$Lambda$158/0x00000008003e9440@59c3ac16, current number of listeners is 9
  40      3.256 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$3@11856498, current number of listeners is 10
  41      3.309 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  42      3.347 DEBUG  (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
  43      3.347 DEBUG  (RocketFigure3d.java:142) Setting up GL capabilities...
  44      3.347 VBOSE  (RocketFigure3d.java:144) GL - Getting Default Profile
  45      4.525 VBOSE  (RocketFigure3d.java:147) GL - creating GLCapabilities
  46      4.526 VBOSE  (RocketFigure3d.java:151) GL - setSampleBuffers
  47      4.526 VBOSE  (RocketFigure3d.java:154) GL - setNumSamples
  48      4.526 VBOSE  (RocketFigure3d.java:164) GL - Creating GLCanvas
  49      4.533 VBOSE  (RocketFigure3d.java:168) GL - Registering as GLEventListener on canvas
  50      4.534 VBOSE  (RocketFigure3d.java:171) GL - Adding canvas to this JPanel
  51      4.534 VBOSE  (RocketFigure3d.java:174) GL - Setting up mouse listeners
  52      4.534 VBOSE  (RocketFigure3d.java:177) GL - Rasterizing Carets
  53      4.562 VBOSE  (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@2dc57d20
  54      4.591 VBOSE  (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
  55      4.591 VBOSE  (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
  56      4.591 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  57      4.592 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  58      4.592 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  59      4.593 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  60      4.593 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  61      4.594 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  62      4.594 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@563aa472, current number of listeners is 11
  63      4.610 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@329064e, current number of listeners is 12
  64      4.613 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@1c7b7aae, current number of listeners is 13
  65      4.639 VBOSE  (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
  66      4.642 VBOSE  (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@13f8696e
  67      4.643 VBOSE  (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@674eaa
  68      4.643 VBOSE  (DoubleModel.java:919) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@674eaa
  69      4.643 VBOSE  (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@5004f4d1
  70      5.160 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  71      5.161 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@367cacb5, current number of listeners is 14
  72      5.161 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@480d5fdf, current number of listeners is 15
  73      5.180 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  74      5.194 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  75      5.194 DEBUG  (ExampleDesignFile.java:118) Current jar file is: C:\Users\blward\Workspace\PRJ\OpenRocket\swing\build\jar\.\OpenRocket.jar
  76      5.203 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@7eb7a8b2, current number of listeners is 16
  77      5.211 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@62d83926, current number of listeners is 17
  78      5.342 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
  79      5.344 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  80      5.349 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  81      5.350 DEBUG  (BasicFrame.java:276) ... Setting Initial Selection: [Rocket, Sustainer]
  82      5.350 DEBUG  (BasicFrame.java:280) BasicFrame instantiation complete
  83      5.376 INFO   (SwingStartup.java:194) Checking update status
  84      5.376 INFO   (SwingStartup.java:83) Startup complete
  85      5.511 DEBUG  (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1382,height=777]
  86      5.515 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  87      5.516 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  88      5.530 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  89      5.530 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  90      5.532 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  91      5.533 VBOSE  (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.258657 user scale, 1222.00 overall scale
  92    310.923 USER   (BasicFrame.java:718) Rocket optimization selected
  93    310.930 VBOSE  (Rocket.java:439) Added ComponentChangeListener net.sf.openrocket.document.OpenRocketDocument@384c86ec, current number of listeners is 1
  94    310.966 VBOSE  (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 1): javax.swing.JSpinner$ModelListener@2a375cb4
  95    310.999 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[AWT-EventQueue-0,6,main]
   > java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
   > 	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
   > 	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.populateSimulations(GeneralOptimizationDialog.java:923)
   > 	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.<init>(GeneralOptimizationDialog.java:364)
   > 	at net.sf.openrocket.gui.main.BasicFrame$20.actionPerformed(BasicFrame.java:719)
   > 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
   > 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
   > 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
   > 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
   > 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
   > 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
   > 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
   > 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
   > 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
   > 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
   > 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
   > 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
   > 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
   > 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
   > 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
   > 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
   > 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
   > 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
   > 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
   > 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
   > 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
   > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
   > 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
   > 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
   > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
   > 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   > 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
  96    311.000 STDERR (SwingExceptionHandler.java:49) java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
  97    311.000 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
  98    311.000 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.populateSimulations(GeneralOptimizationDialog.java:923)
  99    311.000 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.gui.dialogs.optimization.GeneralOptimizationDialog.<init>(GeneralOptimizationDialog.java:364)
 100    311.000 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.gui.main.BasicFrame$20.actionPerformed(BasicFrame.java:719)
 101    311.000 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
 102    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
 103    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
 104    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
 105    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
 106    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
 107    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
 108    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
 109    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
 110    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
 111    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
 112    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
 113    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
 114    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
 115    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
 116    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
 117    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
 118    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
 119    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
 120    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
 121    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
 122    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
 123    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
 124    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.AccessController.doPrivileged(Native Method)
 125    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 126    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
 127    311.001 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
 128    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
 129    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.AccessController.doPrivileged(Native Method)
 130    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 131    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
 132    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
 133    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
 134    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
 135    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
 136    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 137    311.002 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 138    311.002 INFO   (SwingExceptionHandler.java:61) Exception handler running on EDT, showing dialog
 139    311.002 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 140    317.168 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 141    317.171 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by SiboVG** [comment]
Thanks for the bug report! #1059 should fix this issue. The problem is that the optimizer optimizes a simulation. When the document does not have any simulations created yet, it would throw an Exception. #1059 adds a check for the no-simulations situation.
