### ISSUE TITLE
Rocksim Subassemblies are not supported in OpenRocket, No warning on import

### ISSUE THREAD

**Issue by soupwizard** [openrocket/openrocket#106]
Rocksim Subassemblies are not supported in OpenRocket, with no warning given when a rocksim file containing those is opened in OpenRocket - those features will be silently dropped from the model.

Rocksim file showing problem (bottom half of rocket is lost on import) http://www.rocketreviews.com/wildman-rocketry-wildman-rocket-dual-deploy-7143.html

Possible fix: either warn on open, or add support for subassemblies.

Original Report:
http://www.rocketryforum.com/showthread.php?55541-TWO-OpenRocket-Questions

**Comment by teyrana** [comment]
We have an appropriate component that sounds like it corresponds:
https://github.com/openrocket/openrocket/blob/master/core/src/net/sf/openrocket/rocketcomponent/ComponentAssembly.java

**Comment by SiboVG** [comment]
[SubAssemblyHandler.java](https://github.com/openrocket/openrocket/blob/unstable/core/src/net/sf/openrocket/file/rocksim/importt/SubAssemblyHandler.java) is the file that should be responsible for handling RockSim SubAssemblies. However, it seems like there are still some issues with it, so I think that file and implementations of it should be checked.
