### ISSUE TITLE
"favorite" preset components dropdown doesn't update until edit window is reopened.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1076]
To duplidate:
1) Select a component to edit, and open the edit window
2) Open the dropdown in the upper right corner. Observe the selected presets
3) Select "From database..." to open the component preset chooser dialog
4) Change the set of selected components, either adding or deleting, or both
5) Click "OK" to close the dialog, and open the dropdown again. Observe that the selected presets is unchanged
6) Close and reopen the edit window.  When the dropdown is reopened, the changes have taken place.

**Comment by hcraigmiller** [comment]
I am unable to reproduce this problem using _A simple model rocket_. If I change the nose cone to one from the database, the _Select preset_ window immediately changes to the part number of the database component when the _Okay_ button in pushed.

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by JoePfeiffer** [comment]
Here's what I'm seeing.

First photo, dropdown is open and I'm about to select "From database..."
![photo--1](https://user-images.githubusercontent.com/3065196/151008634-738ec444-3cfa-42ca-aecb-6ab31380a6de.png)

Second photo, I'm in the component preset choose dialog.  I've sorted by the first column, deselected, the BNC-20B, and selected the BNC20L (BNC-20B doesn't appear in the image due to sorting).
![photo-2](https://user-images.githubusercontent.com/3065196/151009058-1bd266d8-2c38-45db-84d7-dca45a2a7da5.png)

Third photo, I've clicked OK and reopened the dropdown. BNC-20B still appears, BNC20L does not.
![photo-3](https://user-images.githubusercontent.com/3065196/151009184-96015d5b-18d2-4234-87e6-fd8e46214fe7.png)

Fourth photo, I've closed and reopened the edit window, and opened the dropdown.  Correct presets are present.
![photo-4](https://user-images.githubusercontent.com/3065196/151009552-a6f12a23-0a06-44f1-9fa0-ddc68cfa27a4.png)

**Comment by hcraigmiller** [comment]
Error replicated in Windows 11.

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by SiboVG** [comment]
Also would like to point out that clicking 'Cancel' in the 'Choose component preset' window does not undo selections that you have made, there is just no difference between the 'Ok' and 'Cancel' button. If I select 2 new presets and click 'Cancel', the presets should not be added to the preset dropdown, as is the case currently.

**Comment by JoePfeiffer** [comment]
Yes.  I think what will work most smoothly with the rest of the component editor will be to replace the "OK" and "Cancel" buttons with a single "Close" button.
