### ISSUE TITLE
Add Opacity slider to Appearance panel

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1078]
Unstable release adds support for alpha channel in the 3D renders.  Right now the only way to control it is inside the color picker, in the RGB/HSL/blah blah blah section.  This is far too hidden and too inaccessible.  Propose a slider, labeled "Opacity", somewhere under the color button, either above or below the "Shine" control.

The Alpha channel controls in the color picker could still be there, it doesn't hurt to have it in both places.  Obviously, editing in either place should show up in the other.

See #401, which is related but not quite the same.

**Comment by hcraigmiller** [comment]
The transparency slider needs to be added to the RGB and CMYK color picker pages (see Issue #401).

**Comment by neilweinstock** [comment]
There's already an alpha channel setting there.  It works and is fine.  No need to go mucking with the color picker.  Purpose here is simply to surface the same functionality in a more friendly way, e.g.:

![image](https://user-images.githubusercontent.com/243872/150894398-b965e12f-7816-4642-8017-a1d8b11599e2.png)

I would really prefer the opacity slider to go from 0-100%, but it may be much easier to just have it be 0-255 and therefore be exactly the same as the alpha channel value.  Otherwise need to convert back and forth, which is possible but not idea.

**Comment by hcraigmiller** [comment]
I agree that the opacity (transparency) slider should go from 0-100% as suggested by @neilweinstock.

**Comment by neilweinstock** [comment]
I may try to implement this myself at some point if no one else gets to it first.
