### ISSUE TITLE
Newly created motor config still not automatically selected properly

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1088]
This was fixed a long time ago, but it has come to my attention that it still doesn't work right.

After creating a new motor configuration, the motor is highlighted, but it is not properly "selected", e.g.:
![image](https://user-images.githubusercontent.com/243872/151636702-419caab9-aa60-48ce-8e32-c267ba64959a.png)
None of the buttons at the bottom are enabled, so you still need to click on the new one before going in to select the motor.

After creating a new motor config, it should look like this:
![image](https://user-images.githubusercontent.com/243872/151636804-59e5f3fd-711f-403c-9ad6-00deb395ce69.png)

As a bonus, I would love the "Select Motor" button to be the default action, so you'd only need to hit <return> to select motor after creating the new config.  Or just go and open the motor selection dialog immediately.  But it's possible that could be slightly confusing with multi-stage designs.  

Most important thing: properly auto-select the new config.

**Comment by hcraigmiller** [comment]
Confirmed misbehavior.

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]
