### ISSUE TITLE
[Bug] Grey background color on selected button (Mac)

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1099]
The background color of e.g. the stage selection buttons in the middle have a grey background instead of a blue one. This behavior is not inclusive for ToggleButtons, but can also be seen if I press down and hold a normal Button.
![image](https://user-images.githubusercontent.com/11031519/151702164-4112f801-8e0d-4c4b-aa31-d744e58e93e5.png)

Occurs in unstable as well as in OR 15.03.

The issue is not present in buttons of a JOptionPane:
![image](https://user-images.githubusercontent.com/11031519/151702348-d8d9fc3e-9d89-4215-9bf0-d433326fdecb.png)

[macOS Monterey 12.1, MacBook Pro M1]

**Comment by neilweinstock** [comment]
I am now seeing this on my M1 iMac, running Monterey 12.2.

**Comment by neilweinstock** [comment]
We can close this now, right?
