### ISSUE TITLE
[Bug] 'Simulation extensions and scripting' example design throws exception when simulating

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1108]
The 'Simulation extensions and scripting' example design throws an exception when running the second/third simulation.
[Bug report Sim3 - Roll control.txt](https://github.com/openrocket/openrocket/files/8011245/Bug.report.Sim3.-.Roll.control.txt)
[Bug report Sim2 - Active roll control.txt](https://github.com/openrocket/openrocket/files/8011243/Bug.report.Sim2.-.Active.roll.control.txt)

Tested on latest unstable, macOS version 12.1, MacBook Pro M1.

**Comment by hcraigmiller** [comment]
> The 'Simulation extensions and scripting' example design throws an exception when running the second/third simulation. [Bug report Sim3 - Roll control.txt](https://github.com/openrocket/openrocket/files/8011245/Bug.report.Sim3.-.Roll.control.txt) [Bug report Sim2 - Active roll control.txt](https://github.com/openrocket/openrocket/files/8011243/Bug.report.Sim2.-.Active.roll.control.txt)

When attempting to open either of the two design files, I get an error message.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by SiboVG** [comment]
> > The 'Simulation extensions and scripting' example design throws an exception when running the second/third simulation. [Bug report Sim3 - Roll control.txt](https://github.com/openrocket/openrocket/files/8011245/Bug.report.Sim3.-.Roll.control.txt) [Bug report Sim2 - Active roll control.txt](https://github.com/openrocket/openrocket/files/8011243/Bug.report.Sim2.-.Active.roll.control.txt)
> 
> When attempting to open either of these two design files, I get an error message.

Yes, they're not design files, but the bug reports after running simulation 2 and simulation 3 🙃

**Comment by SiboVG** [comment]
I don't have this issue when I run OR from my IDE IntelliJ, only when I run it from a JAR.
