### ISSUE TITLE
Change Request: Hide motors not in production

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1121]
When opening the "Select a rocket motor" dialog box, most users expect the motors shown to be in regular production. Current;ly, the default state is to show OOP motors.

This request is to change the hide motors not in production by either:
1. Making "Hide motors which are not in regular production" the default setting when the "Select a rocket motor" dialog box is opened; or
2. Rewording "Hide motors which are not in regular production" to "Show motors which are not in regular production", with the default being off, similar to the legacy component library functionality.

I prefer number 2.

**Comment by JoePfeiffer** [comment]
I definitely prefer #2.  Negative options (turn this option on to not see/do something) are a pet peeve of mine.

**Comment by hcraigmiller** [comment]
Current unstable. Option 1 above has been implemented. 

![Current 2022-03-21 Rev_01](https://user-images.githubusercontent.com/68821492/159412685-560c9e25-160c-45c5-bf73-a12196fce69c.png)

Should this issue be closed, or is a change to option 2 anticipated?
