### ISSUE TITLE
[Bug] Nose cone/transition configuration dialogs are so large as to extend beyond the screen edge.

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1125]
![Nose cone](https://user-images.githubusercontent.com/68821492/153719773-2986e1d0-e751-4af7-832b-06782d31f3c5.png)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by SiboVG** [comment]
Ah voila, didn't see you made an issue request for it, see PR #1126
