### ISSUE TITLE
3D not working on Mac ARM packaged version

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1136]
The ARM packaged app for Mac has _much_ better performance than the x86 package on Apple Silicon Macs.  However, the 3D stuff doesn't work at all, presumably due to incompatibilities with the existing JOGL library.  

Enabling a 3D view yields this:
![image](https://user-images.githubusercontent.com/243872/154606907-90b1127f-a230-40ee-a6e6-42a3779bceda.png)

**Comment by neilweinstock** [comment]
I labeld this one "Release blocker" because we should at least give it a shot before release.  The ARM version performed *so* much better than the x86 version, other than lack of 3D, and there are a lot of Apple Silicon Macs out there now.  SO I think it's worth a little effort.  If it looks intractable, then we can defer it to a future release.

**Comment by Code-Assembly** [comment]
I'm experiencing the same issue when building form source on an M1 Mac (ARM), but I've got the 3d view running.

However, I'm doing so using the [Intel build of JDK 11](https://www.azul.com/downloads/?version=java-11-lts&os=macos&package=jdk)

I've found the clue in this [Stack exchange Tread](https://apple.stackexchange.com/questions/431573/how-to-handle-java-apps-lacking-arm-support-using-java-sdk-on-m1-mac) 

I don't know anything bout Java builds and library liking but perhaps there's a clue in that thread.

![image](https://user-images.githubusercontent.com/41145873/159187850-f3c8e7c9-a21d-4295-afd8-04a717575d8f.png)

**Comment by neilweinstock** [comment]
As far as I understand what you did, that's still an Intel build running on Intel JDK, and then running on Rosetta II on your Mac.

Our goal is a ARM-native build running on ARM JDK, which brings huge performance improvements.  It seems that the JOGL library is Intel-only or the moment.

**Comment by JoePfeiffer** [comment]
> Our goal is a ARM-native build running on ARM JDK, which brings huge performance improvements. It seems that the JOGL library is Intel-only or the moment.

And, as far as I know, for the foreseeable future.  We'll need to revisit this when we're closer to this release, but I suspect we'll need to make "move to something other than JOGL" a priority for the following release.

**Comment by SiboVG** [comment]
> "move to something other than JOGL"

I've been waiting to send this message for over two months now 🙃

**Comment by RemingtonHolder** [comment]
Also can confirm am having same issues on M1 Macbook Air
![293EC2AC-FBC6-41E3-B797-5D2BC0AA4F20_1_105_c](https://user-images.githubusercontent.com/45955060/160244811-dc87d590-780e-4f77-a459-b70e5cb40ab2.jpeg)

**Comment by RemingtonHolder** [comment]
@neilweinstock This was not from the pre-packaged version but here is the stack trace if it may help. I beleive you were right in saying its another JOGL issue.

[stackTrace.txt](https://github.com/openrocket/openrocket/files/8355729/stackTrace.txt)

**Comment by neilweinstock** [comment]
Yeah, it's as simple as that: JOGL is not ARM-native, and may or may not ever be, which is why we're going to move away from it.  But that'll take a little time.  An ARM-native OR is definitely something we want to be able to offer, performance is *way* better.

**Comment by RemingtonHolder** [comment]
@neilweinstock Possible solution/fix? https://forum.jogamp.org/JOGL-for-Mac-ARM-Silicon-td4040887.html

**Comment by JoePfeiffer** [comment]
That looks promising.

**Comment by neilweinstock** [comment]
I dunno there's a lot of crashing and unreliability in that thread.  Not sure if there's still really a reliable solution for this.  Need to decide if effort is best spend going down the rabbit hole of trying to get JOGL to work, or spend that effort moving to something newer and more solidly supported on ARM.
