### ISSUE TITLE
Homogenize capitalization of rocket component names

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1137]
This is a very nitpicky thing, I know, but it bothers me slightly that there are some rocket components that by default have all the words in their name capitalized, while others don't.

More specifically, I would make the following changes:

- Inner Tube --> Inner tube (in the component tree)
- Launch Lug --> Launch lug (both in the component tree and the create new component button)
- Rail Button --> Rail button (both in the component tree and the create new component button)
- Mass Component --> Mass component (both in the component tree and the create new component button)

This would just tidy things up a bit.

Or we could of course do it the other way around, changing the other component names to capitalize everything (e.g. 'Body tube' --> 'Body Tube'). @hcraigmiller @neilweinstock any opinions on this?

**Comment by neilweinstock** [comment]
I agree with your proposal.  First word capitalized only.

**Comment by JoePfeiffer** [comment]
I'd actually prefer the opposite -- all words capitalized.

**Comment by SiboVG** [comment]
Right, I'll post a practical comparison of the two here in a sec.

**Comment by SiboVG** [comment]
<img width="3680" alt="combined" src="https://user-images.githubusercontent.com/11031519/154804722-236b0c5f-18e6-499e-9b56-22aaede4be2d.png">

I must say, seeing it in real, I prefer the capitalized version.

**Comment by neilweinstock** [comment]
That's fine with me.  I think first word capitalized is likely more "correct", but capitalization rules can be funny in this sort of situation.

Consistency is most important.  Go for the capitalized version.

**Comment by hcraigmiller** [comment]
Either works for me, no real preference.

**Comment by RogueXT** [comment]
I Vote for all Capital Myself. It is a Very Bad Habit I have Developed in Forty (40) Years of Designing Tooling. :-)

-JP
