### ISSUE TITLE
[Bug] Shock cord config dialog Packed length label cut off

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1141]
The 'Packed length' label in the shock cord config dialog is cut off in the beginning:
<img width="1728" alt="Screenshot 2022-02-19 at 15 31 48" src="https://user-images.githubusercontent.com/11031519/154805267-5da69899-d307-4b4d-95bd-1ea5523e379f.png">

Tested on latest unstable, macOS Monterey 12.1, MacBook Pro M1.

**Comment by hcraigmiller** [comment]
Must be a Mac thing... those darn Macs. Just kidding. Windows functionality for FYI

Upon opening.
![Shock cord](https://user-images.githubusercontent.com/68821492/154807026-e3915bec-49eb-497e-bc39-4dfaa73395d8.png)

Resized window until began clipping.
![Shock cord2](https://user-images.githubusercontent.com/68821492/154807214-92232d04-58e2-472b-8ce6-d8374e489a3c.png)

Functions as expected in Windows.
[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]
