### ISSUE TITLE
Linux 3D isn't working

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1156]
Hadn't been verifying 3D was still working for Linux after my system rebuild last week; discovered tonight it's not.

When going to a 3D view I'm getting an error in the window: "Unable to load 3d Libraries: XXX0 profile[2]: GL2->profileImpl GL3bc !!! not mapped

Hoping distributing as an appimage will let me include old enough openGL libraries to get it working again....

**Comment by SiboVG** [comment]
Well, well, well, looks like I'll be having my virtual beer from PR #1155 after all 😎

**Comment by JoePfeiffer** [comment]
All too likely at the moment.

**Comment by SiboVG** [comment]
98% sure it won't make a difference, but can you check if [this jar](https://drive.google.com/file/d/1WbkM2vrf-3LkcDlrHlMp5qIkxIP4llY-/view?usp=sharing) has the same issue? It uses a newer version of JOGL.

**Comment by JoePfeiffer** [comment]
No change

**Comment by SiboVG** [comment]
Maybe [useful forum question](https://jogamp.org/bugzilla/show_bug.cgi?id=1426) (although we don't use GLProfile.getMaxProgrammable or GLProfile.getMaxProgrammableCore).

FYI: I used JOGL v2.4.0-rc-20210111 in the JAR file I posted, downloaded [from here](https://jogamp.org/deployment/v2.4.0-rc-20210111/jar/).

**Comment by SiboVG** [comment]
Aha @JoePfeiffer I think [this JAR](https://drive.google.com/file/d/1WbkM2vrf-3LkcDlrHlMp5qIkxIP4llY-/view?usp=sharing) fixes it (at least it fixed it on my machine). OR previously used JOGL packages for linux-amd64 and linux-i586. I also added packages for linux-aarch64 and linux-armv6hf.

**Comment by JoePfeiffer** [comment]
Doesn't fix it on mine, rats.  Same error.  My machine is AMD64.  I'm not sure what the error message even means...

**Comment by SiboVG** [comment]
Hm, crap... I'm running ARM64, so that explains why it now works for me with the added packages...

**Comment by SiboVG** [comment]
Did you test running OR in different Java versions?

**Comment by SiboVG** [comment]
I'm sorry @JoePfeiffer you'll have to be my tester for now, does [this JAR](https://drive.google.com/file/d/13uXXQjkZIfC9wv9O5rcIQUbRjA4NwcuM/view?usp=sharing) do anything?

**Comment by JoePfeiffer** [comment]
You got it! Hmmm, now I've got to find a way to get you a real beer...

**Comment by JoePfeiffer** [comment]
Are there MacOS arm jogl's we could try?  That could be the solution to that problem, too.

**Comment by SiboVG** [comment]
> You got it! Hmmm, now I've got to find a way to get you a real beer...

Don't bother sending any American beers here, remember, I'm Belgian 😉
