### ISSUE TITLE
Update Mac installer to single bundle with Applications folder target

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1160]
Something like this:
![image](https://user-images.githubusercontent.com/243872/155628007-ee873195-1909-4bf3-8b0e-c37be16c2204.png)

**Comment by neilweinstock** [comment]
This seems rather well-explained here: https://www.ej-technologies.com/resources/install4j/v/8.0/help/doc/concepts/dmgStyling.html

I am not convinced that, at least initially, we need the custom background, just the Applications shortcut.  Although a background that includes that Arrow would be nice, I suppose.  Maybe I'll try to concoct one.

**Comment by neilweinstock** [comment]
Maybe you can try this as a background image for the .dmg window.
![mac_installer_bg](https://user-images.githubusercontent.com/243872/155859462-373930ce-6ace-4007-801a-57b4cfa96a18.png)

**Comment by SiboVG** [comment]
Custom installation backdrops always bring a small smile on my face, so I'm definitely pro. Maybe my one concern will be that the black backdrop will cause bad contrast between the background and application icon/folder and text.

**Comment by neilweinstock** [comment]
Argh, you might be right.  On the desktop, the OS automatically chooses a font color to contrast with the background... but in a finder window, seemingly, it does not.  WTF.

So with the above background, you won't see the names until you select one of them, then it shows up in white.

What other background would make sense?  The arrow is useful if nothing else, but I was hoping to do something fun in the background.  If it's going to be too much of a problem, then I'll bag the idea.  In the meantime, here's an image with just the arrow.

![mac_installer_bg](https://user-images.githubusercontent.com/243872/155890125-466d1e40-d57e-4331-9d6f-be34f8c3f502.png)

**Comment by SiboVG** [comment]
Maybe putting semi-transparent (e.g. 10% opacity) white rectangles with feathered edges in the spots where the 2 items will be can help.

**Comment by neilweinstock** [comment]
That'll work if I know exactly where they'll be.  I'd first need an installer with the Applications folder in place, then I could create the image, and then we could apply it back into the installer.  That's a bit of effort; for the first go-round I guess let's just use the arrow, and I can add the stars later.

**Comment by SiboVG** [comment]
Also I'd propose to use the starfield from OR's website, it's a bit cleaner and it's a nice touch to use the same image.

**Comment by neilweinstock** [comment]
Ok, here is is with the starfield from openrocket.info.  I don't know if we'll be able to use, but just in case...
![mac_installer_bg_stars](https://user-images.githubusercontent.com/243872/155912844-c82024d4-7937-4783-ae72-04fe45b8cc6a.png)
