### ISSUE TITLE
Sign flip in fin component offset when opening .rkt file

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#1164]
Opening "Estes Argent.rkt", things generally look good, but the fins are in the middle of the body. I initially wondered whether this is due to the model having two coupled tubes in the main body. Apparently not.

<img width="2560" alt="Screen Shot 2022-02-25 at 9 26 12 PM" src="https://user-images.githubusercontent.com/35353530/155825519-11a823c1-ffdb-437d-9845-a92b5c798d2c.png">

However, intuition said that flipping the sign on the fin offset would put the fins where they belong, and this appears to work.

<img width="1055" alt="Screen Shot 2022-02-25 at 9 26 37 PM" src="https://user-images.githubusercontent.com/35353530/155825579-82877ac4-7817-4dfe-937f-2df935083c37.png">

Not sure whether this occurs with other components, but a quick check shows the sign-flip on fins in other .rkt files.

I'm using 22.02.beta.01, MacOS Catalina, installed from .dmg package, Intel machine

**Comment by hcraigmiller** [comment]
BUG CONFIRMED: On import of ,rkt file, **the pos/neg sign of fin reference point** is reversed when referenced from the _tip of the nose cone_, and when referenced from the _top of the parent component_. When referenced from the _bottom of the parent component_, the pos/neg sign is correct.

**Comment by SiboVG** [comment]
Does exporting an OpenRocket-design to Rocksim also have the same fin flip issue inside of Rocksim?

**Comment by hcraigmiller** [comment]
Upon export, Rocksim opens with the fins correctly placed, in reference to all points.
