### ISSUE TITLE
In the rocket view, motor configuration dropdown box doesn't have the motor names

### ISSUE THREAD

**Issue by CarVac** [openrocket/openrocket#1166]
![Screenshot_20220225_222936](https://user-images.githubusercontent.com/4342361/155827225-36f6ab31-8c3f-4161-944c-4c3eb639e1e6.png)

Left is 15.03, right is the new 22.02 beta 1.

On Pop!OS Linux, running the .jar file using OpenJDK 11.0.13 2021-10-19 (yes I know this isn't the recommended configuration, but I prefer a standalone file like the AppImage and there isn't an AppImage available).

**Comment by JoePfeiffer** [comment]
I'm not seeing this on my Debian box -- could you send me (or add it to this bug report) your .ork file? You'll need to zip it first for github to accept the upload.

**Comment by hcraigmiller** [comment]
Could not reproduce.

![1166 01 Flight Configuration](https://user-images.githubusercontent.com/68821492/155835796-e56c721b-4b67-4ab0-90d4-67cf1103a118.png)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by CarVac** [comment]
[Area_Rule_3.0.zip](https://github.com/openrocket/openrocket/files/8146563/Area_Rule_3.0.zip)

I have a nickname on the configurations that tell me what case the motor goes with. I guess the syntax for including the currently-selected motor isn't respected anymore?

In 15.03, when I create a new configuration and try to rename it it defaults to `[{motors}]` which I just prefixed by the case and manufacturer, but on 22.02 it defaults to the actual name of the currently selected motor.

**Comment by JoePfeiffer** [comment]
Inadvertently.  This is a regression we need to look at.
