### ISSUE TITLE
[New feature request] Option to turn CG and CP markings on and off in the 3D views

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1168]
In the current unstable, in the _3D views_, the visible CG and CP markings interfere with the user's ability to take screen shots for esthetic purposes, particularly in the _3D Finished_ view. TRF user K'Tesh has asked about an option to allow these markings to be turned on and off.

**Comment by SiboVG** [comment]
Would also be a good way to mask the CG/CP issues in the 3D view on Mac's 🙃

**Comment by RemingtonHolder** [comment]
Just tinkering around, this is a surprisingly frustrating thing to do. The code for CG and CP points seems to be pretty deeply integrated to just always exist. 🤷

**Comment by SiboVG** [comment]
> Just tinkering around, this is a surprisingly frustrating thing to do. The code for CG and CP points seems to be pretty deeply integrated to just always exist/display. 🤷

It's not that hard to do in fact, if you comment out `drawCarets(gl, glu);` on `line 327` in `swing/src/net/sf/openrocket/gui/figure3d/RocketFigure3d.java`, the markings are gone:
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/11031519/160042296-4082e2bd-c650-4506-9639-f8dc4fa846bc.png">

So the only thing that would need to be added for this PR is create a checkbox in the preferences dialog, store that checkbox value in preferences and create a simple if-condition on `line 327` that if the checkbox is checked, that you should call `drawCarets(gl, glu);`.

**Comment by RemingtonHolder** [comment]
Seems as if I were looking at the wrong things. 😂

**Comment by RemingtonHolder** [comment]
@SiboVG Do you think a preference for this would best fit in the Design or Graphics preference tab.

**Comment by JoePfeiffer** [comment]
My first thought is that it could be a button in the rocket figure toolbar -- there's plenty of room for it there, and a user could turn it on/off without having to go to another tab or something.  We could disable it for the non-3D views (much like the scale buttons are disabled for 3D views now -- though I think there's a consensus we'd like that to change that some day).  For that matter, there's no compelling reason to not let users turn them off in the non-3D views as well.

**Comment by hcraigmiller** [comment]
Fix complete by way of PR #1393.
