### ISSUE TITLE
Putting fins on transitions shows less accurate aerodynamics than the old 0-length body tube hack.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1173]
A user on FB reports CP on a V2 model using the the 0-length body tube hack is very close for OR and RockSim.  Attaching fins to transition moves CP unreasonably far forward.

RockSim image:
![rocksim-image](https://user-images.githubusercontent.com/3065196/155854256-fbe2921c-eaac-4b61-8280-0f71ee62ff09.jpg)
RockSim file:
[V2_BT101rkt.zip](https://github.com/openrocket/openrocket/files/8147190/V2_BT101rkt.zip)

0-length body tube hack image:
![o-bodytube](https://user-images.githubusercontent.com/3065196/155854569-bb031211-44cb-49ac-884f-84b602a1bf0b.jpg)
OR file:
[V2_BT101ork.zip](https://github.com/openrocket/openrocket/files/8147193/V2_BT101ork.zip)

Fins on transition image:
![transition](https://user-images.githubusercontent.com/3065196/155854592-56c06d02-bef5-4fac-89c8-d8c2289752b6.jpg)
OR file:
[V2_BT101_RS-22.zip](https://github.com/openrocket/openrocket/files/8147195/V2_BT101_RS-22.zip)

**Comment by JoePfeiffer** [comment]
Got another detail from the original reporter last night:

> It dawned on me last night that OR is using straight Barrowman for CP calcs whereas I used RockSims' calculation for the RS
pic I sent.  I opened up the V2 in RS and changed to CP calc method, and it looks close to the OR 22 sim I sent you. 
"mischief managed"
![rocksim-v2](https://user-images.githubusercontent.com/3065196/156415444-388e1171-0bf2-4193-a26f-37c67c12223f.png)

I'm still troubled by it

**Comment by hcraigmiller** [comment]
As to the original issue title of "Putting fins on transitions shows less accurate aerodynamics than the old 0-length body tube hack", a comparison between the current unstable, Rocksim 10, and RASAero II, using an airframe compatible with all three, shows very little difference in altitude in some cases, and a huge difference between OpenRocket and Rocksim and RASAero II in others [all simulations have polished surfaces using Barrowman].

![0001 Comparison 54mm](https://user-images.githubusercontent.com/68821492/159097298-d0df60b7-9c2a-42f9-9e1d-80ea758b5a03.png)

Rocksim 10 and RASAero II seem to be fairly close to one another.

If this is helpful, I can do additional comparisons.

**Comment by JoePfeiffer** [comment]
I'd be very curious to see how results compare using the same rocket and motors, but no boat tail (same diameter all the way back).

**Comment by hcraigmiller** [comment]
Here are the results:

![Compare Rev_02](https://user-images.githubusercontent.com/68821492/159126057-e95f580d-91d9-49a5-9beb-cbda040c418f.png)

**Comment by JoePfeiffer** [comment]
Looks like whatever is causing those wildly optimist results, it isn't the transition.  Could you post the .ork for the straight-tube version?

**Comment by hcraigmiller** [comment]
Here are the files for the straight body... I removed the rail buttons so that all three are exactly the same.

[02.01.Comparison.Rev_02.ork.txt](https://github.com/openrocket/openrocket/files/8310437/02.01.Comparison.Rev_02.ork.txt)
[02.02.Comparison.Rev_02.rkt.txt](https://github.com/openrocket/openrocket/files/8310438/02.02.Comparison.Rev_02.rkt.txt)
[02.03.Comparison.Rev_02.CDX1.txt](https://github.com/openrocket/openrocket/files/8310439/02.03.Comparison.Rev_02.CDX1.txt)
