### ISSUE TITLE
App should check JRE at startup and report to user if it's no good

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1176]
To the extent possible (I don't know what that is), the app (.jar file, in particular) should try to check the JRE version at startup and report to the user if it is unsupported, and refuse to proceed any further in that case.  Maybe this would save us some unnecessary bug reports.

**Comment by SiboVG** [comment]
Good idea... Should we set up a range of versions that we know are supported? Was it Java 11, 12 and 13?
