### ISSUE TITLE
Request: add back propellant designations in "Select Motor" window

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1178]
15.03 showed propellant designations for AT motors (e.g., F44W).  The new beta only shows F44.  Would be useful if we could add back the propellant suffix.

https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2246538

**Comment by SiboVG** [comment]
@JoePfeiffer does this have to do with PR #1032 where in some parts DESIGNATION got replaced by COMMON_NAME?

**Comment by JoePfeiffer** [comment]
That's exactly what it is.  The manufacturer's designations are wildly inconsistent as to what information is provided -- Aerotech includes a propellant code, but it's not consistent (most use a single-letter code immediately following the average impulse, but the D7-RCT has a dash in between, and the F20W/L uses W/L for white lightning).  CTI puts the total impulse before the impulse class, doesn't include a propellant designation, and does include a delay.  The common name is an impulse class followed by average thrust, and is consistent.

15.03 used the .eng and .rse files directly, without the metadata provided by thrustcurve.org, so the designations were whatever the person who submitted the curve wanted it to be.  At some point in the process toward this release, OR switched to using the manufacturer's designations, which struck me as being really ugly where CTI was concerned.  I switched it to the common name, not realizing there were people really wedded to the propellant designations on Aerotech motors.

It occurs to me that there are columns in the motor selection table that I almost never use (like diameter.  I filter by diameter so the motors I look at will fit my mount, and then pick a motor, and use an adapter if needed).  And, while it strikes me as really odd, I know people who actually choose motors based on propellant.  Would it be reasonable to put checkboxes on the lines of the Detailed motor tab, so people can select whatever set they want to see in the table?

**Comment by neilweinstock** [comment]
I think that's reasonable approach.

To be honest, I kind of suspect that at least for AT, a pretty good percentage of folks would want to see the propellant suffixes in there, because that's kind of how you know the motor.  But I also understand why you went with the common designators in the first place.  It's a tricky problem.

**Comment by hcraigmiller** [comment]
Has this issue been sufficiently resolved by way of the "Use manufacturer's designation" feature so that it should be closed?

**Comment by SiboVG** [comment]
> Has this issue been sufficiently resolved by way of the "Use manufacturer's designation" feature so that it should be closed?

Yes.
