### ISSUE TITLE
Feature Request: Add straight section to nosecone base

### ISSUE THREAD

**Issue by neutronium95** [openrocket/openrocket#1179]
Many nosecones have a section towards the base that is cylindrical. It is pretty easy to model this with an additional section of body tube, but being able to specify that the bottom 3 inches of a nose cone are cylindrical would be convenient.

**Comment by hcraigmiller** [comment]
Duplicate of #839; recommend that this issue be close.

**Comment by JoePfeiffer** [comment]
Duplicate of #839
