### ISSUE TITLE
Better color picker for Linux

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1187]
I was just astonished to learn that in Linux, the color picker is this:
![image](https://user-images.githubusercontent.com/243872/155907102-a7c02e3c-50c7-4708-9864-0f4d84765b48.png)
Apart from its other glaring deficiencies, this picker does not apparently (at least as invoked by OR) support alpha channel, which kneecaps one of the features of the new release.

I am no fan of the Windows/Mac picker but at least it's functional.

Is there a way to get a more functional picker into the Linux builds?  Or at the very least, enable alpha channel operation?

Better long term solution for alpha is an opacity slider in the appearance panel, but until we get that the picker should offer it.

**Comment by JoePfeiffer** [comment]
By default, Java applications are supposed to use a look and feel called "Metal", which as I understand it would make the application look similar across all platforms.  The Metal l&f supports transparency. OR actually has code looking for and forbidding the use of the Metal look and feel, in GUIUtil.java, on the grounds that it's ugly (and... it is). You can't even set it on the command line.

The GTK color chooser underlying the implementation in Linux actually does support a transparency slider. I haven't spent a long time on it, but I haven't found a way to get the Java JColorChooser to enable it (I've got no idea why that isn't the default).

**Comment by neilweinstock** [comment]
Is the code actively disabling the RGB and Color Swatch panels?  Can't figure out why they're there in Mac & Win and not Linux.

This is of course a lower-priority item.

**Comment by JoePfeiffer** [comment]
#1197 fixes the functional issue here.
