### ISSUE TITLE
"Shine" slider in Linux Appearance tab has (apparently) zero width

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#1189]
![image](https://user-images.githubusercontent.com/35353530/155927821-8dde4441-0152-49bf-8377-8e631dcaa762.png)

Shine slider looks like a nubbin in a box on Linux. Works as expected on macOS.

**Comment by SiboVG** [comment]
@jimmiedave since my machine doesn't suffer from the issue, can you verify that [this JAR](https://drive.google.com/file/d/1DtnsOs2Ih-M6W4DqHQlDTOZQnE_RWumY/view?usp=sharing) fixes the issue?

**Comment by jimmiedave** [comment]
Running the JAR gives (only) this message in the terminal:

`Gtk-Message: 11:32:52.297: Failed to load module "canberra-gtk-module"`

Related?

**Comment by SiboVG** [comment]
> Running the JAR gives (only) this message in the terminal:
> 
> `Gtk-Message: 11:32:52.297: Failed to load module "canberra-gtk-module"`
> 
> Related?

No, I also get that message, but the slider still works on my Ubuntu build. (I also haven't researched what the Gtk-Message means, I chose to peacefully ignore it)

**Comment by SiboVG** [comment]
> Reboot of machine doesn't improve matters.
> 
> Could the 10x value thing be related? Maybe not enough pixels to encompass a range of 0-1000 making the widget be weird?

Hm, I don't know, but it's just very strange that the slider button also differs from the rotation slider button. Before this PR I had the same, round button as in the last screenshot you posted, but after the JAR, on my machine the slider button changed to the same one as the rotation slider...

**Comment by jimmiedave** [comment]
Uninstalled (purged, with aptitude, actually) Ubuntu's default-jre and default-jre-headless, reinstalled, noted same results.

Also noted in fiddling with this that using the arrow gadgets on the Shine value box (i.e. not the slider) will allow negative values. Should probably be clipped to 0%. Do you want a fresh bug on this?

**Comment by SiboVG** [comment]
By the way you can get rid of the Gtk-Message by running `sudo apt install libcanberra-gtk-module`

**Comment by SiboVG** [comment]
Myeah something must be wrong... And I'll include the shine value clipping in the PR of this issue, no need to make it a separate issue.

**Comment by SiboVG** [comment]
Okay just so I'm certain, does [this JAR](https://drive.google.com/file/d/134MyTskKzKVDzEY2eTRBTjfdVOSsniPT/view?usp=sharing) change anything at all? (this JAR btw also has the clamping so you can play around with that)

**Comment by jimmiedave** [comment]
Yes, correct slider, and the clamp works great!

Only thing left: value window changes sizes, making the slider a little jittery as you drag it, but that's so minor, I think it's livable:

![image](https://user-images.githubusercontent.com/35353530/156050948-dcf7e37c-3fbc-4f0a-900c-da80a257b94f.png)
![image](https://user-images.githubusercontent.com/35353530/156050987-bf0443d4-e4f2-4845-aa60-10bbb02cc31f.png)

**Comment by SiboVG** [comment]
> Only thing left: value window changes sizes, making the slider a little jittery as you drag it, but that's so minor, I think it's livable:

Let's file that as a problem for future me 😉

**Comment by jimmiedave** [comment]
Sounds good - the Rotation slider on the same panel has the same jitter thing, and different sliders in panels in the material tabset deal with this in different ways - so a little bigger than fixing the single jitter.

Appreciate your quick work on this.
