### ISSUE TITLE
"Close" button in configuration dialogs cut off on Linux

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#1190]
vis:
![image](https://user-images.githubusercontent.com/35353530/155927937-aefff33b-ade2-4975-944d-27e55f2a4ecc.png)

Testing Ubuntu LTS 20.04 on AMD Ryzen 3400G (integrated Vega graphics), resolution set to HD (1920x1080)

**Comment by SiboVG** [comment]
This doesn't appear on my machine, does [this JAR](https://drive.google.com/file/d/1XWHvSbUjUZh3_kpltOnAWMeq7ocbthXG/view?usp=sharing) solve it @jimmiedave?

**Comment by JoePfeiffer** [comment]
Confirmed on my Debian machine; the jar fixes it for me.

**Comment by jimmiedave** [comment]
Close button fixed here on Ubuntu LTS 20.04
