### ISSUE TITLE
[Bug] CP duplication in 3D views

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1191]
TRF user K'Tesh found this bug: https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/page-5#post-2247144.

K'Tesh provided the .ork file and I deconstructed the components to identify the cause. It appears to be related to _Fin 3_ on the sustainer. The attached screenshots show the reconstruction of _Fin 3_, in steps, and the effect of those steps as the bug manifests itself.

![01 Reconstruction Fin_3](https://user-images.githubusercontent.com/68821492/155980260-ce86ba1e-257d-46c0-9b51-d33fe8cdf517.png)

The .ork files are attached.  And, the file names are labeled on each screenshot.

In _Revision 4_ , _Fin 3_ has been reconstructed, except for the final point; its position is Base 0. This is the first that you get a hint that there's a problem when a second partial CP point appears.

In _Revision 5 , _Fin 3_ has been fully reconstructed; its position is Base 0.  Again, there is a hint that there is a problem when the CP disappears and reappears as the rocket is rotated horizontally.

In _Revision 6_ , _Fin 3_ has been fully reconstructed, ; its position is Base -1.125, the same as the other two fins. A second full CP point appears.

This particular design has a booster, and the Fin 3 on the booster causes the same issue.

Renamed .ork to .txt.

Original file:
[Estes Magnum Payloader (2032)(Clear Testbed).txt](https://github.com/openrocket/openrocket/files/8153272/Estes.Magnum.Payloader.2032.Clear.Testbed.txt)

Reconstructed _Fin 3_
[00.Build.Partial.01.04.05.Body_Tube.Fin-3.Booster_False.txt](https://github.com/openrocket/openrocket/files/8153212/00.Build.Partial.01.04.05.Body_Tube.Fin-3.Booster_False.txt)
[00.Build.Partial.01.04.06.Body_Tube.Fin-3.Booster_False.txt](https://github.com/openrocket/openrocket/files/8153213/00.Build.Partial.01.04.06.Body_Tube.Fin-3.Booster_False.txt)
[00.Build.Partial.01.04.04.Body_Tube.Fin-3.Booster_False.txt](https://github.com/openrocket/openrocket/files/8153214/00.Build.Partial.01.04.04.Body_Tube.Fin-3.Booster_False.txt)

**Comment by neilweinstock** [comment]
Closely connected to #939, except on the Mac it's not dependent on anything... you *always* get the original CP/CG markings being left behind when you rotate the rocket.
