### ISSUE TITLE
Request: default component color something other than black

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#1192]
Suggest we make default color something like #7F7F7F so that the black and white boxes in the preview area initially make some intuitive sense to users. They've never made sense to me until just a moment ago when I opened one of the sample files that was colored up (something I've never really used OR for).

The black-and-white preview boxes aren't labeled (other than being in the preview area), and unless the color chosen is not black (which is one of the colors in the boxes that's being used for preview against your chosen colors), they just look like a bunch of weird black and white boxes, and it's not clear that you can see your text on the sample backgrounds (because black-text-on-black and black-text-on-background-and-white don't give you the sense that you're looking at your chosen color).

**Comment by neilweinstock** [comment]
This is an interesting thought.

In general, I think I would like to see all the default colors be the same, and a mid-gray would make sense for that.

**Comment by SiboVG** [comment]
So you want something like this?
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11031519/156058474-5e38062a-f662-451d-ab94-6ebdf3236ec9.png">

**Comment by neilweinstock** [comment]
Hmm, that's a bit dark... I propose BBBBBB

**Comment by SiboVG** [comment]
Fine by me, here's the #BBBBBB result:
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/11031519/156061034-5525905e-6e09-48be-80ef-5be9aec333df.png">

**Comment by neilweinstock** [comment]
Works for me.  I'm sure people will complain. :)

**Comment by jimmiedave** [comment]
I'm fine with the #BBBBBB - what I'm particularly trying to avoid is the scenario below where the screen is filled with mysterious black and white symbols, because unknown to the user, the default color #000000 is the same color as the black areas to which it's being compared, and black text, which is the common default. It's not intuitive what one is to do with this.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/35353530/156061948-481d1757-019e-45df-b7c2-3203b6c6c151.png">

#BBBBBB is a better choice, and gives:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/35353530/156062578-7a0e6749-8cc2-43da-b5bc-ffcb1787d5e7.png">

**Comment by jimmiedave** [comment]
And of course, the highlighted swatch should be #BBBBBB, assuming it's in the  swatches.

**Comment by neilweinstock** [comment]
> I'm fine with the #BBBBBB - what I'm particularly trying to avoid is the scenario below where the screen is filled with mysterious black and white symbols, because unknown to the user, the default color #000000 is the same color as the black areas to which it's being compared, and black text, which is the common default. It's not intuitive what one is to do with this.

To be fair... there are already about 20 other ways the color picker is not intuitive. ;)

But I agree, the black default is not ideal, the grey will be better.  And this will save me from changing every component manually to gray when I first enter a design, so I'm all for it. :)

**Comment by SiboVG** [comment]
> And of course, the highlighted swatch should be #BBBBBB, assuming it's in the swatches.

#BBBBBB is not in the swatches, but either way if I set the default color to a color that is in the swatches, that swatch did not get selected, so let's just silently forget about it 😉

**Comment by neilweinstock** [comment]
The swatches don't highlight, and it's also happy to have the same color
appear multiple times in the "recently used" grid on the right side, and if
you choose a color in one of the other panels it does *not* show up in the
recently used grid.

It is not a good color picker, but it's what we seem to be stuck with for
now.
