### ISSUE TITLE
[Bug] Stage CG override not correct in design window, stability not correct

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1204]
The Stage override is displaying a different value than that entered, and both the CG distance and stability values in the design window (upper-right corner) are incorrect.  It is 1.076" too far from the tip on this design. For example, to get the CG at 9.414", you have to enter 8.127"

[Cone_Rocket.Tip_Composite.txt](https://github.com/openrocket/openrocket/files/8159086/Cone_Rocket.Tip_Composite.txt)

**Comment by JoePfeiffer** [comment]
Sorry I didn't look at this one before:  near as I can tell, it is working as intended.  The CG override is for the empty stage; adding motors then changes it.  This way we don't need a different override for every different motor.

**Comment by hcraigmiller** [comment]
After reading the comments of @JoePfeiffer, I believe that he is correct, it is functioning properly. I didn't realize at the time that the motor was causing the disparity. The override should not override the effect of the motor mass.

**Comment by JoePfeiffer** [comment]
@hcraigmiller should this be closed?
