### ISSUE TITLE
[Bug] Tube Fin flight profile significantly differs from 15.03

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1207]
TRF user **Neutron95** reported a disparity in flight data for tube fin rockets between 15.03 and the beta release: (https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/page-6#post-2248246)

Using the example tube fin rocket included with OR, I ran flight comparisons and confirmed the report

![Error Tube_Fin Flight_Profile](https://user-images.githubusercontent.com/68821492/156377630-6b99ed74-76ec-441c-8f6c-e570d3f73332.png)
.
The flight profiles are significantly different; the same disparity exists with the current unstable.

@neilweinstock ran a comparison using macOS and found no material difference: (https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/page-6#post-2248323)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by neilweinstock** [comment]
My test was on Windows, for what it's worth.

**Comment by SiboVG** [comment]
Same behavior noted on macOS (note: you should re-run the simulations on the unstable version, because the present simulation results are cached results)

**Comment by neilweinstock** [comment]
Yes, I was looking at cached results, oops.  I confirm this issue as well.

**Comment by SiboVG** [comment]
FYI: This issue is a result of commit [74ec0be340baf06d63cdc0e81cfd45e79bc2fa48](https://github.com/openrocket/openrocket/commit/74ec0be340baf06d63cdc0e81cfd45e79bc2fa48)

**Comment by hcraigmiller** [comment]
To begin, 15.03 does not support tube fins. The user used a hack to simulate this feature, using launch lugs. The 15.03 results are at least 2x as high as both the unstable and Rocksim 10, using the user’s .ork file.

![Comparison](https://user-images.githubusercontent.com/68821492/157167351-e819e839-db16-4fa2-ac2e-63ef054646fe.png)
 
This does not look like an issue with the current unstable.

**Comment by SiboVG** [comment]
Then I would suggest to update the simulation of the Tube Fins example design with unstable's results.

**Comment by neilweinstock** [comment]
Wait, now I'm confused on multiple fronts.

1) Why do you say 15.03 didn't support tube fins?  It certainly did.  It was labeled "experimental" but it was there, using the same (I believe) approximation for simulating them as Rocksim (personally I would remove the "experimental" tag at this point but that's a minor detail).
2) I downloaded the ORK file he attached to his TRF posting, and it definitely used Tube fins.  Where is the ORK file that used a launch lug hack?
3) When this was first posted, we did tests on the posted file and verified the discrepancy.

**Comment by neilweinstock** [comment]
Well, in this case the user said that 15.03 was already slightly *underestimating* the altitude on his tube fin rocket, and now we cut the estimate in half.  I have no explanation for the moment why Craig's Rocksim example shows estimates even lower than the beta.

I think I would like to start with a clear explanation of _why_ the beta changed.  I see you identified the commit that caused the change (and the description certainly seems to support that) but I don't have a clear idea what was the nature of the change.

**Comment by neilweinstock** [comment]
> I just wanted to have another indication of which simulation is the best, other than a user report, that's why I asked Craig if he would want to simulate it in RockSim (since my guess was that we can trust them?)

Uh, maybe?  My gut feel is that the simulation aspects of Rocksim are pretty well-developed, but it is also true that Rocksim is tremendously buggy.  I *think* that we're all using the same tube fin approximation though, which is (if I recall correctly), three fins with equivalent profile for each tube fin.  So the results shouldn't be that different.

I am still trying to understand where the ORK file with launch lugs used as tube fins came from.

> As far as I could tell, the biggest change was that after the mentioned commit, the instancecount of a TubeFinSet was no longer the default '1' of a RocketComponent, but was now changed to the number of fin instances (so e.g. '6' in the Tube Fin example). Changing the instanceount back to 1 provided the same simulation results as in OR 15.03. But the instancecount-change is not necessarily the root cause, could be something deeper which I haven't found yet.

Ah, that's interesting.  I would hope that the *default* instancecount shouldn't really make a difference for the case where the user overrode the default to 3 or 6 or whatever, unless it was still simulating as if the value were still equal to the default.  Some quick tests ought to reveal the answer to that.

Certainly, something very significant changed from 15.03 to the beta, we should endeavor to understand it clearly before making any determinations on this issue.

Overall I still find this whole situation very perplexing.

**Comment by hcraigmiller** [comment]
@neilweinstock is correct about 15.03 supporting tube fins; I only looked at the icon and didn't realize that the tube fins had a nearly indistinguishable icon from launch lugs. I am going to do some additional testing using a variety of tube sizes to see if that makes a difference.

**Comment by neilweinstock** [comment]
And you're right that in 15.03, the icons are *extremely* similar for the launch lug and tube fins.  In the beta the tube fin icons were updated, and now look much different from the lug.

However, both icons are... well they could use a bit of work.  I'll give that a go when I get a chance; obviously not urgent.

**Comment by neilweinstock** [comment]
Yikes

**Comment by JoePfeiffer** [comment]
I say we all build some tube fin rockets and collect some data.

**Comment by hcraigmiller** [comment]
Here are the comparisons.
![Comparison BT-20](https://user-images.githubusercontent.com/68821492/157287471-12716c82-631b-4cea-b116-e4792935a198.png)
![Comparison BT-50](https://user-images.githubusercontent.com/68821492/157287508-902cf76a-6b93-42e7-afaa-cc1b9393f7a1.png)
![Comparison BT-60](https://user-images.githubusercontent.com/68821492/157287538-80ad9ebf-66c4-43df-a3da-fcd8c07c34cf.png)
![Comparison BT-80](https://user-images.githubusercontent.com/68821492/157287598-bd61170b-b6fb-4b52-9b04-6893848e98bf.png)
![Comparison 4_in](https://user-images.githubusercontent.com/68821492/157287639-43f8eb66-e912-4ac2-8b9f-a149a3579199.png)

The bigger the airframe and more powerful to motor, the closer you get to the Rocksim 10 results. The results for the BT-80 tests are _impossible_.

**Comment by neilweinstock** [comment]
Note that you have 0 delays for all the motors in Rocksim... that's gonna lose you a lot of estimated altitude.

**Comment by neilweinstock** [comment]
Something is screwy with the Rocksim results in that last batch... longer delays resulted in *lower* apogee???

**Comment by hcraigmiller** [comment]
Here's a BT-20 for comparison... Apogee says that a 0 delay on motors that are not plugged is the equivalent of no ejection charge.

![Comparison BT-20 30s_Delay](https://user-images.githubusercontent.com/68821492/157307547-45a1c5c5-b7c0-4ee2-8c6d-052ac9e06da0.png)

**Comment by neilweinstock** [comment]
Ah, OK.  Look at all we're learning today! :)

**Comment by JoePfeiffer** [comment]
Real data!  I was only able to get data with B6 and C6 motors; I didn't have any A8-5's to get a long enough delay to reach apogee.  Collected with a Jolly Logic Altimeter 3, dead calm air, approximately 70F, launch rod at a 7 degree angle from vertical.

[tubular.zip](https://github.com/openrocket/openrocket/files/8403482/tubular.zip)
![render](https://user-images.githubusercontent.com/3065196/161403826-53222a6b-f8b5-4a90-afd8-2a78217c71e8.png)
![photo](https://user-images.githubusercontent.com/3065196/161403905-bf8139f4-f532-4640-b3e4-d6b955e34f4a.jpg)
[FlightLog-edited.xlsx](https://github.com/openrocket/openrocket/files/8403488/FlightLog-edited.xlsx)

**Comment by SiboVG** [comment]
Awesome!! Good job @JoePfeiffer!

**Comment by JoePfeiffer** [comment]
Some more data from TRF thread https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-2-is-now-available.171295/post-2265497
