### ISSUE TITLE
1st simulation always fails

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1209]
[Sim_test.zip](https://github.com/openrocket/openrocket/files/8171234/Sim_test.zip)
1st run simulator always fails See images 
![SIM_1](https://user-images.githubusercontent.com/53155232/156405904-123c9431-c500-4416-98d3-d57ccc3bb367.png)
![SIM_2](https://user-images.githubusercontent.com/53155232/156405951-8528461e-d772-4659-8bad-67bf4bcf5812.png)

**Comment by SiboVG** [comment]
This issue should have been fixed in PR #1201. We will release a new beta version soon that has this change implemented.

**Comment by sjh114961** [comment]
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
