### ISSUE TITLE
Separating stages at booster ignition causes numerical instability

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1210]

**Comment by sjh114961** [comment]
[Pod-Boosters.zip](https://github.com/openrocket/openrocket/files/8171762/Pod-Boosters.zip)
Modified existing model to have pods. Using a "c6 " motor configuration results in wild values simulation, see screenshots
![Pod1](https://user-images.githubusercontent.com/53155232/156420399-14edabc3-aa61-4132-a760-a128dfad92ea.png)
![Pod2](https://user-images.githubusercontent.com/53155232/156420407-03868e24-adc6-4a55-8a25-10f1d5473fbd.png)
.

**Comment by SiboVG** [comment]
Confirmed behavior, even just re-running one simulation multiple times yields widely varying results

**Comment by JoePfeiffer** [comment]
This was originally reported as a bug against parallel stages; it turns out it also affects axial stages and has been lurking.
[premature-separation.zip](https://github.com/openrocket/openrocket/files/8174785/premature-separation.zip)

**Comment by hcraigmiller** [comment]
As I'm looking at the .ork, it is set for stage separation on lower stage ignition. That means the separation event is on the pad; that's not a premature ignition, _that's an event that should never be allowed_. Or, am I missing something? 

If you set separation on lower stage ignition, plus at least 1 second, the simulation runs correctly; otherwise it does not.

**Comment by sjh114961** [comment]
Since this ork is only parallel staging, setting the separation to be "Never" seems to work.

**Comment by JoePfeiffer** [comment]
> As I'm looking at the .ork, and it is set for stage separation on lower stage ignition. That means the separation event is on the pad; that's not a premature ignition, _that's an event that should never be allowed_. Or, am I missing something?
> 
> If you set separation on lower stage ignition, plus at least 1 second, the simulation runs correctly; otherwise it does not.

I'm guessing the purpose is to allow exactly what you did -- set separation for some fixed time after liftoff.  Regardless of whether it should be allowed, it shouldn't be the default for parallel staging and it *certainly* shouldn't break the simulation (rockets can break.  The simulation can't!).

Haven't looked into the details yet, but I think terminating the simulation branch if a stage starts tumbling under boost would be a reasonable fix for the instability.
