### ISSUE TITLE
Not-a-number (NaN) exception when simulating large staged clusters

### ISSUE THREAD

**Issue by questionablerocket** [openrocket/openrocket#1226]
Not-a-number (NaN) exception when simulating 15 x D12-0 to 15 x D12-7 staged cluster (originally encountered with A10s but reproduced with D12s to avoid any complications caused by my workaround of issue #1219). The rocket has 3 clusters of 5 motors each in each stage, since there is no option for 15 motor clusters otherwise. Simulations work for the sustainer alone but fail with an internal exception error when a booster is added:

    ERROR (SwingExceptionHandler.java:119) An exception occurred during the simulation
    > net.sf.openrocket.util.BugException: BUG: Simulation resulted in not-a-number (NaN) value, please report a bug, c=(NaN,NaN,NaN)

I'm not running the beta, but I am building unstable every time I see a new commit.  Builds that produced the bug report below were from 3 March at 18:36 UTC, right after pull request 1213 was merged, though the problem persists after more recent commits.

Platforms are:
        Ubuntu 18.04 with the 5.4.0-99-generic kernel running on an octo-core, 16-thread Xeon E-2286M with 128 GB RAM
        MacOS 12.2.1 running on a base model M1 Air with 8 GB RAM.

The simulation will run in 15.03, albeit with questionable plots and extraordinarily long run times (26 seconds on Linux/Xeon, 27 seconds on MacOS/M1, compared to nearly instantaneously for most simulations on either platform), but it fails on both platforms in unstable with either the 15.03 ork or one made using unstable (parts are slightly different due to the different databases). Changing ignition on the sustainer from automatic to burnout does not help.

The ork files created in 15.03 and unstable can be found in this post on TRF since I can't figure out how to attach them here.

https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2249083

This is an edge case with an obvious workaround of making custom engine files aggregating motors, so it's not necessarily a high priority unless indicative of a deeper problem.

Edit: bug report now attached to 4th comment.

**Comment by questionablerocket** [comment]
Formattiing of the above report is wonky due to my forgetting how to paste code blocks into github.  The bug report can also be found in the aforementioned TRF post.

**Comment by JoePfeiffer** [comment]
You can attach them to issues and comments in github by changing the file extension. So call it rocket.ork.txt or some such and github will take it (if anyone can find a setting anywhere in github that will let it accept custom file extensions, we will be eternally grateful).
