### ISSUE TITLE
When exporting templates, draw fin roots correctly for fins-on-nose cones and fins-on-transitions

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1227]
As reported by @MadRocketer on TRF: https://www.rocketryforum.com/threads/announcement-openrocket-version-22-02-public-beta-is-underway-download-it-now.171295/post-2250080

When a fin is placed on a transition or nose cone, the exported template still shows a straight edge.
![image](https://user-images.githubusercontent.com/243872/156952771-830a44e2-97b3-4f2f-b3a7-b7399172269f.png)
Exports like this:
![image](https://user-images.githubusercontent.com/243872/156952807-b21c228c-5430-4601-9c99-29fdd80a0473.png)

Obviously it would be preferable for the exported template to show the correct root edge contour.

**Comment by hcraigmiller** [comment]
This may be associated with Issue #1021 "Bug: Fin root edge not drawn correctly on transitions". Although Issue #1021 references only transitions specifically, it applies to nose cones as well.

**Comment by neilweinstock** [comment]
Related but not the same.

**Comment by SiboVG** [comment]
Note: the issue is not only present in the exported template, in certain scenarios you can see the fin protruding the inside of the transition.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/11031519/184548496-b9a1dc2d-e308-4fad-bd4f-68b4e4a949c8.png">
