### ISSUE TITLE
Exception during simulation

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1243]
I was trying to simulate my XL5 ork file and got this exception, Ork file included, 

[xl5.zip](https://github.com/openrocket/openrocket/files/8240639/xl5.zip)

---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1.
2.
3.
Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- Exception stack trace ----------
net.sf.openrocket.gui.main.SwingExceptionHandler$InternalException: An exception occurred during the simulation at net.sf.openrocket.gui.main.SwingExceptionHandler.handleErrorCondition(SwingExceptionHandler.java:120) at net.sf.openrocket.gui.simulation.SimulationRunDialog$InteractiveSimulationWorker.simulationInterrupted(SimulationRunDialog.java:414) at net.sf.openrocket.gui.simulation.SimulationWorker.done(SimulationWorker.java:98) at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847) at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857) at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317) at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) at java.desktop/java.awt.Dialog.show(Dialog.java:1070) at java.desktop/java.awt.Component.show(Component.java:1716) at java.desktop/java.awt.Component.setVisible(Component.java:1663) at java.desktop/java.awt.Window.setVisible(Window.java:1031) at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005) at net.sf.openrocket.gui.main.SimulationPanel.activating(SimulationPanel.java:656) at net.sf.openrocket.gui.main.BasicFrame.stateChanged(BasicFrame.java:1734) at net.sf.openrocket.gui.main.BasicFrame_changeAdapter.stateChanged(BasicFrame.java:1747) at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418) at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269) at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143) at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74) at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622) at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597) at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4090) at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632) at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342) at java.desktop/java.awt.Component.processEvent(Component.java:6400) at java.desktop/java.awt.Container.processEvent(Container.java:2263) at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843) at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544) at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307) at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) Caused by: net.sf.openrocket.util.BugException: BUG: Simulation resulted in not-a-number (NaN) value, please report a bug, c=(NaN,NaN,NaN,w=NaN) at net.sf.openrocket.simulation.AbstractSimulationStepper.checkNaN(AbstractSimulationStepper.java:219) at net.sf.openrocket.simulation.RK4SimulationStepper.computeParameters(RK4SimulationStepper.java:299) at net.sf.openrocket.simulation.RK4SimulationStepper.step(RK4SimulationStepper.java:124) at net.sf.openrocket.simulation.BasicEventSimulationEngine.simulateLoop(BasicEventSimulationEngine.java:138) at net.sf.openrocket.simulation.BasicEventSimulationEngine.simulate(BasicEventSimulationEngine.java:90) at net.sf.openrocket.document.Simulation.simulate(Simulation.java:373) at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:55) at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:24) at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)

---------- Thread information ----------
Thread[AWT-EventQueue-0,6,main]

---------- System information ----------
OpenRocket version: 22.02.beta.01
OpenRocket source: default
OpenRocket location: C:\Program Files\OpenRocket\.\OpenRocket.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_US
System properties:
awt.toolkit=sun.awt.windows.WToolkit
exe4j.consoleCodepage=cp0
exe4j.isInstall4j=true
exe4j.launchName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.moduleName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.semaphoreName=Local\c:_program_files_openrocket_openrocket.exe0
exe4j.tempDir=
exe4j.unextractedPosition=0
file.encoding=Cp1252
file.separator=\
install4j.appDir=C:\Program Files\OpenRocket\
install4j.exeDir=C:\Program Files\OpenRocket\
install4j.launcherId=59
install4j.swt=false
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\OpenRocket\.install4j\i4jruntime.jar;C:\Program Files\OpenRocket\.\OpenRocket.jar
java.class.version=55.0
java.home=c:\program files\openrocket\jre
java.io.tmpdir=C:\Users\sj_h1\AppData\Local\Temp\
java.library.path=c:\program files\openrocket\jre\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ANT\apache-ant-1.9.14-bin\bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Users\sj_h1\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\sj_h1\AppData\Local\Programs\Python\Python39\;C:\Users\sj_h1\AppData\Local\Microsoft\WindowsApps;;C:\Users\sj_h1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\sj_h1\.dotnet\tools
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.14.1+1-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=11.0.14.1
java.version.date=2022-02-08
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=BellSoft
java.vm.version=11.0.14.1+1-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln18438591202770445851
line.separator=\u000d\u000a
os.arch=amd64
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=c:\program files\openrocket\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\OpenRocket\OpenRocket.exe
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=US
user.dir=C:\Program Files\OpenRocket
user.home=C:\Users\sj_h1
user.language=en
user.name=sj_h1
user.script=
user.timezone=America/Chicago
user.variant=
---------- Error log ----------
1 0.001 INFO (SwingStartup.java:62) Starting up OpenRocket version 22.02.beta.01
2 0.001 INFO (SwingStartup.java:65) Checking for graphics head
3 0.003 INFO (SwingStartup.java:76) Moving startup to EDT
4 0.121 INFO (SwingStartup.java:130) Initializing the splash screen
5 0.222 INFO (SwingStartup.java:134) Registering exception handler
6 0.227 INFO (SwingStartup.java:140) Loading databases
7 1.270 INFO (TranslatorProvider.java:49) Using default locale en_US
8 1.285 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 1.288 INFO (SwingStartup.java:152) Starting update check
10 1.293 INFO (SwingStartup.java:161) Setting best LAF
11 1.297 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
12 1.297 INFO (MotorDatabaseLoader.java:87) Starting reading serialized motor database
18 1.558 INFO (SwingStartup.java:173) Opening main application window
19 1.599 INFO (BasicFrame.java:1638) New action initiated
24 1.936 INFO (MotorDatabaseLoader.java:93) Ending reading serialized motor database, motorCount=1878
25 1.945 INFO (MotorDatabaseLoader.java:68) Starting reading user-defined motors
26 1.947 WARN (MotorDatabaseLoader.java:75) User-defined motor file C:\Users\sj_h1\AppData\Roaming\OpenRocket\ThrustCurves is neither file nor directory
27 1.947 INFO (MotorDatabaseLoader.java:78) Ending reading user-defined motors, motorCount=1878
90 2.717 INFO (UpdateInfoRetriever.java:156) Current build is newer
155 5.778 INFO (SwingStartup.java:195) Checking update status
156 5.779 INFO (SwingStartup.java:84) Startup complete
175 14.748 INFO (BasicFrame.java:1285) Starting OpenFileWorker
176 14.749 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@6aaeed68
177 14.754 INFO (OpenRocketLoader.java:42) Loading .ork file
208 0.000 DEBUG (-) ===== 112 DEBUG lines removed =====
208 14.821 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
209 14.821 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass]]
210 14.824 DEBUG (Rocket.java:574) Freezing Rocket
211 14.824 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
212 14.824 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass]]
213 14.827 DEBUG (Rocket.java:574) Freezing Rocket
214 14.827 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
215 14.827 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass]]
216 14.829 DEBUG (Rocket.java:574) Freezing Rocket
217 14.829 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
218 14.830 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero]]
219 14.836 DEBUG (Rocket.java:574) Freezing Rocket
220 14.836 DEBUG (Rocket.java:478) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
221 14.836 DEBUG (Rocket.java:600) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero]]
222 14.869 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=129.9 maxVelocity=48.825 maxAcceleration=102.68 maxMachNumber=0.14447 timeToApogee=5.1986 flightTime=40.908 groundHitVelocity=3.4767 launchRodVelocity=12.212
223 14.869 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=129.9 maxVelocity=48.825 maxAcceleration=102.68 maxMachNumber=0.14447 timeToApogee=5.1986 flightTime=40.908 groundHitVelocity=3.4767 launchRodVelocity=12.212
224 14.875 INFO (OpenRocketLoader.java:96) Loading done
225 14.965 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
226 14.965 DEBUG (BasicFrame.java:1351) Opening new frame with the document
227 14.965 DEBUG (BasicFrame.java:176) Instantiating new BasicFrame
230 14.968 DEBUG (BasicFrame.java:199) Constructing the BasicFrame UI
244 15.042 DEBUG (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
245 15.042 DEBUG (RocketFigure3d.java:142) Setting up GL capabilities...
256 0.000 VBOSE (-) ===== 96 VBOSE lines removed =====
256 15.045 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
257 15.045 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
258 15.045 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
259 15.046 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
260 15.046 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
261 15.047 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
262 15.048 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
263 15.048 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
264 15.049 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@311f91b3, current number of listeners is 11
265 15.054 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@105b8639, current number of listeners is 12
266 15.056 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@36dda8a6, current number of listeners is 13
267 15.056 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
268 15.056 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@f3acfc9
269 15.057 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@5479de10
270 15.057 VBOSE (DoubleModel.java:919) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@5479de10
271 15.057 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@63c578ea
272 15.114 INFO (RocketPanel.java:807) using pre-existing simulation
273 15.116 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
274 15.116 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@a15f3a7, current number of listeners is 14
275 15.116 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@ec85262, current number of listeners is 15
276 15.119 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
277 15.121 DEBUG (JarUtil.java:40) Found jar file using codeSource
278 15.121 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
279 15.137 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@7c76e03c, current number of listeners is 16
280 15.141 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@17feb5f, current number of listeners is 17
281 15.183 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
282 15.185 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.488237 user scale, 1845.31 overall scale
283 15.187 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.488237 user scale, 1845.31 overall scale
284 15.188 DEBUG (BasicFrame.java:279) ... Setting Initial Selection: [XL-5, Sustainer]
285 15.188 DEBUG (BasicFrame.java:283) BasicFrame instantiation complete
286 15.200 INFO (BasicFrame.java:1210) Closing window because it is replaceable
287 15.200 DEBUG (BasicFrame.java:1610) Disposing window
288 15.362 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1056]
289 15.365 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
290 15.366 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1056]
291 15.366 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
292 15.370 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
293 15.371 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
294 15.371 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
295 15.377 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1056]
296 15.379 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
297 15.380 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
298 15.381 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
299 15.382 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
300 15.382 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
301 15.390 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1056]
302 15.391 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
303 15.442 DEBUG (Simulation.java:371) Simulation: calling simulator
304 15.459 INFO (BasicEventSimulationEngine.java:88) >>Starting simulation of branch: Sustainer
305 15.460 VBOSE (BasicEventSimulationEngine.java:263) HandleEvents: current branch = Sustainer
306 15.460 VBOSE (BasicEventSimulationEngine.java:265) Obtained event from queue: FlightEvent[type=LAUNCH,time=0.0,source=XL-5,data=null]
307 15.460 VBOSE (BasicEventSimulationEngine.java:266) Remaining EventQueue = []
308 15.461 INFO (BasicEventSimulationEngine.java:293) Queueing Ignition Event for: Inner Tube/de11aec5 / C6 - Armed @: 0.0
309 15.461 VBOSE (BasicEventSimulationEngine.java:348) Handling event FlightEvent[type=LAUNCH,time=0.0,source=XL-5,data=null]
310 15.461 VBOSE (BasicEventSimulationEngine.java:265) Obtained event from queue: FlightEvent[type=IGNITION,time=0.0,source=Inner Tube,data=C6]
311 15.461 VBOSE (BasicEventSimulationEngine.java:266) Remaining EventQueue = []
312 15.461 VBOSE (BasicEventSimulationEngine.java:348) Handling event FlightEvent[type=IGNITION,time=0.0,source=Inner Tube,data=C6]
313 15.461 INFO (BasicEventSimulationEngine.java:359) Igniting motor: Inner Tube/de11aec5 / C6 - Armed @0.0
314 15.461 VBOSE (BasicEventSimulationEngine.java:137) Taking simulation step at t=0.0 altitude 0.0
315 15.480 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
316 15.481 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.751674 user scale, 2840.98 overall scale
317 15.507 DEBUG (SymmetricComponentCalc.java:389) vel = [ 1.2, 1.25, 1.3, 1.4, 1.6, 2.0, 2.4, ]
318 15.507 DEBUG (SymmetricComponentCalc.java:390) cd = [ 0.2631358093961808, 0.29168875144346373, 0.31069997799405985, 0.3254043696452452, 0.3365568942315719, 0.35346667013634764, 0.36176304276713284, ]
319 15.507 DEBUG (SymmetricComponentCalc.java:407) cdMach0 = 2.5193272907456552E-6
320 15.507 DEBUG (SymmetricComponentCalc.java:408) minDeriv = 0.5710588409456596
321 21.312 DEBUG (Simulation.java:371) Simulation: calling simulator
322 21.313 INFO (BasicEventSimulationEngine.java:88) >>Starting simulation of branch: Sustainer
323 21.313 VBOSE (BasicEventSimulationEngine.java:263) HandleEvents: current branch = Sustainer
324 21.313 VBOSE (BasicEventSimulationEngine.java:265) Obtained event from queue: FlightEvent[type=LAUNCH,time=0.0,source=XL-5,data=null]
325 21.313 VBOSE (BasicEventSimulationEngine.java:266) Remaining EventQueue = []
326 21.313 INFO (BasicEventSimulationEngine.java:293) Queueing Ignition Event for: Inner Tube/de11aec5 / C6 - Armed @: 0.0
327 21.313 VBOSE (BasicEventSimulationEngine.java:348) Handling event FlightEvent[type=LAUNCH,time=0.0,source=XL-5,data=null]
328 21.313 VBOSE (BasicEventSimulationEngine.java:265) Obtained event from queue: FlightEvent[type=IGNITION,time=0.0,source=Inner Tube,data=C6]
329 21.313 VBOSE (BasicEventSimulationEngine.java:266) Remaining EventQueue = []
330 21.313 VBOSE (BasicEventSimulationEngine.java:348) Handling event FlightEvent[type=IGNITION,time=0.0,source=Inner Tube,data=C6]
331 21.313 INFO (BasicEventSimulationEngine.java:359) Igniting motor: Inner Tube/de11aec5 / C6 - Armed @0.0
332 21.313 VBOSE (BasicEventSimulationEngine.java:137) Taking simulation step at t=0.0 altitude 0.0
333 21.316 DEBUG (SymmetricComponentCalc.java:389) vel = [ 1.2, 1.25, 1.3, 1.4, 1.6, 2.0, 2.4, ]
334 21.316 DEBUG (SymmetricComponentCalc.java:390) cd = [ 0.2631358093961808, 0.29168875144346373, 0.31069997799405985, 0.3254043696452452, 0.3365568942315719, 0.35346667013634764, 0.36176304276713284, ]
335 21.316 DEBUG (SymmetricComponentCalc.java:407) cdMach0 = 2.5193272907456552E-6
336 21.316 DEBUG (SymmetricComponentCalc.java:408) minDeriv = 0.5710588409456596
337 21.322 DEBUG (SimulationRunDialog.java:236) Progressbar value 0
338 21.322 DEBUG (SimulationRunDialog.java:241) No simulation status data available, setting empty labels
339 21.377 DEBUG (SimulationRunDialog.java:337) Method 1: t=0.0 est=1.8300017723084288
340 21.377 DEBUG (SimulationRunDialog.java:424) Setting progress to 0 (real 0)
341 21.377 DEBUG (SimulationRunDialog.java:236) Progressbar value 0
342 21.379 ERROR (SwingExceptionHandler.java:119) An exception occurred during the simulation
> net.sf.openrocket.util.BugException: BUG: Simulation resulted in not-a-number (NaN) value, please report a bug, c=(NaN,NaN,NaN,w=NaN) > at net.sf.openrocket.simulation.AbstractSimulationStepper.checkNaN(AbstractSimulationStepper.java:219) > at net.sf.openrocket.simulation.RK4SimulationStepper.computeParameters(RK4SimulationStepper.java:299) > at net.sf.openrocket.simulation.RK4SimulationStepper.step(RK4SimulationStepper.java:124) > at net.sf.openrocket.simulation.BasicEventSimulationEngine.simulateLoop(BasicEventSimulationEngine.java:138) > at net.sf.openrocket.simulation.BasicEventSimulationEngine.simulate(BasicEventSimulationEngine.java:90) > at net.sf.openrocket.document.Simulation.simulate(Simulation.java:373) > at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:55) > at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:24) > at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) > at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) > at java.base/java.lang.Thread.run(Thread.java:829)
343 21.379 INFO (SwingExceptionHandler.java:142) Running in EDT, showing dialog
344 21.379 INFO (SwingExceptionHandler.java:201) Showing Exception dialog
345 34.722 USER (SwingExceptionHandler.java:220) User requested sending bug report
346 34.725 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by sjh114961** [comment]
Problem goes away if you delete all freeform fins from the tail cone transition.

**Comment by hcraigmiller** [comment]
The error is not related to the existence or absence of the tail cone fins. The error is triggered when the height of the fin above the zero-line is less than or equal to 0. The minimum height above the zero-line without error ranges from .001 to .02 inches, depending upon the shape of the fin; a negative maximum fin height always triggers an error.

**Comment by SiboVG** [comment]
Fixed in #1247
