### ISSUE TITLE
I/O error while saving model

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1245]
I am trying save a mode and getting I/O error. See included screenshot.
![ORERROR](https://user-images.githubusercontent.com/53155232/158279543-f0ec9b18-9133-4e3c-b8e9-a934948f4e2c.png)

**Comment by hcraigmiller** [comment]
More information is likely going to be needed. Can you provide the .ork design file in blocks that can be saved, that can be assembled to create the design that you cannot save, and/or can you provide a bug file?

**Comment by sjh114961** [comment]
Well, since it gave me an error trying to save it, no. No bug file as far as I know was created.

**Comment by hcraigmiller** [comment]
This appears to be the Black Star Voyager 5 design for which the .ork file was posted on the OpenRocket Facebook page about five hours ago, with the tag line (by @sjh114961 ): "My latest creation. This one was extremely taxing, took me about a week to figure how to do the triangular fins."

In light of the lack of information provided by the user to enable this Issue to be analyzed and resolved, and, absent further information from the User, I recommend that this issue be closed.

**Comment by neilweinstock** [comment]
I'm going to have to have a look at this one.  It's not clear to me why all the pods were necessary to do this rocket; in fact I suspect the above model could have been created with zero use of pods.  But I'll need to look more closely.

> That said, the design does produce a side view that bears some looking in to.

Both the side view and the 3D view still do not calculate extents correctly to include all pod and internal elements.  I have more issues to file once I do a little more work to isolate the issue.

> That said, this appears to be the type of design that would benefit from inner body tube extensions such as those described by @neilweinstock in his new feature request Issue #1056.

There are many many many designs that would benefit from that feature.

**Comment by hcraigmiller** [comment]
If you want to play with this one... here's one with a corrected airframe {no pods, no discontinuities].

![BlackStarVoyager5 Side_View](https://user-images.githubusercontent.com/68821492/158392983-3df68515-7f3d-48c0-bbc2-33d6571083b6.png)

[BlackStarVoyager5.Deconstruct.Airframe.ork.txt](https://github.com/openrocket/openrocket/files/8253924/BlackStarVoyager5.Deconstruct.Airframe.ork.txt)
[BlackStarVoyager5.Deconstruct.Airframe.Fins.ork.txt](https://github.com/openrocket/openrocket/files/8253931/BlackStarVoyager5.Deconstruct.Airframe.Fins.ork.txt)

Have fun...

**Comment by sjh114961** [comment]
I got one that works, thanks.

**Comment by neilweinstock** [comment]
Closing this.
