### ISSUE TITLE
Nose cone shape menu doesn't change on preset selection

### ISSUE THREAD

**Issue by LithosphereRocketry** [openrocket/openrocket#1246]
Setting a nose cone to a preset doesn't seem to set its shape profile correctly in the UI. Upon selecting a conical preset from the menu, the dropdown still says ogive:
![image](https://user-images.githubusercontent.com/33179745/158398094-cec9f027-7d96-4812-9a7c-59eb91ff453e.png)

Closing and reopening the configuration popup fixes the issue and it shows up as conical as it should.

Observed on Windows 10 on both 1503 and 22.02.beta.01.

**Comment by hcraigmiller** [comment]
Feature functions as expected; no anomalies found. 

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]
