### ISSUE TITLE
Opening RocSim file always seems to put the fins in the wrong place.

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1248]
On every RocSim file I have opened the fins are out of place. It works fine in 15.03. Example included
![Xray](https://user-images.githubusercontent.com/53155232/158663167-436d07e4-bc89-46ab-a7b2-1adcbbd86cea.png)
[oop_estes_x_ray.zip](https://github.com/openrocket/openrocket/files/8268736/oop_estes_x_ray.zip)

**Comment by SiboVG** [comment]
This issue has been resolved in #1164
