### ISSUE TITLE
Cannot see full model in 3D

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1249]
There is no zoom function, so I have relied on the code to fit entire model, which it does NOT.
![Screenshot_1](https://user-images.githubusercontent.com/53155232/158687513-0f96db33-f7c3-4333-9df8-61fddfb4ba4f.png)
[FlatCat.zip](https://github.com/openrocket/openrocket/files/8273864/FlatCat.zip)

**Comment by hcraigmiller** [comment]
Not reproducible using current unstable.

![3D Finished View](https://user-images.githubusercontent.com/68821492/158699709-e5e9aee7-5fcc-476d-8edc-216ad6d68e69.png)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by SiboVG** [comment]
Hm, also not an issue on my machine; macOS Monterey 12.2.1, MacBook Pro M1

**Comment by hcraigmiller** [comment]
@sjh114961, would you provide the following screen shots, or the same information by other means:

![System_Info](https://user-images.githubusercontent.com/68821492/158709594-3675c92b-4067-47e8-910a-14e128a7c135.png)

What you are describing has not yet been able to be reproduced, and this information may help. Also, if you would open the file, set the view to _3D Finished_, then select _Help->Bug report_, and provide that report as well, that may also help identify your issue.

**Comment by sjh114961** [comment]
![Or1](https://user-images.githubusercontent.com/53155232/158905019-ea9d1143-9ff7-4282-bacd-d14e023a2e10.png)

**Comment by SiboVG** [comment]
Can you enable 'Use Off-screen Rendering' and report back the effect?

**Comment by sjh114961** [comment]
It is working now with the checkbox on or off.

**Comment by hcraigmiller** [comment]
FYI, after you change any of those three settings, you must exit OpenRocket and restart the application to give effect to the change. So, if you check all three boxes, exit and restart OpenRocket, then the 3D display panel shows the entire rocket correctly, is that true?

**Comment by sjh114961** [comment]
I did what you asked and its working fine either way.

**Comment by JoePfeiffer** [comment]
sounds like this has been resolved.

**Comment by sjh114961** [comment]
Too bad there isn't a "watch" status. I do agree it can't seem to be re-created.
