### ISSUE TITLE
[Bug] can't read selected rows in tables on Linux

### ISSUE THREAD

**Issue by cabbey** [openrocket/openrocket#1257]
I'm running on Ubuntu Linux 21.10.

Anywhere in the UI that uses a table is rendering with the selected cell/row of the table in black text on a black background. A similar color contrast issue is present when rendering dropdowns. This can be seen with both the 22.02.beta.01 installer delivered file and with a locally built jar from the unstable branch at 0adcf040ba84059a831cc4d2ad3426a977f0df91

![OR showing black text on black background simulation list](https://user-images.githubusercontent.com/522147/159594664-ec949637-a0ef-4bb7-b080-ddaaa56d909a.png)

![motor config](https://user-images.githubusercontent.com/522147/159594673-ce3a74af-c536-4f33-bbfb-c2002e918f4f.png)

![drop down](https://user-images.githubusercontent.com/522147/159594681-137760de-3e60-4b24-bc1a-f3ce23612abe.png)

---------- System information ----------
OpenRocket version: 22.02.beta.01
OpenRocket source: default
OpenRocket location: /home/cabbey/OpenRocket/OpenRocket.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_US
System properties:
awt.toolkit=sun.awt.X11.XToolkit
exe4j.moduleName=/home/cabbey/OpenRocket/OpenRocket
file.encoding=UTF-8
file.separator=/
install4j.appDir=/home/cabbey/OpenRocket/
install4j.exeDir=/home/cabbey/OpenRocket/
install4j.jvmDir=/home/cabbey/OpenRocket/jre
install4j.launcherId=59
install4j.swt=false
java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
java.awt.printerjob=sun.print.PSPrinterJob
java.class.path=/home/cabbey/OpenRocket/.install4j/i4jruntime.jar:/home/cabbey/OpenRocket/.install4j/launcher47cd7162.jar:/home/cabbey/OpenRocket/OpenRocket.jar
java.class.version=55.0
java.home=/home/cabbey/OpenRocket/jre
java.io.tmpdir=/tmp
java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.net.useSystemProxies=true
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.14.1+1-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=11.0.14.1
java.version.date=2022-02-08
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=BellSoft
java.vm.version=11.0.14.1+1-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln3240169098456319610
line.separator=\u000a
os.arch=amd64
os.name=Linux
os.version=5.13.0-37-generic
path.separator=:
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=/home/cabbey/OpenRocket/jre/lib
sun.cpu.endian=little
sun.cpu.isalist=
sun.desktop=gnome
sun.font.fontmanager=sun.awt.X11FontManager
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=install4j.net.sf.openrocket.startup.OpenRocket
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=UTF-8
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=unknown
user.country=US
user.dir=/home/cabbey/OpenRocket
user.home=/home/cabbey
user.language=en
user.name=cabbey
user.timezone=America/Los_Angeles
---------- Error log ----------
1 0.001 INFO (SwingStartup.java:62) Starting up OpenRocket version 22.02.beta.01
2 0.001 INFO (SwingStartup.java:65) Checking for graphics head
3 0.002 INFO (SwingStartup.java:76) Moving startup to EDT
4 0.060 INFO (SwingStartup.java:130) Initializing the splash screen
5 0.117 INFO (SwingStartup.java:134) Registering exception handler
6 0.121 INFO (SwingStartup.java:140) Loading databases
7 0.691 INFO (TranslatorProvider.java:49) Using default locale en_US
8 0.701 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 0.702 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
10 0.703 INFO (MotorDatabaseLoader.java:87) Starting reading serialized motor database
11 0.704 INFO (SwingStartup.java:152) Starting update check
14 0.707 INFO (SwingStartup.java:161) Setting best LAF
18 0.854 INFO (MotorDatabaseLoader.java:93) Ending reading serialized motor database, motorCount=1878
19 0.856 INFO (MotorDatabaseLoader.java:68) Starting reading user-defined motors
20 0.856 INFO (MotorDatabaseLoader.java:78) Ending reading user-defined motors, motorCount=1878
21 0.908 INFO (SwingStartup.java:173) Opening main application window
25 0.919 INFO (BasicFrame.java:1638) New action initiated
81 0.000 DEBUG (-) ===== 59 DEBUG lines removed =====
81 1.094 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/quest.orc
82 1.100 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/quest.orc contained 71 presets
83 1.100 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc-legacy.orc
84 1.100 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc-legacy.orc
85 1.155 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc-legacy.orc contained 874 presets
86 1.156 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc.orc
87 1.156 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc.orc
90 1.216 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc.orc contained 1676 presets
91 1.220 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/top_flight.orc
92 1.220 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/top_flight.orc
93 1.223 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/top_flight.orc contained 34 presets
94 1.225 DEBUG (ComponentPresetDatabaseLoader.java:59) Time to load presets: 523ms 4311 loaded from 21 files
95 1.233 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
105 1.470 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
106 1.478 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: OpenRocket_technical_documentation-v13.05
107 1.478 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: Development_of_an_Open_Source_model_rocket_simulation-thesis-v20090520
108 1.479 INFO (UpdateInfoRetriever.java:156) Current build is newer
110 1.501 DEBUG (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
111 1.501 DEBUG (RocketFigure3d.java:142) Setting up GL capabilities...
143 1.869 DEBUG (JarUtil.java:40) Found jar file using codeSource
144 1.869 DEBUG (ExampleDesignFile.java:118) Current jar file is: /home/cabbey/OpenRocket/OpenRocket.jar
150 1.946 DEBUG (BasicFrame.java:279) ... Setting Initial Selection: [Rocket, Sustainer]
151 1.946 DEBUG (BasicFrame.java:283) BasicFrame instantiation complete
152 1.951 INFO (SwingStartup.java:195) Checking update status
153 1.952 INFO (SwingStartup.java:84) Startup complete
163 7.390 INFO (BasicFrame.java:1252) Opening file from url=jar:file:/home/cabbey/OpenRocket/OpenRocket.jar!/datafiles/examples/Three-stage rocket.ork filename=Three-stage rocket.ork
165 7.395 INFO (BasicFrame.java:1285) Starting OpenFileWorker
166 7.397 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@71cd20aa
167 7.402 INFO (OpenRocketLoader.java:42) Loading .ork file
169 7.428 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation A8, diameter 0.018, length 0.07, digest 22aec01287ea1e3b8c6f66b26fe5fea6, warnings WarningSet[]
170 7.430 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation C6, diameter 0.018, length 0.07, digest c8743ef3fa99e14a89885cbe0ead47b2, warnings WarningSet[]
171 7.432 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation C6, diameter 0.018, length 0.07, digest c8743ef3fa99e14a89885cbe0ead47b2, warnings WarningSet[]
173 7.444 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation B6, diameter 0.018, length 0.07, digest ebc2af7f8c6f8665d1bec720ddc2b5e1, warnings WarningSet[]
174 7.445 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation B6, diameter 0.018, length 0.07, digest ebc2af7f8c6f8665d1bec720ddc2b5e1, warnings WarningSet[]
175 7.446 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation C6, diameter 0.018, length 0.07, digest c8743ef3fa99e14a89885cbe0ead47b2, warnings WarningSet[]
177 7.454 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation B6, diameter 0.018, length 0.07, digest ebc2af7f8c6f8665d1bec720ddc2b5e1, warnings WarningSet[]
178 7.455 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation B6, diameter 0.018, length 0.07, digest ebc2af7f8c6f8665d1bec720ddc2b5e1, warnings WarningSet[]
179 7.456 DEBUG (DatabaseMotorFinder.java:48) type Single-use, manufacturer Estes, designation C6, diameter 0.018, length 0.07, digest c8743ef3fa99e14a89885cbe0ead47b2, warnings WarningSet[]
180 7.491 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=245.06 maxVelocity=78.63 maxAcceleration=118.05 maxMachNumber=0.23249 timeToApogee=5.9729 flightTime=64.973 groundHitVelocity=0.0 launchRodVelocity=11.365
181 7.491 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=245.06 maxVelocity=78.63 maxAcceleration=118.05 maxMachNumber=0.23249 timeToApogee=5.9729 flightTime=64.973 groundHitVelocity=0.0 launchRodVelocity=11.365
182 7.514 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=469.82 maxVelocity=118.52 maxAcceleration=169.68 maxMachNumber=0.35041 timeToApogee=8.9791 flightTime=122.01 groundHitVelocity=0.0 launchRodVelocity=10.714
183 7.514 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=469.82 maxVelocity=118.52 maxAcceleration=169.68 maxMachNumber=0.35041 timeToApogee=8.9791 flightTime=122.01 groundHitVelocity=0.0 launchRodVelocity=10.714
184 7.546 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=659.05 maxVelocity=131.86 maxAcceleration=153.93 maxMachNumber=0.39096 timeToApogee=10.97 flightTime=168.94 groundHitVelocity=0.0 launchRodVelocity=10.503
185 7.546 DEBUG (FlightData.java:247) Computed flight values: maxAltitude=659.05 maxVelocity=131.86 maxAcceleration=153.93 maxMachNumber=0.39096 timeToApogee=10.97 flightTime=168.94 groundHitVelocity=0.0 launchRodVelocity=10.503
186 7.547 INFO (OpenRocketLoader.java:96) Loading done
187 7.598 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
188 7.598 DEBUG (BasicFrame.java:1351) Opening new frame with the document
189 7.600 DEBUG (BasicFrame.java:176) Instantiating new BasicFrame
192 7.606 DEBUG (BasicFrame.java:199) Constructing the BasicFrame UI
206 7.689 DEBUG (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
207 7.689 DEBUG (RocketFigure3d.java:142) Setting up GL capabilities...
234 0.000 VBOSE (-) ===== 106 VBOSE lines removed =====
234 7.703 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@505f765d
235 7.726 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
236 7.727 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@5556d3da, current number of listeners is 14
237 7.727 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@69f18f27, current number of listeners is 15
238 7.728 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
239 7.730 DEBUG (JarUtil.java:40) Found jar file using codeSource
240 7.730 DEBUG (ExampleDesignFile.java:118) Current jar file is: /home/cabbey/OpenRocket/OpenRocket.jar
241 7.733 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@5ae8c3b3, current number of listeners is 16
242 7.737 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@40481a5c, current number of listeners is 17
243 7.762 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
244 7.762 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.430608 user scale, 1627.49 overall scale
245 7.763 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.430608 user scale, 1627.49 overall scale
246 7.764 DEBUG (BasicFrame.java:279) ... Setting Initial Selection: [Three-staged rocket, Sustainer]
247 7.764 DEBUG (BasicFrame.java:283) BasicFrame instantiation complete
248 7.766 INFO (BasicFrame.java:1210) Closing window because it is replaceable
249 7.766 DEBUG (BasicFrame.java:1610) Disposing window
250 7.777 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.configdialog.ComponentConfigDialog[dialog0,68,34,0x0,invalid,hidden,layout=java.awt.BorderLayout,MODELESS,title=,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@41d9d0a9,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true], current number of listeners is 18
251 7.780 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@5e1f957b, current number of listeners is 19
252 7.780 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@5e1f957b, current number of listeners is 19
253 7.780 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@439d1f05, current number of listeners is 20
254 7.782 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideMass] adding listener (total 1): javax.swing.JSpinner$ModelListener@54ef162
255 7.783 VBOSE (DoubleModel.java:897) DoubleModel[constant=1.0] adding listener (total 1): net.sf.openrocket.gui.adaptors.DoubleModel$ValueSliderModel@77afe136
256 7.783 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideMass] adding listener (total 2): javax.swing.JSlider$ModelListener@598db40
257 7.783 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideMass] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@62e034fe
258 7.785 VBOSE (DoubleModel.java:919) DoubleModel[Rocket:OverrideMass] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@62e034fe
259 7.785 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideMass] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@331465d2
260 7.785 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@78bb1a2b, current number of listeners is 21
261 7.785 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@78bb1a2b, current number of listeners is 21
262 7.786 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@b355a52, current number of listeners is 22
263 7.786 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCGX] adding listener (total 1): javax.swing.JSpinner$ModelListener@64c6fbcf
264 7.788 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.adaptors.DoubleModel$ValueSliderModel@20277ff
265 7.788 VBOSE (DoubleModel.java:897) DoubleModel[constant=1.12] adding listener (total 1): net.sf.openrocket.gui.adaptors.DoubleModel$ValueSliderModel@20277ff
266 7.788 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCGX] adding listener (total 2): javax.swing.JSlider$ModelListener@51c9fcf3
267 7.788 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCGX] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@739ebccb
268 7.788 VBOSE (DoubleModel.java:919) DoubleModel[Rocket:OverrideCGX] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@739ebccb
269 7.788 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCGX] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@72abb011
270 7.788 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@7db7dad3, current number of listeners is 23
271 7.788 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@7db7dad3, current number of listeners is 23
272 7.789 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@54cd450a, current number of listeners is 24
273 7.790 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCD] adding listener (total 1): javax.swing.JSpinner$ModelListener@bf4159b
274 7.791 VBOSE (DoubleModel.java:897) DoubleModel[constant=1.0] adding listener (total 1): net.sf.openrocket.gui.adaptors.DoubleModel$ValueSliderModel@79e4342d
275 7.791 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCD] adding listener (total 2): javax.swing.JSlider$ModelListener@473fcb0e
276 7.791 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCD] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@6ccc56bf
277 7.791 VBOSE (DoubleModel.java:919) DoubleModel[Rocket:OverrideCD] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@6ccc56bf
278 7.791 VBOSE (DoubleModel.java:897) DoubleModel[Rocket:OverrideCD] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@155831c5
279 7.791 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@749bff02, current number of listeners is 25
280 7.791 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@749bff02, current number of listeners is 25
281 7.809 INFO (OpenRocketDocument.java:536) Adding undo position 'Modify Rocket' to net.sf.openrocket.document.OpenRocketDocument@33c5b84a, document was in clean state
282 7.877 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
283 7.877 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
284 7.878 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
285 7.880 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
286 7.881 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
287 7.881 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
288 7.919 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
289 7.920 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.562712 user scale, 2126.79 overall scale
290 10.488 DEBUG (GUIUtil.java:232) Clearing all models of window net.sf.openrocket.gui.configdialog.ComponentConfigDialog[dialog0,1525,549,555x462,invalid,hidden,layout=java.awt.BorderLayout,MODELESS,title= Rocket configuration,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,37,555x425,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@41d9d0a9,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
291 10.491 DEBUG (MemoryManagement.java:56) Adding object into collectable list: net.sf.openrocket.gui.configdialog.ComponentConfigDialog[dialog0,1525,549,555x462,invalid,hidden,layout=java.awt.BorderLayout,MODELESS,title= Rocket configuration,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,37,555x425,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@41d9d0a9,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
292 10.492 VBOSE (Rocket.java:446) Removed ComponentChangeListener net.sf.openrocket.gui.configdialog.ComponentConfigDialog[dialog0,1525,549,555x462,invalid,hidden,layout=java.awt.BorderLayout,MODELESS,title= Rocket configuration,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,37,555x425,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@41d9d0a9,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true], current number of listeners is 24
293 17.130 USER (BasicFrame.java:822) Bug report selected
294 17.134 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by JoePfeiffer** [comment]
Do you have any other desktops available to you?  I've been doing all of my development under Debian, with the xfce desktop, and have not observed this.  Installing gnome now...

**Comment by cabbey** [comment]
I've just noticed that it's NOT present with the OS installed JVM, only with the one the installer choose to install:

works fine:
```
cabbey@cheshire:~$ java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.22.10)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.22.10, mixed mode, sharing)
```
shows the problem:
```
cabbey@cheshire:~$ OpenRocket/jre/bin/java --version
openjdk 11.0.14.1 2022-02-08 LTS
OpenJDK Runtime Environment (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-LTS, mixed mode)
```

**Comment by cabbey** [comment]
@JoePfeiffer as you mentioned on slack,  I'm suspecting it's something about the modifications Ubuntu or Debian are making to the upstream build. I've been poking at what all they change and, well, it's a lot, and nothing seems to jump out as the key change. http://archive.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-lts_11.0.14+9-0ubuntu2~22.10.debian.tar.xz

One of the big things they do is step the default gtk back to version 2 instead of version 3... playing with that I stumbled over an interesting observation... when it is legible, I get this error logged from the jvm. (note, I get this error with *all* java apps that use swing.)

```
Gtk-Message: 20:42:32.091: Failed to load module "canberra-gtk-module"
```
if I don't get that message, either because I use gtk3 with the installed jvm, or because I use any version of gtk with the bundled jvm, then I can't see the text. Sadly that error message doesn't seem to lead to any of the changes they are making to the jvm.

**Comment by jimmiedave** [comment]
Checked a minute ago: I'm on Ubuntu 20.04 LTS, and have no legibility problem, but notice that Ubuntu and OpenRocket appear to have the same (or very close) JVM versions  installed:

```
~$ java --version
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

```
```
~$ OpenRocket/jre/bin/java --version
openjdk 11.0.14.1 2022-02-08 LTS
OpenJDK Runtime Environment (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-LTS, mixed mode)

```

**Comment by SiboVG** [comment]
This should be fixed after the switch from Linux's native LAF to FlatLaf.
