### ISSUE TITLE
Bug upon launch

### ISSUE THREAD

**Issue by mornawka** [openrocket/openrocket#1262]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1. Downloaded jar file from website
2. Opened OpenRocket and bug immediately presented itself
3.
Include your email address (optional; it helps if we can contact you in case we need additional information):

matt48763@hotmail.com

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List; at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)

---------- Thread information ----------
Thread[UpdateInfoFetcher,6,main]

---------- System information ----------
OpenRocket version: 22.02.beta.01
OpenRocket source: default
OpenRocket location: C:\Users\matt4\Downloads\OpenRocket-22.02.beta.01.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_CA
System properties:
awt.toolkit=sun.awt.windows.WToolkit
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Users\matt4\Downloads\OpenRocket-22.02.beta.01.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files (x86)\Java\jre1.8.0_191\lib\endorsed
java.ext.dirs=C:\Program Files (x86)\Java\jre1.8.0_191\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
java.home=C:\Program Files (x86)\Java\jre1.8.0_191
java.io.tmpdir=C:\Users\matt4\AppData\Local\Temp\
java.library.path=C:\Program Files (x86)\Java\jre1.8.0_191\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X64\;C:\Program Files (x86)\Pulse Secure\VC142.CRT\X86\;C:\Program Files (x86)\Common Files\Pulse Secure\TNC Client Plugin\;C:\Users\matt4\AppData\Local\Microsoft\WindowsApps;C:\Users\matt4\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Nmap;;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_191-b12
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.util.Arrays.useLegacyMergeSort=true
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_191
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) Client VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.191-b12
jnlp.jogamp.tmp.cache.root=jln8682483593138951088
line.separator=\u000d\u000a
os.arch=x86
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=32
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.class.path=C:\Program Files (x86)\Java\jre1.8.0_191\lib\resources.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\rt.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\sunrsasign.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\jsse.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\jce.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\charsets.jar;C:\Program Files (x86)\Java\jre1.8.0_191\lib\jfr.jar;C:\Program Files (x86)\Java\jre1.8.0_191\classes
sun.boot.library.path=C:\Program Files (x86)\Java\jre1.8.0_191\bin
sun.cpu.endian=little
sun.cpu.isalist=pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Users\matt4\Downloads\OpenRocket-22.02.beta.01.jar
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot Client Compiler
sun.os.patch.level=
user.country=CA
user.dir=C:\Users\matt4\Downloads
user.home=C:\Users\matt4
user.language=en
user.name=matt4
user.script=
user.timezone=America/Denver
user.variant=
---------- Error log ----------
1 0.006 INFO (SwingStartup.java:62) Starting up OpenRocket version 22.02.beta.01
2 0.006 INFO (SwingStartup.java:65) Checking for graphics head
3 0.046 INFO (SwingStartup.java:76) Moving startup to EDT
4 0.109 INFO (SwingStartup.java:130) Initializing the splash screen
5 0.165 INFO (SwingStartup.java:134) Registering exception handler
6 0.168 INFO (SwingStartup.java:140) Loading databases
7 1.372 INFO (TranslatorProvider.java:49) Using default locale en_CA
8 1.376 INFO (TranslatorProvider.java:61) Set up translation for locale en_CA, debug.currentFile=messages.properties
9 1.385 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
10 1.385 INFO (MotorDatabaseLoader.java:87) Starting reading serialized motor database
11 1.387 INFO (SwingStartup.java:152) Starting update check
17 1.400 INFO (SwingStartup.java:161) Setting best LAF
18 1.525 INFO (SwingStartup.java:173) Opening main application window
19 1.537 INFO (BasicFrame.java:1638) New action initiated
21 1.650 INFO (MotorDatabaseLoader.java:93) Ending reading serialized motor database, motorCount=1878
22 1.653 INFO (MotorDatabaseLoader.java:68) Starting reading user-defined motors
23 1.654 INFO (MotorDatabaseLoader.java:78) Ending reading user-defined motors, motorCount=1878
58 0.000 DEBUG (-) ===== 36 DEBUG lines removed =====
58 1.847 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/estes_ps2.orc contained 30 presets
59 1.847 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/fliskits-legacy.orc
60 1.847 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/fliskits-legacy.orc
61 1.863 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/fliskits-legacy.orc contained 160 presets
62 1.863 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/generic_materials.orc
63 1.863 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/generic_materials.orc
64 1.866 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/generic_materials.orc contained 0 presets
65 1.866 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/giantleaprocketry-legacy.orc
66 1.866 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/giantleaprocketry-legacy.orc
67 1.869 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/giantleaprocketry-legacy.orc contained 74 presets
68 1.869 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/loc_precision.orc
69 1.869 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/loc_precision.orc
70 1.874 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/loc_precision.orc contained 64 presets
71 1.874 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/madcow.orc
72 1.874 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/madcow.orc
73 1.886 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/madcow.orc contained 240 presets
74 1.887 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/mpc.orc
75 1.887 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/mpc.orc
76 1.889 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/mpc.orc contained 49 presets
77 1.890 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/publicmissiles-legacy.orc
78 1.890 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/publicmissiles-legacy.orc
79 1.900 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/publicmissiles-legacy.orc contained 115 presets
80 1.900 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/quest.orc
81 1.900 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/quest.orc
82 1.908 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/quest.orc contained 71 presets
83 1.909 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc-legacy.orc
84 1.909 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc-legacy.orc
85 2.054 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc-legacy.orc contained 874 presets
86 2.055 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc.orc
87 2.055 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc.orc
90 2.140 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc.orc contained 1676 presets
91 2.143 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/top_flight.orc
92 2.143 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/top_flight.orc
93 2.144 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/top_flight.orc contained 34 presets
94 2.159 DEBUG (ComponentPresetDatabaseLoader.java:59) Time to load presets: 782ms 4311 loaded from 21 files
99 0.000 VBOSE (-) ===== 10 VBOSE lines removed =====
99 2.235 VBOSE (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
100 2.356 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@11aeeff, current number of listeners is 7
101 2.360 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@4d3e3e, current number of listeners is 8
102 2.362 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.RecoveryConfigurationPanel$$Lambda$35/358952@1375add, current number of listeners is 9
103 2.364 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$4@15ddefd, current number of listeners is 10
104 2.379 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
105 2.396 DEBUG (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
106 2.396 DEBUG (RocketFigure3d.java:142) Setting up GL capabilities...
107 2.396 VBOSE (RocketFigure3d.java:144) GL - Getting Default Profile
108 2.487 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
109 2.880 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
110 2.885 ERROR (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[UpdateInfoFetcher,6,main]
> java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List; > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362) > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142) > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)
111 2.886 STDERR (SwingExceptionHandler.java:49) java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List;
112 2.886 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362)
113 2.886 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142)
114 2.886 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)
115 2.886 INFO (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
116 3.315 VBOSE (RocketFigure3d.java:147) GL - creating GLCapabilities
117 3.315 VBOSE (RocketFigure3d.java:151) GL - setSampleBuffers
118 3.316 VBOSE (RocketFigure3d.java:154) GL - setNumSamples
119 3.316 VBOSE (RocketFigure3d.java:164) GL - Creating GLCanvas
120 3.322 VBOSE (RocketFigure3d.java:168) GL - Registering as GLEventListener on canvas
121 3.322 VBOSE (RocketFigure3d.java:171) GL - Adding canvas to this JPanel
122 3.322 VBOSE (RocketFigure3d.java:174) GL - Setting up mouse listeners
123 3.322 VBOSE (RocketFigure3d.java:177) GL - Rasterizing Carets
124 3.335 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@e793a2
125 3.335 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
126 3.335 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
127 3.335 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
128 3.335 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
129 3.336 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
130 3.336 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
131 3.336 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
132 3.336 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
133 3.337 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@1e069ed, current number of listeners is 11
134 3.343 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@1c2ed80, current number of listeners is 12
135 3.344 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@11e9b0a, current number of listeners is 13
136 3.345 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
137 3.347 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@1597b97
138 3.347 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@81c4d
139 3.348 VBOSE (DoubleModel.java:919) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@81c4d
140 3.348 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@1859010
141 3.643 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
142 3.643 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@80fbf8, current number of listeners is 14
143 3.643 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@1c97465, current number of listeners is 15
144 3.644 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
145 3.652 DEBUG (JarUtil.java:40) Found jar file using codeSource
146 3.652 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Users\matt4\Downloads\OpenRocket-22.02.beta.01.jar
147 3.671 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@11d9535, current number of listeners is 16
148 3.676 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@f25c8b, current number of listeners is 17
149 3.733 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
150 3.734 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.413544 user scale, 1563.00 overall scale
151 3.738 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.413544 user scale, 1563.00 overall scale
152 3.738 DEBUG (BasicFrame.java:279) ... Setting Initial Selection: [Rocket, Sustainer]
153 3.738 DEBUG (BasicFrame.java:283) BasicFrame instantiation complete
154 3.763 INFO (SwingStartup.java:195) Checking update status
155 3.764 INFO (SwingStartup.java:84) Startup complete
156 3.857 INFO (SwingExceptionHandler.java:201) Showing Exception dialog
157 3.909 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
158 3.910 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
159 3.911 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
160 3.911 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
161 3.912 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
162 3.916 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
163 3.916 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
164 3.917 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
165 3.918 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
166 3.918 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
167 3.918 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
168 3.925 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
169 3.925 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
170 4.027 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
171 4.028 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
172 16.576 USER (SwingExceptionHandler.java:220) User requested sending bug report
173 16.578 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by SiboVG** [comment]
You are running OpenRocket from java 8. OpenRocket should run using Java 11, or you can run it with the [packaged installer](https://github.com/openrocket/openrocket/releases/download/release-22.02.beta.01/OpenRocket-22.02.beta.01-Windows.exe).
