### ISSUE TITLE
[Bug/FYI] Screen layering when application opens

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1271]
An RTF user reported the following:

![1648495178674](https://user-images.githubusercontent.com/68821492/160473768-c6431360-de73-44b6-9c10-d64d776908fb.png)

This was the fix the user found: "Basically what I did is, I switched the Graphical settings from NVIDIA to Intel Integrated. Seems to do the trick (so far). I will keep testing it, and in case I get the same glitch again, I'll let you know."

The user installed Beta 2 and does not have Java installed on the device.

**Comment by neilweinstock** [comment]
OK, it sounds like it was fixed... maybe a good thing to document for future reference?

**Comment by SiboVG** [comment]
> OK, it sounds like it was fixed... maybe a good thing to document for future reference?

Documentation fixed [here](http://wiki.openrocket.info/FAQ#Windows_Graphics_Settings) by @hcraigmiller

**Comment by Reysean05** [comment]
Same issue, but I dont have integrated graphics to switch to.
