### ISSUE TITLE
[Bug] Preferences --> Simulation --> Simulation Options: Reset to Default button has no effect

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1278]
If the _Preferences_ &rarr; _Simulation_ &rarr; _Simulation Options_ are changed, then the _Reset to Default_ button clicked, the default settings are not restored.

**Comment by RemingtonHolder** [comment]
I was testing this out in the most current build and this button only resets the time step, is the only other thing it needs to reset the Geodetic Calculations?
