### ISSUE TITLE
[Bug] Incorrectly Reporting Stability Percentage on 2 Stage Rockets

### ISSUE THREAD

**Issue by abean74525** [openrocket/openrocket#1283]
When calculating the stability percentage for separate stages, Open Rocket takes the full length of the rocket instead of just the length of the stage, underreporting the stability.

shows 8% for sustainer when acutally 16%
shows 11% for booster when actually 20%

Using openrocket 22.02 beta, windows 10. 

![sustainer](https://user-images.githubusercontent.com/72224230/162257131-8fb36bfc-a33a-472d-90c7-f2aba1288ee9.png)
![full rocket](https://user-images.githubusercontent.com/72224230/162257133-37fa5524-f85b-4fc1-b2de-af6afe7f3e93.PNG)
![booster](https://user-images.githubusercontent.com/72224230/162257135-d3730a08-385a-434c-a331-68d107a21ea0.png)

**Comment by hcraigmiller** [comment]
Assuming there are no active overrides:
![Percentage](https://user-images.githubusercontent.com/68821492/162362155-b7972652-4b11-4364-a7ce-38fc6e6d365a.png)

**Comment by JoePfeiffer** [comment]
I'm not seeing this with the "Three-stage rocket" example file -- hand calculating stability % is matching OR exactly.
Please see if the bug is still there (I don't remember us making any changes that would fix it, but it's always possible), and if it is post your .ork file.  You'll need to zip it to get github to upload it.

**Comment by abean74525** [comment]
I just restarted OpenRocket and it seems to be working fine now. Not entirely sure what changed, but I'll upload the file for reference anyway.
[2 stage MD both stages v3 1.zip](https://github.com/openrocket/openrocket/files/8595026/2.stage.MD.both.stages.v3.1.zip)

**Comment by JoePfeiffer** [comment]
Is that a revised design?  It looks like it's shorter than the one you had in your bug report.

**Comment by abean74525** [comment]
yes this is an updated version, but i was still having the issue up until just earlier today. Here is the file that i originally uploaded a screenshot of which seems to have the issue fixed as well. 
[2 stage v4.zip](https://github.com/openrocket/openrocket/files/8595109/2.stage.v4.zip)

**Comment by JoePfeiffer** [comment]
Whatever happened it seems to be OK now... if you have no objection I'll close the issue.
