### ISSUE TITLE
Using Gradle as build tool

### ISSUE THREAD

**Issue by ghost** [openrocket/openrocket#1300]
Has anyone considered using Gradle as the build tool instead of Ant? Ant scripts would be very easy to move over to Gradle and Gradle as a whole seems to be a much more powerful build tool.

The only other issue regarding upgrading the build tool is this one #409 
https://github.com/openrocket/openrocket/issues/409
In that issue, problems were brought up such as having to change file structure, but it's been nearly two years since that issue has had new posts and things may have changed since. I'm hoping this issue can bring up a fresh discussion of this topic.

**Comment by JoePfeiffer** [comment]
I don't think anyone is particularly wedded to ant, but we probably don't want to change build systems without a compelling reason while we're in beta.
