### ISSUE TITLE
crash after adding engine

### ISSUE THREAD

**Issue by InertialMeasurementUnit** [openrocket/openrocket#1301]
I tried to add engine and openrocket crashed. Completely uninstalling not working  (at least I assume I did uninstall but maybe not, because after re-installation still it tries adding motor at the starting, and get crash) 

I need help

**Comment by JoePfeiffer** [comment]
Does this describe what you're seeing:

1) you added a motor to the user motor directory
2) you tried to start OR; a popup appeared saying "Loading motors"
3) a popup appeared with the title "Error upon thrust curve import" with a message including "Two thrust values for single time point" and giving details about exactly where in the motor thrustcurve the error appeared
4) OR remained in this state until you killed it

If so, thanks -- this hadn't actually been reported here before, but will be fixed before the next beta.  In the mean time, you can edit the motor file to remove the error (if it's a commercial motor, it should already be in OR's database so you don't need your motor file).

If something else, please give us a detailed description of exactly what happened.

**Comment by IlgarB** [comment]
That's exactly what happened up to 2'th. Error Message is: IllegalArgumentException:MALFORMED. 

I couldnt open openrocket, already tried uninstall and remove all files. I got the same error again on reinstallation

**Comment by JoePfeiffer** [comment]
Does it still happen if you remove the motor file you added?  Please upload the motor file.  You'll need to change the extension to .txt to get github to allow you to upload.

**Comment by IlgarB** [comment]
> Does it still happen if you remove the motor file you added? Please upload the motor file. You'll need to change the extension to .txt to get github to allow you to upload.

Yes, I removed everything about openrocket but still can't run program.

Also this is the engine i tried to add: [Cesaroni_M2020_lenght.txt](https://github.com/openrocket/openrocket/files/8500845/Cesaroni_M2020_lenght.txt)

Cesaroni M2020 but lenght is different ( The competition we participated in wants us to design with this engine file, so I tried to install it)

**Comment by IlgarB** [comment]
![sa](https://user-images.githubusercontent.com/40150029/163714645-5d7232eb-501d-4061-80fb-c57273d78825.png)

**Comment by IlgarB** [comment]
`---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:




Include your email address (optional; it helps if we can contact you in case we need additional information):




(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadFile(MotorDatabaseLoader.java:98)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:67)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)

---------- Thread information ----------
Thread[DatabaseLoadingThread,1,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: C:\Users\Ilgar\AppData\Local\OpenRocket\app\OpenRocket-15.03.jar
JOGL version: 2.1.5
Current default locale: tr_TR
System properties:
  app.preferences.id=net/sf/openrocket/startup
  awt.toolkit=sun.awt.windows.WToolkit
  file.encoding=Cp1254
  file.encoding.pkg=sun.io
  file.separator=\
  java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
  java.awt.printerjob=sun.awt.windows.WPrinterJob
  java.class.path=C:\Users\Ilgar\AppData\Local\OpenRocket\app\OpenRocket-15.03.jar
  java.class.version=52.0
  java.endorsed.dirs=C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\endorsed
  java.ext.dirs=C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\ext;C:\Windows\Sun\Java\lib\ext
  java.home=C:\Users\Ilgar\AppData\Local\OpenRocket\runtime
  java.io.tmpdir=C:\Users\Ilgar\AppData\Local\Temp\
  java.launcher.path=C:\Users\Ilgar\AppData\Local\OpenRocket
  java.library.path=C:\Users\Ilgar\AppData\Local\OpenRocket\app;C:\Users\Ilgar\AppData\Local\OpenRocket
  java.runtime.name=Java(TM) SE Runtime Environment
  java.runtime.version=1.8.0_111-b14
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=1.8
  java.vendor=Oracle Corporation
  java.vendor.url=http://java.oracle.com/
  java.vendor.url.bug=http://bugreport.sun.com/bugreport/
  java.version=1.8.0_111
  java.vm.info=mixed mode
  java.vm.name=Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=1.8
  java.vm.vendor=Oracle Corporation
  java.vm.version=25.111-b14
  line.separator=\u000d\u000a
  os.arch=amd64
  os.name=Windows 10
  os.version=10.0
  path.separator=;
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.class.path=C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\resources.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\rt.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\sunrsasign.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\jsse.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\jce.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\charsets.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\lib\jfr.jar;C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\classes
  sun.boot.library.path=C:\Users\Ilgar\AppData\Local\OpenRocket\runtime\bin
  sun.cpu.endian=little
  sun.cpu.isalist=amd64
  sun.desktop=windows
  sun.io.unicode.encoding=UnicodeLittle
  sun.jnu.encoding=Cp1254
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=
  user.country=TR
  user.dir=C:\Users\Ilgar\AppData\Local\OpenRocket\app
  user.home=C:\Users\Ilgar
  user.language=tr
  user.name=Ilgar
  user.script=
  user.timezone=Asia/Istanbul
  user.variant=
---------- Error log ----------
   1      0,000 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0,000 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0,047 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0,072 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0,072 INFO   (SwingStartup.java:133) Registering exception handler
   6      0,080 INFO   (SwingStartup.java:139) Loading databases
   7      0,649 STDERR (TranslatorProvider.java:83) Nis 17, 2022 3:41:48 PM java.util.prefs.WindowsPreferences <init>
   8      0,649 STDERR (TranslatorProvider.java:83) WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
   9      0,649 INFO   (TranslatorProvider.java:49) Using default locale tr_TR
  10      0,657 INFO   (TranslatorProvider.java:61) Set up translation for locale tr_TR, debug.currentFile=messages.properties
  11      0,657 INFO   (ComponentPresetDatabaseLoader.java:51) Loading component presets from datafiles/presets
  12      0,665 INFO   (SwingStartup.java:151) Starting update check
  13      0,665 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  14      0,665 INFO   (SwingStartup.java:160) Setting best LAF
  15      0,665 INFO   (MotorDatabaseLoader.java:55) Starting reading serialized motor database
  16      0,665 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  17      0,692 DEBUG  (MotorDatabaseLoader.java:83) Reading motors from file datafiles/thrustcurves/thrustcurves.ser
  18      0,744 INFO   (SwingStartup.java:172) Opening main application window
  19      0,749 INFO   (BasicFrame.java:1518) New action initiated
  20      0,757 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.rocketcomponent.Configuration@324b605e, current number of listeners is 1
  21      0,757 DEBUG  (Rocket.java:394) Firing rocket change event ComponentChangeEvent[tree]
  22      0,757 INFO   (OpenRocketDocument.java:414) Clearing undo history of net.sf.openrocket.document.OpenRocketDocument@6ba1958c
  23      0,757 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.document.OpenRocketDocument@6ba1958c, current number of listeners is 2
  24      0,804 DEBUG  (BasicFrame.java:170) Instantiating new BasicFrame
  25      0,849 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.SimulationPanel$22@9064563, current number of listeners is 3
  26      0,865 DEBUG  (Icons.java:24) Starting to load icons
  27      0,881 DEBUG  (Icons.java:94) Icons loaded
  28      0,890 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.RocketActions$2@45f9bc23, current number of listeners is 4
  29      0,890 DEBUG  (BasicFrame.java:193) Constructing the BasicFrame UI
  30      0,913 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.componenttree.ComponentTreeModel@563d2430, current number of listeners is 5
  31      1,022 DEBUG  (ComponentPresetDatabaseLoader.java:91) Time to load presets: 365ms 1622 loaded from 1 files
  32      1,080 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.MotorConfigurationPanel$6@5fa249b2, current number of listeners is 6
  33      1,088 INFO   (BlockingMotorDatabaseProvider.java:65) Motor database not loaded yet, displaying dialog
  34      1,104 INFO   (MotorDatabaseLoader.java:61) Ending reading serialized motor database, motorCount=1721
  35      1,104 INFO   (MotorDatabaseLoader.java:64) Starting reading user-defined motors
  36      1,104 WARN   (MotorDatabaseLoader.java:71) User-defined motor file C:\Users\Ilgar\AppData\Roaming\OpenRocket\ThrustCurves is neither file nor directory
  37      1,104 DEBUG  (MotorDatabaseLoader.java:96) Loading motors from file D:\İndirilenler\teknofest_m2020.zip
  38      1,108 INFO   (ZipFileMotorLoader.java:76) Loaded 1 motors from ZIP entry teknofest_m2020/Cesaroni_M2020_Teknofest.eng
  39      1,119 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[DatabaseLoadingThread,1,main]
   > java.lang.IllegalArgumentException: MALFORMED
   > 	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
   > 	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
   > 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
   > 	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
   > 	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
   > 	at net.sf.openrocket.database.MotorDatabaseLoader.loadFile(MotorDatabaseLoader.java:98)
   > 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:67)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
  40      1,119 STDERR (SwingExceptionHandler.java:49) java.lang.IllegalArgumentException: MALFORMED
  41      1,119 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
  42      1,119 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
  43      1,119 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
  44      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
  45      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
  46      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.MotorDatabaseLoader.loadFile(MotorDatabaseLoader.java:98)
  47      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:67)
  48      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
  49      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
  50      1,119 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
  51      1,119 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
  52      1,136 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
  53      1,205 DEBUG  (UpdateInfoRetriever.java:173) Update response code: 404
  54      1,205 WARN   (UpdateInfoRetriever.java:184) Unknown server response code: 404
  55      2,205 USER   (SwingExceptionHandler.java:220) User requested sending bug report
  56      2,205 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

`

**Comment by JoePfeiffer** [comment]
Yes, please add the bug report.  I'm having a hard time duplicating the problem; I've now tried your motor file under both Linux and Windows and it's worked fine with both.

**Comment by SiboVG** [comment]
@IlgarB could you try to recreate this issue again and send us the bug report so that we can debug the issue?

**Comment by JoePfeiffer** [comment]
We couldn't duplicate and no response from user after four months.
