### ISSUE TITLE
OpenRocket hangs on bad thrustcurve

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1304]
If a motor with a bad thrustcurve is imported into OR, a message dialog is popped up describing the error.  Unfortunately, since the motor loading progress dialog is modal, this message is unresponsive and OR hangs.  Screenshot showing the situation is at https://www.rocketryforum.com/attachments/or_error-png.514239/

**Comment by JoePfeiffer** [comment]
Sibo, I'm thinking you're better at this stuff than I am.

**Comment by SiboVG** [comment]
Can't really test it myself because it works fine on my machine, but @JoePfeiffer could you verify if [this JAR](https://drive.google.com/file/d/1c5LRrqLwS9QC3_Bhpb3IwOslcOmpMmGr/view?usp=sharing) fixes anything?

**Comment by JoePfeiffer** [comment]
Looks like that got it!  Something I probably should have put into the original report:  would it be reasonable to put the full path to the thrustcurve causing the problem in the error dialog, instead of just the filename?  We've had at least one user who installed a bad thrustcurve at some point in the past, forgot about it, and then had a hard time finding the file from just the filename.

**Comment by SiboVG** [comment]
> Looks like that got it! Something I probably should have put into the original report: would it be reasonable to put the full path to the thrustcurve causing the problem in the error dialog, instead of just the filename? We've had at least one user who installed a bad thrustcurve at some point in the past, forgot about it, and then had a hard time finding the file from just the filename.

Added full filename support in #1309
