### ISSUE TITLE
OpenRocket - v2022 beta 2 - export to RockSim Drops sub-sub assemblies

### ISSUE THREAD

**Issue by spigalau** [openrocket/openrocket#1321]
Our existing model has several parts of the model which have 3 levels of componentry  - eg 1) Switch Band which is attached to 2) Tube Coupler and inside that are 3) Other bits (Electronics, Charge-wells, Bulkheads, etc)

**ORK FIle with full tree of components:**
![v2022 ORK File with full component detail](https://user-images.githubusercontent.com/104698340/166123637-e1e46a04-ce03-423e-9556-7b7868255e59.PNG)

**Exported to RKT format and re-opening in OR - missing sub-sub level components**
![v2022 RKT file with initial component list - note missing bits](https://user-images.githubusercontent.com/104698340/166123639-cdd11056-f71f-4de0-90e2-01ff76ce30e0.PNG)

**ORK file with Electronics component shifted from sub-sub level to sub level**
![v2022 ORK File with full component detail - electronics shifted to Switchband Level](https://user-images.githubusercontent.com/104698340/166123635-f087db58-a1f2-488b-a3bd-d55684c1e9ff.PNG)

**Exported to RKT and re-opened in OR and now the Electronics appear**
![v2022 RKT file with initial component list - note electronics now appearing](https://user-images.githubusercontent.com/104698340/166123638-e5104169-bc3c-45dd-9561-e6d9c3e8828d.PNG)

It appears that the Open Rocket export routine is not exporting out any item that is a sub-sub component.

**Comment by SiboVG** [comment]
The issue you're describing only applies to tube coupler sub-sub assemblies. RockSim does not support child components to tube couplers, while OpenRocket does. So OpenRocket has to drop those sub-sub assemblies, because RockSim simply does not support it.
![image](https://user-images.githubusercontent.com/11031519/198821362-bccb1d2d-a3f6-4689-bf8a-cec2971431f3.png)

**Comment by SiboVG** [comment]
You know what, my apologies, that was a simple answer of me. It would be better for the export to move the tube coupler sub-components outside of the tube coupler, so that the sub-components aren't just thrown away, and RockSim can still read the file.
