### ISSUE TITLE
Does not import RKT pods

### ISSUE THREAD

**Issue by BigMacDaddy72** [openrocket/openrocket#1348]
I have not tried many file formats but it seems to be well-known that OR does not import pods from RKT files. It would be incredibly valuable if it could parse the data and at least get whatever comparable elements of the pods imported that it can.

For example, this X-15 RKT files does not import: https://www.apogeerockets.com/downloads/rocksim_files/ApogeeX-15.rkt

**Comment by neilweinstock** [comment]
LOL, you beat me to it by an hour. :)

**Comment by neilweinstock** [comment]
Our big challenge here is going to be that OR only supports pods attached to the airframe, whereas Rocksim supports pods on other components (most importantly, fins).

I have a suspicion that a pretty large proportion of the pods designs that folks are going to want to import from Rocksim are going to be pods-on-fins, and in many cases there isn't going to be a straightforward way to import them.

**Comment by JoePfeiffer** [comment]
Ah, OK.  So resolving #1145 is a prerequisite.

**Comment by neilweinstock** [comment]
I *think* so.
