### ISSUE TITLE
Export of simulated latitude and longitude needs more decimals

### ISSUE THREAD

**Issue by OZ1SEJ** [openrocket/openrocket#1354]
When doing a simulation and afterwards exporting latitude and longitude, only three decimals are exported, corresponding to a rectangular area 111 meters wide. This is a bit too coarse for my use, at least - why not just two more decimals, which would create a box just 1 meter wide.

Also, the text boxes where latitude and longitude are inputted have a strange behaviour (Ubuntu 22.04, v. 22.02.beta.01) where it's possible to paste e.g. a line break into the box.

Feature request: Export directly as KML-file for visualization of 3D flight path in Google Earth.

Feature request: Built-in 2D top-down map-view for easy viewing of flight ground track.

**Comment by JoePfeiffer** [comment]
I should mention -- these are all great ideas (the kml export is especially appealing), and we'll need to figure out what's going on with the lat/long entry (do other number entry fields do it?).  But it would be helpful if they had been four issues so they could more easily be tracked.

**Comment by vvishwa** [comment]
I see that default unit for latitude and longitude is degree, for each unit there is associated conversion factor. As a result, it comes to same latitude (decimal precision is still an issue)
eg. 0.7853981633831798 all comes to 45 degrees. If unit is kept to radian it should remain precise to original calculated value.

**Comment by OZ1SEJ** [comment]
You should be able to convert between radians and degrees without any loss of precision; 0.7853981633831798 isn't the same as 45°, it's the same as 45.00000000000000°. There must be some rounding at play somewhere.

**Comment by JoePfeiffer** [comment]
I should have guessed there would be extra complexities! 

Yes, we definitely want to continue to let users select their units, and just changing units for output shouldn't be causing a noticeable loss of precision.

It looks like a method called MathUtil.doubleToString() is used to produce the string representation, and it's rounding to fit things in five characters.  That method seems to be used in the UI for optimization, in CSV export, and in OpenRocketSaver().  I don't see any reason why file output should ever be limiting the precision, so just not calling textToString() there would seem to take care of it.

**Comment by vvishwa** [comment]
Some debugging reveals that the call toUnit(double) uses multiplier which is first initialized, probably when simulation result is prepared. The division always gives a number which only seems rounded but in reality not, so here is trace..
<img width="1742" alt="Screen Shot 2022-05-21 at 3 24 42 PM" src="https://user-images.githubusercontent.com/2761955/169666549-06982381-a3c9-4ab8-8595-2e742078ddba.png">

0.7853981633974483/0.017453292519943295 = 45

	/**
	 * Converts from SI units to this unit.  The default implementation simply divides by the
	 * multiplier.
	 * 
	 * @param value  Value in SI unit
	 * @return       Value in these units
	 */
	public double toUnit(double value) {
		return value / multiplier;
	}

I think the original simulation result is in degrees, when conversion happens it uses artificial multiplier to convert from value (again converted) to same. It will be interesting to find out - getting hand a bit wet to begin

**Comment by JoePfeiffer** [comment]
See my earlier comment about doubleToString().  That's where the rounding is happening.

**Comment by Sparrowhawk120** [comment]
#1037 and #1036 talk about this issue and a solution already
