### ISSUE TITLE
Feature request: update zoom button icons

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1382]
The current zoom button icons are honestly unreadable... The actual +/-/frame icon is just too small to know what is what

example from the simulation panel that proves my point (had to hold my laptop 10 cm from my face to actually know which is which):
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/11031519/170554081-8a929ba8-f023-4e72-95c7-bb69109e476e.png">

**Comment by SiboVG** [comment]
I think that a general revamp and modernization of all the pictograms in OR is not a bad idea. @neilweinstock is this something you would be willing to look into?

**Comment by neilweinstock** [comment]
I agree about the zoom button icons.  I can fix those easily enough.

As for the rest of the program, though... I actually can't find too many other pictograms in the rest of the program.  Did you have any in mind?

**Comment by SiboVG** [comment]
> I agree about the zoom button icons. I can fix those easily enough.
> 
> As for the rest of the program, though... I actually can't find too many other pictograms in the rest of the program. Did you have any in mind?

For example these icons are just all too detailed and hardly distinguishable.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/11031519/170560575-44e628b6-fe6e-478f-b488-54cb7222a7c4.png">

Also the simulation icons IMO don't need the bevel emboss and drop shadow etc. Just looks a bit outdated.
<img width="52" alt="image" src="https://user-images.githubusercontent.com/11031519/170560781-abcd00c2-1f72-452a-859a-c0ba717a227b.png">

**Comment by neilweinstock** [comment]
I don't disagree.  Redoing all the icons in the menus is a bit of a job, best accomplished by taking a pre-existing set (free or purchased).

My suggestion for now would be to incrementally fix the worst of them (I agree with the zoom icons and the dots, less inclined to go after the menus right now).

Here are some better zoom in and zoom out icons.  I confess I have little idea yet what to do with the one in the middle.
![image](https://user-images.githubusercontent.com/243872/170565161-4af60d6a-7554-49b0-8233-b4b7b16d7b30.png)

**Comment by SiboVG** [comment]
I would suggest doing something like this for the middle one, so two brackets [ ]
![Screenshot 2022-05-26 at 21 44 57](https://user-images.githubusercontent.com/11031519/170565830-34feea6a-3c38-4939-bb45-29493a34b73a.jpg)

And I would indeed use existing icons, for example the ones from Font Awesome or any other open source icon pack (there are a bunch out there).

**Comment by neilweinstock** [comment]
Not sure about the brackets.  Others improved slightly.

![image](https://user-images.githubusercontent.com/243872/170569377-5cdda6aa-9e0a-4ad2-81e6-bf382f746107.png)

**Comment by SiboVG** [comment]
Maybe make the brackets slightly smaller so you can separate them more?

**Comment by neilweinstock** [comment]
Tried but with no success.  Can fiddle some more.  Make sure you're viewing the latest I put there at 100% size.

**Comment by SiboVG** [comment]
That looks really good!


________________________________

**Comment by SiboVG** [comment]
Fixed in #1386
