### ISSUE TITLE
22.02.beta.03, MacOS 12.2.1 : "Can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by broofa** [openrocket/openrocket#1392]
I just installed the latest beta, `22.02.beta.03` and upon opening it I get the following error:

![CleanShot 2022-05-30 at 16 21 45@2x](https://user-images.githubusercontent.com/164050/171067567-0f5c2db4-0135-4b76-831e-715fa3ca9691.png)

Note: [There is a workaround](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac), but it looks like this is an issue that should be addressed here, hence filing this issue.

**Comment by JoePfeiffer** [comment]
The workaround is in the Mac instructions on the download page.  The "real" issue appears as issue #1144

**Comment by hcraigmiller** [comment]
Have you tries following the instructions here: https://openrocket.info/downloads.html?vers=22.02.beta.03

"Show macOS installation instructions"

**Comment by SiboVG** [comment]
Also want to point out that we are working on getting OpenRocket code signed by Apple so that it is included as a trusted software on macOS.

**Comment by broofa** [comment]
@JoePfeiffer, @hcraigmiller :  FWIW, I ran into this issue after launching `beta.02` and being instructed to "Install Update" (below).  Clicking that button triggers a direct browser download of the `.dmg` image.  There's no warning about this issue in that workflow.

![CleanShot 2022-05-30 at 19 14 09@2x](https://user-images.githubusercontent.com/164050/171079572-e7de5436-6e4b-4674-86fc-d169c52debff.png)

**Comment by SiboVG** [comment]
> @JoePfeiffer, @hcraigmiller : FWIW, I ran into this issue after launching `beta.02` and being instructed to "Install Update" (below). Clicking that button triggers a direct browser download of the `.dmg` image. There's no warning about this issue in that workflow.

The direct download in the software updater is meant to ease the pain of installing a new update. But again: this issue is only temporarily, once we get the code signing to work, the warnings will be gone. Thanks for bringing it up though.
