### ISSUE TITLE
Feature Request: display OR version more quickly in the splashscreen

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1394]
Right now it takes some time for the OR version to be displayed in the splashscreen, and often only in the last 10% of the load time. It would be better if it could be displayed from the start.

**Comment by JoePfeiffer** [comment]
This is pretty much the same thing as #1112.  To me it seems perfectly to add that insertion to the build scripts so it's part of the actual splash image.

**Comment by SiboVG** [comment]
> This is pretty much the same thing as #1112. To me it seems best to add that insertion to the build scripts so it's part of the actual splash image.

It's not really the same as #1112. This issue is about the existing build version text on the splashscreen to be shown earlier, #1112 is about changing moving all the other text from the GIMP file to also be code generated. So I would leave this issue in so that we can first fix this bug and later on we can work on #1112.

**Comment by JoePfeiffer** [comment]
I may have expressed myself poorly in that issue:  what I really want there is for the splash image to be static so it all turns up immediately, and for changes from build date and version to happen automatically.
