### ISSUE TITLE
3D Decals fail to display on systems that do not support NPOT textures.

### ISSUE THREAD

**Issue by bkuker** [openrocket/openrocket#140]
Using textures with sizes that are not power of two causes those textures to not be displayed on some older  systems. See https://www.opengl.org/wiki/NPOT_Texture for background.

It ends up looking like this:

![image](https://f.cloud.github.com/assets/1305026/1134523/a5520cc2-1bf2-11e3-9f8a-108f4c6bd6fe.png)

Textures need sizes like 64x128 or 32x256 on these systems. If I read the above wiki link correctly this is not supposed to happen, but this is a circa 2010 imac which might have one of those Radeon cards.

Courses of action include:
- Resizing images before passing to GL either
  - if NPOT is not supported (The trouble with this is that GL2 requires NPOT support, so there is no way to ask)
  - or based on a user preference.
- Use power of two textures in examples and
- document the problem and wait for older computers to break

**Comment by dkingsley** [comment]
I have tested this on two different windows machines one with an integrated Inlel HD 520 graphics and one with a NVidia Quatro K51000 and neither have a problem with non-power of two sized images. I recommend that some others test this and if no one can reproduce the issue that we close this issue.

**Comment by neilweinstock** [comment]
No one has seen this in a long time, closing.
