### ISSUE TITLE
[Bug] Hover total mass multiplies total fin mass by fin count

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1409]
When computing the **hover** total mass, the computation multiplies the mass of a fin set by the fin count in that set, and substitutes that value for the fin set mass.

Reported design:
![1409 Hover](https://user-images.githubusercontent.com/68821492/172072068-7aa8dd4a-8793-4c25-8f8e-e4622856edf6.png)

Issue verification:
![1409 Hover n_02](https://user-images.githubusercontent.com/68821492/172072373-7ce19e11-8106-429b-a955-17452796cbcf.png)

I just used the override on the fins for convenience; the **hover** total mass computation multiplies the mass of a fin set by the fin count in that set even when the fin set mass is not overridden, and whether or not the tube mass is overridden.

**Comment by JoePfeiffer** [comment]
Is this the one that was reported on FB earlier today?  I'm attaching the .ork file.
Did you establish that's the whole bug he's seeing, or just part of it?
[MICA-EM2v22.ork.zip](https://github.com/openrocket/openrocket/files/8840836/MICA-EM2v22.ork.zip)

**Comment by hcraigmiller** [comment]
Yes.
