### ISSUE TITLE
[Bug] Click in the design window while in 3D modes causes exception

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1420]
This exception occurs each time you left-click on or off the rocket in the desgin window, in any of the 3D modes.

![3D Finished Exception](https://user-images.githubusercontent.com/68821492/172898672-2c9b254d-0f10-47ad-97d4-482711590348.png)

[Composite_Warehouse.Pink_Lady.ork.txt](https://github.com/openrocket/openrocket/files/8872257/Composite_Warehouse.Pink_Lady.ork.txt)

[Windows 11 Pro, Version 21H2, OS Build 22000.675, Windows Feature Experience Pack 1000.22000.675.0]
[Java version "17.0.3.1" 2022-04-22 LTS; Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)]

**Comment by SiboVG** [comment]
Can you try running the latest unstable with Java 11?

**Comment by SiboVG** [comment]
Oh, nevermind, it also occurs in Java 11...
