### ISSUE TITLE
OpenRocket-22.02.beta.04-macOS.dmg Install Failure

### ISSUE THREAD

**Issue by AlbyVA** [openrocket/openrocket#1461]
I'm having an issue where trying to install the package to the Applications Directory
fails with an Error Code -36 about something in the package that cannot be read.

<img width="678" alt="Screen Shot 2022-06-17 at 8 39 11 PM" src="https://user-images.githubusercontent.com/18426976/174415626-acc9f813-047d-46f7-aeaf-906001958816.png">

**Comment by SiboVG** [comment]
Could you download the installer again (I updated it), should be fixed now. Have no idea what the issue was, I think install4j generated a corrupt installer because I just did a re-run of the installation and now it seems to work).

**Comment by AlbyVA** [comment]
Confirmed. Download and Installation was successful this time around. 
Thanks,
