### ISSUE TITLE
Bug: Keep checked preset row highlighted after checked

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1516]
When checking a preset in the preset dialog, the table row first gets highlighted, but then loses its highlight. I would keep the highlight so that it is also more clear for users that highlighting (and checking) a preset applies that preset to the component. 

(if you think that it would also be beneficial to add an additional info text stating that checking + highlighting a preset applies it to the component, then do reply. I'm not yet sure if this is needed, although I do find it confusing now to know the difference between checking a preset and simply selecting a preset in the preset table)

**Comment by hcraigmiller** [comment]
It would be beneficial.
