### ISSUE TITLE
Feature request: don't require preset to be checked to be applied

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1518]
Right now, the only way to apply a preset is to first check the preset in the preset dialog, and then to either select the (checked) preset in the preset dialog, or to close the preset dialog and then select the preset from the preset drop down menu in the component edit dialog.

I propose to also apply a preset when it is highlighted in the preset dialog, without being checked.

The only thing that makes this issue not an easy feat is: how would you display a preset in the preset combo box that is unchecked (so not a favorite) vs one that is checked (a favorite). Maybe to make it clear that checked presets are seen as 'favorites', you could add a star icon next to the preset name? I'm open to other suggestions.
![Screenshot 2022-07-05 at 00 25 10](https://user-images.githubusercontent.com/11031519/177222005-a2093e76-4a4b-4336-9955-c0273cbdc392.jpg)

**Comment by hcraigmiller** [comment]
Use a star icon and order the presets first, followed by recently used (no stars).

**Comment by hcraigmiller** [comment]
I think @neilweinstock prefers this order:

![Config_Pane Rev_01](https://user-images.githubusercontent.com/68821492/177223523-80f98624-c172-4cb4-a8ef-902ef2698107.png)

**Comment by neilweinstock** [comment]
> Right now, the only way to apply a preset is to first check the preset in the preset dialog, and then to either select the (checked) preset in the preset dialog, or to close the preset dialog and then select the preset from the preset drop down menu in the component edit dialog.

Since when is this the case?  It has never been so, unless a PR snuck in that made this change while I wasn't looking.

**Comment by SiboVG** [comment]
> Since when is this the case? It has never been so, unless a PR snuck in that made this change while I wasn't looking. I don't even want to look at the proposed solutions until I'm clear on why this is a problem in the first place.

Whoops, sorry @neilweinstock, I was wrong, this is still the case (thought I tested this before, but I guess not thoroughly enough). But even though the initial reason for this issue is wrong, maybe it is useful to add a distinction between favorites and recently used presets (as proposed by @hcraigmiller)?

**Comment by neilweinstock** [comment]
> Whoops, sorry @neilweinstock, I was wrong, this is still the case (thought I tested this before, but I guess not thoroughly enough). But even though the initial reason for this issue is wrong, maybe it is useful to add a distinction between favorites and recently used presets (as proposed by @hcraigmiller)?

I originally proposed the Recently Used function, and after further thought decided that it's more trouble than it's worth (discussed in another PR or issue somewhere).  But either way, it's completely unrelated to the subject of this feature request.

In fact, since the premise on which this feature request was in error, I think this issue should just be closed.  Discussion of various ways to improve and/or rethink the way presets work should continue elsewhere.
