### ISSUE TITLE
[Bug] Edit window not opening

### ISSUE THREAD

**Issue by fabioski01** [openrocket/openrocket#1521]
Whenever I double click on a component, or whenever I click edit on a component, or whenever I add a new component, no window opens to change the component lenght, mass etc. Edit simulation and plot simulation work  as expected. 
Windows 11,  v15.03 and 22.02.beta.04 have the same problem.

**Comment by hcraigmiller** [comment]
Can you ensure that you are running Java 11, then download and run [Build 742](https://github.com/openrocket/openrocket/suites/7070065819/artifacts/278981404) and see if the issue persists?

**Comment by fabioski01** [comment]
Java 11 solved for the 22.02.beta.04, thanks.
