### ISSUE TITLE
Sluggish UI in  V22.02

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1533]
There are a number of areas where the v22 UI is noticeably sluggish compared to v15.03.  Two obvious examples:

- [x] Dragging around a vertex in the finset editor
- [ ] Adding a new component and waiting for the config window to open

I don't know if this is related to Java 11 or if something changed in the UI implementation that is making it slower.  Accordingly, I don't know if it's readily fixable.  But it would be good to know the reason.

Tested on M1 iMac, not yet confirmed on other platforms.

**Comment by hcraigmiller** [comment]
Confirmed in Windows 11.
