### ISSUE TITLE
Issue with motor configuration

### ISSUE THREAD

**Issue by zeke800** [openrocket/openrocket#1554]
Hello, 

Thank you so much for the great software!! I really enjoy using OpenRocket. 

I am using the latest beta version. When opening the motor dialog, it looks really weird and does not seem to load properly. 
![image](https://user-images.githubusercontent.com/82127189/180670879-ed6f8acf-25b4-432e-87c2-63d3fd8e83cc.png)
How can I fix this?

Thank you!!

**Comment by zeke800** [comment]
Here is the file by the way:
[rocket.zip](https://github.com/openrocket/openrocket/files/9176967/rocket.zip)

**Comment by hcraigmiller** [comment]
Could not replicate.

![1554 Motor Config](https://user-images.githubusercontent.com/68821492/180671802-746460bb-a982-4130-9d20-d9eca18397e7.png)

> I am using the latest beta version. 

Which OS Platform, are you using the .jar or an installer, and where did you get it from?

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by zeke800** [comment]
Hello, I am using the Windows installer. I can confirm it works on the beta02 version, but not on the beta04 version. I got it from the official releases page. My system is Windows 10 Home.

![image](https://user-images.githubusercontent.com/82127189/180785093-58a3f278-69e8-4000-9d01-bc6ded16bbd5.png)

**Comment by hcraigmiller** [comment]
Have you tried to uninstall all of the beta versions, reboot, and reinstall beta 4?

**Comment by zeke800** [comment]
Yes I have.

**Comment by SiboVG** [comment]
Does this issue also persist in beta 3?

**Comment by SiboVG** [comment]
Well this is interesting... I'm working on a fix for #1561 and while testing out some code, I was able to replicate this exact issue. So the issue has nothing to do with the setup of @zeke800.

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/11031519/181651194-ed99fae6-ac47-49d8-a457-18162aff4ba6.png">

**Comment by SiboVG** [comment]
@zeke800 are you somewhat experienced with running OpenRocket from the JAR file? If so, could you verify whether [this JAR file](https://github.com/openrocket/openrocket/suites/7571532513/artifacts/313024235) fixes this issue?
