### ISSUE TITLE
Feature request: command line option(s) to suppress loading built-in databases

### ISSUE THREAD

**Issue by ehingsbe** [openrocket/openrocket#1579]
I have been an OpenRocket user since before v15.03, and find it very useful. However, I have had issues with the contents of the motor and parts databases. I would like to see a command-line (or configuration) option that allows the user to suppress automatic loading of those databases.

**Comment by neilweinstock** [comment]
What kind of issues are you seeing, and how will not loading the databases fix your issues?

**Comment by ehingsbe** [comment]
I'd found inaccuracies in the databases (motor thrust curves that didn't
match those that the mfr supplied, and if I recall correctly, some parts DB
issues too).
Ultimately, of course, those errors should be fixed, but I don't have notes
on the specifics.
If the database tables were externally accessible, that could also be a
reasonable solution, but that seems like it could be disruptive.

Thanks!
Ed
