### ISSUE TITLE
Photo Studio scaling issue with High-DPI settings (Windows 10)

### ISSUE THREAD

**Issue by ReinhardR** [openrocket/openrocket#1599]
When High-DPI settings are enabled, the window scales with the DPI scaling settings but the active drawing area doesn't.

The effect is proportional to the scaling factor. The screenshot was made with 150%.
![grafik](https://user-images.githubusercontent.com/5122021/185489882-168da294-b5c6-45a1-a8c5-7c4cda1baa8c.png)

The issue is present in 2022.02.beta.04 but can not be reproduced with 15.03.

Windows 10 21H2, Intel HD driver 20.19.15.5126

**Comment by hcraigmiller** [comment]
Have you made the post-installation settings adjustments (see [Wiki](http://wiki.openrocket.info/Downloading_%26_Installing#Check_Settings))?

**Comment by ReinhardR** [comment]
I haven't done that before.
Enabling "Use Off-Screen Rendering" fixes the issue.

**Comment by hcraigmiller** [comment]
That's great. . . please close this issue.
