### ISSUE TITLE
BUG:set nose cone base diameter can trigger unknown java error

### ISSUE THREAD

**Issue by ZCY571864845** [openrocket/openrocket#1607]
While I try to set a optional value to nose cone base diameter,such as 5m 10m or 100m,unknown java error occured.
This error just occured in side view and back view.
![图片](https://user-images.githubusercontent.com/19361354/186153490-c0907b14-ac1d-4e63-848a-169f4c97c563.png)

**Comment by SiboVG** [comment]
You should not set the diameter too high. 5m, 10m etc. is just too large, OpenRocket is only designed for model rocketry, not for NASA SLS-like rockets that you're trying to simulate 🙃
