### ISSUE TITLE
Feature request: add warning when no motor selected in first stage of simulation

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1611]
Simulations fail and motor not detected.
[SST_ShuttleD.zip](https://github.com/openrocket/openrocket/files/9419004/SST_ShuttleD.zip)

**Comment by JoePfeiffer** [comment]
In the case of the design triggering the bug, the booster stage is completely empty (should be noted the sustainer is actually named "Booster" and the booster is named "Glider")

**Comment by hcraigmiller** [comment]
After playing with this design, OpenRocket appears to be functioning correctly with the exception that there is no warning that the aft-most stage does not have a motor.

Is this just a duplication/variation of Issue #1468.

**Comment by JoePfeiffer** [comment]
It's a variation...  I think #1468 will turn out to be a special case of this one (need a warning if there's no motor in the bottom stage).  Shall we close that one and mark it as superceded by this?

**Comment by hcraigmiller** [comment]
I would say that the two are sufficiently connected that fixing Issue #1611 also fixes Issue #1468, but not the other way around. I would close Issue #1468; this discussion is a sufficient reference to take a look there when resolving this issue.
