### ISSUE TITLE
[Bug] Transition fin tab auto calculate errors

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1613]
If the transition ends are the same, then the fin tab auto calculate works correctly. But if either end is smaller than the other, the auto calculate does not function correctly.

![Transition Fin Tab](https://user-images.githubusercontent.com/68821492/186700298-0437f85a-bdf0-466b-be94-3d94351c7cc6.png)

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by hcraigmiller** [comment]
The fin tab function also results in the root edge being drawn incorrectly on curved transitions.

![Root Edge](https://user-images.githubusercontent.com/68821492/186704082-7c84a580-c1b7-448a-899b-249b3675f14f.png)
.

**Comment by SiboVG** [comment]
An additional bug that I now notice (already present in beta 4) is that the auto calc functionality doesn't work when the centering rings are a child of the inner tube instead of a direct child of the fin's parent tube.

**Comment by hcraigmiller** [comment]
> An additional bug that I now notice (already present in beta 4) is that the auto calc functionality doesn't work when the centering rings are a child of the inner tube instead of a direct child of the fin's parent tube.

I'm not sure that doing so would have the best outcome. The way it is, the user can nest one motor mount inside of another and the fin tab uses the direct child of the fin's parent tube approach to identify the correct centering rings. Wouldn't allowing the identification of centering rings that are a child of the inner tube defeat this ability?

**Comment by SiboVG** [comment]
> > An additional bug that I now notice (already present in beta 4) is that the auto calc functionality doesn't work when the centering rings are a child of the inner tube instead of a direct child of the fin's parent tube.
> 
> I'm not sure that doing so would have the best outcome. The way it is, the user can nest one motor mount inside of another motor mount (inner tube and centering rings) and the fin tab uses the direct child of the fin's parent tube approach to identify the correct centering rings. Wouldn't allowing the identification of centering rings that are a child of the inner tube defeat this ability?

Hm, you may be right, didn't think about it that way.
