### ISSUE TITLE
[Bug] When fin tabs are used on curved nose cones and transitions, the fin root edge is not being drawn correctly

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1618]
![Root Edge 01](https://user-images.githubusercontent.com/68821492/186938399-22f0a62e-694d-4fee-bd5e-17bbb24c35de.png)

**Comment by hcraigmiller** [comment]
Nose cone behaves similarly. . .

![Root Edge 02](https://user-images.githubusercontent.com/68821492/186944725-c7c9c898-aeb4-4888-be09-fec9b6fae467.png)

[Fin Tab Errors.txt](https://github.com/openrocket/openrocket/files/9434601/Fin.Tab.Errors.txt)

**Comment by SiboVG** [comment]
Current unstable branch. Are you sure you're using the latest unstable?
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/11031519/186952015-09ab2bc9-7b92-49c0-ae1b-5ad78ce5411d.png">

This issue should have been resolved by PR #1598.

**Comment by hcraigmiller** [comment]
The issue is not with the fin tab itself (the fin tabs function correctly), it is that if a fin tab is used on a curved nosecone or transition then the root chord that is not part of the fin tab does not follow the curve (it is straight). I shorthened the fin tab length to make the error more pronounced.

**Comment by SiboVG** [comment]
Ah now I see, it happens if the tab height is non zero and the tab length is smaller than the fin length.
