### ISSUE TITLE
Show calculated Mass, CG, and CD values for non-overridden components

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1629]
In the Override tab, if a component isn't overridden then an override value of 0 is shown for all three values unless changed by the user. Showing the calculated values would give the user a starting point for overrides.

**Comment by SiboVG** [comment]
Should the CD be taken at Mach 0.30? (since the component analysis CD is also at Mach 0.30 by default).

**Comment by JoePfeiffer** [comment]
All the various displayed aerodynamics' Mach numbers should be coordinated -- I *think* the right place to set this is in the component analysis window (the only two places I can remember to change it are in the preferences, which sets the default, and in the component analysis window).  Ah, just noticed changing it in the component analysis window doesn't change it in the rocket view (but changing the wind direction and angle of attack does).

**Comment by JoePfeiffer** [comment]
Correction -- it changes the calculation, it just doesn't change the displayed mach number
