### ISSUE TITLE
Exception when double-clicking motor in Motor Configuration panel

### ISSUE THREAD

**Issue by broofa** [openrocket/openrocket#1634]
Double-clicked a motor to open the editor for it (see screenshot), and got [this stack dump](https://gist.github.com/broofa/0eb44491c31e41c3fc70ce0bf908fc32).

![CleanShot 2022-08-31 at 13 41 39@2x](https://user-images.githubusercontent.com/164050/187778099-b0ad006b-6974-46d1-9b14-780dacba5de6.png)

**Comment by SiboVG** [comment]
This issue is not present anymore on the current unstable branch and will be fixed in beta 5.
