### ISSUE TITLE
Rocket design window doesn't change displayed Mach number

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1638]
In the upper right corner of the rocket design window, where the stability, CG, and CP are displayed, the displayed Mach number remains fixed even though the CP moves as the user changes the speed in the component analysis dialog.

**Comment by hcraigmiller** [comment]
See also, Issue #934 if sufficiently code related.

**Comment by JoePfeiffer** [comment]
> See also, Issue #934 if sufficiently code related.

That's something else that should be resolved some day, but is really part of a general "preferences updates require a restart" problem.  They're pretty completely unrelated.
