### ISSUE TITLE
Imperial motor dimension labels are unintelligible

### ISSUE THREAD

**Issue by broofa** [openrocket/openrocket#1643]
Set your preferred units to "default imperial", and you get this ...

![CleanShot 2022-09-03 at 06 55 54@2x](https://user-images.githubusercontent.com/164050/188273701-66d3fe76-76cf-4ab0-bf15-9ac21dfa53bb.png)

**Comment by hcraigmiller** [comment]
It looks like rounding the motor diameter to 2 decimal points will fix the issue.
