### ISSUE TITLE
[Bug] Centering ring automatic outer diameter does not work correctly inside transition

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1652]
Centering ring automatic outer diameter does not work correctly inside transitions of any shape.

![Transition-CR](https://user-images.githubusercontent.com/68821492/188931203-8c4ce5cf-9eea-4011-848f-b3b5307ea7a1.png)

**Comment by SiboVG** [comment]
Actually, it does work, the wall thickness of the transition is just set extremely high (take a look at the 3D view; the automatic outer diameter works as intended).
