### ISSUE TITLE
[Bug] Incorrect rendering of freeform fin set when ending point is (0, 0)

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1679]
I'm not sure what is causing this. . . I even copied the 13mm hook to the 24mm mount, and it still disappeared.

![Engine Hook](https://user-images.githubusercontent.com/68821492/190881670-5e0c1bc1-5f36-4b10-a99c-6389ad35557f.png)

[Nested.Estes 24mm Motor Mount.No Error.txt](https://github.com/openrocket/openrocket/files/9592882/Nested.Estes.24mm.Motor.Mount.No.Error.txt)
[Nested.Estes 13mm Motor Mount.Error.txt](https://github.com/openrocket/openrocket/files/9592883/Nested.Estes.13mm.Motor.Mount.Error.txt)

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by hcraigmiller** [comment]
I figured it out. . . the starting and ending points cannot both be 0,0.

**Comment by SiboVG** [comment]
> I figured it out. . . the starting and ending freeform fin points cannot both be 0,0; need a warning in the Wiki.

Actually, OR should be able to handle such an "error". So I'm going to re-open this issue.
