### ISSUE TITLE
Apply change in unit without having to reopen design

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1694]
Small QoL change: when changing a unit in the preferences, it would be nice to not have to close the design file, and reopen it to apply the unit change. Instead, after changing the unit, the change should take effect in the rocket view immediately after you close the preference dialog (or possibly even after you change the unit, and still have the preferences dialog open).

**Comment by JoePfeiffer** [comment]
This would apply to all the preferences.

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalies found. Very nice. 

Build 1133
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]
