### ISSUE TITLE
3D views and Photo Studio issues

### ISSUE THREAD

**Issue by smstachwick** [openrocket/openrocket#1708]
After upgrading to Public Beta 5, I've observed issues in the 3D views that carry over to Photo Studio.  Specifically, the rendering appears to be misplaced on my screen.

![Photo Studio](https://user-images.githubusercontent.com/114778661/193358251-616907dc-cb76-4f44-af88-3e0de61451c1.jpg)

![3d finished](https://user-images.githubusercontent.com/114778661/193358277-7ef4a0a2-fd56-4aa1-9d28-f2d13b3d9131.jpg)

The right edge of the 3D Finished view is cut off.  Also note that CP and CG are off-centerline, which was also the case in Public Beta 4.  Both issues are present in 3D Unfinished view.  Neither are present in the standard 2D drawings.

**Comment by hcraigmiller** [comment]
This appears to be a settings issue on your device. Please follow these steps and reports back: http://wiki.openrocket.info/Downloading_%26_Installing#Check_Settings

**Comment by smstachwick** [comment]
> 

That fixed it.  Please feel free to close this issue.
