### ISSUE TITLE
Stage separation requires parallel stages to separate before core stage

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1712]
In a rocket similar to a Falcon 9 Heavy, with a core booster and side boosters all of which need to separate, if the core separates before the side boosters then no simulation branch is created for the side boosters.  The attached .ork demonstrates the problem.

It can be argued that separating the payload from the core booster before dropping the side boosters is ridiculous, but we should handle the situation anyway.
[bogusheavy.zip](https://github.com/openrocket/openrocket/files/9692900/bogusheavy.zip)

**Comment by SiboVG** [comment]
Closed through #1720.
