### ISSUE TITLE
[Bug] Parachute length changes when saved, quit OR, then reopened

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1723]
Open .ork file, **_delete_** parachutes, add parachutes back, save file, quit OpenRocket, and reopen. Parachute lengths are lost.

![Mass Object Length Error](https://user-images.githubusercontent.com/68821492/194724602-a1d28c32-8bf3-4a3a-89fa-6a1c001013eb.png)

[Sea Killer.ork.txt](https://github.com/openrocket/openrocket/files/9740150/Sea.Killer.ork.txt)

**Comment by smstachwick** [comment]
I also see this.  They default to 25mm on my device when they should be longer.
