### ISSUE TITLE
[Bug] Uncaught exception when adding/running new simulation

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1728]
With run outdated simulations on:

1. Open .ork
2. Run simulation with existing configuration.
3. Add second configutation (same one); runs very slow.
4. Go to flight simulations tab.
5. Add third configutation (same one)
4. Go to flight simulations tab (uncaught exception).

![Crash](https://user-images.githubusercontent.com/68821492/194784725-1f25cbac-86ff-4486-853e-37a20d373343.png)
[Bug Report.txt](https://github.com/openrocket/openrocket/files/9742769/Bug.Report.txt)
[Sea Killer.ork.txt](https://github.com/openrocket/openrocket/files/9742770/Sea.Killer.ork.txt)

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
I'm kindly handing this bug over to @JoePfeiffer, it's a bit over my head. For some reason, `status.getRocketPosition().z` on line 443 in `swing/src/net/sf/openrocket/gui/simulation/SimulationRunDialog.java` can equal zero, thus setting `apogeeAltitude` to zero, and later triggering the exception on line 368 of `SimulationRunDialog.java`, because you're doing `MathUtil.map(status.getRocketPosition().z, apogeeAltitude, 0, APOGEE_PROGRESS, 1.0)`, which becomes `MathUtil.map(status.getRocketPosition().z, 0, 0, APOGEE_PROGRESS, 1.0)` (fromMin and fromMax in MathUtil.map both become 0).

**Comment by JoePfeiffer** [comment]
In addition to that, I'm seeing a couple of other things:
1) Simulations 2 and 3 are coming off the rail much faster than Simulation 1
2) If Simulation 3 hits the ground before the exception happens, the ground hit velocity is ridiculous
Are you also seeing these?
![simdata](https://user-images.githubusercontent.com/3065196/194959600-33cb7636-7a4c-436a-952f-af17aa9e75f7.png)

**Comment by SiboVG** [comment]
> In addition to that, I'm seeing a couple of other things:
> 
> 1. Simulations 2 and 3 are coming off the rail much faster than Simulation 1
> 2. If Simulation 3 hits the ground before the exception happens, the ground hit velocity is ridiculous
>    Are you also seeing these?
>    ![simdata](https://user-images.githubusercontent.com/3065196/194959600-33cb7636-7a4c-436a-952f-af17aa9e75f7.png)

The first one not, just because I wasn't monitoring that, but I did noticed the second issue as well.

**Comment by JoePfeiffer** [comment]
The velocity off the rod was a red herring -- when duplicating a configuration, the simulation conditions aren't duplicated so my simulations 2 and 3 were using a 17 foot rail.

**Comment by SiboVG** [comment]
I have to reopen this. #1755 did not fix this issue. In fact, strangely, it appears that I can more easily replicate this issue now.

1. Open 'A simple model rocket'
2. Select all the simulation
3. Click "Run simulations"
4. First run goes well
5. Click "Run simulations" again
6. Exception

[bug report.txt](https://github.com/openrocket/openrocket/files/9847629/bug.report.txt)

Pinging @JoePfeiffer so he doesn't miss this message.

**Comment by JoePfeiffer** [comment]
Thanks for the ping.
