### ISSUE TITLE
[Feature request] Ability to output Cn_alpha

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1734]
Request from a user on the r/rocketry Discord server: I'd love to get Cn_alpha (Normal force coefficient derivative) exposed, for dynamic stability calculations.

**Comment by CarVac** [comment]
Basically the idea is to use Cn_alpha and stability margin and rotational inertia to get the pitch oscillating frequency, and use that to get an idea of whether that gets low enough to intersect a plausible roll frequency, which would result in coning (pitch-roll coupling).

**Comment by SiboVG** [comment]
Actually, I wasn't aware that this is already possible in the 'Tools -> Component Analysis' dialog in the Stability section.
