### ISSUE TITLE
[Bug] Unit selector in rocket optimization "seek value of" does not work

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1746]
The unit selector for the "seek value of" spinner is just blank and unresponsive:
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/11031519/195988318-d6a4d167-8d57-4c88-9e9d-3afadc74dce2.png">

In addition, I'd also like to increase the spinner width to at least 3 digits, right now it's just one '0'.

**Comment by hcraigmiller** [comment]
The spinner itself functions as expected with no anomalies found. Not so much for the results.

Parachute (ft/sec):
![Optimize Parachute](https://user-images.githubusercontent.com/68821492/196542513-f04092ef-d300-4161-b09d-bbcd10eb0b7c.png)

This appears to be a situtation where each parameter will need to be tested and reported if in error. For example, body tube length optimization **functions perfectly when seeking stability by calibers**, but not so much for stability by inches:

![Optimize Stability Inches](https://user-images.githubusercontent.com/68821492/196544055-520c4c5b-7b92-4170-9228-3504a60144db.png)

Build 1107
[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]
