### ISSUE TITLE
Bad CP computed for some fin shapes

### ISSUE THREAD

**Issue by kruland2607** [openrocket/openrocket#175]
The Wildman Vindicator mini has unusual fin shapes.  A user was able to create an ork file (perhaps converted from rkt), where the CP is computed very poorly.  The lower set of fins seem to have the issue since if the upper fins are removed, the cp is still behind the rocket. Further if the fore most point on the lower fin is tweaked a little bit, the CP pops into a reasonable position.  Contact kruland2607 for ork file.

**Comment by dkingsley** [comment]
This does seem to be fixed in the unstable branch, recommend it be closed.

**Comment by wcravens** [comment]
Dan confirmed that this is fixed in Unstable
