### ISSUE TITLE
[Feature Request] Use JSON instead of XML

### ISSUE THREAD

**Issue by gautamdayal** [openrocket/openrocket#1786]
Recently my university rocketry team has been interested in parsing ork files so that we can use our openrocket designs in our own student-design software in loop simulation. We've also been interested in automating the process of getting a 3D model file by parsing the ork file and using something like blender python to create a 3d model. 

So far, we've been parsing the XML files which works decently, but I feel like a much more modern way to store rocket designs under the hood would be JSON instead of XML. It would make it way easier for users to integrate OpenRocket into their own engineering design processes and creative workflows.

**Comment by SiboVG** [comment]
I don't really see advantages to using JSON over XML for our use case. We don't need the extra readability that JSON offers, or other more complex features such as JSON arrays. I understand that XML is more difficult to parse for you, but that's not compelling enough to completely change the way we store ork files (and have a total break in compatibility with previous OR versions).

If you need help with parsing ork files, be sure to send us a message (on [Slack](https://join.slack.com/t/openrocket/shared_invite/zt-dh0wtpc4-WmkSK1ysqAOqHa6eFN7zgA) or something)! Good luck with the project!
