### ISSUE TITLE
[Bug] Pods "Number of copies" spinner can have 0 and negative value

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1794]
You can type 0, and negative number in the pods configuration "Number of copies" spinner, which should not be possible. Typing e.g. '0' does not have an effect on the actual pod instance count though.

**Comment by alperozoner** [comment]
@SiboVG What about negative values? Do they also affect the actual pod instance?

**Comment by SiboVG** [comment]
> @SiboVG What about negative values? Do they also affect the actual pod instance?

Nope, they do not. (sorry if you wanted to work on this issue, I just put up PR #1797 to fix this issue; didn't see your message earlier)
