### ISSUE TITLE
[Bug] Rocket Optimization: Opimization Goal does not use units selected in preferences.

### ISSUE THREAD

**Issue by timothymhuang** [openrocket/openrocket#1802]
### Description
When using the rocket optimization tool, there is an option to set the optimization goal to "seek value of". You can use this to set a specific goal (e.g. Apogee Altitude to 5000ft). However, the number you type in ignores what preferred units you set in preferences, and instead uses the default metric units. The box also does not display units next to it, meaning you can't immediately know what unit it is and can't change it.

### Steps to reproduce
1. Set your preferred units to imperial for the optimization goal you want to test. (e.g. to test the apogee altitude optimization goal, set distance to ft) Make sure you restart OR after changing values
2. In a rocket file (you must already have a rocket built in OR), make sure you have a working flight simulation.
3. Open Tools > Rocket optimization.
4. Select parameters to be optimized (e.g. Trapezoidal fin height, root chord, swept, and tip chord).
5. In optimization options, set the optimized value to the option you want to test (e.g. Apogee Altitude) and set the optimization goal to "Seek Value Of".
6. Enter the optimization goal (assuming it is in the preferred units you set in preferences).

### Expected Result
The optimization goal will be in your preferred units by default, and will also have the option to change it. This means if your preferred unit for distance is feet, and you type in 5000 for the apogee altitude optimization goal, the optimization tool should make the rocket go to 5000 ft.

### Actual Result
The optimization goal uses the default metric unit, regardless of what your preferred units are. This means if you typed in 5000 for the apogee altitude optimization goal, it is simulating to 5000 meters even if your preferred units are feet.
There is also no unit displayed next to the box, and you can't change the unit there.

### Other Info
**OR Version:** OpenRocket 22.02.beta.05
**Device:** Windows 10

![image](https://user-images.githubusercontent.com/59073651/200682968-7e016d85-f228-478d-ac34-7a7d9ed09e2b.png)
Image: I want the optimization goal to be 1530 feet, but OR sets the goal to be 1530 meters, which is around 5020 feet. You can also see that it doesn't display a unit next to the number.
I tested this for Apogee Altitude, Maximum Acceleration, and Maximum Velocity and I can confirm it happens on all three of these. I don't know what other optimization values are affected, but I'm guessing all the options are affected.

**Comment by SiboVG** [comment]
I created a PR (PR #1752) that fixes the unit selector in the rocket optimizer. Not only does that PR fix your issue, but you can now also switch between different units. The result of that PR will be included in the next release (it was implemented after the beta 05 release).
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/11031519/200699669-57f55552-e411-4435-9d49-0cb6e30a90a8.png">
