### ISSUE TITLE
Ability for custom component names for preset components

### ISSUE THREAD

**Issue by benrussell11** [openrocket/openrocket#1815]
I've changed the component names by added a "S - " or "B - " for the sustainer and booster chutes.

![image](https://user-images.githubusercontent.com/49837944/201411840-efc0fd33-e176-486d-83d4-d910a559b9c6.png)
![image](https://user-images.githubusercontent.com/49837944/201411903-011c63d0-1630-4941-abc2-a482dc17a518.png)

File -> Save - Quit
File -> Open recent

Updates to the component names not saved
Sustainer
![image](https://user-images.githubusercontent.com/49837944/201412266-08f68e5e-4c82-4108-8792-1de34698e4ac.png)
Booster
![image](https://user-images.githubusercontent.com/49837944/201412351-1c39dab3-e0c7-474e-81cc-d9d24a7f2e1d.png)

Design file attached
[GW ContestRocketOR_v7.ork.txt](https://github.com/openrocket/openrocket/files/9992781/GW.ContestRocketOR_v7.ork.txt)

**Comment by hcraigmiller** [comment]
Behavior replicated in current unstable using parachutes from the parts list, but not standard (custom) parachutes (such as the A simple model rocket parachute). If you change the _A simple model rocket_ parachute to a parachute from the parts list, change its name, then save and reopen, the name reverts to the parts list name.

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by SiboVG** [comment]
The issue is that the parachutes you renamed are preset parachutes. Currently, OpenRocket just always loads the preset component name. It should be possible to have custom names for preset components, without clearing the preset.
