### ISSUE TITLE
Launch failure in macOS Ventura 13.0.1

### ISSUE THREAD

**Issue by SkierPiau** [openrocket/openrocket#1833]
OpenRocket simply doesn't launch, or launches but doesn't appear on screen.

<img width="1440" alt="Screenshot 2022-11-15 at 18 47 54" src="https://user-images.githubusercontent.com/103027217/201990607-a789a14b-b5cf-4213-8073-1374e0412910.png">

<img width="1440" alt="Screenshot 2022-11-15 at 18 48 16" src="https://user-images.githubusercontent.com/103027217/201990625-58eade10-1f2c-4095-93d5-a9f5469f497c.png">

Tried the solutions offered by this issue: https://github.com/openrocket/openrocket/issues/827 but doesn't work. Made sure access was enabled even though it is unsigned and the typical "unidentified developper" prompt from apple appears, after which I simply click on open, but the app doesn't launch.

**Comment by JoePfeiffer** [comment]
Which version are you attempting to run?  If 15.03, download the current version from https://openrocket.info/downloads.html?vers=22.02.beta.05

**Comment by SkierPiau** [comment]
Worked with the beta, thank you!

**Comment by JoePfeiffer** [comment]
You're welcome!
