### ISSUE TITLE
Support common HPR fin profiles explicitly (e.g. "beveled")

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1846]
OR offers square, rounded, and airfoil as the three fin profiles.  However, HPR rockets seem most often to be built with beveled fins.  We should offer this as an option.

**Comment by SiboVG** [comment]
Duplicate of your own issue #1626?

**Comment by neilweinstock** [comment]
Yes, because apparently I am stupid.  Closing...

**Comment by SiboVG** [comment]
Happens to the best of us
