### ISSUE TITLE
"Edit Simulation" button text blanks when edit panel open

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#1851]
Mac OS Catalina, Intel Mac Book Pro 2019, beta 22b5

<img width="217" alt="Screen Shot 2022-11-24 at 4 18 46 PM" src="https://user-images.githubusercontent.com/35353530/203864413-7f3486b3-22b5-487c-a015-a34528fdd3c1.png">

Not happening on Linux, Windows 7 (yes, really).

Steps to repro:

1. Open example ASMR.
2. Click "Flight Simulations" tab.
3. Click "Edit Simulation" button.

All versions installed with installers.

**Comment by hcraigmiller** [comment]
Unable to reproduce.

Beta 5
Current Unstable

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Comment by jimmiedave** [comment]
Yeah, not happening on Windows, Linux, as noted in first post.
