### ISSUE TITLE
No windows appear in MacOS ventura

### ISSUE THREAD

**Issue by NinjaOwO** [openrocket/openrocket#1870]
When I updated to MacOS ventura openrocket stopped working, the app launches but nothing appears and "Show all windows" just outlines an invisible square. I have tested on apple silicon and intel, neither of them work so I'm guessing its a problem with MacOS ventura.

**Comment by SiboVG** [comment]
Yes, Ventura breaks compatibility with Java 8 programs... You can try our beta software which uses Java 11 and runs just fine in Ventura: https://openrocket.info/downloads.html?vers=22.02.beta.05


________________________________
From: Charlotte ***@***.***>
Sent: Sunday, December 4, 2022 11:23:33 AM
To: openrocket/openrocket ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [openrocket/openrocket] No windows appear in MacOS ventura (Issue #1870)


When I updated to MacOS ventura openrocket stopped working, the app launches but nothing appears and "Show all windows" just outlines an invisible square. I have tested on apple silicon and intel, neither of them work so I'm guessing its a problem with MacOS ventura.
