### ISSUE TITLE
Add "backwards" option for nose cones

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1889]
I would like a checkbox on nose cones to orient them backwards.  This is useful for the tail end of pods.

Currently, you have to do it with a transition, and that means entering all the values from scratch.  What you'd like to be able to do is choose from the nose cone parts library, which you can't do right now.

Being able to put a backwards nose cone there would be perfect, since it's exactly what you would be doing in real life.

**Comment by SiboVG** [comment]
Related to #1683?

**Comment by neilweinstock** [comment]
Yup, looks like it’s a duplicate
________________________________

**Comment by JoePfeiffer** [comment]
Very closely related, but not quite the same thing.  You can have a transition go either direction, you just can't pick it that way from the database.  You simply can't put a nose cone on backwards.

**Comment by neilweinstock** [comment]
Well that issue does mention nosecones being used as tailcones, which is what I'm asking for here.
