### ISSUE TITLE
[Bug] Warning that inline pods "may not simulate accurately"

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1894]
An increasing number of users are positioning pods so that a component (I'll use a transition) can be placed inline as if the transition is the next airframe component after the body tube. @JoePfeiffer confirmed that from an aerodynamic standpoint, this technique may not be (is not) being simulated accurately.

![Transition Pod_Transition](https://user-images.githubusercontent.com/68821492/208042893-301e938f-3529-49f2-9e87-dc527e82993e.png)

With the increasing number of users implementing this technique, if there is a way to **_fairly easily_** determine whether a pod component is positioned in line with the airframe to which it is attached (_only warn if **the pod position is relative to center of the parent component AND the radial distance of zero**_), a warning should be given that "Pods with inline components may not simulate accurately."**_ In any event, a description of this issue and warning should be included in the Wiki._**

I am not suggesting aerodynamic correction. If I understood @JoePfeiffer, he does not believe that aerodynamic correction is feasible, even if possible, because of too many nuances in design variations and should not be undertaken.

[Test.Boosted Dart Example.Transition.zip](https://github.com/openrocket/openrocket/files/10243488/Test.Boosted.Dart.Example.Transition.zip)

**Comment by JoePfeiffer** [comment]
I feel like this leads us down a rabbit hole of trying to anticipate every crazy thing a user can do; at some point, we just have to say "OR doesn't have a general geometry engine" and leave it at that.

**Comment by hcraigmiller** [comment]
**No rabbit holes wanted here.** Only warning if and only if the pod position is relative to center of the parent component AND the radial distance of zero, and, most importantly, if and only if it can be accomplished with relative ease.

**Comment by JoePfeiffer** [comment]
Just came across someone on FB recommending using pods to position things to get a simulation of a non-cylindrical body tube to simulate.  Never mind that I've got no idea how getting something to look right doing that would even work, it's clear you're right that it's a seductive mistake.  We do need the warning.

But the warning should be for anything involving in-line pods, not just when they're butting up against them.

**Comment by hcraigmiller** [comment]
Agreed, only warn if the pod position is relative to center of the parent component AND if and only if the radial distance is zero.

**Comment by neilweinstock** [comment]
> at some point, we just have to say "OR doesn't have a general geometry engine" and leave it at that.

This is incredibly important, but very hard to convey.  I have expressed this sentiment about 1000 times on TRF and (I think?) on the podcast.  I don't how to ensure that users really take it to heart, and I don't know how the program can detect geometries that will not simulate accurately, in the general case.

I do think it's useful to flag, when possible, invalid geometries that might be commonly use and readily detectable.  It's just going to be whack-a-mole with this stuff pretty much forever as far as I can tell.

**Comment by SiboVG** [comment]
Was not fixed by #1979, #1979 was just linked to this issue by accident.
