### ISSUE TITLE
[Bug] Only one recovery device is calculated on descent when multiple boosters/pods each have a recovery device

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1910]
With the mass fixed (overridden), increasing and decreasing the number of boosters with parachutes does not change the descent rate accordingly. Only one of the booster parachutes is ever counted in the descent rate computation.

![Recovery Booster-Pod](https://user-images.githubusercontent.com/68821492/208704966-d65af9d1-1f60-46e9-b532-9c17acead39f.png)

[Boosters.Recovery_Device_Test.ork.txt](https://github.com/openrocket/openrocket/files/10269797/Boosters.Recovery_Device_Test.ork.txt)

**Comment by JoePfeiffer** [comment]
Trying to understand how you ran the multiple-chute tests -- did you duplicate the Booster set to get the second and third tests?

**Comment by hcraigmiller** [comment]
I fixed the mass and ran the test with 1 booster, then 2 boosters, through 4 boosters. The descent rate was the same each time, even though there were more parachutes.
