### ISSUE TITLE
[Bug] Simulation extension error on load of examples

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1923]
The following examples are throwing simulation extension errors when opening the example file:

- Simulation Extensions
- Simulation extensions and scripting

![Simulation Extension](https://user-images.githubusercontent.com/68821492/209439792-f54821bb-a528-4aac-ba03-a5906e04e3c1.png)
The above is the Simulation Extensions example.

**Comment by SiboVG** [comment]
This is the result of PR #1873.

I would also suggest to merge the "Simulation extension" and "Simulation extension and scripting" example, since they're basically the same.

**Comment by JoePfeiffer** [comment]
Rather than combine them, maybe we should separate them?  Having the Java extension do the roll control and air start in the extension example, and having the JavaScript script do both in the scripting example (currently a script is used for roll control, and an extension for air start)?

**Comment by JoePfeiffer** [comment]
@hcraigmiller could you check to see if this is still happening for you?  It isn't for me.  I do still want to better separate the examples, as I suggested above, before we close this.

**Comment by hcraigmiller** [comment]
Using the current unstable, both appear fully functional, not only when loaded, but when all of the simulations are run as well.
