### ISSUE TITLE
When a nose cone is reversed, should be some way to match diameter of previous component in library selector

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1926]
When setting a nose cone to be reversed as a tail, there is currently no way to have the library selector match the diameter of the previous component.

**Comment by SiboVG** [comment]
What do you mean exactly?

**Comment by hcraigmiller** [comment]
I believe that one element that @neilweinstock is looking for is the parts library "Match aft diameter" feature. After a nose cone is flipped to a tail cone, I believe that he would like the "Match aft diameter" feature to be enabled.

**Comment by neilweinstock** [comment]
That's correct.
