### ISSUE TITLE
[Bug] Post-recent merge, nose cone flip to tail cone is gone, and pod example does not have tail cones

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#1932]
The pod example is the old pod example, not the new one created by @neilweinstock.

**Comment by SiboVG** [comment]
It's the right one on my machine, did you use the latest unstable branch? I just updated your remote unstable branch with the latest openrocket unstable branch.

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/11031519/210019589-ee846abf-a4d5-4349-af67-faf3b916d6c5.png">

**Comment by hcraigmiller** [comment]
Just downloaded the new zip and its works fine.
