### ISSUE TITLE
[Feature request] Change Inner Tube cluster tube separation from unitless to distance unit

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1970]
In the Cluster tab of an inner tube, the tube separation is set as a unitless value, where 1 is tubes touching, 2 is 2 tubes distance I guess etc. Wouldn't it make more sense to have this be an actual distance instead of the ambiguous mess that it is now.

**Comment by jura0207** [comment]
Hi, can I work on this issue?

I managed already to change units to length and add an unit selector to the subpanel. Now I just have to configure it to be for a distance and not a scale.

**Comment by JoePfeiffer** [comment]
Go for it!  Let us know if you have any questions on how to proceed.

**Comment by SiboVG** [comment]
Thanks for your interest @jura0207! If I can give you a suggestion on your implementation, because it appears a simple task, but to do it properly, you'll need some background information.

You can see in `InnerTubeConfig.java` that the separation double model equals:
```Java
DoubleModel dm = new DoubleModel(component, "ClusterScale", 1, UnitGroup.UNITS_NONE, 0);
```
The `"ClusterScale"` key means that the double model will search for a `setClusterScale` method in the `InnerTube` class to set the inner tube's cluster scale, and the `getClusterScale` to get the cluster scale.

Internally, InnerTubes also have a `getClusterSeparation` method (declared in `core/src/net/sf/openrocket/rocketcomponent/Clusterable.java`). That's the method that we're after, since it declares cluster separation in units of distance.

So now your goal is to replace `ClusterScale` with `ClusterSeparation`. You'll need to create a `setClusterSeparation` method in `Clusterable.java` and implement `setClusterSeparation` in `InnerTube.java`. Now you need to get rid of the `clusterScale` variable inside `InnerTube.java` and replace it with a `clusterSeparation` variable. The `getClusterSeparation` and `setClusterSeparation` get/set the `clusterSeparation` variable. The `getClusterScale` method returns the cluster scale, transformed back from the `clusterSeparation` variable (the reverse operation of what's currently implemented in `getClusterSeparation`). The `setClusterScale` sets the `clusterSeparation` variable using the same back-transformation.

The reason why you still need `getClusterSeparation` and `setClusterSeparation` is for backward compatibility reasons with OpenRocket 15.03 (more on this later).

Now there are some cautionary areas that need changes:
1. Document saving
2. Document importing
3. Component scaling
4. RockSim saving
5. Other

**1. Document saving**
The .ork design file saves the cluster separation using the cluster scale. We want to change that to cluster separation, but we also want to maintain backward compatibility between OpenRocket 15.03. By this I mean that if you save a design file in OpenRocket 22.02, OpenRocket should (as much as possible) still be able to read that 22.02 design file. If you were to save the cluster separation, and discard the cluster scale, then OpenRocket 15.03 will not be able to read it.

To cope for this, you will need to save the cluster separation twice, but in two **different formats**: once as `clusterscale`, so OpenRocket 15.03 can read it, and one as `clusterseparation`, which is the format that we eventually want to keep.

So in `core/src/net/sf/openrocket/file/openrocket/savers/InnerTubeSaver.java` you will need to implement this:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/11031519/212556240-9eeac6bf-108f-4d50-9e77-fa1a2e753bfa.png">

**2. Document importing**
Analogous to the document saving, OpenRocket 22.02 should be able to read old design files that still have the `clusterscale` parameter. So in `core/src/net/sf/openrocket/file/openrocket/importt/DocumentConfig.java` you need something like this:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/11031519/212556409-4fcce5f1-aedb-4e8b-9ac2-9ff9a8bf67d1.png">

**3. Component scaling**
You can scale an inner tube by selecting it in the component tree, and then selecting in the application ribbon: "Edit > Scale". The `clusterScale` parameter does not need to be scaled, because it is independent of the component size (it's a unitless parameter). However, now you switched to the `componentSeparation` parameter, which does need to be scaled. So, in `swing/src/net/sf/openrocket/gui/dialogs/ScaleDialog.java` you need to add: 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/11031519/212556657-466feb7b-d31e-48af-9b97-6c841b32a860.png">

**4. RockSim saving**
OpenRocket can export .ork files to a RockSim file. I haven't looked at the code of how OR does this for inner tubes, but the change to `clusterseparation` may have broken something. If you don't have RockSim to test something out, don't worry. Either give a quick look at the code to find obvious mistakes, or just remind us to test the RockSim saving when you create your Pull Request on this issue.

**5. Other**
I suggest you do a general file search in the source code for "clusterscale" to find other code areas that need some changes. E.g. I did a "clusterscale" search and found the following code:
```Java
public static InnerTube makeIndividualClusterComponent(Coordinate coord, String splitName, RocketComponent theInnerTube) {
  InnerTube copy = (InnerTube) theInnerTube.copy();
  copy.clearConfigListeners();
  copy.setClusterConfiguration(ClusterConfiguration.SINGLE);
  copy.setClusterRotation(0.0);
  copy.setClusterScale(1.0);     <--- bingo!
  copy.setRadialShift(coord.y, coord.z);
  copy.setName(splitName);
  return copy;
}
```
Here you see the code `copy.setClusterScale(1.0);`. I would replace this with `copy.setClusterSeparation( <inner tube diameter> );`. In fact I would try to replace as much as the `clusterscale` occurrences as possible. Only for backward compatibility reasons, you can keep `clusterscale`. When we don't want backward compatibility anymore, we're gonna delete all the code references to `clusterscale` anyways.

---

I'm sorry @jura0207  for the very long explanation, and am equally sorry if I gave away too many answers that you wanted to discover yourself. Just want to make sure that you don't get overwhelmed with weird bugs, and that it's done properly. Also, if some of my demo code is wrong, I apologize 🙃.

**Comment by jura0207** [comment]
Thank you @SiboVG for a detailed issue analysis! It's very helpful. I managed to work something out by myself. I replaced scaling with distance and it worked, but I got funny readings while opening files, because .ork file still had scaling as input.

Now that you gave me a notice about the backwards compatibility and some tips I have some idea how to do it.

With distance now working, I can add on a function where a file is loaded an _if case_ to see if the file has clusterScaling and clusterSeparation, then with getOuterDimeter we can calculate and add clusterSeparation if it's missing or vice versa for the backwards compatibility. This way there is no need for clusterScaling.
Also, on saving, this way we can calculate and set clusterScaling too.

This way when the support for OR 15.03 stops, there is minimum changes to be made. There would be no parallel functions, getters and setters for scaling and distance, but only for distance. And clusterScale would be converted. I can try it this way and I'll report my results back.

Thank you for giving a notice to backward compatibility, I forgot about that.

For testing RockSim simulation, I saw that there are some default rocket models, could I test it with those?

**Comment by jura0207** [comment]
I got progress. It turned out I have to use setClusterScale and in it I'm also calculating clusterSeparation out of the scale:
![image](https://user-images.githubusercontent.com/59030624/212563316-31ca5326-be67-4acb-ba3f-6d007eba53af.png)

After reading clusterScale, I'm reading clusterSeparation:
![image](https://user-images.githubusercontent.com/59030624/212563580-b0c3d766-0460-4bf8-a475-36e4faaedf4e.png)

It saves both clusterScale and clusterSeparation:
![image](https://user-images.githubusercontent.com/59030624/212564046-3d720b27-90d1-4dd3-9a3e-933905ca25f8.png)

**Comment by SiboVG** [comment]
> I got progress. It turned out I have to use setClusterScale and in it I'm also calculating clusterSeparation out of the scale: ![image](https://user-images.githubusercontent.com/59030624/212563316-31ca5326-be67-4acb-ba3f-6d007eba53af.png)
> 
> After reading clusterScale, I'm reading clusterSeparation: ![image](https://user-images.githubusercontent.com/59030624/212563580-b0c3d766-0460-4bf8-a475-36e4faaedf4e.png)
> 
> It saves both clusterScale and clusterSeparation: ![image](https://user-images.githubusercontent.com/59030624/212564046-3d720b27-90d1-4dd3-9a3e-933905ca25f8.png)

It's better for `setClusterScale` to be:
```Java
public void setClusterScale(double scale) {
    double separation = scale * getOuterRadius() * 2;
    setClusterSeparation(separation);
}
```

then you can keep all the logic inside the `setClusterSeparation` method.

**Comment by SiboVG** [comment]
And in the parameter saving, don't type out the formula for cluster scale, but call the method `tube.getClusterScale()` and then have that method be
```Java
public double getClusterScale() {
    return getClusterSeparation() / (getOuterRadius() * 2);
}
```

You want to maintain all the logic inside `InnerTube.java`, that's just good practice.

**Comment by jura0207** [comment]
Yes, thank you! I believe that's the better way. I've changed it, tested the software and everything works as expected. I've tested loading files with only clusterScale and both clusterScale and clusterSeparation, I've tested scaling, resetting, creating new cluster and spliting clusters. I haven't tested changes in RockSim.

Are there some documentation changes that I should change?

**Comment by SiboVG** [comment]
> Yes, thank you! I believe that's the better way. I've changed it, tested the software and everything works as expected. I've tested loading files with only clusterScale and both clusterScale and clusterSeparation, I've tested scaling, resetting, creating new cluster and spliting clusters. I haven't tested changes in RockSim.

Great! If you're ready with everything, you can push your PR.

> Are there some documentation changes that I should change?

You should delete this:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/11031519/212569066-c54285e0-36fe-42e9-a1f8-6f1ec298f16c.png">

plus all the `InnerTubeCfg.lbl.ttip.TubeSep` translation keys inside the messages-files in `core/resources/l10n`
<img width="391" alt="image" src="https://user-images.githubusercontent.com/11031519/212569110-52e565ef-b78d-4965-8b53-7e81be495d2b.png">

**Comment by jura0207** [comment]
Language changes implemented and pull request created
