### ISSUE TITLE
Update example rockets to include simulation data

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#1972]
The current example rockets aren't all saved with simulation data included. E.g. if you open "A simple model rocket" and go to the simulation's tab, you can see that the simulations are marked as out-of-date.

**Comment by hcraigmiller** [comment]
This issue may be interrelated with Issue #1973. For example, using the _Pods--airframes and winglets_ example:

![Motor Configurations](https://user-images.githubusercontent.com/68821492/212572415-d0ea96d6-dede-424b-a06d-19649bd9178c.png)

The three example designs that seem to be affected by this are: (1) Dual parachute deployment, (2) Pods--airframes and winglets, and (3) Simulation extensions and scripting. The other example designs do not exhibit this behavior.

**Comment by SiboVG** [comment]
> This issue may be interrelated with Issue #1973. For example, using the _Pods--airframes and winglets_ example:
> 
> ![Motor Configurations](https://user-images.githubusercontent.com/68821492/212572415-d0ea96d6-dede-424b-a06d-19649bd9178c.png)
> 
> The three example designs that seem to be affected by this are: (1) Dual parachute deployment, (2) Pods--airframes and winglets, and (3) Simulation extensions and scripting. The other example designs do not exhibit this behavior.

Maybe a dumb remark, but you did enable "Save all simulated data" right?
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/11031519/212574917-dfb90260-a6a5-48f6-af3b-64540707bb4a.png">

**Comment by hcraigmiller** [comment]
Good catch. . . ignore my oversight. . . it's been a long few days.

**Comment by SiboVG** [comment]
> Good catch. . . ignore my oversight. . . it's been a long few days.

No worries, I'm just happy that there's no new bug 🙂.
