### ISSUE TITLE
Slider is not working

### ISSUE THREAD

**Issue by Filipposcmd** [openrocket/openrocket#2014]
![Στιγμιότυπο οθόνης 2023-02-02 212552](https://user-images.githubusercontent.com/79402496/216442045-f0ba860b-f971-4e94-874a-a20cf81bc343.png)

The marked slider is not working (Windows NT 11.0(windows 11))

**Comment by Filipposcmd** [comment]
*ignore my rocket it is unfinished*

**Comment by hcraigmiller** [comment]
The slider is not intended to function in 3D views. Instead, in 3D views, left-click (hold) while sliding the mouse controls the movement of the rocket in the display window, 360-degree movement.

**Comment by JoePfeiffer** [comment]
We should probably hide the rotation slider in 3D views, but it's not an immediate concern.

**Comment by neilweinstock** [comment]
That is a good idea.  Or maybe even rethink the slider, because its operation is apparently not obvious to a lot of people.

Gonna close this one.
