### ISSUE TITLE
Component Analysis Dialog enhancements

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2019]
A couple of things have come to mind trying to use the dialog to explain how OR is calculating drag on a recent rocket:

1.  when a row in the dialog is clicked, the corresponding component in the rocket design should be highlighted.
2. a fifth column should be added to the drag tab, giving the aggregate total Cd for each component.  The current fourth column, showing per instance total Cd, should be retained. The grand total Cd should be over this fifth column.

**Comment by SiboVG** [comment]
> 2\. a fifth column should be added to the drag tab, giving the aggregate total Cd for each component.  The current fourth column, showing per instance total Cd, should be retained. The grand total Cd should be over this fifth column.

Should we blank out the per instance CD of the rocket?
<img width="923" alt="image" src="https://github.com/user-attachments/assets/3b845e0a-0382-44cd-9d65-83bc7676e1e6">

Doesn't make much sense to me to sum up the instance CD's and compare the relative influence. WDYT @JoePfeiffer?

**Comment by JoePfeiffer** [comment]
> Should we blank out the per instance CD of the rocket? 
> Doesn't make much sense to me to sum up the instance CD's and compare the relative influence. WDYT @JoePfeiffer?

In the particular case of the whole rocket it makes sense to either blank it out or show it as equal to the rocket's total (so it isn't the sum of the per-component CDs). Blanking it out is probably marginally better, so we don't have users expecting it to be the sum of the per-component CDs.

Thinking about it further, this is only one example of a component assembly, which in general are hard to deal with in a table. Suppose the rocket has three pods; we should show the per-pod CD, and then the sum of the pods. But now suppose the pods each have four fins; we should show the per-fin CD, but then is the sum of the fins 4 times or 12 times a single fin?

**Comment by SiboVG** [comment]
> Thinking about it further, this is only one example of a component assembly, which in general are hard to deal with in a table. Suppose the rocket has three pods; we should show the per-pod CD, and then the sum of the pods. But now suppose the pods each have four fins; we should show the per-fin CD, but then is the sum of the fins 4 times or 12 times a single fin?

Good point. I guess for pods and booster, we just use one complete instance CD (sum of all children instances). For a rocket, I would still blank out the result, since that's really the grand total of all CDs.

**Comment by SiboVG** [comment]
> > Thinking about it further, this is only one example of a component assembly, which in general are hard to deal with in a table. Suppose the rocket has three pods; we should show the per-pod CD, and then the sum of the pods. But now suppose the pods each have four fins; we should show the per-fin CD, but then is the sum of the fins 4 times or 12 times a single fin?
> 
> Good point. I guess for pods and booster, we just use one complete instance CD (sum of all children instances). For a rocket, I would still blank out the result, since that's really the grand total of all CDs.

Wait, currently we don't even add pods and booster in the component analysis tables... (because the CD is just 0)
