### ISSUE TITLE
Get rid of option to save subset of simulation data

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2024]
**Is your feature request related to a problem? Please describe.**
This is an option that was introduced when disks were much smaller (possibly at the beginning of the project). ork files, even with many simulations, just aren't big enough to worry about any more.

There appears to have been at least one case of a user who used this option to save a subset of the data, and then thought the data hadn't been generated.

**Describe the solution you'd like**
Just get rid of the "Every xx seconds" option in the file save dialog

**Describe alternatives you've considered**

**Additional context**

**Comment by neilweinstock** [comment]
I would love to get rid of this option.  Every time I save a file and the dialog comes up I wonder why it is asking me that.

How big could a file get if all data were saved at max resolution?  Thinking for a high-flying rocket with a lot of simulations.

**Comment by JoePfeiffer** [comment]
The .ork file from one run of an "orbital" design, which times out at 1200 seconds -- it hits a peak altitude of 1.29e7 ft -- is 73,563,451 bytes. That's pretty much a worst case (I came across the design because the user seemed to feel our chopping a sim off at 1200 seconds was a bug).

Remember the suggestion is just to not allow saving part of the data.  It leaves the option of saving no data at all available.

**Comment by neilweinstock** [comment]
That is big. :)

We then need to have a sensible policy for what to do when the file is loaded.  I guess someone doing something like that would have "automatically update simulations" disabled, don't want to kick off the sims every time a file like that is loaded.  I guess in that case the sims would just be marked "out-of-date", and it would behave as normal according to that scenario.

I do like an "all-or-nothing" approach.  The middle option is just confusing in most cases.

**Comment by JoePfeiffer** [comment]
The .ork has 9 identical (I think -- they at least all use the same motor configuration) simulations defined.  I wanted to present a *real* worst case of saving all of them, but life is just too short to run them all. They're several minutes each.

We should be showing sims as having been loaded from a file when that's the case.
