### ISSUE TITLE
[Bug] Parachute Location error after updating packed length

### ISSUE THREAD

**Issue by Rocketman-1969** [openrocket/openrocket#2036]
**Describe the bug**
The Location for the parachute icon is in the wrong place when you enter the packed length and the parachute location relative to the bottom of the parent component. 

**To Reproduce**
Create a parachute, change the packed length to 4 in, change the relative location to the bottom of the parent component, and change the location. 

**Expected behavior**
I would expect that the parachute icon would be at a reasonable distance from the bottom of the parent component 

**Screenshots**
![bug report](https://user-images.githubusercontent.com/96217580/218285412-bc13cbc1-e674-421b-be61-b5cf6b09f0f1.PNG)

**ORK File**
If the problem is triggered by a particular ORK file, please zip it and attach it to this issue.

**Platform**
 - OS: [e.g. Windows10]
 - OpenRocket version (e.g. 22-02)
 - Graphics card (Ninvida 

**Additional context**

**Comment by SiboVG** [comment]
Can confirm if the "Auto" packed diameter checkbox is checked.

**Comment by Rocketman-1969** [comment]
I unchecked it and it seemed to resolve the issue
