### ISSUE TITLE
[Bug] Quotes in part names keep .ork files from loading.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2051]
**Describe the bug**
Quotes in .ork files cause a failure to load

**To Reproduce**
Attempt to open the attached file.  An error popup appears, stating the the XML is malformed.  The issue is the 11" long tube.

**Expected behavior**
File opens

**Additional context**
Note that a workaround is to load the problematic part from the parts library, then change a parameter and then change it back so the part name isn't saved.

[ork_test.zip](https://github.com/openrocket/openrocket/files/10727839/ork_test.zip)

**Comment by sjh114961** [comment]
The right thing to do is fix the ORC file with the error. Please add an issue to DCooks parts database.

**Comment by SiboVG** [comment]
> The right thing to do is fix the ORC file with the error. Please add an issue to DCooks parts database.

Not really necessary, we can sanitize the XML ourselves (see my PR #2054). Dave shouldn't worry about this kind of stuff :)
