### ISSUE TITLE
[Feature Request] Add option to show stability in cals and as a percentage

### ISSUE THREAD

**Issue by Ash2772** [openrocket/openrocket#2079]
I find my self frequently switching between stability calibers and the stability as a percentage.

Could there be an option in the units preferences to show cals and % at the same time in the rocket design tab?

![image](https://user-images.githubusercontent.com/79996740/221412996-85b38909-bc08-45c4-8265-0821912bf85d.png)

**Comment by neilweinstock** [comment]
I agree with this.  We should show both all the time, and remove the option.

Propose something like this:
![image](https://github.com/openrocket/openrocket/assets/243872/34d0c6a2-401a-4504-bcf5-91a746e0b475)

**Comment by SiboVG** [comment]
> In the Simulation Plot/Export, there is currently "Stability Margin Calibers" available as a Y axis type. I would then add "Stability Margin Percentage" as an addition type. I _think_ that's the only other place in the UI that stability appears.

I would make a new ticket for this to add units to the "Stability Margin" data type. I would prefer this over having a separate "Stability Margin Percentage" data type.

**Comment by neilweinstock** [comment]
Yes, of course that is better.  I was working too fast and forgot that there was a units option for each Y axis type. I'll create the new issue.
