### ISSUE TITLE
[Bug] undo loses custom configuration names

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2101]
bryceliposky@gmail.com reports on the sourceforge bug mailing list:

Whenever I hit CTRL-Z or Edit/Undo, I lose all of the custom
configuration names I've created.  The configurations remain, but the names
revert to the default names.  Model file attached.  Thanks for looking into
this!

**Comment by hcraigmiller** [comment]
Functions as expected, no anomalous behavior found.

OR Build: 1633
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
