### ISSUE TITLE
[Feature Request] Display & dynamically update International Standard Atmosphere temperature and pressure text

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2104]
When ISA conditions are selected, it would be useful if the pressure and temperature change when the altitude changes, so users don't think the temperature and pressure is always stuck at 15 °C and 1013 mbar.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/11031519/223288997-3c66414e-f23b-45c7-b0ed-273fe5ec3a3d.png">

**Comment by SiboVG** [comment]
Well I guess the text boxes don't even display the ISA conditions, they display what was typed in before. I think it's better to display the ISA values there regardless of what was typed in the boxes before.

**Comment by JoePfeiffer** [comment]
I agree completely -- see #1217 :)

**Comment by SiboVG** [comment]
> I agree completely -- see #1217 :)

Ahh, I searched the open issues, so I didn't find it. Well I have to disagree with my March 15th 2022 opinion, I actually like your #1217 proposition Joe 🙃.
