### ISSUE TITLE
OR saving malformed XML

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2114]
Look at attached ORK file.  There's an XML error in it: 

`<bodytube>
<name>Body Tube</name>
<preset type="BODY_TUBE" manufacturer="Rocketarium" partno="29mm Motor Mount tube 5.5"" digest="ef554285e8e7ab49e1bfc595ac240a5b"/>
`

The double quote in the part number is not being escaped.

[BP Max Altitude.zip](https://github.com/openrocket/openrocket/files/10961791/BP.Max.Altitude.zip)

**Comment by SiboVG** [comment]
Duplicate of #2051, already fixed.
