### ISSUE TITLE
[Improvement] Throw warning when users tries to save filename with illegal character

### ISSUE THREAD

**Issue by Voyhager3** [openrocket/openrocket#2131]
**Describe the bug**
When saving a design file (as of yesterday), the file will no longer save as a .ork, only as a .tmp, the file still works, but it doesn't save the name, so finding the file to rename it is a problem. 

**To Reproduce**
No one else seems to be having this issue, but I am using a flash-drive (but also have been for the past year+) with plenty of storage. But it occurs no matter how I try to save it.

**Expected behavior**
The file to save as a normal .ork file, not whatever 73047023984792374274.tmp is

**Screenshots**
![image](https://user-images.githubusercontent.com/128533597/226723733-e2b24846-aab7-40a3-8704-a73dd3434227.png)
![image](https://user-images.githubusercontent.com/128533597/226723799-35cf3b4c-990b-4147-ad5c-ba3a8cf2a80b.png)

**ORK File**
If the problem is triggered by a particular ORK file, please zip it and attach it to this issue.

**Platform**
 - OS: [e.g. Windows10] windows 10
 - OpenRocket version (e.g. 22-02) (22-02)
 - Graphics card (if a graphics or display-related problem)

**Additional context**

**Comment by hcraigmiller** [comment]
Could not reproduce.

OR Build: 2022-02
Microsoft Windows 11 Pro; 10.0.22621 Build 22621.1105; Windows Feature Experience Pack 1000.22638.1000.0
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)

**Comment by Voyhager3** [comment]
I figured out the error was caused by the save file name including illegal characters, sorry, my bad.

**Comment by SiboVG** [comment]
> I figured out the error was caused by the save file name including illegal characters, sorry, my bad.

Actually this is still an interesting bug. I'm gonna re-open this and change the title. @Voyhager3 could you give us the illegal character(s) that caused the problem?

**Comment by Voyhager3** [comment]
The illegal character I was using was the colon ":", but a list of other illegal characters I found were as follows
/ \ ? * " : < > | 
I don't know if its a global computer thing, or just an .ork thing.
