### ISSUE TITLE
Overriding subcomponents makes for a very ugly component tree

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2188]
I appreciate the thought process that went into this last release but IMHO this is really not appealing, as it makes the whole component tree harder to read, and just generally ugly:
![image](https://user-images.githubusercontent.com/243872/230908301-27add6ca-ee12-4b03-9839-0df8a6c83efd.png)

The reason I care enough to actually file an issue is that overriding mass and CG of an entire rocket is a common and in fact recommended thing to do, and so there will be a lot of finished OR files the look just like the above.  Yuck.

As is so often the case, I'm not sure how to fix it yet.  Some thoughts I had were:
1) make the grey subcomponent override icons *smaller*
2) Put the override icons in their own column at the left
3) Do something else on the left side.  I'll try to mock something up.

**Comment by neilweinstock** [comment]
Some mockups:
![image](https://user-images.githubusercontent.com/243872/230912061-3e957994-4adf-44b7-bcb0-f92b9e4712f5.png)

I'll do more to show at least one other override configuration.

**Comment by neilweinstock** [comment]
I suppose that technically, this is an option as well, but I don't think it's better than any of the others.
![image](https://user-images.githubusercontent.com/243872/230938152-bd9e192e-cc19-46b9-aad1-cb8f9b490506.png)

**Comment by SiboVG** [comment]
It's not possible to put stuff in the left column + I'm also not a fan of it.

**Comment by neilweinstock** [comment]
If so then maybe we can start off by just smallifying the icons, which would be better than nothing.

**Comment by JoePfeiffer** [comment]
I honestly don't see the problem with the current component tree display. I don't find the current override icons to be ugly, and I don't see them as making the tree harder to read.  Even if it were possible to move the icons to their own column, moving them farther from the components they refer to would, I believe, make it harder to associate them with the components.  I don't have any real objection to making them smaller, just so they stay large enough to still be easily visible.

**Comment by neilweinstock** [comment]
Current appearance really bugs me.  We'll try some smaller icons; I think they can be kept completely readable.  If folks don't agree we won't do it.

**Comment by SiboVG** [comment]
> Current appearance really bugs me. We'll try some smaller icons; I think they can be kept completely readable. If folks don't agree we won't do it.

I think it's a good suggestion to make those icons smaller, I can experiment with it a bit to see what works.

**Comment by neilweinstock** [comment]
If you can wait, I'll have a draft PR up by tonight.

**Comment by SiboVG** [comment]
> If you can wait, I'll have a draft PR up by tonight.

Sure. Can you use the `Icons.getScaledIcon` when scaling down the icons, instead of uploading new images? So, in `swing/src/net/sf/openrocket/gui/main/componenttree/ComponentTreeRenderer.java`:
```Java
double overrideSubcomponentIconScale = 0.8;
if (c.getMassOverriddenBy() != null) {
	p.add(new JLabel(Icons.getScaledIcon(Icons.MASS_OVERRIDE_SUBCOMPONENT, overrideSubcomponentIconScale)));
} else if (c.isMassOverridden()) {
	p.add(new JLabel(Icons.MASS_OVERRIDE));
}
if (c.getCGOverriddenBy() != null) {
	p.add(new JLabel(Icons.getScaledIcon(Icons.CG_OVERRIDE_SUBCOMPONENT, overrideSubcomponentIconScale)));
} else if (c.isCGOverridden()) {
	p.add(new JLabel(Icons.CG_OVERRIDE));
}
if (c.getCDOverriddenBy() != null) {
	p.add(new JLabel(Icons.getScaledIcon(Icons.CD_OVERRIDE_SUBCOMPONENT, overrideSubcomponentIconScale)));
} else if (c.isCDOverridden()) {
	p.add(new JLabel(Icons.CD_OVERRIDE));
}
```

Makes it easier for you to experiment with changing the scale + ensures we won't have to do actual image editing.

**Comment by neilweinstock** [comment]
I could, but my hand-edited icons will be sharper and nicer.  At small
sizes, scaling becomes very much sub-optimal, and if we're going to be
evaluating for readability then I'd hate to be handicapped by the scaling
algorithm.  And these are only three small monochrome images, very very
easy to modify.  For now, for demonstration/mockup purposes, I'll just
throw in my edited images and we can decide what to do next based on the
feedback.

**Comment by neilweinstock** [comment]
Instead of a draft PR here are mockups for evaluation.
![image](https://user-images.githubusercontent.com/243872/230980320-38950ced-8c69-4342-8646-3073cc2872de.png)

**Comment by neilweinstock** [comment]
After staring for a while I like option 3 best.  It is still (IMHO) very clear, but noticeably de-emphasizes the overridden subcomponents.  But I would settle for (2) if I had to.

**Comment by SiboVG** [comment]
I can go along with no. 3.

**Comment by SiboVG** [comment]
@neilweinstock could you open a PR with the nr 3 icons?

**Comment by neilweinstock** [comment]
Thank you for the reminder.

Do I need to do anything other than swap the new images in?
