### ISSUE TITLE
edit components error

### ISSUE THREAD

**Issue by oscar1703** [openrocket/openrocket#2193]
I been trying to edit a component in a model that im making but it just dont let me and i try new ones and it happend the same

**Comment by JoePfeiffer** [comment]
Please give us some more information about exactly what's happening -- does it happen with all components?  When you try to edit a component, does an edit window appear?  Are you unable to change parameters in the edit window?  If you are able to change parameters in the edit window, do they not get reflected in the design? Do you have a .ork file that it's happening with?

**Comment by SiboVG** [comment]
Closing due to lack of information.
