### ISSUE TITLE
[Bug] Sim NaN when mass is 0

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2196]
### Describe the bug

As described in the title.  See the thread in openrocket-bugs https://sourceforge.net/p/openrocket/mailman/openrocket-bugs/thread/CH2PR22MB1781F48240B44FD3B8E79425A29C9%40CH2PR22MB1781.namprd22.prod.outlook.com/#msg37804943
[ErrorOut.zip](https://github.com/openrocket/openrocket/files/11296760/ErrorOut.zip)

### To Reproduce

1. 
2. 
3. 
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

22.02

### What platform are you running on?

Linux

**Comment by SiboVG** [comment]
[ernest.and.dillon.zip](https://github.com/openrocket/openrocket/files/11302290/ernest.and.dillon.zip)
.ork file to reproduce

FYI: only you and I can see the sourceforge discussion @JoePfeiffer, it's not public.
