### ISSUE TITLE
Parachute packed length can be N/A

### ISSUE THREAD

**Issue by mikerupert1971** [openrocket/openrocket#2198]
Attaching compressed zip file
[Erika, Kylie.zip](https://github.com/openrocket/openrocket/files/11298981/Erika.Kylie.zip)

**Comment by SiboVG** [comment]
For some reason, the packed length of your parachute is set to N/A, which causes the simulation error.
Could you guide us through how you added the parachute? Was is picked from a component preset or something else?

**Comment by SiboVG** [comment]
@mikerupert1971 a follow-up on this?

**Comment by SiboVG** [comment]
No response from the user, closing this. I also pushed an update some time ago in #2176 that should alleviate the risk of these N/A values.
