### ISSUE TITLE
Major problem in tube fin set mass calculation

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2217]
See attached ORK file:

- The body tube is 15" long.  Calculated mass is .827 oz.
- The tube fins are a set of 5, each 3" long.  Calculated mass is 4.3 oz.
- Both are based on the same library component (BMS T60-34).

There seems to be an extra multiplication by the number of fins (i.e. the mass of one fin is getting multiplied by 5 *twice*).  Pretty much confirmed this by experimenting with the number of fins in the set.

[tube_fins_mass.zip](https://github.com/openrocket/openrocket/files/11546443/tube_fins_mass.zip)

**Comment by SiboVG** [comment]
FYI: this is only present in the latest unstable, not in 22.02.

**Comment by neilweinstock** [comment]
OK, in that case it proves beyond doubt that at some point I swapped in an unstable build on my Windows machine.

Even if only in unstable, definitely needs fixing, but glad to hear it is not affecting 22.02 users.

**Comment by JoePfeiffer** [comment]
Hmm, not sure when that would have snuck in... I'll look for that too
