### ISSUE TITLE
[Enhancement] Include data before stage separation in sim export

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2225]
Update: this is not a bug as described in this comment. See comments below for more info. What the enhancement should be is to include the sustainer data before separation (which is common to all stages) in the sim export.

### Describe the bug

Reported by user david314 on our Discord server:
I found a bug, when exporting a multi-stage rocket simulation, the lower stage has no data until separation.

### To Reproduce

1. Open 'Three-stage rocket' example design
2. Go to the simulations tab
3. Export one of the simulations
4. Select export variables, e.g. export time and altitude
5. Select one of the bottom stages (e.g. booster 2)
6. Export
7. You'll see that the exported CSV starts its time at the stage separation time of the exported stage

#### Screenshot(s):
Example export of the three-stage rocket example design.
Sustainer export:
<img width="461" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/b23d1dcc-894f-4931-8042-5a57dccd3d24">

Booster 1 export:
<img width="384" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/627ff560-5b3a-48e4-88d0-dee702f934b3">

Booster 2 export:
<img width="378" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/8d1acff0-9da7-49fa-8450-96531f459350">

### OpenRocket version

22.02, unstable

### What platform are you running on?

macOS

**Comment by JoePfeiffer** [comment]
This isn't a bug, it's a result of how simulations are processed.  The first stage has no independent data until after  the upper stages separate.  If you look at the sustainer data, you'll see that it includes the mass for the booster and the sustainer, and it shows the thrust from the booster motor, up until stage separation time.  At separation, the booster begins getting tracked separately from the sustainer.

You can see the same thing in the data plots:  if you plot everything, you see a single line up until separation, and then a  line for the sustainer and one for the booster.  If you just ask for the sustainer, you see a single line for the entire flight.  If you ask for just the booster, the line doesn't start until separation.

The advantage of doing it this way is that if you just export the sustainer data, you end up with all the data 99% of users want in a single CSV. The only people with any interest in the behavior of the booster after separation are people who have a heavy enough booster on a high power rocket that it has a recovery system.  For people doing low power, the booster just tumbles immediately after separation and lands immediately.  The max altitude achieved by the booster isn't significantly higher than the altitude at separation.

This has caught a few people by surprise (I could swear there have been previous bug reports about it, but I haven't been able to find them in a search on github this morning), and there have been proposals for other approaches.  One user was absolutely adamant that the simulation should start with the booster stage, and the sustainer data shouldn't be started until after separation.  That might be clearer for a new user, but it does exactly the wrong thing in terms of putting all the useful data in a single export.

**Comment by SiboVG** [comment]
Okay, I understand your explanation, but it still confusing that the data is exclusive to the sustainer data export. It would be more sensible to include the data before separation (the sustainer data) in the sim export of other stages. Not only would this remove confusion, it also eliminates the need to manually merge data from the sustainer export to get a complete sim export for the other stages.

I will re-open this, but mark it as an enhancement.
