### ISSUE TITLE
Fin root chord does not account for canted angle

### ISSUE THREAD

**Issue by B3-1973** [openrocket/openrocket#2231]
### Describe the bug

I am not sure if this is a bug or a desired feature. I am building a rocket with a large ring fin supported by 4 canted fins from the main body tube. The main body tube and the ring fin have a common axis of rotation.
1. As far as I could determine, OpenRocket 22 does not allow this type of fin configuration.
2. The pattern for the canted fins prints with a straight line for the root attached to the main body tube but this should be a parabolic section. I worked out the math for the intersection and set up a spreadsheet that allows me to change the cant angle and radius of the body tube. I was able to 'correct' the OpenRocket fin pattern. I would be glad to share my work if you are interested.

### To Reproduce

1. Add BT60 nose come of any type then add a BT60 body tube.
2. Add trapezoidal fins with a 15 cm root and a 5 degree cant angle.
3. Print the fin pattern and you will note the root is straight instead of a mild parabola. 
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

22.02

### What platform are you running on?

Windows

**Comment by JoePfeiffer** [comment]
You are correct that OR does not support ring fins at present. You can fake it with a single tube fin, but I'd be pretty leery of believing simulation results based on it.
