### ISSUE TITLE
[Bug] top, side views of rocket don't draw canted fins along body tube.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2251]
### Describe the bug

When showing canted fins in the top or side views, the fin root is shown as straight, not following the curve of the airframe.

### To Reproduce

1. create a new design
2. add a body tube
3. add fins; set a long root chord and high cant

### Screenshots / .ork file

![fins](https://github.com/openrocket/openrocket/assets/3065196/a18166ff-2772-4297-87f9-e25b002c83e2)

### OpenRocket version

unstable

### What platform are you running on?

Linux

### Additional context

Very, very minor bug

**Comment by SiboVG** [comment]
I'm confused, this is a duplicate of #2231, which is fixed by #2243, right?

**Comment by SiboVG** [comment]
Latest unstable:
<img width="704" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/2cf1c55b-a378-4df7-abdd-e99e163036f9">

**Comment by JoePfeiffer** [comment]
Oops, yes. Somehow when I was looking at it after merging, I apparently was looking at top and side views from before.
