### ISSUE TITLE
[Bug] component analysis drag characteristics table doesn't change color tracking "dark mode" in desktop.

### ISSUE THREAD

**Issue by Bob-The-Ai** [openrocket/openrocket#2255]
### Describe the bug

The values in the drag characteristics tab of the component analysis interface is white on beige which makes it unreadable.

### To Reproduce

1. Create a basic rocket
2. Tools > Component analysis
3. Go to drag characteristics

### Screenshots / .ork file

![image](https://github.com/openrocket/openrocket/assets/131916103/6942c9b9-4ec8-4f68-af86-a6d5dad32a09)

### OpenRocket version

22.02

### What platform are you running on?

Linux

### Additional context

I am using KDE in dark mode.

**Comment by JoePfeiffer** [comment]
If you switch to light mode, is it readable (I'm wondering if Java is picking up that you're in dark mode and setting all the text to white in spite of being on a light background.  That's what it looks like to me; having the text become black if you switch to light mode would help confirm it).

**Comment by JoePfeiffer** [comment]
We basically don't support dark at the moment.  There is an open PR (#1089) to support it in a future release. Some things work just because Java itself support dark mode, but that's pretty much by accident.

**Comment by Bob-The-Ai** [comment]
It would appear that the cells not changing color because the color of the cells is "manually" set to indicate how "much" drag there is.

**Comment by JoePfeiffer** [comment]
> It would appear that the cells are not changing color because the color of the cells is "manually" set to indicate how "much" drag there is.

Yes, you're correct.  So fixing it would require coming up with a different set of calculations to set the colors when in dark mode.
