### ISSUE TITLE
[Feature Request] Add JSpinners to Component analysis dialog

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2258]
**Is your feature request related to a problem? Please describe.**
The only way of editing the parameters in the component analysis dialog is via the sliders. So to reach a specific value, you have to fine-tune the slider instead of typing a value.

**Describe the solution you'd like**
Change the static text box to a JSpinner where you can type a desired value and increment it as well. We could also add a unit selector.

<img width="916" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/fd05dd0f-5ea2-4bf6-b881-bef4d63d37d0">

**Comment by isaacjones99** [comment]
I would like to work on this issue.

**Comment by JoePfeiffer** [comment]
Go for it!  Let us know if you need any help.
