### ISSUE TITLE
[Bug] Illegible motor manufacturers in dark mode

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2298]
### Describe the bug

In dark mode, the manufacturers are unreadable.

### To Reproduce

.

#### Screenshot(s):
<img width="1353" alt="Screenshot 2023-08-19 at 19 13 07" src="https://github.com/openrocket/openrocket/assets/11031519/6ba4526a-a9ec-4a04-bec7-b39e5996f02f">

### OpenRocket version

unstable

### What platform are you running on?

macOS

### Additional context

UI font size set to 13.

**Comment by JoePfeiffer** [comment]
Confirmed under Linux
