### ISSUE TITLE
[Bug] hover/tooltip with aggregate mass only appears for overriden components

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2329]
### Describe the bug

In v. 22.02 and prior, hovering over, for example the body tube, would present a tooltip with the component mass and aggregate mass of all the components and sub-components of the body tube (body tube, fin set, inner tube, CRs, chute, etc.)

In v. 23.xx unstable, the hover does not appear, unless the hovered component has a mass override.

There does not appear to be an alternate way to get aggregate mass of sub-components in 23.xx unstable.

### To Reproduce

1. Open A Simple Model Rocket example in v23.xx unstable
2. Close info box
3. Hover over body tube in the component tree with the mouse, and keep it still
4. Note that no hover information appears
5. Override the body tube's mass
6. Hover over body tube in the component tree with the mouse, and keep it still
7. Note that a hover message does appear for the overriden part
...

#### Screenshot(s):
Mac screengrab does not record mouse pointer properly. I'm hovering over the body tube in both cases.

v. 22.02
<img width="289" alt="v2202" src="https://github.com/openrocket/openrocket/assets/35353530/9d4da45f-92ab-474d-a48d-59a9b4fb0797">

v. 23.xx unstable
<img width="289" alt="v23xx" src="https://github.com/openrocket/openrocket/assets/35353530/cbc9a665-ea07-442f-a217-66fd06bf72af">

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

23.xx unstable

### What platform are you running on?

macOS

**Comment by SiboVG** [comment]
Good catch, thanks!
