### ISSUE TITLE
23.09b1: Export complete sustainer as separate files generates exception

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2341]
The attached ORK file generates an exception when selecting the sustainer and then exporting OBJ as separate files.

ORK file and exception stack trace are attached.

[Contest_2024_10K.ork.zip](https://github.com/openrocket/openrocket/files/12667696/Contest_2024_10K.ork.zip)
[exception.txt](https://github.com/openrocket/openrocket/files/12667706/exception.txt)

**Comment by SiboVG** [comment]
Okay, this one is pretty funny, the cause of the bug is that some component names use the "/" character, which will then be used in the filename and cause the previous filename text to be interpreted as a directory.

Love it when users break your code in unexpected ways.
