### ISSUE TITLE
Optimum Delay column of Flight Simulations tab is not populated

### ISSUE THREAD

**Issue by Roo59** [openrocket/openrocket#2353]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1.Design created with this version
2.on the Flight simulations tab, the Optimum Delay column is not populated.
3.

If possible, please send us the .ork file that caused the bug.

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- System information ----------
OpenRocket version: 23.09.beta.01
OpenRocket source: default
OpenRocket location: C:\Program Files\OpenRocket\.\OpenRocket.jar
User-defined thrust curves location: C:\Users\alexl\AppData\Roaming\OpenRocket\ThrustCurves
LAF: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
JOGL version: 2.5.0-rc-20230523
Current default locale: en_AU
System properties:
exe4j.consoleCodepage=cp0
exe4j.isInstall4j=true
exe4j.launchName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.moduleName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.semaphoreName=Local\c:_program_files_openrocket_openrocket.exe0
exe4j.tempDir=
exe4j.unextractedPosition=0
file.encoding=Cp1252
file.separator=\
install4j.appDir=C:\Program Files\OpenRocket\
install4j.exeDir=C:\Program Files\OpenRocket\
install4j.launcherId=59
install4j.swt=false
java.class.path=C:\Program Files\OpenRocket\.install4j\i4jruntime.jar;C:\Program Files\OpenRocket\.\OpenRocket.jar
java.class.version=61.0
java.home=c:\program files\openrocket\jre
java.io.tmpdir=C:\Users\alexl\AppData\Local\Temp\
java.library.path=c:\program files\openrocket\jre\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microchip\xc8\v2.41\bin;C:\Program Files\Microchip\xc16\v2.00\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Users\alexl\AppData\Local\Microsoft\WindowsApps;
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=17.0.7+7-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=17
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=17.0.7
java.version.date=2023-04-18
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=17
java.vm.vendor=BellSoft
java.vm.version=17.0.7+7-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln17771990699299607277
line.separator=\u000d\u000a
native.encoding=Cp1252
os.arch=amd64
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=c:\program files\openrocket\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\OpenRocket\OpenRocket.exe
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=AU
user.dir=C:\Program Files\OpenRocket
user.home=C:\Users\alexl
user.language=en
user.name=alexl
user.script=
user.timezone=Australia/Sydney
user.variant=
---------- Error log ----------
1 0.001 INFO (SwingStartup.java:68) Starting up OpenRocket version 23.09.beta.01
2 0.005 INFO (SwingStartup.java:77) Checking for graphics head
3 0.007 INFO (SwingStartup.java:88) Moving startup to EDT
4 0.124 INFO (SwingStartup.java:180) Initializing the splash screen
5 0.249 INFO (SwingStartup.java:184) Registering exception handler
6 0.253 INFO (SwingStartup.java:190) Loading databases
7 2.712 INFO (TranslatorProvider.java:49) Using default locale en_AU
8 2.733 INFO (TranslatorProvider.java:61) Set up translation for locale en_AU, debug.currentFile=messages.properties
9 2.736 INFO (ComponentPresetDatabaseLoader.java:91) Loading component presets from datafiles/components
10 2.736 INFO (MotorDatabaseLoader.java:90) Starting reading serialized motor database
16 2.816 INFO (SwingStartup.java:258) Starting update check
17 2.821 INFO (SwingStartup.java:203) Setting LAF
18 3.251 INFO (MotorDatabaseLoader.java:96) Ending reading serialized motor database, motorCount=1899
19 3.259 INFO (MotorDatabaseLoader.java:71) Starting reading user-defined motors
20 3.261 INFO (MotorDatabaseLoader.java:81) Ending reading user-defined motors, motorCount=1899
21 3.264 INFO (SwingStartup.java:226) Opening main application window
22 3.291 INFO (BasicFrame.java:1901) New action initiated
122 0.000 DEBUG (-) ===== 93 DEBUG lines removed =====
122 4.509 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file semroc-legacy.orc contained 874 presets
123 4.511 DEBUG (ComponentPresetDatabaseLoader.java:115) loading from file: semroc.orc
124 4.511 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file semroc.orc
129 4.722 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file semroc.orc contained 1676 presets
131 4.731 DEBUG (ComponentPresetDatabaseLoader.java:115) loading from file: top_flight.orc
132 4.731 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file top_flight.orc
133 4.738 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file top_flight.orc contained 47 presets
134 4.761 DEBUG (ComponentPresetDatabaseLoader.java:57) Time to load presets: 2020ms 5309 loaded from 31 files
135 4.789 DEBUG (RocketFigure3d.java:142) Initializing RocketFigure3D OpenGL Canvas
136 4.789 DEBUG (RocketFigure3d.java:144) Setting up GL capabilities...
138 5.328 DEBUG (GitHubAPIUtil.java:76) Update checker response code: 200
168 6.229 DEBUG (JarUtil.java:40) Found jar file using codeSource
169 6.230 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
177 6.387 DEBUG (BasicFrame.java:320) ... Setting Initial Selection: [Rocket, Sustainer]
178 6.387 DEBUG (BasicFrame.java:324) BasicFrame instantiation complete
179 6.415 DEBUG (SwingStartup.java:311) Welcome dialog ignored
180 6.415 INFO (SwingStartup.java:234) Checking update status
181 6.416 INFO (SwingStartup.java:96) Startup complete
182 6.478 DEBUG (GitHubAPIUtil.java:76) Update checker response code: 200
183 6.501 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: OpenRocket_technical_documentation-v13.05
184 6.501 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: Development_of_an_Open_Source_model_rocket_simulation-thesis-v20090520
185 6.502 INFO (UpdateInfoRetriever.java:148) Current build is newer
192 21.029 USER (BasicFrame.java:832) Open... selected
193 31.721 USER (BasicFrame.java:1186) Opening files [C:\Users\alexl\Documents\Rockets\Designs\My 60mm Auspost mailtube.ork]
194 31.721 INFO (BasicFrame.java:1189) Opening file: C:\Users\alexl\Documents\Rockets\Designs\My 60mm Auspost mailtube.ork
196 31.731 INFO (BasicFrame.java:1309) Starting OpenFileWorker
197 31.735 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@6e1cda45
198 31.747 INFO (OpenRocketLoader.java:44) Loading .ork file
199 31.799 DEBUG (Rocket.java:682) Freezing Rocket
200 31.799 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
201 31.799 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
202 31.799 DEBUG (Rocket.java:708) Thawing rocket, freezeList=[ComponentChangeEvent[mass], ComponentChangeEvent[mass,aero]]
203 31.816 DEBUG (DatabaseMotorFinder.java:47) type Single-use, manufacturer AeroTech, designation F44W, diameter NaN, length NaN, digest 276d2632f5c06dc8317a664271e190bb, warnings Messages[]
204 31.818 DEBUG (DatabaseMotorFinder.java:67) motor is F44W
205 31.821 DEBUG (DatabaseMotorFinder.java:47) type Reloadable, manufacturer Cesaroni Technology, designation 53F70-14A, diameter NaN, length NaN, digest ffcc1e50c2a5ca713aff40e7099f76f4, warnings Messages[]
206 31.825 DEBUG (DatabaseMotorFinder.java:47) type Reloadable, manufacturer Cesaroni Technology, designation 110G250-14A, diameter NaN, length NaN, digest 41eacc01b49952c890441af900f81b6b, warnings Messages[]
207 31.830 DEBUG (DatabaseMotorFinder.java:67) motor is 110G250-14A
208 31.859 DEBUG (Rocket.java:682) Freezing Rocket
209 31.859 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
210 31.859 DEBUG (Rocket.java:708) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero]]
211 31.952 INFO (OpenRocketLoader.java:96) Loading done
212 31.954 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
213 31.954 DEBUG (BasicFrame.java:1363) Opening new frame with the document
214 31.954 DEBUG (BasicFrame.java:185) Instantiating new BasicFrame
215 31.954 DEBUG (BasicFrame.java:196) Constructing the BasicFrame UI
231 32.112 DEBUG (RocketFigure3d.java:142) Initializing RocketFigure3D OpenGL Canvas
232 32.112 DEBUG (RocketFigure3d.java:144) Setting up GL capabilities...
237 0.000 VBOSE (-) ===== 79 VBOSE lines removed =====
237 32.114 VBOSE (RocketFigure3d.java:166) GL - Creating GLCanvas
238 32.114 VBOSE (RocketFigure3d.java:170) GL - Registering as GLEventListener on canvas
239 32.114 VBOSE (RocketFigure3d.java:173) GL - Adding canvas to this JPanel
240 32.114 VBOSE (RocketFigure3d.java:176) GL - Setting up mouse listeners
241 32.114 VBOSE (RocketFigure3d.java:179) GL - Rasterizing Carets
242 32.117 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@eb39bd8
243 32.117 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
244 32.117 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
245 32.118 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
246 32.118 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
247 32.118 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
248 32.119 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
249 32.119 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
250 32.120 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
251 32.120 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@70def779, current number of listeners is 11
252 32.130 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@7ee49a0b, current number of listeners is 12
253 32.132 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@35421568, current number of listeners is 13
254 32.132 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
255 32.133 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@49b4ddb
256 32.133 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@2fa326a0
257 32.133 VBOSE (DoubleModel.java:975) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@2fa326a0
258 32.133 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@4466e39d
259 32.180 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
260 32.181 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@41eb0405, current number of listeners is 14
261 32.181 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@313ef109, current number of listeners is 15
262 32.181 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
263 32.195 DEBUG (JarUtil.java:40) Found jar file using codeSource
264 32.195 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
265 32.207 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@6f6b85e, current number of listeners is 16
266 32.304 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
267 32.306 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0415490 user scale, 235.553 overall scale
268 32.307 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0415490 user scale, 235.553 overall scale
269 32.309 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0415490 user scale, 235.553 overall scale
270 32.309 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0415490 user scale, 235.553 overall scale
271 32.310 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0415490 user scale, 235.553 overall scale
272 32.310 DEBUG (BasicFrame.java:320) ... Setting Initial Selection: [60mm AusPost, Sustainer]
273 32.310 DEBUG (BasicFrame.java:324) BasicFrame instantiation complete
274 32.329 INFO (BasicFrame.java:1231) Closing window because it is replaceable
275 32.329 DEBUG (BasicFrame.java:1838) Disposing window
276 32.502 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
277 32.503 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
278 32.504 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
279 32.514 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
280 32.516 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
281 32.517 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
282 52.143 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
283 52.144 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
284 61.276 DEBUG (FileHelper.java:144) File name does not contain extension, adding 'obj'
285 61.285 VBOSE (DoubleModel.java:953) DoubleModel[OBJExportOptions:ScalingDouble] adding listener (total 1): javax.swing.JSpinner$ModelListener@2bc0a17d
286 61.286 VBOSE (DoubleModel.java:953) DoubleModel[OBJExportOptions:ScalingDouble] adding listener (total 2): net.sf.openrocket.file.wavefrontobj.OBJOptionChooser$10@3b9901ad
287 61.287 VBOSE (DoubleModel.java:953) DoubleModel[OBJExportOptions:ScalingDouble] adding listener (total 3): net.sf.openrocket.file.wavefrontobj.OBJOptionChooser$7@17386cd0
288 61.292 DEBUG (DoubleModel.java:809) Setting value 1000.0 for DoubleModel[OBJExportOptions:ScalingDouble]
289 103.210 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
290 103.213 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
291 103.304 WARN (DoubleModel.java:1006) DoubleModel[OBJExportOptions:ScalingDouble] being garbage-collected while having listeners [javax.swing.JSpinner$ModelListener@2bc0a17d, net.sf.openrocket.file.wavefrontobj.OBJOptionChooser$10@3b9901ad, net.sf.openrocket.file.wavefrontobj.OBJOptionChooser$7@17386cd0]
292 105.086 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0779579 user scale, 441.966 overall scale
293 143.594 DEBUG (GUIUtil.java:381) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1295,height=695]
294 143.595 DEBUG (GUIUtil.java:386) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
295 143.677 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0882380 user scale, 500.247 overall scale
296 143.678 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0882380 user scale, 500.247 overall scale
297 143.679 VBOSE (AbstractScaleFigure.java:193) ____ Updating RocketFigure to: 0.0882380 user scale, 500.247 overall scale
298 243.622 DEBUG (GUIUtil.java:381) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1295,height=695]
299 243.623 DEBUG (GUIUtil.java:386) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
300 248.944 USER (BasicFrame.java:796) About selected
301 251.885 DEBUG (GUIUtil.java:272) Clearing all models of window net.sf.openrocket.gui.dialogs.AboutDialog[dialog0,127,127,453x490,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=OpenRocket 23.09.beta.01,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,7,30,439x453,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
302 251.887 DEBUG (MemoryManagement.java:56) Adding object into collectable list: net.sf.openrocket.gui.dialogs.AboutDialog[dialog0,127,127,453x490,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=OpenRocket 23.09.beta.01,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,7,30,439x453,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
303 263.463 USER (BasicFrame.java:754) Bug report selected
304 263.465 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by SiboVG** [comment]
Hi, thanks for your report. Could you please share the .ork file that produces this error?

**Comment by Roo59** [comment]
Sorry,  I thought that I had attached it.

It is attached on this email

Regards,
Richard.

**Comment by Roo59** [comment]
Thanks, I'll check it out!
