### ISSUE TITLE
Switching to Matrix as community chat?

### ISSUE THREAD

**Issue by AgentSmith0** [openrocket/openrocket#2361]
What about switching to Matrix as community chat?

Why Matrix?
- Open Standard
- Decentralization
- Interoperability

https://matrix.org/
https://element.io/

It is also possible to create a bridge between the already existing Discord server and the Matrix room.

**Comment by JoePfeiffer** [comment]
Darn! I wish we'd known about this before our recent switch to discord. Moving to another platform ends up having problems with having our users follow us there, as well as setting up our channels and losing our previous conversations. It's not something I want to do without a really compelling reason (slack only holding conversations for a short set time was the compelling reason that moved us to discord).

We'll see what the other devs say, but my initial reaction is we should stay put.

**Comment by SiboVG** [comment]
Cool app, but I still prefer Discord. Discord is very widespread, whereas I had never even heard of Matrix before (and I assume a lot of our users haven't either). The goal of the Discord server was to close the gap between our user base. From the standpoint of a user, I wouldn't bother to install yet another chat app; I'd rather use something I already have and am familiar with.
