### ISSUE TITLE
[Bug] LOC STC-3.90 Stiffener maybe corrupt? No 3D view for Figure, Unfinished, Finished

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2371]
### Describe the bug

Creating a model of a new Mega Der Red Max I'm building. I've got a coupler with a stiffener inside for robustness where the top tube will be removable. Trying to switch to 3D Finished view, I get a black View window, no model. Initially got a white View window. Black started on quitting and restarting OR.

### To Reproduce

1. Open enclosed .ork (on Mac OS Catalina, Mac Book Pro 16in Intel 2019, Radeon graphics, on external monitor).
2. Try to switch View Type to "3D Finished".
3. Observe black View window.
4. Note Photo Studio 3D view works as expected.
5. Switch back to "Side View" (or other non-3D view).
6. Delete ~~one or both~~ stiffener ~~and coupler~~.
7. Try to switch View Type to "3D Finished" again.
8. Note Finished View appears.
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*
<img width="202" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/15a5f3ce-704a-432c-b49b-e5b0002049fc">

<img width="1440" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/83e53fe5-1bae-4e06-960b-b44ea4cff3d4">

#### .ork file:
*(drag-and-drop the file here as a .zip file)*
[Daves 38mm Mega Der Red Max_or22ß_231015.ork.zip](https://github.com/openrocket/openrocket/files/12911657/Daves.38mm.Mega.Der.Red.Max_or22ss_231015.ork.zip)

### OpenRocket version

23.09 beta (from Drive)

### What platform are you running on?

macOS

### Additional context

Running from .jar on command line

I've tried with offscreen rendering on and off, to no effect.

**Comment by jimmiedave** [comment]
OK, maybe the bug is with the 7.5in LOC Coupler Stiffener I pulled from the Parts Library

I used the LOC part STC-3.90, and shortened it up to 140mm as was my need.

I suffered the 3D problem as listed above.

I re-opened the .ork file, deleted the stiffener, and added it back using the same settings by hand, and tested: No more 3D problem.

Changing issue title.

**Comment by JoePfeiffer** [comment]
Not seeing the issue under Linux. I can open the .ork and  view it in all three 3D views in the design window, and in the photo studio.

**Comment by SiboVG** [comment]
Also no issues on MacBook Pro M1, macOS 14. Strange...

**Comment by jimmiedave** [comment]
Interesting. Same issue came back for me immediately on the file next day after a cold start.

Suggestion: I'll try and recreate the problem in a new file with the part from parts library, and if no issue, we call it "random cosmic ray" or something.

**Comment by jimmiedave** [comment]
Windows 7 VM, same Mac, upon switching to one of the 3D views (don't think this is a valid part of the issue, but for a full report):

<img width="610" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/6640809c-0d8a-4f79-afff-7df06677297b">

**Comment by jimmiedave** [comment]
Not seeing on Ubuntu Linux, different iron.

**Comment by jimmiedave** [comment]
Tried to recreate with the changed JAR in the Drive files. Cannot break it in the way the weird file does. Closing.
