### ISSUE TITLE
[Bug] Auto pop of parts library resets units (to prior value?)

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2373]
### Describe the bug

Noticed during testing that my units kept reverting from mm to cm. The parts library was set to "Always open...".

Figured out that the pop up of the parts library appeared to be causing the trouble.

### To Reproduce

Setup:

1. Set parts library to "Always open..." when adding a body tube
2. Close any design
3. Set Units:Rocket dimensions to "cm" and "OK"

Demo:

1. New design
2. Click sustainer
3. Add a body tube
4. Close Parts Library and Cancel adding a body tube
5. Set Units:Rocket dimensions to "mm" and OK
6. Quit OpenRocket
7. Start OpenRocket
8. Click sustainer
9. Add a body tube
10. **BUG:** Note rocket dimensions are again in "cm"

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

23.09 from Drive

### What platform are you running on?

macOS

### Additional context

Running from jar on command line

**Comment by SiboVG** [comment]
I'm not seeing this bug on my machine... Can someone else confirm? You're quite good at triggering custom bugs @jimmiedave 😉.

**Comment by jimmiedave** [comment]
Is it possible that I've got a permissions problem with preferences on my machine, or something similar?

**Comment by jimmiedave** [comment]
On my Catalina Intel Mac, in `~/Preferences/`, I see:

`./openrocket.favoritepresets.centering_ring.plist
./openrocket.favoritepresets.nose_cone.plist
./openrocket.favoritepresets.bulk_head.plist
./openrocket.favoritepresets.launch_lug.plist
./openrocket.favoritepresets.rail_button.plist
./openrocket.favoritepresets.body_tube.plist
./openrocket.favoritepresets.engine_block.plist
./openrocket.favoritepresets.tube_coupler.plist
./openrocket.favoritepresets.streamer.plist
./openrocket.objexportoptions.coordtransform.plist
./openrocket.favoritepresets.transition.plist
./openrocket.favoritepresets.parachute.plist`

Where are OR's actual prefs (to include Units) saved on MacOS, that I might check and see if I have a permissions issue? Doesn't seem like it'd be any of these.

**Comment by jimmiedave** [comment]
Not seeing reset of prefs in Ubuntu Linux

**Comment by jimmiedave** [comment]
OK, kind of mean trick to switch out the .jar file in Drive...

Testing with NOT the file I've been testing with since they were released to Drive, I no longer see units being reset.

**Comment by jimmiedave** [comment]
OK, can't see this, and it's apparent the JAR in Drive has changed. Closing.
