### ISSUE TITLE
[Bug] Nose Cone Shoulder changes diameter between save and re-open

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2378]
### Describe the bug

I've repeatedly re-set the shoulder of my nose cone to 100mm diameter.

Whenever I save the model, upon re-opening it, the shoulder has changed to a much smaller diameter. This time (first time I've looked at the exact number in the diameter field) it's 50mm in diameter.

Before Save:

<img width="465" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/25602030-3fce-43de-9b35-d96383618880">

After quit, restart OR, Load:

<img width="445" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/a06f3b92-762c-404a-ab47-b01641f52233">

fixed shoulder, saved again

After OR Close File, Open file (very careful to open exactly the file I've just saved this time):

<img width="445" alt="image" src="https://github.com/openrocket/openrocket/assets/35353530/c43ee308-999a-4a60-9bbf-1854d070d17e">

I expect the nose cone shoulder to stay at the diameter I've set it.

### To Reproduce

1. Open enclosed .ork file
2. Note nose cone shoulder is 50mm / 5cm wide
3. Adjust to correct 100mm / 10cm wide
4. Save file
5. Close file
6. Re-open just-saved file
7. **BUG:** Note nose cone has changed to 50mm / 5cm shoulder
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*
See above

#### .ork file:
*(drag-and-drop the file here as a .zip file)*
[Daves 38mm Mega Der Red Max_or22ß_231015.ork.zip](https://github.com/openrocket/openrocket/files/13054941/Daves.38mm.Mega.Der.Red.Max_or22ss_231015.ork.zip)

### OpenRocket version

23.09 beta from drive

### What platform are you running on?

macOS

### Additional context

Mac OS Catalina, run as .jar from command line.

Also note that rocket measurement units still reverting to mm, even though I've not accessed the Parts Library (see #2373)

**Comment by neilweinstock** [comment]
Very odd.  I can reproduce this with your file, but not on any file I've created on my own.

**Comment by jimmiedave** [comment]
I've wondered whether it's the Eggtimer that lives in the shoulder - maybe there's code that's trying to get the shoulder out of the way, but that doesn't seem like it makes any kind of sense. Maybe 'cuz it's an internal tube that's not a motor mount tube, the shoulder thinks it has something to do? Doesn't make any more sense than the first idea.
