### ISSUE TITLE
Adding a Run All Simulations button

### ISSUE THREAD

**Issue by kavred** [openrocket/openrocket#2384]
I have quite a few simulations that I have to run after every edit I make and this task seems to be very annoying to me since I have to do it all the time.

I would definitely appreciate a button that just runs all the simulations for me.

Don't really think there are many less time consuming alternatives for this.

**Comment by JoePfeiffer** [comment]
You should be able to click the first sim and shift-click the last one, and then click "Run simulations" to get them all run.

**Comment by kavred** [comment]
True, but I have more than 300 simulations. (Scrolling does take a second or two.) However if it's not possible, I won't mind.

**Comment by jimmiedave** [comment]
CTRL+A (Select All), Hit "Run Simulations" button.

CMD+A if on a Mac for (Select All)

**Comment by neilweinstock** [comment]
Yes, CTRL-A works.  Also, if you want to run all simulations after every edit then just enable that in simulation preferences.
![image](https://github.com/openrocket/openrocket/assets/243872/e5149f2a-f3d1-436e-b7f0-efa9cbe1f780)

**Comment by neilweinstock** [comment]
Request is adequately covered by existing program functionality.  Closing.
