### ISSUE TITLE
Text is too small

### ISSUE THREAD

**Issue by MitchMan1** [openrocket/openrocket#2391]
I downloaded the newest version of OpenRocket 22.02 a few days ago. For some reason, the text size is incredibly small.

Here is an attached photo (I hope it shows up.) The text size in the display/view area is the correct size, but all text is menus is extremely small. Additionally, if I open any more menus, such as those used to edit parts, the text is the same small size.
![Screenshot 2023-11-02 194700](https://github.com/openrocket/openrocket/assets/65968600/fbb9b007-eeb4-4792-86fa-86a43e54d04f)

I am using a Dell XPS, with a display resolution of 3456x2160 (which is recommended based on my 4k display), a scale of 250% (also recommended), and text size of 100%.

I had an older version of OpenRocket that worked well which didn't have any problems with text size.

**Comment by SiboVG** [comment]
OpenRocket has had issues with high-resolution settings and >100% scaling before. The next release of OpenRocket will allow you to change the UI font size.
