### ISSUE TITLE
[Bug] Mass and CG overrides have an unexpected interaction

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2394]
### Describe the bug

Turning CG override for all subcomponents on and off can affect rocket mass.

### To Reproduce

1. Open "simple model rocket" example and select "no motors". Note rocket mass is 48.2g and CG is 20.6cm.
2. Override mass and set to 50g. Note mass is now 98.2g if "override for subcomponents" is off. Leave it off.
3. Override CG and set to 20cm. Note mass is now 98.2 if "override (CG) for subcomponents" is off and 48.2 if on. It shouldn't change.
4. Note that if mass override is set on for subcomponents then mass remains 50g whether CG override is on or off.
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

unstable

### What platform are you running on?

Linux

### Additional context

This seems a lot like #2393 (Overrides tab is confusing for Stages) but is distinct enough to warrant its own issue, and is definitely a bug.

**Comment by JoePfeiffer** [comment]
Ah, it's worse than I thought. In the attached pathologically simple "rocket" (just a nose cone and body tube), adding a mass override to the stage moves the CG.
[nose-body.zip](https://github.com/openrocket/openrocket/files/13330343/nose-body.zip)

**Comment by SiboVG** [comment]
Are you already looking into this @JoePfeiffer? I've tried but don't have a lot of time on my hands to debug it thoroughly...

**Comment by JoePfeiffer** [comment]
Yes. I was swamped until yesterday afternoon; giving a serous look now.
