### ISSUE TITLE
23.09 crashes opening this ORK file

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2403]
This ORK file was created with 22.02.  23.09 gives an exception when opening it.
[BT-50 High School Confidential.zip](https://github.com/openrocket/openrocket/files/13396583/BT-50.High.School.Confidential.zip)

**Comment by JoePfeiffer** [comment]
Regression since the beta, looks like where I was working on moment of inertia stuff fixing another bug.
