### ISSUE TITLE
Strange errors trying to plot this design

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2404]
This CHAD-staged design yields some weird errors when plotting.
[Estes Big Bertha 3 Stage.zip](https://github.com/openrocket/openrocket/files/13396638/Estes.Big.Bertha.3.Stage.zip)

Here's what the design it looks like:
![image](https://github.com/openrocket/openrocket/assets/243872/0feb532a-247c-46b3-b415-98a77b7177a1)

The two booster stages just have a body tube, but nothing to create stability.  I'm guessing this is where the problem lies.

Steps to recreate:
1) Start with a fresh instance of 23.09.
2) Load the attached ORK file
3) Go to Flight Simulations, select the first sim, and click "Plot / Export".  The little progress dialog says "Running simulations", and then you get this:
![image](https://github.com/openrocket/openrocket/assets/243872/76a8047a-e360-4ac8-9b8a-73686428004a)

Although it says "simulation branch "Sustainer"", I guessed that it is after first stage burnout and it is gagging on the finless first stage which has just been ejected.  But this might not be right.
4) Click OK
5) The Plot dialog then comes up.  Click "Plot".  Here's what you get:
![image](https://github.com/openrocket/openrocket/assets/243872/682ea587-5289-4f0b-88ef-c1599eebcae1)

Note that this should normally show additional lines for the two booster stages after separation, but they're not there.  This supports my theory about the finless boosters.  But notice that the Exception actually occurs at the end of the plot, at apogee.  This... is puzzling to me.

Anyway: if the finless boosters are causing the problem, there should be a graceful way of handling them.  May need to make an assumption about stability (assume -1 caliber or something like that?) to enable the plot to finish gracefully.

22.02 does not report any errors.

**Comment by JoePfeiffer** [comment]
This one is a regression between 22.02 and the beta. No idea (at the moment) where this behavior would be coming from...

**Comment by SiboVG** [comment]
I think this issue is fixed in 24.12.beta.01. I'm not getting an exception and the plot appears logical:
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/df368a08-fadb-4ebb-86f8-db2c11431be8" />

@neilweinstock or @JoePfeiffer could you please verify?

**Comment by JoePfeiffer** [comment]
Yes, this was fixed as part of #2431 and should have been closed then.
