### ISSUE TITLE
[Bug] Nosecone Shape parameter is rounded to 1 decimal

### ISSUE THREAD

**Issue by Exsthain** [openrocket/openrocket#2409]
### Describe the bug

When trying to use a 3/4 parabolic nosecone, the shape parameters get approximated to 0.8

### To Reproduce

1. input 3/4 or .75 in the nosecone shape parameter box

### Screenshots / .ork file

![image](https://github.com/openrocket/openrocket/assets/123779767/5ef62722-e800-45de-b493-f337cdacc1d3)

### OpenRocket version

23.09 stable

### What platform are you running on?

Windows

**Comment by Exsthain** [comment]
Shouldn't this be considered a bug as it affects the geometry/simulation of the rocket and it worked just fine in the last stable version?

**Comment by SiboVG** [comment]
> Shouldn't this be considered a bug as it affects the geometry/simulation of the rocket and it worked just fine in the last stable version?

Well, whatever it is, I pushed a fix for it in #2411.

**Comment by Exsthain** [comment]
> > Shouldn't this be considered a bug as it affects the geometry/simulation of the rocket and it worked just fine in the last stable version?
> 
> Well, whatever it is, I pushed a fix for it in #2411.

Alright, thank you very much!
