### ISSUE TITLE
Identify where 'Discontinuity in rocket body diameter' is

### ISSUE THREAD

**Issue by wcravens** [openrocket/openrocket#241]
When we get the 'Discontinuity in rocket body diameter' warning it would be good if it identified the components that are on either side of the error.  If there was more than one then perhaps it could just suggest the one closest to the nose.

**Comment by teyrana** [comment]
FYI, this will need updating once boosters and pods are in the mix.  Recommend deferring until the current patch is in beta. --DMW

**Comment by hcraigmiller** [comment]
See Issue #999 for probable cause.
