### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by Mahmaaa** [openrocket/openrocket#2420]
Yakalanmamış istisna adı altında sürekli yazılımda hata olduğunu belirtiyor. ne demek olduğunu çözemiyorum.

**Comment by SiboVG** [comment]
Translation: "It keeps stating that there is a bug in the software under the name of uncaught exception. I can't figure out what it means."

First of all: formulate your text in English.

Second: Please give us more information: which OpenRocket version do you use, what was the exception you got, which steps did you take to recreate the bug, provide us with the .ork,...

**Comment by JoePfeiffer** [comment]
No further information from user
