### ISSUE TITLE
[Bug] Update Aerotech M4500ST thrustcurve from Thrustcurve.org data

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2423]
### Describe the bug

There is a single curve for AT M4500ST in the OR internal database (checked: no thrust curves in my local OR folder). It does not match the current single curve for AT M4500ST in the ThrustCurve.org database. In particular the OpenRocket curve's **Launch mass of 234oz** and the **Empty mass of 233oz** looks... incorrect at best. the ThrustCurve curve for the same motor lists a Total weight of 6,622g (234oz) and a propellant weight of 3,425g (121oz).

Burn time, Avg Thrust, Total impulse differ as well.

### To Reproduce

1. Ensure no local thrust curves in OpenRocket ThrustCurves folder to interfere with this repro
2. Set a motor configuration with an Aerotech M4500-P in OpenRocket (a 98mm motor)
3. Look up M4500 in the ThrustCurve.org online database
4. Compare figures
...

#### Screenshot(s):

From OpenRocket
<img width="240" alt="Screen Shot 2023-12-16 at 1 45 03 PM" src="https://github.com/openrocket/openrocket/assets/35353530/0cb4b6f6-64b2-4f81-8398-7b817530e874">

From https://www.thrustcurve.org/motors/AeroTech/M4500ST/
<img width="491" alt="Screen Shot 2023-12-16 at 1 45 52 PM" src="https://github.com/openrocket/openrocket/assets/35353530/408a5014-c132-46f2-9429-5ee1699380db">

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

23.09

### What platform are you running on?

macOS

### Additional context

Reported by Discord user @luiskis. I've just been checking it out.

**Comment by JoePfeiffer** [comment]
This is a problem with thrustcurve, not us. If you click through to the particular thrustcurve, you get this table (and the actual curve, of course):
![m4500](https://github.com/openrocket/openrocket/assets/3065196/80a8f817-0f5c-4f40-a95f-25a26c7e6c47)
The propellant weight on that file is 8g, which is the significant difference between them. All the other values agree to within rounding error except average thrust, which is still accurate to within .08%.
