### ISSUE TITLE
Provide saved configurations for plots

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2434]
Simulation plots are infinitely configurable.  I suspect it would be useful to allow users to save plot configurations so they can be recalled quickly.

Mostly likely we could add a few pre-configured plots as well.

I would make this global for the app, not per-design.

**Comment by SiboVG** [comment]
I guess this is a duplicate of #2162? 

Do you want to add more pre-configured plots than the existing ones?
<img width="792" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/e26d1162-f922-45c7-aee7-9c06e33d76fa">

**Comment by neilweinstock** [comment]
Holy crap I never noticed those preset configurations were there.  Yikes.

In any case yet, this is a duplicate of #2162, I'll close it now.
