### ISSUE TITLE
[Bug] exception in RockSim export

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#2438]
### Describe the bug

User "CP Fleck" <cfleck@mi.rr.com> reports a null pointer exception exporting to RockSim
I've confirmed the exception still occurs in current Unstable.

### To Reproduce

1. 
2. 
3. 
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*
[SLS Block I.V2.zip](https://github.com/openrocket/openrocket/files/13929534/SLS.Block.I.V2.zip)

### OpenRocket version

23.09

### What platform are you running on?

Windows

### Additional context

java.lang.NullPointerException: Cannot invoke "String.length()"
because "str" is null at
java.base/java.io.Writer.write(Writer.java:249) at
net.sf.openrocket.file.rocksim.export.RockSimSaver.save(RockSimSaver.java:67)
at
net.sf.openrocket.file.GeneralRocketSaver.saveInternal(GeneralRocketSaver.java:245)
at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:165)
at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:113)
at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:74)
at
net.sf.openrocket.gui.main.BasicFrame.saveRockSimFile(BasicFrame.java:1630)
at
net.sf.openrocket.gui.main.BasicFrame.saveAsRockSim(BasicFrame.java:1618)
at
net.sf.openrocket.gui.main.BasicFrame.exportRockSimAction(BasicFrame.java:1577)
at
net.sf.openrocket.gui.main.BasicFrame$7.actionPerformed(BasicFrame.java:439)
at
java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
at
java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
at
java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
at
java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
at
java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
at
java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
at
java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
at java.desktop/java.awt.Component.processEvent(Component.java:6391)
at java.desktop/java.awt.Container.processEvent(Container.java:2266)
at
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
at
java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
at
java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
at
java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) at
java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) at
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) at
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

	 ---------- Thread information ----------  

	 Thread[AWT-EventQueue-0,6,main]  

	 ---------- System information ----------  

	 OpenRocket version: 23.09  

	 OpenRocket source: default  

	 OpenRocket location: C:Program FilesOpenRocket.OpenRocket.jar  

	 User-defined thrust curves location:
C:UserscfleckAppDataRoamingOpenRocketThrustCurves  

	 LAF: com.sun.java.swing.plaf.windows.WindowsLookAndFeel  

	 JOGL version: 2.5.0  

	 Current default locale: en_US  

	 System properties:  

	 exe4j.consoleCodepage=cp0  

	 exe4j.isInstall4j=true  

	 exe4j.launchName=C:Program FilesOpenRocketOpenRocket.exe  

	 exe4j.moduleName=C:Program FilesOpenRocketOpenRocket.exe  

	 exe4j.semaphoreName=Localc:_program_files_openrocket_openrocket.exe0
 

	 exe4j.tempDir=  

	 exe4j.unextractedPosition=0  

	 file.encoding=Cp1252  

	 file.separator=  

	 install4j.appDir=C:Program FilesOpenRocket  

	 install4j.exeDir=C:Program FilesOpenRocket  

	 install4j.launcherId=59  

	 install4j.swt=false  

	 java.class.path=C:Program
FilesOpenRocket.install4ji4jruntime.jar;C:Program
FilesOpenRocket.OpenRocket.jar  

	 java.class.version=61.0  

	 java.home=c:program filesopenrocketjre  

	 java.io.tmpdir=C:UserscfleckAppDataLocalTemp  

	 java.library.path=c:program
filesopenrocketjrebin;C:ProgramDataOracleJavajavapath;C:Program Files
(x86)InteliCLS Client;C:Program FilesInteliCLS
Client;C:WINDOWSsystem32;C:WINDOWS;C:WINDOWSSystem32Wbem;C:Program
Files (x86)ATI TechnologiesATI.ACECore-Static;C:Program Files
(x86)AMDATI.ACECore-Static;C:Program FilesIntelIntel(R) Management
Engine ComponentsDAL;C:Program Files (x86)IntelIntel(R) Management
Engine ComponentsDAL;C:Program FilesIntelIntel(R) Management Engine
ComponentsIPT;C:Program Files (x86)IntelIntel(R) Management Engine
ComponentsIPT;C:Program Files (x86)QuickTimeQTSystem;C:Program
Filesnodejs;C:Program FilesCloud
Foundry;C:WINDOWSSystem32WindowsPowerShellv1.0;C:WINDOWSSystem32WindowsPowerShellv1.0;C:WINDOWSSystem32OpenSSH;C:Program
Filesdotnet;C:UserscfleckAppDataRoamingnpm;C:UserscfleckAppDataLocalatombin;%USERPROFILE%AppDataLocalMicrosoftWindowsApps;
 

	 java.runtime.name=OpenJDK Runtime Environment  

	 java.runtime.version=17.0.7+7-LTS  

	 java.specification.name=Java Platform API Specification  

	 java.specification.vendor=Oracle Corporation  

	 java.specification.version=17  

	 java.util.Arrays.useLegacyMergeSort=true  

	 java.vendor=BellSoft  

	 java.vendor.url=https://bell-sw.com/  

	 java.vendor.url.bug=https://bell-sw.com/support  

	 java.version=17.0.7  

	 java.version.date=2023-04-18  

	 java.vm.compressedOopsMode=32-bit  

	 java.vm.info=mixed mode  

	 java.vm.name=OpenJDK 64-Bit Server VM  

	 java.vm.specification.name=Java Virtual Machine Specification  

	 java.vm.specification.vendor=Oracle Corporation  

	 java.vm.specification.version=17  

	 java.vm.vendor=BellSoft  

	 java.vm.version=17.0.7+7-LTS  

	 jdk.debug=release  

	 jnlp.jogamp.tmp.cache.root=jln9955853474797328234  

	 line.separator=u000du000a  

	 native.encoding=Cp1252  

	 os.arch=amd64  

	 os.name=Windows 10  

	 os.version=10.0  

	 path.separator=;  

	 sun.arch.data.model=64  

	 sun.awt.enableExtraMouseButtons=true  

	
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
 

	 sun.boot.library.path=c:program filesopenrocketjrebin  

	 sun.cpu.endian=little  

	 sun.cpu.isalist=amd64  

	 sun.io.unicode.encoding=UnicodeLittle  

	 sun.java.command=C:Program FilesOpenRocketOpenRocket.exe  

	 sun.jnu.encoding=Cp1252  

	 sun.management.compiler=HotSpot 64-Bit Tiered Compilers  

	 sun.os.patch.level=  

	 user.country=US  

	 user.dir=C:Program FilesOpenRocket  

	 user.home=C:Userscfleck  

	 user.language=en  

	 user.name=cfleck  

	 user.script=  

	 user.timezone=America/New_York  

	 user.variant=  

	 ---------- Error log ----------  

	 145892 0.000 USER (-) ===== 108 USER lines removed =====  

	 145892 1187.976 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-217.0
converted=-0.217  

	 145901 1188.225 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-216.0
converted=-0.216  

	 145910 1188.468 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-215.0
converted=-0.215  

	 145919 1188.690 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-214.0
converted=-0.214  

	 145928 1188.940 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-213.0
converted=-0.213  

	 145937 1189.174 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-212.0
converted=-0.212  

	 145946 1189.500 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-211.0
converted=-0.211  

	 149744 1190.354 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-210.0
converted=-0.21  

	 153298 1193.058 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-211.0
converted=-0.211  

	 156136 1193.724 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-212.0
converted=-0.212  

	 156861 1195.228 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-213.0
converted=-0.213  

	 160418 1196.808 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-214.0
converted=-0.214  

	 163976 1199.041 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-213.0
converted=-0.213  

	 163985 1199.274 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-212.0
converted=-0.212  

	 163994 1199.510 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-211.0
converted=-0.211  

	 164003 1199.787 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-210.0
converted=-0.21  

	 167565 1201.724 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-209.0
converted=-0.209  

	 171353 1221.217 USER (DoubleModel.java:111) SpinnerModel setValue
called for DoubleModel[MassComponent:AxialOffset] newValue=-209.0
converted=-0.209  

	 175016 1235.171 USER (BasicFrame.java:393) Save selected  

	 175288 1282.649 USER (BooleanModel.java:299) Value of
BooleanModel[internal value] changed to false oldValue=true  

	 175303 1322.973 USER (BooleanModel.java:299) Value of
BooleanModel[internal value] changed to true oldValue=false  

	 175322 1337.523 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=314
scaledValue=0.314 converted=0.31  

	 175329 1337.810 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=465
scaledValue=0.465 converted=0.46  

	 175336 1338.005 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=570
scaledValue=0.57 converted=0.5700000000000001  

	 175343 1338.235 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=640
scaledValue=0.64 converted=0.64  

	 175350 1338.444 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=674
scaledValue=0.674 converted=0.67  

	 175357 1338.655 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=698
scaledValue=0.698 converted=0.7000000000000001  

	 175364 1338.948 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=709
scaledValue=0.709 converted=0.71  

	 175371 1339.155 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=733
scaledValue=0.733 converted=0.73  

	 175378 1339.369 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=767
scaledValue=0.767 converted=0.77  

	 175385 1339.587 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=791
scaledValue=0.791 converted=0.79  

	 175392 1339.806 USER (DoubleModel.java:364) SliderModel setValue
called for DoubleModel[AppearanceBuilder:Shine] newValue=779
scaledValue=0.779 converted=0.78  

	 175561 1410.916 USER (BasicFrame.java:393) Save selected  

	 188319 1873.781 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 803: ThrustCurveMotorSet[Estes B6, type=Single-use,
count=2]  

	 188320 1873.781 USER (ThrustCurveMotorSelectionPanel.java:684)
Selected table row -1, nothing selected  

	 188321 1873.781 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 803: ThrustCurveMotorSet[Estes B6, type=Single-use,
count=2]  

	 188322 1873.781 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 803: ThrustCurveMotorSet[Estes B6, type=Single-use,
count=2]  

	 188323 1873.781 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 803: ThrustCurveMotorSet[Estes B6, type=Single-use,
count=2]  

	 188324 1878.515 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 808: ThrustCurveMotorSet[Estes C6, type=Single-use,
count=2]  

	 188325 1878.664 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 808: ThrustCurveMotorSet[Estes C6, type=Single-use,
count=2]  

	 188326 1880.443 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 806: ThrustCurveMotorSet[Estes Industries, Inc. C5,
type=Single-use, count=1]  

	 188327 1880.564 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 806: ThrustCurveMotorSet[Estes Industries, Inc. C5,
type=Single-use, count=1]  

	 188328 1886.867 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 805: ThrustCurveMotorSet[Estes C5, type=Single-use,
count=2]  

	 188329 1886.964 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 805: ThrustCurveMotorSet[Estes C5, type=Single-use,
count=2]  

	 188330 1892.644 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 808: ThrustCurveMotorSet[Estes C6, type=Single-use,
count=2]  

	 188331 1892.763 USER (ThrustCurveMotorSelectionPanel.java:679)
Selected table row 808: ThrustCurveMotorSet[Estes C6, type=Single-use,
count=2]  

	 191324 0.000 INFO (-) ===== 1751 INFO lines removed =====  

	 191324 1897.512 INFO (BasicEventSimulationEngine.java:108)
>>Starting simulation of branch: Booster Set  

	 191336 1897.512 INFO (BasicEventSimulationEngine.java:108)
>>Starting simulation of branch: Core  

	 191340 1897.512 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: SRB/24aa94c3 / A8 - Armed @: 0.0  

	 191341 1897.512 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: Inner Tube/00704ecb / C6 - Armed @: 0.0  

	 191346 1897.512 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: SRB/24aa94c3 / A8 - Armed @0.0  

	 191350 1897.512 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: Inner Tube/00704ecb / C6 - Armed @0.0  

	 191648 1897.552 INFO (BasicEventSimulationEngine.java:511) ==>> @
0.534000; from Branch: Core ---- Branching: Booster Set ----  

	 192433 1897.612 INFO (BasicEventSimulationEngine.java:114) Starting
simulation of branch: Booster Set  

	 192771 1897.642 INFO (BasicEventSimulationEngine.java:114) Starting
simulation of branch: Core  

	 192908 1902.622 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: SRB/24aa94c3 / A8 - Armed @: 0.0  

	 192909 1902.622 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: Inner Tube/00704ecb / C6 - Armed @: 0.0  

	 192915 1902.622 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: SRB/24aa94c3 / A8 - Armed @0.0  

	 192919 1902.623 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: Inner Tube/00704ecb / C6 - Armed @0.0  

	 193213 1902.652 INFO (BasicEventSimulationEngine.java:511) ==>> @
0.534000; from Branch: Core ---- Branching: Booster Set ----  

	 195879 1902.821 INFO (BasicEventSimulationEngine.java:114) Starting
simulation of branch: Booster Set  

	 195892 1902.822 INFO (BasicEventSimulationEngine.java:108)
>>Starting simulation of branch: Core  

	 195896 1902.822 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: SRB/24aa94c3 / A8 - Armed @: 0.0  

	 195897 1902.822 INFO (BasicEventSimulationEngine.java:325) Queueing
Ignition Event for: Inner Tube/00704ecb / C6 - Armed @: 0.0  

	 195903 1902.822 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: SRB/24aa94c3 / A8 - Armed @0.0  

	 195907 1902.822 INFO (BasicEventSimulationEngine.java:400) Igniting
motor: Inner Tube/00704ecb / C6 - Armed @0.0  

	 196199 1902.853 INFO (BasicEventSimulationEngine.java:511) ==>> @
0.534000; from Branch: Core ---- Branching: Booster Set ----  

	 196975 1902.930 INFO (BasicEventSimulationEngine.java:114) Starting
simulation of branch: Booster Set  

	 197315 1902.952 INFO (BasicEventSimulationEngine.java:114) 
java.lang.NullPointerException: Cannot invoke "String.length()"
because "str" is null > at
java.base/java.io.Writer.write(Writer.java:249) > at
net.sf.openrocket.file.rocksim.export.RockSimSaver.save(RockSimSaver.java:67)
> at
net.sf.openrocket.file.GeneralRocketSaver.saveInternal(GeneralRocketSaver.java:245)
> at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:165)
> at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:113)
> at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:74)
> at
net.sf.openrocket.gui.main.BasicFrame.saveRockSimFile(BasicFrame.java:1630)
> at
net.sf.openrocket.gui.main.BasicFrame.saveAsRockSim(BasicFrame.java:1618)
> at
net.sf.openrocket.gui.main.BasicFrame.exportRockSimAction(BasicFrame.java:1577)
> at
net.sf.openrocket.gui.main.BasicFrame$7.actionPerformed(BasicFrame.java:439)
> at
java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> at
java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
> at
java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
> at
java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> at
java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
> at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
> at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
> at
java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
> at
java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
> at java.desktop/java.awt.Component.processEvent(Component.java:6391)
> at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> at
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
> at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> at
java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) >
at
java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> at
java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> at
java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> at
java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) >
at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
> at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) > at
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) > at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
> at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) > at
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) > at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743) >
at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

	 198443 3950.417 STDERR (SwingExceptionHandler.java:49)
java.lang.NullPointerException: Cannot invoke "String.length()"
because "str" is null  

	 198444 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.io.Writer.write(Writer.java:249)  

	 198445 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.file.rocksim.export.RockSimSaver.save(RockSimSaver.java:67)
 

	 198446 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.file.GeneralRocketSaver.saveInternal(GeneralRocketSaver.java:245)
 

	 198447 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:165)
 

	 198448 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:113)
 

	 198449 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.file.GeneralRocketSaver.save(GeneralRocketSaver.java:74)
 

	 198450 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.gui.main.BasicFrame.saveRockSimFile(BasicFrame.java:1630)
 

	 198451 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.gui.main.BasicFrame.saveAsRockSim(BasicFrame.java:1618)
 

	 198452 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.gui.main.BasicFrame.exportRockSimAction(BasicFrame.java:1577)
 

	 198453 3950.417 STDERR (SwingExceptionHandler.java:49) at
net.sf.openrocket.gui.main.BasicFrame$7.actionPerformed(BasicFrame.java:439)
 

	 198454 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
 

	 198455 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
 

	 198456 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
 

	 198457 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
 

	 198458 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
 

	 198459 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
 

	 198460 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
 

	 198461 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
 

	 198462 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
 

	 198463 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Component.processEvent(Component.java:6391)  

	 198464 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Container.processEvent(Container.java:2266)  

	 198465 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
 

	 198466 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
 

	 198467 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)  

	 198468 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
 

	 198469 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
 

	 198470 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
 

	 198471 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
 

	 198472 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)  

	 198473 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)  

	 198474 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
 

	 198475 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)  

	 198476 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)  

	 198477 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 

	 198478 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 

	 198479 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
 

	 198480 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)  

	 198481 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)  

	 198482 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 

	 198483 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 

	 198484 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)  

	 198485 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
 

	 198486 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
 

	 198487 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
 

	 198488 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
 

	 198489 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 

	 198490 3950.417 STDERR (SwingExceptionHandler.java:49) at
java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
 

	 198491 3950.417 INFO (SwingExceptionHandler.java:61) Exception
handler running on EDT, showing dialog  

	 198492 3950.417 INFO (SwingExceptionHandler.java:201) Showing
Exception dialog  

	 198493 3960.666 USER (SwingExceptionHandler.java:220) User requested
sending bug report  

	 198494 3960.674 DEBUG (JarUtil.java:40) Found jar file using
codeSource

**Comment by SiboVG** [comment]
Interesting, the bug is caused by the boosters in the design. Does RockSim even support boosters?

**Comment by SiboVG** [comment]
I guess a booster in RockSim is a pod that can be ejected during simulation?
![image](https://github.com/openrocket/openrocket/assets/11031519/ef861701-62c6-48eb-909a-86d05ef112e6)
