### ISSUE TITLE
Multi-Select Motor & Configurations table for Removal/Deletion

### ISSUE THREAD

**Issue by wcravens** [openrocket/openrocket#244]
Be able to multi-select rows from the 'Motors & Configuration' table to allow multiple simultaneous removal of configurations

**Comment by SpamWall** [comment]
I have completed this and will be sending the Pull Request by the weekend.  I also modified the tables on the Motor Configuration page to add some height to the cells since they were too small for the text.  I also widened the Motor Mount table a bit so the component names didn't get cut off.

**Comment by dkingsley** [comment]
It does not look the the PR from SpamWall ever happened?
