### ISSUE TITLE
[Feature Request] Air density Plot

### ISSUE THREAD

**Issue by Ash2772** [openrocket/openrocket#2462]
Could a plot for the air density at a particular point in time be added? I usually calculate it using pressure and temperature in Matlab / Python but might be nice to have it plotable in Openrocket.

The same goes for the stability percentage added last update.

**Comment by JoePfeiffer** [comment]
Those are both very reasonable requests.

**Comment by SiboVG** [comment]
> The same goes for the stability percentage added last update.

This is already addressed in #2221.
