### ISSUE TITLE
[Bug] Edit>Scale (downscale at least) appears to over-affect NC shoulder

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2463]
### Describe the bug

Scaled a rocket design to 75% (selected components only) and excluded only MMT and CRs. (Nose cone was selected)

Everything else scaled as expected, but the nose cone shoulder was scaled down in diameter past 75% of the original. Calculated shoulder diameter should probably be 57.15mm diameter, but shoulder is scaled to 44.4mm diameter. Shoulder length scales as expected.

Upscale does not appear to cause a problem.

### To Reproduce

1. Load a design
2. Select all the components
3. Deselect MMT and its children (might not be necessary)
4. Edit>Scale
5. Select "Only selected component(s)"
6. Click "Scale"
7. Observe nose cone shoulder.
...

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*
<img width="457" alt="Screenshot 2024-03-05 at 3 02 08 PM" src="https://github.com/openrocket/openrocket/assets/35353530/78917384-373f-4cd7-b2bb-49660ffe8d28">

<img width="470" alt="Screenshot 2024-03-05 at 3 02 40 PM" src="https://github.com/openrocket/openrocket/assets/35353530/8027ae29-790b-4b8b-8f74-d4f9d8416e1c">

#### .ork file:
*(drag-and-drop the file here as a .zip file)*
[ArgentFG54v01.ork.zip](https://github.com/openrocket/openrocket/files/14500761/ArgentFG54v01.ork.zip)

### OpenRocket version

23.09

### What platform are you running on?

macOS

### Additional context

Interestingly, "44.4 mm" is the rounded value of ( ShoulderLength * .75 * .75 )

**Comment by AhanuDewhirst** [comment]
Hello. I'd like to work on this bug.

**Comment by SiboVG** [comment]
> Hello. I'd like to work on this bug.

Great, thanks!
