### ISSUE TITLE
Parts library error: plastic nose cone shown as "filled"

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2480]
Estes part #72413 (9.75" x 2.5" plastic nose cone) shows as "filled". I don't know what the correct wall thickness should be but I'm pretty certain it should be hollow.
<img width="437" alt="image" src="https://github.com/openrocket/openrocket/assets/243872/fb067408-837a-4353-913c-06949a87a64f">

**Comment by SiboVG** [comment]
Should we move component database issue to [here](https://github.com/openrocket/openrocket-database/issues) from now on?

**Comment by JoePfeiffer** [comment]
> Should we move component database issue to [here](https://github.com/openrocket/openrocket-database/issues) from now on?

I'd say so. Note the problem appears to be that the wall thickness is .125 with no units, so it's being limited to the radius of the nose cone and marked as "filled" (even though it's not marked as filled in the database). 72653 has the same problem (but not the other components in that file).
