### ISSUE TITLE
[Feature Request] Hide components

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2485]
**Is your feature request related to a problem? Please describe.**
Sometimes, designs can get visually cluttered by components. I'd like a way to visually hide components. The hidden components would still account for simulations etc., but would just not show in the rocket design view.

**Describe the solution you'd like**
An option in the Edit menu and context menu to Hide the selected component. Once a component is hidden, the Edit menu item would change from "Hide selected component" to "Unhide selected component". There should also be an option to Unhide all components.

Components that are hidden should have greyed out text in the component tree and a hidden icon:
<img width="184" alt="image" src="https://github.com/openrocket/openrocket/assets/11031519/a6321556-4070-4ebb-ba94-149140451abe">

**Comment by AhanuDewhirst** [comment]
Hello. I'd like to work on this feature.

**Comment by SiboVG** [comment]
> Hello. I'd like to work on this feature.

Hello, that's great! Be sure to check out our developer's guide to get you started: [https://openrocket.readthedocs.io/en/latest/dev_guide/development_overview.html](https://openrocket.readthedocs.io/en/latest/dev_guide/development_overview.html).

**Comment by JoePfeiffer** [comment]
Welcome aboard! As @SiboVG says, check out the developer's guide. Also, please feel free to ask questions about anything that's unclear. We'll be more than happy to help you get started.

**Comment by AhanuDewhirst** [comment]
Thank you both for pointing me in the right direction. I've familiarised myself with the developer's guide :smile:

Addressing this feature, I've taken the following approach:

1. Component visibility can be toggled through the Edit and Context menus, or using the command `CTRL + ,`.
2. A hidden state is visually indicated by greyed out text and a hidden icon.
3. The visibility of multiple components can be toggled at once.
4. Toggling the visibility of a rocket or stage component affects the visibility of its child components.

Here's what this looks like using a simple model rocket:

![1](https://github.com/user-attachments/assets/22f1ed40-e52d-46c9-8dc5-d761a059c970)

![C](https://github.com/user-attachments/assets/f249ac74-54ed-4c68-9b27-2eb3f007ca17)

Let me know what you think!

**Comment by SiboVG** [comment]
Already looks pretty good @AhanuDewhirst, great job! The best thing you can do now is to create a Pull Request so we can check your code and test the functionality.

> 1. or using the command `CTRL + ,`

I wouldn't do this, since this is the shortcut to open the preference dialog.

**Comment by AhanuDewhirst** [comment]
Will do!

> I wouldn't do this, since this is the shortcut to open the preference dialog.

Noted. I'll remove the shortcut for now.
