### ISSUE TITLE
[Bug] Custom Expression for Damping Ratio outputs N/A

### ISSUE THREAD

**Issue by djangovanderplas** [openrocket/openrocket#2498]
### Describe the bug

When trying to plot the damping ratio (custom expression) over time, OpenRocket currently outputs an empty plot and N/A. Damping ratio is a rather crucial parameter for dynamic analysis of rockets and hence it needs to be fixed.

It is currently possible to work around by exporting all parameters of the damping ratio and then plotting it in an external spreadsheet program as equation. The expression for damping ratio is as follows:
`Cdm/(2*sqrt(Il*Ccm))`
This is according to the openrocket wiki useful custom expressions.

### To Reproduce

1. Create custom expressions for the following equations by copying the expression on the [OpenRocket wiki.](http://wiki.openrocket.info/List_of_Useful_Custom_Expressions#Corrective_moment_coefficient_.28Ccm.29). The expressions are Corrective Moment Coefficient (Ccm) and Damping Ratio (ζ)
2. In simulation config > simulation options > add extension > Post-step flight conditions > Dampening Moment Coefficient (Cdm)
3. Simulate & Plot
4. Create plot with Damping Ratio on y-axis and time on x-axis > plot
5. No output is visible
When exporting the values to csv it is portrayed as N/A.

When directly copying the custom expression for Ccm into the damping ratio equation it is possible to get some results, but it is hard to figure out which one would be correct or not. The following expression for damping ratio outputs N/A:
`( Cdm )/(2* sqrt(  Il * (Vt^2 * Ar * (Cn/α) * (Cp-Cg) * (P/(287.058*T)) / 2)))`

Whilst the following expression provides an output which is quite reasonable it seems:
`( Cdm )/(2* sqrt(  Il * (Vt^2 * Ar * (Cn/α)(Cp-Cg) * (P/(287.058*T)) / 2)))`

But it would be great if someone could validate this.

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

23.09

### What platform are you running on?

macOS

**Comment by JoePfeiffer** [comment]
At a first look, it appears using variables produced by simulation extensions in custom expressions is broken. I added the Cdm extension and created a custom expression that just made a copy of it, and got nothing from that custom expression in the plot. I then made a new custom expression that was just a copy of total velocity, and got a plot from that.
