### ISSUE TITLE
[Feature Request] Separation of parts in objs

### ISSUE THREAD

**Issue by Marcotrix** [openrocket/openrocket#2501]
I would really like if you could separate parts in wavefront objs produced by the program, for example i need to 3d print multiple parts but they keep heir shape as in they stay up like theyre still attached to the non existant tube  , maybe even an option to lay them all flat on the plate for easier 3d printing?
![](https://github.com/openrocket/openrocket/assets/99425422/ed52b933-05a2-4412-8be9-b301115525ea)

**Comment by SiboVG** [comment]
You can select "Export as separate files" in the OBJ export settings, see [our tutorial](https://openrocket.info/tutorials/export-obj-3d-printing.html#export-parameters).
