### ISSUE TITLE
[Bug] Parts Library: Rocketarium "BT-60" tube has either wrong measurements or wrong designation.

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#2526]
### Describe the bug

Way big tube to be a BT-60. See screenshot of Parts Library below to compare with adjacent lines

### To Reproduce

1. Open Parts Library
2. Search up BT-60
3. Look at Rocketarium 9-inch tube entry's measurements compared to adjacent BT-60 components.
4. Say "Dude...naw..."

#### Screenshot(s):
<img width="1173" alt="Screenshot 2024-08-07 at 2 32 47 PM" src="https://github.com/user-attachments/assets/f1b85bbb-2a0e-4ad5-97f2-9c216a55ab1d">

### OpenRocket version

23.09

### What platform are you running on?

macOS

### Additional context

Rocketarium's stated Imperial measurements calculate (manually, by me) to those of an actual BT-60. So the Parts Library's measurements are wack.

https://www.rocketarium.com/Build/Airframes/60-090

**Comment by SiboVG** [comment]
Moved this issue to the database repo: https://github.com/openrocket/openrocket-database/issues/2
