### ISSUE TITLE
Strange CP calculation inconsistency

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2541]
Look at the CP location on the following two nearly identical files (included in the attached zip file):
![image](https://github.com/user-attachments/assets/e70db938-b826-41c1-bff6-67083c80ae16)

![image](https://github.com/user-attachments/assets/0455d4c4-89ca-49c3-b4e9-f68f61d6852e)

Although the component analysis shows only very slight differences, the aggregate CP location on the rocket figure is wildly different.

But there's more weirdness:  In the second design, the fins appear to be rotate by a certain amount, even though they're set to rotation of 0.

Collectively, I have no idea what's going on here, but it seems like some sort of bug.

Original report: https://www.rocketryforum.com/threads/water-rocket-cp-calculation-with-open-rocket.187953/

[waterBottleRocketCalcsCp.zip](https://github.com/user-attachments/files/16691864/waterBottleRocketCalcsCp.zip)

**Comment by SiboVG** [comment]
I'm not seeing this in the latest unstable.
<img width="1617" alt="image" src="https://github.com/user-attachments/assets/01eb3581-e7a6-490e-814f-8bbd1acdfdf6">

**Comment by SiboVG** [comment]
> But there's more weirdness: In the second design, the fins appear to be rotate by a certain amount, even though they're set to rotation of 0.

This is normal. It's because you opened the component analysis, which has the wind direction set to 178° (because the "Worst" toggle button is enabled).

**Comment by neilweinstock** [comment]
> This is normal. It's because you opened the component analysis, which has the wind direction set to 178° (because the "Worst" toggle button is enabled).

Ha, I learned something today.

Was there a known change since last release that explains why this problem went away?

**Comment by SiboVG** [comment]
> Was there a known change since last release that explains why this problem went away?

I don't know, maybe @JoePfeiffer does.

**Comment by JoePfeiffer** [comment]
> > Was there a known change since last release that explains why this problem went away?
> 
> I don't know, maybe @JoePfeiffer does.

Not specifically... The more I look at the 23.09 results the screwier it gets; in particular, the CP as reported in the design window exactly matches the finset CP as reported in the component analysis for waterBottleRocketCalcsCpTail, but not for waterBottleRocketCalcsCpForward. The total CP as reported in the component analysis (in 23.09) matches the total CP as reported in the design window for current unstable. I can see a few relevant changes in BarrowmanCalculator relating to component assemblies, but nothing jumps out at me as being the one that must have fixed it.
