### ISSUE TITLE
[Bug] Launch lug pressure CD is extremely high for Mach values very close, but over 1

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2543]
### Describe the bug

When you enter an extremely small number, that is just over 1 (e.g. 1.0000000000000007), the pressure CD of launch lugs is extremely high.
<img width="891" alt="image" src="https://github.com/user-attachments/assets/46e00fea-a0e2-4833-8fa2-e7a40888ea43">

Note that this does not happen when you input '1', or a small number just below 1 (e.g. 0.9999999999999993).

### To Reproduce

1. Open 'A simple model rocket'
2. Open the Component Analysis Tool
3. Copy this value to your clipboard: 1.0000000000000007
4. Paste the value in the Mach Number spinner 
5. Extremely high pressure CD

### OpenRocket version

unstable

### What platform are you running on?

macOS

**Comment by JoePfeiffer** [comment]
I'm seeing this too.
Cut-and-pasting 1.0000000000000007 into Mach gives really high pressure CD
Change Mach value to .1; pressure CD is reasonable
Typing or cut-and-pasting 1.0 still gives a reasonable CD

it's important to not just go straight from 1.0000000000000007 to 0.9999999999999993; the values are close enough it doesn't get recalculated (which caused me a few minutes of confusion).

**Comment by SiboVG** [comment]
> it's important to not just go straight from 1.0000000000000007 to 0.9999999999999993; the values are close enough it doesn't get recalculated (which caused me a few minutes of confusion).

Me too! I didn't know that was the reason for it; I just ignored it :)

**Comment by JoePfeiffer** [comment]
> > it's important to not just go straight from 1.0000000000000007 to 0.9999999999999993; the values are close enough it doesn't get recalculated (which caused me a few minutes of confusion).
> 
> Me too! I didn't know that was the reason for it; I just ignored it :)

I was 99% sure we had two bugs before I finally realized what was going on!

**Comment by SiboVG** [comment]
The error is caused by the Prandtl-Glauert correction to the friction coefficient in `TubeCalc.java`:
```java
// If we're supersonic, apply a correction
if (conditions.getMach() > 1) {
    f = f / conditions.getBeta();
}
```

Beta is calculated as `sqrt(abs(1 - Mach^2))`, which becomes very small when Mach moves towards 1. As a consequence, the division of f by beta becomes very large.

@JoePfeiffer I'm heading into very unknown territory, but have you considered the Van Driest II method for calculating the pressureCD in `TubeCalc.java`?

**Comment by JoePfeiffer** [comment]
> @JoePfeiffer I'm heading into very unknown territory, but have you considered the Van Driest II method for calculating the pressureCD in `TubeCalc.java`?

Pretty unknown for me as well! I was starting to think maybe we could consider having choked flow take over from Darcy-Weissbach when the pressure drop gets too great, but hadn't really explored it yet. I'll look at VanDriest II as well, thanks.

**Comment by SiboVG** [comment]
In "Active Guidance and Dynamic Flight Mechanics for Model Rockets", David Ketchledge (1993), it is stated that the correction factor should be clamped to 0.6 between a Mach of 0.8 and 1.1. What do you think @JoePfeiffer? Also: why do we only apply the Prandtl correction at supersonic speeds, I thought it needs to be applied to both subsonic and supersonic?

<img width="696" alt="image" src="https://github.com/user-attachments/assets/e9594e3c-3930-4ce8-87ae-4f4d9bc66651">
