### ISSUE TITLE
[Bug] Unnecessary "Forward end of airframe is open" warnings in Booster stage of "Three-stage rocket"

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2553]
### Describe the bug

For some reason, the body tubes in the booster stages in the "Three-stage rocket" example design show 2 warnings that the forward end of the airframe is open. Interestingly enough, those warnings disappear when you disable the sustainer.

### To Reproduce

1. Open the "Three-stage rocket" example design
2. Go to the simulations tab
3. Rerun all sims
4. The sim warnings appear

### OpenRocket version

unstable

### What platform are you running on?

macOS

**Comment by JoePfeiffer** [comment]
Question here is under what conditions the warning should appear?

1. Booster has no recovery system (as in the 3 stage example). This will be either a black powder staged rocket with a tumble recovery booster, or a high altitude shot with a ballistic booster recovery. In either case the flyer doesn't care what happens to the booster and the warning shouldn't appear.
2. Booster has a recovery system, and uses motor eject to deploy. The user is likely to be using OR to try to set the motor delay, and should be warned the sim after separation will be inaccurate. But maybe the warning should be specific about calculated optimal delay is likely to be wrong?
3. Booster has a recovery system, and uses electronics to deploy. Results will be inaccurate, but how much is the user likely to care? I could go both ways on this one.

**Comment by SiboVG** [comment]
> Question here is under what conditions the warning should appear?
> 
> 1. Booster has no recovery system (as in the 3 stage example). This will be either a black powder staged rocket with a tumble recovery booster, or a high altitude shot with a ballistic booster recovery. In either case the flyer doesn't care what happens to the booster and the warning shouldn't appear.
> 2. Booster has a recovery system, and uses motor eject to deploy. The user is likely to be using OR to try to set the motor delay, and should be warned the sim after separation will be inaccurate. But maybe the warning should be specific about calculated optimal delay is likely to be wrong?
> 3. Booster has a recovery system, and uses electronics to deploy. Results will be inaccurate, but how much is the user likely to care? I could go both ways on this one.

I'm sorry, am I missing something? What does this have to do with the forward airframe being open?

**Comment by JoePfeiffer** [comment]
> I'm sorry, am I missing something? What does this have to do with the forward airframe being open?

The airframe is actually open in all these cases. The question is whether the user is likely to be expecting to simulate the booster flight post-separation, in which case they should be reminded that they aren't going to get an accurate result.

**Comment by JoePfeiffer** [comment]
Related -- there's no need to flag a "high angle of attach" warning on a booster stage that's starting to tumble (as is the case for both stages in this example).
