### ISSUE TITLE
[Feature Request] Backwards compatibility with java

### ISSUE THREAD

**Issue by Jark5455** [openrocket/openrocket#2568]
**Is your feature request related to a problem? Please describe.**
Why is it that I have to use a specific java installation for openrocket? Its really annoying configuring java to use openrocket on arch linux.

**Describe the solution you'd like**
Isn't java backwards compatible? Cant we just run same jar with a higher jvm version and get the same result?

**Describe alternatives you've considered**
Removing the jvm version check.

**Comment by JoePfeiffer** [comment]
We have had issues in the past in which a lack of backward compatibility in Java required users to run specific Java versions (notably 15.03 wouldn't run on anything more recent than Java 8).
