### ISSUE TITLE
Open Rocket Bug Report

### ISSUE THREAD

**Issue by 19BCK** [openrocket/openrocket#2572]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1.
2.
3.

If possible, please send us the .ork file that caused the bug.

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- Exception stack trace ----------
net.sf.openrocket.gui.main.SwingExceptionHandler$InternalException: An exception occurred during the simulation at net.sf.openrocket.gui.main.SwingExceptionHandler.handleErrorCondition(SwingExceptionHandler.java:120) at net.sf.openrocket.gui.simulation.SimulationRunDialog$InteractiveSimulationWorker.simulationInterrupted(SimulationRunDialog.java:454) at net.sf.openrocket.gui.simulation.SimulationWorker.done(SimulationWorker.java:109) at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848) at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858) at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311) at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243) at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) at java.desktop/java.awt.Dialog.show(Dialog.java:1080) at java.desktop/java.awt.Component.show(Component.java:1728) at java.desktop/java.awt.Component.setVisible(Component.java:1675) at java.desktop/java.awt.Window.setVisible(Window.java:1036) at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016) at net.sf.openrocket.gui.main.SimulationPanel.runSimulation(SimulationPanel.java:461) at net.sf.openrocket.gui.main.SimulationPanel$RunSimulationAction.actionPerformed(SimulationPanel.java:994) at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626) at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389) at java.desktop/java.awt.Component.processEvent(Component.java:6391) at java.desktop/java.awt.Container.processEvent(Container.java:2266) at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310) at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743) at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) Caused by: java.lang.IllegalArgumentException: Too high first altitude: 15240.0 at net.sf.openrocket.models.atmosphere.ExtendedISAModel.<init>(ExtendedISAModel.java:64) at net.sf.openrocket.simulation.SimulationOptions.getAtmosphericModel(SimulationOptions.java:326) at net.sf.openrocket.simulation.SimulationOptions.toSimulationConditions(SimulationOptions.java:547) at net.sf.openrocket.document.Simulation.simulate(Simulation.java:395) at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:55) at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:24) at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.lang.Thread.run(Thread.java:833)

---------- Thread information ----------
Thread[AWT-EventQueue-0,6,main]

---------- System information ----------
OpenRocket version: 23.09
OpenRocket source: default
OpenRocket location: C:\Program Files\OpenRocket\.\OpenRocket.jar
User-defined thrust curves location: C:\Users\bkane\AppData\Roaming\OpenRocket\ThrustCurves
LAF: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
JOGL version: 2.5.0
Current default locale: en_US
System properties:
exe4j.consoleCodepage=cp0
exe4j.isInstall4j=true
exe4j.launchName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.moduleName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.semaphoreName=Local\c:_program_files_openrocket_openrocket.exe0
exe4j.tempDir=
exe4j.unextractedPosition=0
file.encoding=Cp1252
file.separator=\
install4j.appDir=C:\Program Files\OpenRocket\
install4j.exeDir=C:\Program Files\OpenRocket\
install4j.launcherId=59
install4j.swt=false
java.class.path=C:\Program Files\OpenRocket\.install4j\i4jruntime.jar;C:\Program Files\OpenRocket\.\OpenRocket.jar
java.class.version=61.0
java.home=c:\program files\openrocket\jre
java.io.tmpdir=C:\Users\bkane\AppData\Local\Temp\
java.library.path=c:\program files\openrocket\jre\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Intuit\QBPOSSDKRuntime;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Users\bkane\AppData\Local\Microsoft\WindowsApps;
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=17.0.7+7-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=17
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=17.0.7
java.version.date=2023-04-18
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=17
java.vm.vendor=BellSoft
java.vm.version=17.0.7+7-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln13838800447304434729
line.separator=\u000d\u000a
native.encoding=Cp1252
os.arch=amd64
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=c:\program files\openrocket\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\OpenRocket\OpenRocket.exe
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=US
user.dir=C:\Program Files\OpenRocket
user.home=C:\Users\bkane
user.language=en
user.name=Barry
user.script=
user.timezone=America/Denver
user.variant=
---------- Error log ----------
1 0.000 INFO (SwingStartup.java:68) Starting up OpenRocket version 23.09
2 0.016 INFO (SwingStartup.java:77) Checking for graphics head
3 0.016 INFO (SwingStartup.java:88) Moving startup to EDT
4 0.078 INFO (SwingStartup.java:180) Initializing the splash screen
5 0.172 INFO (SwingStartup.java:184) Registering exception handler
6 0.187 INFO (SwingStartup.java:190) Loading databases
7 2.179 INFO (TranslatorProvider.java:49) Using default locale en_US
8 2.194 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 2.194 INFO (ComponentPresetDatabaseLoader.java:91) Loading component presets from datafiles/components
10 2.194 INFO (MotorDatabaseLoader.java:90) Starting reading serialized motor database
16 2.246 INFO (SwingStartup.java:258) Starting update check
17 2.261 INFO (SwingStartup.java:203) Setting LAF
18 2.559 INFO (MotorDatabaseLoader.java:96) Ending reading serialized motor database, motorCount=1900
19 2.561 INFO (MotorDatabaseLoader.java:71) Starting reading user-defined motors
20 2.561 INFO (MotorDatabaseLoader.java:81) Ending reading user-defined motors, motorCount=1900
33 2.894 INFO (SwingStartup.java:226) Opening main application window
37 2.909 INFO (BasicFrame.java:1901) New action initiated
128 3.793 INFO (UpdateInfoRetriever.java:145) Current build is latest version
172 0.000 DEBUG (-) ===== 107 DEBUG lines removed =====
172 5.980 DEBUG (JarUtil.java:40) Found jar file using codeSource
173 5.980 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
181 6.105 DEBUG (BasicFrame.java:320) ... Setting Initial Selection: [Rocket, Sustainer]
182 6.105 DEBUG (BasicFrame.java:324) BasicFrame instantiation complete
183 6.527 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
184 6.527 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
185 6.527 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
186 6.527 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
187 6.527 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
188 6.527 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
192 6.542 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
193 6.542 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
198 6.558 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
199 6.558 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
202 15.837 INFO (SwingStartup.java:234) Checking update status
203 15.837 INFO (SwingStartup.java:96) Startup complete
204 15.837 DEBUG (GUIUtil.java:276) Clearing all models of window net.sf.openrocket.gui.dialogs.WelcomeDialog[dialog0,128,128,814x637,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Welcome to OpenRocket,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,7,30,800x600,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
205 15.853 DEBUG (MemoryManagement.java:56) Adding object into collectable list: net.sf.openrocket.gui.dialogs.WelcomeDialog[dialog0,128,128,814x637,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Welcome to OpenRocket,defaultCloseOperation=DISPOSE_ON_CLOSE,rootPane=javax.swing.JRootPane[,7,30,800x600,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
207 21.243 INFO (BasicFrame.java:1309) Starting OpenFileWorker
208 21.258 INFO (SwingWorkerDialog.java:133) Running SwingWorker net.sf.openrocket.gui.util.OpenFileWorker@708644cd
209 21.258 INFO (OpenRocketLoader.java:44) Loading .ork file
210 21.274 DEBUG (Rocket.java:682) Freezing Rocket
211 21.274 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
212 21.274 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
213 21.274 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass] info freeze list
214 21.274 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
215 21.274 DEBUG (Rocket.java:708) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero], ComponentChangeEvent[mass], ComponentChangeEvent[mass], ComponentChangeEvent[mass,aero]]
216 21.289 DEBUG (Rocket.java:682) Freezing Rocket
217 21.289 DEBUG (Rocket.java:546) Rocket is in frozen state, adding event ComponentChangeEvent[mass,aero] info freeze list
218 21.289 DEBUG (Rocket.java:708) Thawing rocket, freezeList=[ComponentChangeEvent[mass,aero]]
219 21.305 DEBUG (DatabaseMotorFinder.java:47) type Reloadable, manufacturer Cesaroni Technology, designation 411I175-14A, diameter NaN, length NaN, digest e78aab5d54aceef5dceb56db8fd89f49, warnings Messages[]
220 21.321 DEBUG (DatabaseMotorFinder.java:67) motor is 411I175-14A
221 21.383 INFO (OpenRocketLoader.java:96) Loading done
222 21.477 INFO (SwingWorkerDialog.java:151) Worker completed before opening dialog
223 21.477 DEBUG (BasicFrame.java:1363) Opening new frame with the document
224 21.477 DEBUG (BasicFrame.java:185) Instantiating new BasicFrame
225 21.477 DEBUG (BasicFrame.java:196) Constructing the BasicFrame UI
241 21.586 DEBUG (RocketFigure3d.java:158) Initializing RocketFigure3D OpenGL Canvas
242 21.586 DEBUG (RocketFigure3d.java:160) Setting up GL capabilities...
243 0.000 VBOSE (-) ===== 78 VBOSE lines removed =====
243 21.586 VBOSE (RocketFigure3d.java:162) GL - Getting Default Profile
244 21.586 VBOSE (RocketFigure3d.java:165) GL - creating GLCapabilities
245 21.586 VBOSE (RocketFigure3d.java:169) GL - setSampleBuffers
246 21.586 VBOSE (RocketFigure3d.java:172) GL - setNumSamples
247 21.586 VBOSE (RocketFigure3d.java:182) GL - Creating GLCanvas
248 21.586 VBOSE (RocketFigure3d.java:186) GL - Registering as GLEventListener on canvas
249 21.586 VBOSE (RocketFigure3d.java:189) GL - Adding canvas to this JPanel
250 21.586 VBOSE (RocketFigure3d.java:192) GL - Setting up mouse listeners
251 21.586 VBOSE (RocketFigure3d.java:195) GL - Rasterizing Carets
252 21.586 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@66942982
253 21.586 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
254 21.586 VBOSE (DoubleModel.java:953) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
255 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
256 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
257 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
258 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
259 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
260 21.586 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
261 21.586 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@202f3fb3, current number of listeners is 11
262 21.602 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@516984e1, current number of listeners is 12
263 21.602 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@1a551d6d, current number of listeners is 13
264 21.602 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
265 21.602 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@fea7ea0
266 21.602 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@7a7616a6
267 21.602 VBOSE (DoubleModel.java:975) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@7a7616a6
268 21.602 VBOSE (DoubleModel.java:953) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@5b4d24c9
269 21.649 INFO (RocketPanel.java:978) using pre-existing simulation
270 21.664 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
271 21.664 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@249703ae, current number of listeners is 14
272 21.664 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@527cf8dd, current number of listeners is 15
273 21.664 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
274 21.664 DEBUG (JarUtil.java:40) Found jar file using codeSource
275 21.664 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
276 21.680 VBOSE (Rocket.java:487) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@4ea841aa, current number of listeners is 16
277 21.742 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 1.00000 user scale, 4724.41 overall scale
278 21.742 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.0907453 user scale, 428.718 overall scale
279 21.742 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.0907453 user scale, 428.718 overall scale
280 21.742 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.0907453 user scale, 428.718 overall scale
281 21.742 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.0907453 user scale, 428.718 overall scale
282 21.758 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.0907453 user scale, 428.718 overall scale
283 21.758 DEBUG (BasicFrame.java:320) ... Setting Initial Selection: [2024-10-09 K-R0C IO IV, Sustainer]
284 21.758 DEBUG (BasicFrame.java:324) BasicFrame instantiation complete
285 21.758 INFO (BasicFrame.java:1231) Closing window because it is replaceable
286 21.758 DEBUG (BasicFrame.java:1838) Disposing window
287 21.964 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
288 21.964 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
289 21.964 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
290 21.964 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
291 21.964 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
292 21.964 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
293 21.964 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
294 21.964 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
295 21.964 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
296 21.979 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
297 21.979 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
298 21.979 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
299 21.979 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
300 21.979 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
301 21.998 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
302 21.998 DEBUG (GUIUtil.java:385) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1550,height=838]
303 21.998 DEBUG (GUIUtil.java:390) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
304 22.107 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
305 22.107 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
306 24.544 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
307 24.544 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
308 31.061 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
309 32.560 VBOSE (AbstractScaleFigure.java:209) ____ Updating RocketFigure to: 0.170884 user scale, 807.327 overall scale
310 32.576 DEBUG (SimulationRunDialog.java:242) Progressbar value 0
311 32.576 DEBUG (SimulationRunDialog.java:247) No simulation status data available, setting empty labels
312 32.623 ERROR (SwingExceptionHandler.java:119) An exception occurred during the simulation
> java.lang.IllegalArgumentException: Too high first altitude: 15240.0 > at net.sf.openrocket.models.atmosphere.ExtendedISAModel.<init>(ExtendedISAModel.java:64) > at net.sf.openrocket.simulation.SimulationOptions.getAtmosphericModel(SimulationOptions.java:326) > at net.sf.openrocket.simulation.SimulationOptions.toSimulationConditions(SimulationOptions.java:547) > at net.sf.openrocket.document.Simulation.simulate(Simulation.java:395) > at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:55) > at net.sf.openrocket.gui.simulation.SimulationWorker.doInBackground(SimulationWorker.java:24) > at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) > at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) > at java.base/java.lang.Thread.run(Thread.java:833)
313 32.623 INFO (SwingExceptionHandler.java:142) Running in EDT, showing dialog
314 32.623 INFO (SwingExceptionHandler.java:201) Showing Exception dialog
315 43.293 USER (SwingExceptionHandler.java:220) User requested sending bug report
316 43.293 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by SiboVG** [comment]
Superseded by #2573.
