### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by owenchen2806** [openrocket/openrocket#2575]
every time i use the scroller something comes up saying i have bug and that i have to report it to the developers. It won't go away please sort it out thanks

**Comment by JoePfeiffer** [comment]
Thank you for your report. Our standard error popup includes a lot of information regarding the version of OR used, where in the program the bug happened, and so forth. Please add that information to your report. Also, I'm not quite sure what "Every time I use the scroller" means -- could you elaborate?

**Comment by JoePfeiffer** [comment]
No further information from user

**Comment by JoePfeiffer** [comment]
No further info
