### ISSUE TITLE
[Feature Request] Add "MRD" motors to database

### ISSUE THREAD

**Issue by app4soft** [openrocket/openrocket#2582]
**Is your feature request related to a problem? Please describe.**

"MRD" (orig. "МРД") is model rocket series produced and widely used in Ukraine and some of exUSSR countries.

OpenRocket database has no "MRD" motors in database yet.

**Describe the solution you'd like**

MRD motors are production is standartized with the `ТУ 84-795-79` Standard ("MRD" is abbreviation of ukr. _"Модельний ракетний двигун"_, lit. _"Model rocket motor"_).

- https://www.russiangost.com/p-204155-tu-84-795-79.aspx

- Dimensions drawing
  ![mrd-dim](https://github.com/user-attachments/assets/26eb8d34-2b93-43cf-bce3-bb0bfe790eb7)
- Specifications
  ![mrd-spec](https://github.com/user-attachments/assets/7c0df009-eb48-4928-8e26-718140db8bfa)
  <img alt="mrd-spec2" src="https://github.com/user-attachments/assets/c5c30ec5-2eb7-4d74-92de-862400547fb9" width="680"/>
- Thrust Curves
  ![mrd-eng](https://github.com/user-attachments/assets/58b902ff-bd51-40ca-bbf2-c54d940ad04a)
  <img alt="mrd-eng2" src="https://github.com/user-attachments/assets/53b92b2e-78f1-47a4-baf7-33e7228fc1f8" width="680"/>

**Describe alternatives you've considered**
None

**Additional context**

Photo of instruction docs included in MRD packages

![mrd-instruction](https://github.com/user-attachments/assets/9036c61b-e0bd-4885-8aa3-b52d75c5651a)

**Comment by JoePfeiffer** [comment]
We pull our motor database straight from thrustcurve.org. If you add the motors there, they will be in the next release (and will also be available to people who make use of that resource  but don't use OpenRocket).
