### ISSUE TITLE
[Feature request] upgrade to latest JDK

### ISSUE THREAD

**Issue by DarkTyger** [openrocket/openrocket#2597]
### Describe the bug

```
NoseConeTest.java:11: error: extraneous semicolon
import static org.junit.jupiter.api.Assertions.assertSame;;
```

### To Reproduce

1. git clone https://github.com/openrocket/openrocket
1. cd openrocket
1. gradle clean build

Expected
Builds.

Actual
Compile failure.

### OpenRocket version

main

### What platform are you running on?

Linux

### Additional context

Looks like a `;;` is messing with the  build.

**Comment by JoePfeiffer** [comment]
Changed it to a feature request, since we're still on 17.

**Comment by DarkTyger** [comment]
> Changed it to a feature request, since we're still on 17.

It's a typo, should be a quick fix. Delete the semicolon.
