### ISSUE TITLE
[Bug] Some flight data types are missing the final sample point

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#2608]
### Describe the bug

[See discussion in #2606](https://github.com/openrocket/openrocket/pull/2606#issuecomment-2525184808). For some flight data types, the final sample point is not included.

### To Reproduce

1. Open 'A simple model rocket'
2. Plot the first simulation
3. Zoom in to the very end of the simulation

![image](https://github.com/user-attachments/assets/472da067-207c-44b8-a7f2-fbc01bbc6811)

### OpenRocket version

unstable

### What platform are you running on?

macOS

### Additional context

This bug is **not** present in 23.09.

**Comment by SiboVG** [comment]
I suggest we also update the unit tests to check if the number of samples for all flight data types is equal.

**Comment by SiboVG** [comment]
I've looked at the data and the following data types produce a `NaN` for the final sample (after the simulation end event in the CSV export result):
- Vertical acceleration
- Total acceleration
- Lateral acceleration
- Mass
- Motor mass
- Longitudinal moment of inertia
- Rotational moment of inertia
- Gravitational acceleration
- CG location
- Thrust
- Thrust-to-weight ratio
- Drag force
- Drag coefficient
- Friction drag coefficient
- Pressure drag coefficient
- Base drag coefficient
- Axial drag coefficient
- Wind velocity
- Simulation time step
- Computation time

Note that all above values do have a valid number in 23.09.

**Comment by JoePfeiffer** [comment]
> I suggest we also update the unit tests to check if the number of samples for all flight data types is equal.

We can't in general do this -- the steppers don't all produce the same data. There's no CP data after we switch to the landing or tumble stepper, for instance.

We could check for off-by-one; if there's a data type that has one less point than the max it's likely a problem.
