### ISSUE TITLE
HTML escaping problem in simulation warnings panel

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2613]
I think this problem was previously found and fixed elsewhere (maybe the warnings in the Rocket Figure display?)

![image](https://github.com/user-attachments/assets/950d85c4-7f51-4e74-9402-e1bbb5a20fd4)

**Comment by SiboVG** [comment]
Can you share the .ork file for this? I'm not seeing this on the latest unstable, are you running the latest unstable? I also wonder why your warnings are different from mine. If I change the body tube diameter in A simple model rocket, the warning first shows the components and then the warning message, whereas it's the reverse for you.

<img width="904" alt="image" src="https://github.com/user-attachments/assets/8ff889cd-6e10-4f01-8fad-0f31f1bc9c35" />

**Comment by neilweinstock** [comment]
Huh, weird.

This is with the recent beta packaged installers Joe made, but I also see it with the current up-to-date builds I'm fiddling with.

Here's the ORK.  Pretty sure I created this with the official 23.09, but I can't be 100% sure (unless it's written into the XML file somewhere).
[boostershot.ork.zip](https://github.com/user-attachments/files/18141184/boostershot.ork.zip)

**Comment by SiboVG** [comment]
If you re-run the sims in the latest unstable version, the formatting is correct (warning texts get updated when you re-run the sims). Should we close this issue then?
<img width="904" alt="image" src="https://github.com/user-attachments/assets/9092bee7-2e01-445c-8b38-8b7aa4b3fe41" />

**Comment by neilweinstock** [comment]
Rerunning the simulations on the latest build fixes the problem.  Closing.
