### ISSUE TITLE
pink noise and wind

### ISSUE THREAD

**Issue by Depressed-kr** [openrocket/openrocket#2637]
I thought pink noise is an explanation of sound (or sth), but in this rep, calculation of wind code is included in the file name 'Pinknoisewindmodel', so i want to ask how pink noise is related to the wind.

**Comment by SiboVG** [comment]
Pink noise refers to a specific type of signal where the power spectral density decreases proportionally with frequency, typically `1/f`. This characteristic makes it relevant to natural phenomena, including wind modeling.

In the context of wind, pink noise simulates semi-realistic, frequency-dependent variations in wind speed or pressure. Wind behavior often exhibits a spectrum where lower-frequency components (large-scale changes) dominate over higher-frequency components (small-scale turbulence), similar to pink noise characteristics.
