### ISSUE TITLE
Preferred units not used by offset or angle for Pods and Boosters.

### ISSUE THREAD

**Issue by matt-kendall** [openrocket/openrocket#304]
My preferred units for distance and angle are set in preferences as mm and degrees:
![image](https://cloud.githubusercontent.com/assets/7656534/20031362/12071050-a36e-11e6-872c-698a800e179f.png)

However, in the configuration for pods or boosters, the 'offset value' and 'angle' fields are given in cm and radians respectively:
![image](https://cloud.githubusercontent.com/assets/7656534/20031366/3a3bc840-a36e-11e6-9893-59f555100836.png)
![image](https://cloud.githubusercontent.com/assets/7656534/20031367/3e2b0218-a36e-11e6-9c99-3fa871935e03.png)

**Comment by matt-kendall** [comment]
PR 306 opened to fix this

**Comment by teyrana** [comment]
PR #306 has been accepted and merged into openrocket/unstable. Recommend we close as this issue as resolved.

**Comment by matt-kendall** [comment]
Closed, I've checked out openrocket/unstable and verified the fix.
