### ISSUE TITLE
Tube fins icon has visible background

### ISSUE THREAD

**Issue by matt-kendall** [openrocket/openrocket#305]
Most icons in the 'add new component' panel have no visible background or border against the button, e.g. this body tube button:
![image](https://cloud.githubusercontent.com/assets/7656534/20032252/25a57d94-a37e-11e6-8d42-03447f10d6f1.png)

However a visible outline of the background is visible on the icon for tube fins in all 3 button states:
![image](https://cloud.githubusercontent.com/assets/7656534/20032254/31a9b754-a37e-11e6-886f-914407930b1a.png)
![image](https://cloud.githubusercontent.com/assets/7656534/20032256/38faf680-a37e-11e6-9606-d830061cd221.png)
![image](https://cloud.githubusercontent.com/assets/7656534/20032257/3c5b8c2c-a37e-11e6-940c-0735b46785a0.png)

**Comment by matt-kendall** [comment]
I've created PR 305 to fix this for now (I set the transparency in the image).

Is the process for icon creation documented anywhere? I see we have resources-src and resources folders and some icons are missing from src (boosters, pods, stages). I also notice that some icons differ between 'small' and 'large' versions (e.g. boosters). Do we have things like required resolutions documented anywhere? This may all change if issue 250 is completed I suppose: https://github.com/openrocket/openrocket/issues/250 

Also noticed that the icon for tube fins looks very similar to the icon for a launch lug:
![image](https://cloud.githubusercontent.com/assets/7656534/20034077/b50e924c-a3a9-11e6-937b-df3996d5e21e.png)![image](https://cloud.githubusercontent.com/assets/7656534/20034078/b9107aa4-a3a9-11e6-9e18-2c14ef120815.png)
Some possible solutions might be to make the tube fin look a little bigger in the icon or redesign it, perhaps with a front view that looks something like this (a front view like the pods icon):

![image](https://cloud.githubusercontent.com/assets/7656534/20034089/24280f64-a3aa-11e6-98d3-e40179ca4a0a.png)

**Comment by kruland2607** [comment]
The reason the tube fin icon looks like the launch lug icon is because I 
created the tube fin one from the launch lug.  I don't know anything 
about gimp/graphics and it was the best I could do. We don't have any 
requirements documented for resolutions and probably they need to be 
completely reworked since they are having difficulty keeping up with 
technology.

**Comment by teyrana** [comment]
This looks like it was fixed by commit 3642398b1a5ea9e59ce91f4b96b31c3f0f816976
Any objections to closing this this Issue as resolved?

**Comment by matt-kendall** [comment]
Yes, I'll close this - I've checked out the latest unstable and verified the fix
