### ISSUE TITLE
JDK regression: JavaScript not supported as scripting language

### ISSUE THREAD

**Issue by plaa** [openrocket/openrocket#308]
The Oracle JDK and OpenJDK comes built-in with support for JavaScript scripting.  When I created the scripting support in the simulation extensions, JavaScript was intended to be supported on all systems by default.  Now when I start OpenRocket on Linux Mint 18 running OpenJDK 1.8.0_111 no scripting languages are supported.  I believe this is caused by changing from OpenJDK 7 to 8 (at which point the Rhino engine was changed to the Nashorn engine as well).

For debugging I added the following code to both OpenRocket.java and SwingStartup.java:

		ScriptEngineManager mgr = new ScriptEngineManager();
		List<ScriptEngineFactory> factories = mgr.getEngineFactories();
		
		for (ScriptEngineFactory factory : factories) {
			System.out.println("ScriptEngineFactory Info");
			String engName = factory.getEngineName();
			String engVersion = factory.getEngineVersion();
			String langName = factory.getLanguageName();
			String langVersion = factory.getLanguageVersion();
			System.out.printf("\tScript Engine: %s (%s)%n", engName, engVersion);
			List<String> engNames = factory.getNames();
			for (String name : engNames) {
				System.out.printf("\tEngine Alias: %s%n", name);
			}
			System.out.printf("\tLanguage: %s (%s)%n", langName, langVersion);
		}

It's evident that initially when starting OpenRocket JavaScript is supported (in OpenRocket.java) but after the startup classpath changes (in SwingStartup.java) the support is no longer present.  I'm unsure why the classpath updates no longer keep the default nashorn.jar on the classpath or how to fix the issue.

As a workaround, copying `/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar` to `~/.openrocket/Plugins/` fixes the issue, as this forces `nashorn.jar` to be on the updated classpath.

**Comment by teyrana** [comment]
Ummm, we use Javascript? For what?

**Comment by plaa** [comment]
In simulation extensions.  Open the example design "Simulation extensions and scripting", then double-click the "Active roll control" simulation, select Simulation options and click the wrench on the "JavaScript script" extension.  Really powerful stuff when you need something custom or want to simulate flight computers.

**Comment by dkingsley** [comment]
Seems to work on Win10 with Oracle Java 8 update 131. I do not have a Linux machine with a Java Dev environment.

**Comment by plaa** [comment]
Problem occurs on Mac OS Sierra with Oracle Java 1.8.0_121.

**Comment by teyrana** [comment]
Reproduced on `unstable`, @a59aadbf
Mac OS 10.12.5, with Oracle Java 1.8.0_31  :    It runs, but the simulation is broken.
Linux: OpenJDK 1.8.0_131:   Fails to simulate with an exception.

So, it definitely exists, but is it our bug, or an OpenJDK "bug"?

**Comment by plaa** [comment]
It's an artifact from the jar-in-jar classpath mungling using Java 8.
Before the classpath update the scripting engine is available, after the
update it's not.  Not sure whether it could be classified as a JRE bug
(i.e. is the classpath mungling something that should work on all Java
implementations), but we need to deal with it anyway.

Don't know how to work around it though.

**Comment by thzero** [comment]
Yup.  This one is still around.  IDE it works fine.  Even in the unit test is working because it does not use the jar-in-jar classpath mungling.  However, the  jar-in-jar classpath mungling does not allow the scripting engine to be available; it seems to be using the application .jar file on the classpath instead of the individual .jar files that the IDE is using.
