### ISSUE TITLE
Transition shoulders ignored when positioning upper/lower body tubes?

### ISSUE THREAD

**Issue by woferry** [openrocket/openrocket#310]
I worked up a model for a Madcow Double Shot that I just received (attached).  While my model has a 2.125" aft shoulder on the ISC, the lower airframe is placed at the end of the transition rather than the end of the shoulder (so it crashes with the shoulder for the full 2.125").  Similarly, if I set a non-zero length on the fore shoulder it does not change the position of the sustainer relative to the ISC, it just crashes at the top also (I just did this one as a test, this transition doesn't have a fore shoulder).

If the shoulder length isn't supposed to be the way to control the positioning of the adjacent airframes, how **_is_** one supposed to specify this?

[Double Shot.ork.zip](https://github.com/openrocket/openrocket/files/659332/Double.Shot.ork.zip)

**Comment by plaa** [comment]
Shoulders are the part that goes inside the adjacent body tube.  A component with both conical and straight sections has to be modeled as a separate transition and body tube.
