### ISSUE TITLE
ChangeEvents should only apply to the currently selected Configuration

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#314]
[optimization][fix] 
This would both prevent extra changes to FlightConfigurations which should not be changing, as well as a preventing unnecessary object updates.   But I'd like to get some maintainers' opinions before I implement it.

**Comment by SiboVG** [comment]
Will close this issue, as it's not entirely clear what the intended refactoring is + at one point, we will have to do a general optimization overhaul, which should also fix this issue
