### ISSUE TITLE
Upgrade to guice-4.1 and guice-multibindings-4.1

### ISSUE THREAD

**Issue by tibbe** [openrocket/openrocket#342]
guice-3.0 is quite old at this point and will stop working with JDK 9, which we need to eventually switch to if we want to support HiDPI screens (which are more and more common among new laptops, for example). I took a quick stab at just bumping the jars to the new version but this quickly led to mysterious guice runtime errors.

If someone who knows guice/java better than me could take a look at it that would be great.

**Comment by itshanney** [comment]
Closing as guice dependency is upgraded to the latest as part of updating to Java 9+.
