### ISSUE TITLE
LogBack instructions unclear

### ISSUE THREAD

**Issue by tibbe** [openrocket/openrocket#344]
I tried to follow the instructions at

http://wiki.openrocket.info/Developer's_Guide#LogBack

to enable logging to stdout without any luck. In particular adding

```
-Dlogback.configurationFile=config/logback-stdout-level-error.xml 
```

to the "Program arguments" in the run configuration setup for SwingStartup doesn't seem to work. The above setting seems off, because I think eclipse runs the project using swing/, not core/, as the working directory and the config file is in the latter. Trivially changing the path to an absolute path had no effect.

**Comment by tibbe** [comment]
I finally got something to the console by putting this in the *VM arguments*:

```
-Dlogback.configurationFile=/usr/local/google/home/tibell/src/openrocket/core/config/logback-stdout-level-error.xml
-Dopenrocket.log.stdout=debug
-Dopenrocket.debug
```

**Comment by dkingsley** [comment]
Is this an issue with the code or documentation for debugging?

**Comment by tibbe** [comment]
I would lean towards documentation.

**Comment by neilweinstock** [comment]
Fixed by @SiboVG, closing.
