### ISSUE TITLE
Motor thrust not multiplied with number booster pods

### ISSUE THREAD

**Issue by ChrisMickelson** [openrocket/openrocket#351]
I have noticed something off with the sims for rockets with motors in booster pods. For example, if a rocket has 4 booster pods, each with a motor, then the thrust should be about 4x a single motor, however it's only being simmed as a single motor. Exported simulation data verifies thrust levels equivalent to a single motor even when there are 2 or more booster pods.

**Comment by teyrana** [comment]
Fix submitted in PR: #353

**Comment by wcravens** [comment]
Dan confirmed that this is fixed in Unstable
