### ISSUE TITLE
3D Views not visible in OSX

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#373]
Applies to versions: 14.11, 15.03, 17.xx
Platform:  OSX  10.12.6
JDK:  oracle; ver 1.8.0_151
Video Cards:
1. Intel HD Graphics 3000
2. AMD Radeon HD 6770M

When switching to the view-select pulldown, and select any of the 3d views:  results in a gray, disabled view panel.

HOWEVER, the photo studio is available and seems to function

**Comment by wcravens** [comment]
3D view works for me with 15.03 and Sierra 10.12.6

**Comment by teyrana** [comment]
Reproduction report:
Platform:  10.13 High Sierra on an early 2015 retina 13” MacBook Pro. 
JDK:  oracle: 1.8.0_144

**Comment by teyrana** [comment]
Reproduction Report:
----
Views Work:
Platform XUbuntu 17.04, 
JDK: OpenJDK 1.8.0_131

**Comment by teyrana** [comment]
closing as not reproducible.   (issue exists on my computer, but is likely to be something system-specific)
