### ISSUE TITLE
Centering ring position in RC1

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#374]
The last two centering rings in the attached model (they appear in the design tree after "Motor Mount" and before "Custom Fin set") are displayed in their correct position in RC0, but are moved quite a ways aft in RC1.  This is true in all views. I don't know if this is solely a display issue or if it also affects simulations.

Note -- it appears github will not permit me to upload a .ork file.  So, I've renamed it as a .txt so it can be uploaded.
[loc_ezi65-mod.txt](https://github.com/openrocket/openrocket/files/1416678/loc_ezi65-mod.txt)

**Comment by teyrana** [comment]
Resolved in:
https://github.com/teyrana/openrocket/commit/33558108b126ac5726e02522b0a930e655ccce25
Will bundle with rc2.
