### ISSUE TITLE
Cannot create new motor configurations in RC1

### ISSUE THREAD

**Issue by zmimlitz** [openrocket/openrocket#377]
In RC1 the button to create new motor configurations is initially disabled while the others are enabled despite having no selected configurations.  The [No Motors] config is also unlisted.  It looks like this:
![image](https://user-images.githubusercontent.com/10762452/32129282-a56bf56c-bb42-11e7-9ea9-626d2975cfc5.png)

In 15.03, I can go through the same intitial steps can the screen looks like this:
![image](https://user-images.githubusercontent.com/10762452/32129298-c3b71588-bb42-11e7-822d-1de45b4f7916.png)

If I open an existing config in RC1 all the buttons are fine it's just starting from new that I see this.

**Comment by teyrana** [comment]
Reproduction Report:
----
1. 'File' > 'New'
2. Add Body Tube
Issue #377a : cannot toggle motor mounts from the configuration tab
3. From 'Rocket Design' tab, edit 'Body tube' > 'Motor' Tab > check 'This component is a motor mount'
4. from 'Motors & Configuration' Tab:
Issue #377b: the 'New Configuration' button should be enabled
