### ISSUE TITLE
Mis-sized component search bar

### ISSUE THREAD

**Issue by GhotiLabs** [openrocket/openrocket#378]
In the preset components menu the search bar has zero width for me. I'm running the current stable release on Windows 7, not sure what Java.

I've heard of this problem from others too. It's been around through several releases.

The bar will widen if you widen the window, but it starts tiny.
![tinybar](https://user-images.githubusercontent.com/33179745/32135214-50cc8486-bbc9-11e7-824d-01800ea9e333.JPG)

**Comment by teyrana** [comment]
Confirmed to be present in rc1.

**Comment by teyrana** [comment]
@GhotiLabs @wcravens recommend to close; fix has been merged into 'unstable'
