### ISSUE TITLE
Cannot click-select components in 3d views

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#385]
On this build I cannot click on components in the 3D view to select them.  This has never worked on the Mac (at least not since I've been using it), but it has always worked on Windows.  Now clicking on the 3D view in Windows has no effect.

**Comment by neilweinstock** [comment]
I'm going to amend this one.  Working on Alpha5, click selection is simply scrambled and/or randomized.  See attached:
[Iris-T_home.zip](https://github.com/openrocket/openrocket/files/2078093/Iris-T_home.zip)

With the 3D view oriented with the nose on the left:

1. Clicking on the main BT generally selects the main BT
2. Clicking on different parts of the nose will select an assortment of other parts of the rocket.  Try it to see. 
3. Clicking on the rear portion of the rocket never selects anything.
3. Changing the orientation of the model in the 3D view can alter the behavior just a little.

**Comment by neilweinstock** [comment]
Confirming that this problem is still present in latest builds.

**Comment by teyrana** [comment]
From looking at RocketRenderer.java:68 ...

This is a more general issue, and applies to all 3d views on all platforms.  Basically, selecting instanced / booster / pods in 3d views probably doesn't work; it looks like it needs to be re-written.]

**Comment by teyrana** [comment]
Addressed in #703
