### ISSUE TITLE
Build 18.01-rc4: CP calculation is bonkers

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#387]
CP calculation is badly broken.  I'm not yet sure what triggered it.  See attached design; OR is showing me CP = -181 inches, which I'm pretty sure is not correct. :)

[plasma_dart2_scoop_newOR.zip](https://github.com/openrocket/openrocket/files/1644761/plasma_dart2_scoop_newOR.zip)

**Comment by teyrana** [comment]
@neilweinstock I took a look at your rocket, and there are two backward facing transitions.  I'm not familiar with this particular model; are both of those supposed to be there?   

I ask because Openrocket, correctly calculates the CP on this rocket, *according to the Barrowman Equations*.

**Comment by neilweinstock** [comment]
Interesting.  I’ll do some more experimentation and see what I can figure out, if anything.

**Comment by neilweinstock** [comment]
I'm seeing this again and I can show some examples.  First, here's a simple test with pods:
![image](https://user-images.githubusercontent.com/243872/44424428-12be4f80-a557-11e8-9dc2-162e7be8683d.png)
This shows the CP way up front, despite the fact that it should clearly be towards the back, and in the text display in the upper right it says "N/A".  Note that in side view, no CP is shown, which perhaps corresponds more closely to "N/A", but I'm not sure why it should be N/A in the first place.

If I add a nose cone, CP moves way to the front.
![image](https://user-images.githubusercontent.com/243872/44424550-6af55180-a557-11e8-8a86-c75cb6089895.png)

In other cases, I'm seeing the CP being rendered off-axis _only in the 3D view_, and only when pods are involved, and when conditions are correct (I haven't figured out exactly what those conditions are).  Here's an example:
![image](https://user-images.githubusercontent.com/243872/44425005-bbb97a00-a558-11e8-8487-0938ca8711a6.png)
Note how the CP is shown axially centered on one of the pods.

Here's the ORK file used for the above screenshots.  If you delete the fins on the pods you can get the CP to jump all the way into the nose cone.

[cp_position.zip](https://github.com/openrocket/openrocket/files/2307796/cp_position.zip)

**Comment by neilweinstock** [comment]
Here's another example of a problem using the latest alpha that Daniel sent me:
![image](https://user-images.githubusercontent.com/243872/45381774-4deef400-b5d4-11e8-8132-6d6f60404d58.png)

I put this file together for another issue, but again the CP is miscalculated to be at the front of the rocket instead of closer to the back.  It also is shown in the 3D view seemingly off axis in the wrong direction.  In side view this rocket shows CP as "N/A" for some reason.

[fin_decal_problem.zip](https://github.com/openrocket/openrocket/files/2372346/fin_decal_problem.zip)

**Comment by wcravens** [comment]
Does it look like these would all be accurate if they were reversed, either
along the length of the rocket or 180 degrees around the CG?  I have to
wonder if there is a negative number multiplication error somewhere.

Wes

**Comment by neilweinstock** [comment]
I tend to doubt it but really I’m just guessing.  There seem to be two separate problems here:

  1.  CP calculation: In this example, CP calculation is apparently failing, given that its position is reported as N/A.  I’m not sure how flipping any signs would make it better, but who knows what might be going on inside the algorithm.  In any case I don’t see why a design like this wouldn’t have a valid CP.  And note that this particular design doesn’t have any pods.
  2.  CP rendering in 3D view: Usually when pods are present in the design, CP is shown off-axis.  In the example I just posted, it’s possible that the CP shown in the 3D view is in fact complete nonsense and we should just ignore it, because if the program things CP position is N/A then who knows what numbers it’s actually using to calculate coordinates of the CP in 3-space.  Other designs (such as shown in previous comment) which have valid CP *and* incorrect display in 3D view are probably more appropriate for diagnosing this problem.  For this design I think the fact that it’s showing a CP at all is the problem.


  *   Neil

**Comment by neilweinstock** [comment]
Here's the same file opened in 15.03:
![image](https://user-images.githubusercontent.com/243872/45384023-d2447580-b5da-11e8-8231-68f787f325fd.png)

Interestingly, the CP once again is calculated as N/A, and yet is displayed in the 3D view.  Although this time it is shown closer to what I would expect to be "correct" in the 3D view.  But I don't know for sure.  So I don't know if my example file actually shows a new calculation problem, maybe just the 3D view display problem.

Also: the file I attached above might have 3 fins rather than 1, due to a previous but that has since been fixed.  Setting number of fins to 1 creates the CP problem.  When #fins=3, the CP is calculated correctly (I think) but once again shown off-axis in the 3D view.

**Comment by neilweinstock** [comment]
Sorry, seemed to have hit "close" by accident.

**Comment by neilweinstock** [comment]
Here's a design that creates a similar bug in rendering the CG in 3D finished mode.
![cg-bug](https://user-images.githubusercontent.com/243872/45935248-877e1280-bf77-11e8-947f-821b2dbddaa1.png)

[cg_render_bug.ork.zip](https://github.com/openrocket/openrocket/files/2409427/cg_render_bug.ork.zip)

**Comment by teyrana** [comment]
That last design: it's neutrally stable: there is no Center of Pressure for us to calculate.  I'm not sure what the expected output is, but I can't think of a better representation.

**Comment by teyrana** [comment]
If we're talking about the example above, with the three detached pods, the 3D CoP seems to be displayed incorrectly in 3D (it's clamped to the x-axis in 2D).  I haven't calculated if the x value makes sense for that design, though.  That's probably the problem.

**Comment by neilweinstock** [comment]
Both the CG and CP are sometimes shown off-axis, as shown above.

As for the design having no actual CP: if that's the case, then as far as I'm concerned nothing should be shown in the drawing.  The red dot indicates a CP.

**Comment by teyrana** [comment]
On Sun, Sep 30, 2018, 8:27 PM Neil Weinstock <notifications@github.com>
wrote:

> Both the CG and CP are sometimes shown off-axis, as shown above.
>
> As for the design having no actual CP: if that's the case, then as far as
> I'm concerned nothing should be shown in the drawing. The red dot indicates
> a CP.
>

Oh, I agree!  Ypure farther ahead than me- I was trying to ascertain if
there was an underlying calculation issue, or "only" a graphical /display
issue.

**Comment by neilweinstock** [comment]
Fair enough! Good luck with your search.

**Comment by ChrisMickelson** [comment]
Looking into this. So far it seems the 3D renderer is being told that CG and CP have a Y value, when any balanced design should be 0.
For example, here is some debug output I inserted into the renderer(RocketFigure3d.java:346) at the point where it's drawing the cg & cp carets:
CP: x=0.38327915090816433, y=0.008364311125459592, z=0.0
I can manually reset the Y value to 0 just prior to this point and it will *look* fine, but doesn't fix where the calculation is happening.
The offset CP seems to follow the first instanced fin attached to the main body tube.
The CG also seems to be pushed ~1% off-axis by pods, which is strange.

This issue is just as present with a simple 3FNC design.
![image](https://user-images.githubusercontent.com/19841931/47987309-cfc73f00-e0a4-11e8-988e-d732618b6838.png)

**Comment by teyrana** [comment]
Oh, I think I know whats going on.  (this is probably related to that last
fins PR).

What's the call site where its asking for the CP?

**Comment by ChrisMickelson** [comment]
I started looking in where the cg & cp in the 3d view gets drawn
...\swing\src\net\sf\openrocket\gui\figure3d\RocketFigure3d.java in the method drawCarets()
around line 344 is where it's taking the cp and projecting them as 2d points before drawing the red dot. 
Working backward, RocketFigure3d.java get's it's local cp value set from RocketPanel:607, which comes from line 586/588, which comes from BarrowmanCalculator:61 which bounces around to line 205. 

That's as far as I can get for now.

That screenshot was just one of the built in examples.

**Comment by neilweinstock** [comment]
Still not fixed in Alpha 10.  On the same design I referenced previously, the CP has gotten closer to the center axis, but still not quite there.

![image](https://user-images.githubusercontent.com/243872/49832606-263f3180-fd65-11e8-9529-33f57a0dbaa7.png)

I'm having a little more trouble getting this condition to show up on other designs, so it has clearly gotten better.

**Comment by neilweinstock** [comment]
Here's a version where I stripped everything out that doesn't affect the CP offset.
[alcubierre_cp.ork.zip](https://github.com/openrocket/openrocket/files/2707695/alcubierre_cp.ork.zip)

**Comment by neilweinstock** [comment]
Alpha 11 report: 
CP seems properly on-axis in most of my tests, but still not this one:
![image](https://user-images.githubusercontent.com/243872/52288087-7be52400-2939-11e9-981c-37974bb6251b.png)

I notice that in this one, the N/A CP is not shown in side view, but *is* shown in nonsense position in 3D view (this may or may not be a change from previous builds; just putting it here because I noticed it and we've discussed this design before).

Side view, no CP:
![image](https://user-images.githubusercontent.com/243872/52288342-029a0100-293a-11e9-8976-375827222675.png)

3D view, nonsense CP:
![image](https://user-images.githubusercontent.com/243872/52288379-15143a80-293a-11e9-9bc7-ad87c264dde9.png)

**Comment by neilweinstock** [comment]
OK, on the *real* alpha 11, Alcubierre CP is shown properly on-axis in the 3D view.

I'm still seeing an off-axis CG problem, though, should I open a separate issue or address it here?  It's the cg_render_bug.ork file from several messages up:
![image](https://user-images.githubusercontent.com/243872/52387239-6d8d2a00-2a57-11e9-9305-7e6f38ec43ee.png)

**Comment by neilweinstock** [comment]
I believe the CP problem has been fixed (haven't seen crazy off-axis CP in quite a while), but the off-axis CG problem is still there, so I'm going to close this and file another just for that problem.
