### ISSUE TITLE
Unable to run new install of OpenRocket

### ISSUE THREAD

**Issue by ndolnack** [openrocket/openrocket#388]
First time install of Open Rocket (OpenRocket-15.03.jar) on IOS El Capitan 10.11.6 with Java 9.0.1+11 
I double click the .jar file to run it and the open rocket loading preview displays and shortly after I get an error stating "Open Rocket encountered an uncaught exception. This typically signifies a bug in the software.       _Runtime Exception:Error starting OpenRocket_ "

Was going to paste the bug report below but it wont allow me to copy it, I also attempted to send a bug report to the developer in the bug report section and get another error stating 
"[BugReportDialog.bugreport.dlg.failedmsg1]       OIException: Server responded with code 404, expecting 202"

Any help appreciated

**Comment by teyrana** [comment]
Hi, this is a known issue.  We're working on a fix.

See #346 #347 for more detail

**Comment by neilweinstock** [comment]
@ndolnack 
Please try this: http://www.rocketryforum.com/showthread.php?143540-OpenRocket-packaged-installers-for-Windows-and-Mac-to-solve-all-your-Java-problems

**Comment by teyrana** [comment]
Openrocket 15.03 and Java 9 js a known incompatibility.  We're working on a
fix, and hope to have it in the next release.

**Comment by muhamed-genco** [comment]
I have the same problem... How can we do ??

**Comment by neilweinstock** [comment]
Did anyone try the link I gave above?

**Comment by itshanney** [comment]
This should all be resolved now with latest builds after upgrading to Java 9. For 15.03 release, Java 8 is still required and will not work with Java 9+. Closing for now and please re-open if there's a fresh occurrence.

**Comment by BrandonGThomson** [comment]
I am having the same problem. I have Ubuntu 18.04 with Java 11.0.6.  
Are there any known issues with Java 11 and openRocket?

**Comment by JoePfeiffer** [comment]
> I am having the same problem. I have Ubuntu 18.04 with Java 11.0.6.
> Are there any known issues with Java 11 and openRocket?

As stated above, "For 15.03 release, Java 8 is still required and will not work with Java 9+." That includes 11.  You should be able to run the appimage at https://www.dropbox.com/s/25we2cz0ukc4bor/OpenRocket.AppImage?dl=0

**Comment by BrandonGThomson** [comment]
@JoePfeiffer 
Thanks for the link to the software. Worked like a charm!
