### ISSUE TITLE
New feature request: associate OpenRocket with .ork file extension

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#403]
It would be very helpful to have the ability to double-click an ORK file to open it in OpenRocket.  This *probably* would have to go hand-in-hand with packaging the jar file (#372).  

Slightly different implementations are needed for Windows and Mac; not sure about Linux.  Oracle docs here: https://docs.oracle.com/javase/tutorial/deployment/selfContainedApps/fileassociation.html

**Comment by itshanney** [comment]
@neilweinstock closing this item and it will be covered as part of #372.
