### ISSUE TITLE
Update Travis to use Java8 JVM

### ISSUE THREAD

**Issue by SpamWall** [openrocket/openrocket#413]
Travis is using a Java7 JVM.  (See attached screenshot).  It needs updated to run tests using a Java8 JVM.
![travis build log showing jvm7](https://user-images.githubusercontent.com/4249207/40852492-333c16fe-6590-11e8-9e87-c7ab9b715261.jpg)

**Comment by teyrana** [comment]
Here you go:
https://github.com/openrocket/openrocket/pull/421

**Comment by teyrana** [comment]
@wcravens 
Nominate to close as resolved.
See PR #421.
