### ISSUE TITLE
Suggestion: show pod locations in side and back views

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#418]
It would be nice to see the pod locations in the side and back views.  I'm not sure how they should be shown, but it is always useful to get a bit of visual feedback what you're doing.

My thinking is that they are not needed in the 3D views.

**Comment by teyrana** [comment]
Please note: the pod's front/middle/back position is calculated based on
the pod's contents.

**Comment by neilweinstock** [comment]
At any given time, though, there's a single point that represents the location of each pod, is there not?

________________________________

**Comment by teyrana** [comment]
So, the positioning works like Fins on a bodyTube, (except more
complicated)

When positioning via 'TOP'  you supply the distance from the top (front) of
nthe body tube to the top of the fins.  And when using bottom, the distance
is from Bottom-to-Bottom.   So the point changes based on the positioning
method.

In addition:  the "front" of a pod or stage is specified by it's contents.
 So if you add a component to a 'TOP'-positioned stage, the bottom of  the
stage move.... if you add a component to a 'Bottom'-positioned pod, the top
will update/move.  (internally, the position is calculated as the
forward-most point of the assembly)

Does that answer your question?




Daniel Williams
equipoise@gmail.com
858-220-8134 (Mobile)
github.com/teyrana
<https://github.com/teyrana>LinkedIn
<https://www.linkedin.com/in/williamsdm>

**Comment by neilweinstock** [comment]
I confess I didn’t really have a question.

My desire is to *see* the root position of the pod indicated on the side and/or rear views.  I know it can be in different places based on different settings. It would be helpful to see where it is.  It would then be doubly useful to be able to double click on it.

I had no expectation to get this feature in this release, so it’s probably not worth too much thought process right now.  Just wanted to register it for future consideration.


  *   Neil

**Comment by neilweinstock** [comment]
This was fixed in 22.02 beta5.
