### ISSUE TITLE
FinSetConfig - Intelligent Resizing

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#424]
When the FinSetConfig window is enlarged, the layout does not respond in an intelligent way. 

Expected:
The typical desire would be for the actual editor area to be enlarged.

Actual:
Lots of expansion of other areas, and only a little enlargement of the editor itself.

**Comment by neilweinstock** [comment]
Looks much better now.

**Comment by neilweinstock** [comment]
Looks good in Alpha 8.
