### ISSUE TITLE
Alpha 8: cannot delete points in freeform fin shape editor

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#439]
I can add points, but I can't seem to delete them with control-click.

**Comment by teyrana** [comment]
Fix implemented.  Btw, was this even in 15.04?  Beacuse it didnt look like it...

**Comment by neilweinstock** [comment]
Yup, worked fine in previous release.

**Comment by teyrana** [comment]
Ah, ok.  I found the original code.  The old code is now fixed, instead of adding new stuff.

**Comment by neilweinstock** [comment]
This seems to be officially fixed.  at this point.  Closing it.
