### ISSUE TITLE
OpenRocket Installation on Fedora 27

### ISSUE THREAD

**Issue by rishiCS** [openrocket/openrocket#448]
It would be great if someone elaborates how to install openrocket on Fedora distro, how to deal with 'no protocol specified' error with Fedora

**Comment by kernelsmith** [comment]
yeah, this is kind of a dupe of #347. For some reason the max compatible version of 8 is not mentioned anywhere obvious so we all keep opening issues like this. Install a jdk (open-jdk or oracle java), but specify version 8

**Comment by itshanney** [comment]
Issue is due to trying to run OpenRocket on a version of Java 9+.
