### ISSUE TITLE
Freeform fin editor: can't move the first root point (0,0)

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#454]
In latest alphas that I've tried, it is impossible to move the first root point at 0,0.  This is a new breakage; in the previous release it is possible to drag the 0,0 point, which stays at 0,0 but causes all the other points to move accordingly.

**Comment by teyrana** [comment]
Sonuva.

I specifically fixed that. :(   What broke?

**Comment by neilweinstock** [comment]
Once the build is fixed I'd be happy to do some more testing if you'll shoot me a jar file.

**Comment by teyrana** [comment]
@neilweinstock Nominate to close.

**Comment by neilweinstock** [comment]
In alpha 9 this problem persists.

**Comment by neilweinstock** [comment]
Looks generally fixed in Alpha 11.  Only remaining weirdness is that if you try to drag the root point to the left of the parent object, at that moment it'll create a new point and leave the root point at the left edge.

Without having really thought about it too much, I think it's probably OK to leave it this way for now.

**Comment by neilweinstock** [comment]
Actually the remaining behavior described above might be related to #471.  Perhaps should leave this open for review until that one is closed.

**Comment by teyrana** [comment]
hrm?  That was exactly the behavior this was supposed to fix.

Okay, I'll have to take another look at this, then.

**Comment by neilweinstock** [comment]
Looks fixed in the *real* alpha 11.  Closing.
