### ISSUE TITLE
Mac OS Mojave: 3D view is crazily magnified first time it is selected

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#469]
Any click restores it to normal, and then it will stay normal while working with that file.  Example:
![image](https://user-images.githubusercontent.com/243872/47958879-3cf6a980-dfab-11e8-828e-fc65fd8ec9cd.png)

This may be relevant:
![image](https://user-images.githubusercontent.com/243872/47958887-58fa4b00-dfab-11e8-9303-fa7152c5ae07.png)

**Comment by teyrana** [comment]
Well that's odd.  We also haven't changed much in the 3d code.  Can you reproduce this in 15.04?

**Comment by neilweinstock** [comment]
Yes, it does happen in 15.03.  That is a new problem, almost certainly connected to the fact that I just recently upgraded to Mojave.

So this is a Mojave issue, somehow.

**Comment by teyrana** [comment]
Yea, I've had technical issues with graphics on my Mac for a while, now.
And then the card just totally died... So I sympathize.

**Comment by itshanney** [comment]
@neilweinstock is this still an issue, or can it be closed?

**Comment by neilweinstock** [comment]
Now that you mention it, I don't see the problem in the latest builds (at least, not in the packaged build you sent me).  I guess we can close it!
________________________________

**Comment by teyrana** [comment]
Awesome :) 

Glad to hear it's resolved :)
