### ISSUE TITLE
Alpha 9: Fins not allowed to extend beyond front or rear of parent component

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#471]
I just noticed that that latest build (maybe this was true in previous builds as well, not sure) will not let fins extend past the front or back of the parent component.

This is going to break a *lot* of old files that used phantom tubes to add fins to transitions and such.  And it gets used for other things as well.

Please restore this function.  Here is a useless example from the previous release version, just to illustrate.  New version will not allow this:
![image](https://user-images.githubusercontent.com/243872/47959008-f60ab300-dfae-11e8-933b-1cf86c654a1e.png)

**Comment by neilweinstock** [comment]
Well, the behavior is that the child object (of any kind) is not bounded by the extents of the parent.  In previous versions of OR where pods were not supported, all kinds of tricks are used to fake it.  Often they involved putting "phantom body tubes" (length and wall thickness of zero) at the rear of the rocket, and then putting fins or tube fins or whatever on them, somewhere further forward on the rocket.  In the new version, this practice may be less useful because now there are real pods, but there's no reason to break the old files.

So anyway, the rule is simple: do not add a constraint to the offset of a child object on a parent object.  Let it stick out the back, off the front, whatever.

I'll have to look through my own files to see which might have used this technique, but as stated above the desired behavior is very straightforward.

**Comment by neilweinstock** [comment]
This is still not working correctly in Alpha 10.

The root edges of freeform fins are not allowed to extend beyond the limits of the parent object, while editing the "offset" parameter in the "general" tab.

Trapezoidal and elliptical fins do not seem to be similarly restricted.  However, the fin root is not drawn if the fin hangs over the rear edge, and the side view is not centered properly to show the whole rocket if the fin is moved in front of the forward edge:
![image](https://user-images.githubusercontent.com/243872/49903293-b4361d80-fe34-11e8-9c91-531053d00a78.png)

I also experienced some exceptions but I'm trying to figure out how to reproduce them.

**Comment by teyrana** [comment]
To extend Freeform fins beyond the end of it's mounting parent, just drag any of the component points past the end--the shape will gladly extend beyond it's mount.  It is true that the interface does not perform in exactly the same way as other fin types, but an interested user may still generate the shape in question.

> Trapezoidal and elliptical fins do not seem to be similarly restricted. 
That is true.  Those fins are defined in much different ways, and are also restricted to much simpler situations.

The display lines in the main window are separate issues.

**Comment by neilweinstock** [comment]
That is weird and unintuitive, and also breaks compatibility with the previous release.  Following screenshot shows design created in 15.03 (left), and the result after reading it into Alpha 10:
![image](https://user-images.githubusercontent.com/243872/49904507-64f1ec00-fe38-11e8-949e-bfa0cf1b4b76.png)

**Comment by neilweinstock** [comment]
No change in Alpha 11.

**Comment by neilweinstock** [comment]
Fixed in the real alpha 11.  Closing.
