### ISSUE TITLE
Zoom problems in fin set shape editor

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#472]
Showing the component the fin attached to is a nice addition (and necessary for transitions and nose cones), but it has brought a couple of related problems regarding zooming.  I'm reporting this as one issue, if you'd prefer to split it into two that's fine.

This issue is *related* in some way to issue #471.

Basically, the editor seems really fixated on the front of the parent component as a Very Important Thing, when in fact it is not particularly relevant to editing a fin shape.  The editor should focus on the extents of the fin outline itself when doing zoom and positioning calculations.

Here are two examples:

1) As far as the fin editor is concerned, the front of the parent component is the farthest point forward it is interested in.  If a point on a fin extends significantly in front of the front of the parent component, there's no way to ever zoom or scroll the editor to get it in view, e.g.:
![image](https://user-images.githubusercontent.com/243872/47959278-34f03700-dfb6-11e8-81a2-829f5676baf0.png)

2) When zooming in, the editor does not try to maintain the center of the editor area, or keep the fin visible.  Instead it seems to be locked on the front of the viewable area, which initially is the front of the parent.  For example, if I start here:
![image](https://user-images.githubusercontent.com/243872/47959298-9a442800-dfb6-11e8-80fd-d9f4b8285879.png)
and then zoom in once, I get this:
![image](https://user-images.githubusercontent.com/243872/47959306-b0ea7f00-dfb6-11e8-9c6d-fbcc58b9aceb.png)
The scrollbar is pinned to the left after the zoom, which is the least useful result.  Aggregating across all rocket designs, I think it would be fair to say that the majority of fins are located towards the rear of the rocket.  So this means that almost every time you try to zoom in, you need to zoom and then scroll to the right.  It's annoying.

3) The fin editor always opens up zoomed out to the parent component.  Often, the means the the fin itself starts out very small, particularly if it's mounted to a long BT.  For example:
![image](https://user-images.githubusercontent.com/243872/47959323-1d657e00-dfb7-11e8-9a51-1231e5fcc9da.png)
OK, so naturally I want to zoom in before editing it.  And then issue 2 crops up; every time I zoom I must also then scroll to the right.

I'm not sure that opening the editor zoomed to the parent component is the best choice.  I think I'd rather have it zoomed to fit the fin itself.  I can always keep the main window open to see the fin in the larger context of the rocket, or zoom out in the editor.

It may be a different story for fins mounted to transitions or nose cones, where seeing the whole thing together could be more likely to be useful, I don't know.

**Comment by teyrana** [comment]
@neilweinstock 
Ok, splitting issue, as suggested.

#474 - Fix viewable bounds
#475 - Fix Zoom Center
#476 - Fix Initial auto-zoom

**Comment by neilweinstock** [comment]
Renamed this one to get "Alpha 9" out of the title.  Problem still present in latest unstable build.

**Comment by teyrana** [comment]
## Addressing PRs:
 - https://github.com/openrocket/openrocket/pull/737 - auto-scroll if points are dragged OOB

**Comment by teyrana** [comment]
Closing as resolved.
