### ISSUE TITLE
FreeformFinConfig: On initial open, auto-scroll should center to fin bounds.

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#476]
> The fin editor always opens up zoomed out to the parent component.  
1. the zoom bounds (size)  don't make sense. 
    - [ ] scroll bars not present when they should be  (canvas size is too small?)
    - [ ] bounds are too small for the fin itself.  (should be mount + fins)
2. The zoom bounds (origin) seems to start at the beginning of the fin (which is probably the desired behavior)

**Comment by neilweinstock** [comment]
Just tried this on a design I'm working on for a friend.  The "About" box says Alpha 12 on the version I'm using (also tried this on the PR525 test version).
![image](https://user-images.githubusercontent.com/243872/55163915-0a5b7200-5141-11e9-85e3-785b86eca170.png)

Here, all the side fins have been combined into one giant fin to (hopefully) get the best drag estimation.  Upon opening, the finset editor is zoomed neither to the parent component *nor* the fin itself... just an arbitrary front portion of the fin.  Here's the file.

[freeform_zoom.zip](https://github.com/openrocket/openrocket/files/3018301/freeform_zoom.zip)

**Comment by teyrana** [comment]
@neilweinstock 

Is that offset part of the bug? It looks different in the main window, than in the fin-point window :/

**Comment by neilweinstock** [comment]
No, I think the offset is OK.  The main tube is actually two separate pieces (connected by a coupler in the real model) in the model the fins are connected to the rear tube.

So I believe that aspect is being shown correctly, the only problem is that the whole fin is not being shown.
