### ISSUE TITLE
Adjust Fin shape editor grid colors

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#482]
In the midst of all the great improvements to the fin shape editor, I just noticed that it lost its grid.

15.03:
![image](https://user-images.githubusercontent.com/243872/48647021-abc70000-e9b8-11e8-9eec-627db98f9738.png)

Alpha 9: 
![image](https://user-images.githubusercontent.com/243872/48647027-b2557780-e9b8-11e8-85ae-8465237230bb.png)

Was this an intentional removal?  The grid was handy.

Note also that the root was shown with a thick grey line, vs. the 1-pixel rendering of the parent object in the new release.  Although the parent object is sometimes useful, the thick grey line contributed more towards readability.

**Comment by teyrana** [comment]
Sooo, this fix worked at the time, and now that it's merged, it no longer does.  -.-
https://github.com/openrocket/openrocket/pull/487

**Comment by teyrana** [comment]
Lightened alpha channel on grid-line colors, and resubmitted.

**Comment by neilweinstock** [comment]
In Alpha 10 I'm seeing:
1) Black grid lines (should be much lighter; I expected them to be given the most recent comment)
2) 5" gridlines.  That is nigh-useless for small rockets.  Not sure if this is supposed to be auto-adapting to the current zoom level, or if it's locked at 5", or what.  In my testing here it seems to stay at 5" always.

Screenshot:
![image](https://user-images.githubusercontent.com/243872/49831700-926c6600-fd62-11e8-891d-cd2661a76ca8.png)

**Comment by neilweinstock** [comment]
I see no change in alpha 11.  Grid is still 5", same darkness as root edge and parent object outline.

**Comment by neilweinstock** [comment]
Grid looks better in the *real* alpha 11.

I would still like to see the parent object outline shown thicker, as it used to be in previous release version.  This makes it easier to visually separate from all the other action in the editor.  Not sure if that should be addressed here or in a separate issue.

**Comment by neilweinstock** [comment]
Here's how it looks in latest alpha:
![image](https://user-images.githubusercontent.com/243872/56386817-c7953300-61f0-11e9-9754-4d561884aaff.png)

Grid is still fixed at 0.5", and outline of parent object is still very hard to distinguish from 5" grid lines.  Was that supposed to have changed?

**Comment by neilweinstock** [comment]
My comments here are unchanged.  The old grid was much "smarter" than the new one, and the parent object outline needs to be more prominent, like in the old release.

**Comment by hcraigmiller** [comment]
New issues created  #(835, #836, and #837) to resolve outstanding elements of this issue.

**Comment by hcraigmiller** [comment]
I have broken down the remaining elements of this issue and created new issues for each individual element, #835 for the physical size of the grid, #836 for the grid color, #837 for the color of the fin "point" indicator boxes, and #838 for the color of the fin lines (to be visually distinctive from the grid lines). Unless @neilweinstock believes something has been missed, this issue should be closed.

**Comment by neilweinstock** [comment]
New issues cover it.  Closing this one.
