### ISSUE TITLE
click+dragging a fin's first point creates many new points, instead of just one.

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#488]
as of alpha-9.

**Comment by neilweinstock** [comment]
In my testing of Alpha 10, dragging the first point *to the right* works fine.  Dragging it *to the left* creates a single new point, leaving the first point anchored to its original spot.  This happened for me repeatably on any freeform fin shape I tried.

So I'd say this one is not quite there.

**Comment by teyrana** [comment]
yea, I noticed that.  It should be fixed by PR #495

**Comment by teyrana** [comment]
Looks closed to me.  
See also #454
