### ISSUE TITLE
Side view horizontal centering problems

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#502]
No ORK file is attached to this one, just follow along to reproduce.  Screenshots show 15.03 on left, new alpha 10 on right.

Start with a new design.  Add a default body tube:
![centering1](https://user-images.githubusercontent.com/243872/50169507-b4626d00-02bb-11e9-9919-c794cdde881c.png)

So far so good.  Now add to the body tube a default freeform fin set.  In the new build, set the number of fins to 3.  Things are starting to go awry:
![centering2](https://user-images.githubusercontent.com/243872/50169576-d9ef7680-02bb-11e9-870f-b2b5e5b6e089.png)

Now edit the shape of the fins (do the same change to each).  Between the first and second points, add a new point at (-20, 1).  In the new build, having all that extra fin area way to the left somehow pulls the side view even more to the left,  Old build handles it properly.
![centering3](https://user-images.githubusercontent.com/243872/50169654-060af780-02bc-11e9-81b8-cbb5b504f1e1.png)

As an aside, neither the old nor new build knows how to zoom this properly in the 3D view:
![centering4](https://user-images.githubusercontent.com/243872/50169692-1327e680-02bc-11e9-897b-4f76b83de859.png)

Back to side view.  For the final step, delete the fin set, leaving only the body tube.  15.03 returns to the original view, while alpha 10 holds the same position as before:
![centering5](https://user-images.githubusercontent.com/243872/50169762-3c487700-02bc-11e9-9001-2c5c13980466.png)

**Comment by teyrana** [comment]
Exacerbated by #503.

**Comment by neilweinstock** [comment]
Checked on Alpha 11:  Behavior is *slightly* changed, but overall pretty similar.  Problem still exists.

**Comment by neilweinstock** [comment]
This problem still exists.  Designs are sometimes not centered properly.  I haven't been able to isolate exactly what causes it.

Removing "Alpha 10" from the title.

**Comment by neilweinstock** [comment]
This issue continues to frustrate.  Today I created a new design, added a body tube with all default parameters, and it was displayed like this:
![image](https://user-images.githubusercontent.com/243872/87430814-c00b3800-c5b3-11ea-8f3f-c0035e4aace3.png)

Using Daniel's build for PR #686 .
