### ISSUE TITLE
Rocket shows very different CG in 15.03 and current unstable

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#522]
Here's a simple DD 3FNC rocket of mine:
[airframe.ork.zip](https://github.com/openrocket/openrocket/files/2898357/airframe.ork.zip)
CG location under 15.03 is at 29.655"
![or15 03](https://user-images.githubusercontent.com/3065196/53304856-89564580-3837-11e9-89fc-b46ead3f06e3.png)
CG under current unstable branch is at 16.81"
![unstable](https://user-images.githubusercontent.com/3065196/53304878-e0f4b100-3837-11e9-8441-e1d703603df2.png)

Starting to look into it now...

**Comment by teyrana** [comment]
closed as resolved.

**Comment by teyrana** [comment]
Closing as resolved.
