### ISSUE TITLE
Rocket max diameter is 0

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#525]
The rocket max diameter, as reported in the second line of the RocketInfo pane, is always 0.  This doesn't seem like another manifestation of #329, since the other items described in the pane (length, mass with motors, mass without motors) do get updated correctly, and it looks (from a cursory look) like they're all updated in the same method.

**Comment by teyrana** [comment]
@JoePfeiffer 
We have several fixes merged against this issue, so closing as resolved.  
If we missed a case, please submit as a new issue.
