### ISSUE TITLE
Alpha 12: Length calculation broken

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#539]
This design is reported as 28" long, but in fact it is 16".
![image](https://user-images.githubusercontent.com/243872/56478640-d1cc6100-647e-11e9-921c-2a2764cefc5f.png)

It also reports max diameter as zero (#525).

[length.ork.zip](https://github.com/openrocket/openrocket/files/3101858/length.ork.zip)

**Comment by wolsen** [comment]
Hmm, I can’t seem to recreate this on the latest unstable. I’m not sure which git hash maps to Alpha 12 so I can’t recreate and see which commit may have fixed this

**Comment by teyrana** [comment]
Well, if it's fixed, it's fixed.

Lets fix the bugs that actually exist, instead :)
