### ISSUE TITLE
Default number of instances for fins should be 3

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#540]
At some point in the new release development, the default number of fins changed from 3 to 1.  I don't think 1 makes a lot of sense as default, should go back to 3 IMHO.

**Comment by bweissinger** [comment]
This seems to be related to #431, at least from what I can tell from the commit history.

**Comment by teyrana** [comment]
@bweissinger 
Yea.  Fins are a type of instance-d component. And instances default to one, if not set otherwise.
