### ISSUE TITLE
Inner tubes with radial offset not displayed correctly

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#544]
When an inner tube is given a radial offset, it is still displayed as being centered.

Here's how a simple test design looks on 15.03 (showing back view, but same problem in other views):
![image](https://user-images.githubusercontent.com/243872/63730173-16ef0e00-c838-11e9-83da-34ade90b3d26.png)

Here it is on a recent alpha build:
![image](https://user-images.githubusercontent.com/243872/63730139-f0c96e00-c837-11e9-8347-6059e43836a3.png)

[offset_inner_tube.ork.zip](https://github.com/openrocket/openrocket/files/3543578/offset_inner_tube.ork.zip)

**Comment by bweissinger** [comment]
It looks like it is coming from this bit inside InnerTube.java:

https://github.com/openrocket/openrocket/blob/b5cde10824440a1e125067b7d149873deec424b4/core/src/net/sf/openrocket/rocketcomponent/InnerTube.java#L217-L226

The offset is just set to the zero coord for a cluster with a single instance. Clusters with more than one instance are updated and display properly. I'll work on getting a PR up.
