### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by Teals53** [openrocket/openrocket#548]
Why This Project Are Abondoned ?

**Comment by celeron533** [comment]
From my observation, until today, the latest code commit on `unstable` branch is on Sep 1, 778413c882c560171e58ca516b423cdea489c323.

**Comment by Teals53** [comment]
> From my observation, until today, the latest code commit on `unstable` branch is on Sep 1, [778413c](https://github.com/openrocket/openrocket/commit/778413c882c560171e58ca516b423cdea489c323).

how can i convert this unstable source code to runnable jar files like in releases ?

**Comment by Teals53** [comment]
its gratifying to see that the project is still going on

**Comment by Teals53** [comment]
I didnt realize that :D
