### ISSUE TITLE
Default rail button size is ginormous

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#554]
Default outer diameter and total height are 1 meter, which is big enough for a Falcon 9 I think. :)

![image](https://user-images.githubusercontent.com/243872/67128102-b7bed180-f1c8-11e9-9135-a2b3c6b62a9f.png)

(also there is no parts library for buttons at this point).

derived from issue #550.

**Comment by wolsen** [comment]
@neilweinstock I've got a branch in progress that fixes the default rail button sizes, cleans up the rail button dialog, and adds some preset options. I should break them out into separate commits. Can you give this a try and let me know if it looks better for you?

**Comment by neilweinstock** [comment]
I'd be happy to try it out.  Any way you could provide me with a jar file?
________________________________

**Comment by teyrana** [comment]
Hey, guys, I've posted a jar on the referenced commit.

@neilweinstock Let us know what you find. 
@wolsen Thanks for fixing that stuff.  It's one of the many bits of cleanup we're trying to get together :)

**Comment by neilweinstock** [comment]
Certainly looks better than before! :)

However, I do have questions and comments.  Here's what my window looked like after adding rail buttons to a body tube; refer to numbered callouts below:
![image](https://user-images.githubusercontent.com/243872/75722771-dbcb0d00-5ca8-11ea-89a4-e669e871840f.png)

1) I note that the side view visualizer does not seem to take the buttons into account when calculating extents.  Probably a separate issue.

2) Does the default size match an existing standard button?  I'm thinking one that would fit a 1010 rail.

3) Default material should probably not be Cardboard. :)

4) It dawned on me while looking at this that the icon on the button for adding Rail Buttons does not actually look much like a rail button, nor does it match the style of the rest of the icons.  Should be replaced.  Who does the icon work?  Also probably a separate issue.

**Comment by teyrana** [comment]
1.  Yea, leta out that in a separate issue.   It's certainly true,  but that's neither a problem exclusive to this PR, nor a showstopper.

2.  Yes.  It is suzed for 1010 rail, according to the commit message.  (+1 for great commit messages, btw :)

3. Concur.

4.  Fair point.  I would advocate that's also a separate issue.

**Comment by wolsen** [comment]
@neilweinstock thanks for testing and feedback!

@teyrana sure I can take a look at 3. I think the right approach is to add two new materials, Nylon and Delrin to the bulk materials list.

According to Wikipedia (and confirming via Dupont's material data center), Delrin appears to have a density of 1.42 g/cm^3 and Nylon has a density of 1.15 g/cm^3.

The overall mass estimate will still be off with the new materials as it doesn't account for any type of mounting hardware, but that's what the mass objects are for.
