### ISSUE TITLE
Freeform fin editor changes not shown in real time in main display

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#555]
I thought this was being tracked somewhere but I can't find it, so I'm create a new one.  Also referenced in issue #550 

Basically, when making edits to the shape of freeform fins, the main display does not update (usually) until you go and click back there and select a different component, e.g.:
![image](https://user-images.githubusercontent.com/243872/67128569-0faa0800-f1ca-11e9-80e0-11bfab334723.png)

**Comment by teyrana** [comment]
Addressed in #626
