### ISSUE TITLE
bug in rocket specs at bottom of screen

### ISSUE THREAD

**Issue by Ross04** [openrocket/openrocket#560]
![Screenshot_20191123_180240](https://user-images.githubusercontent.com/32878239/69487246-e5c4b080-0e1b-11ea-8653-42712ae02f40.png)
The apogee, max velocity, and max acceleration are not working properly (see screenshot).
system: fedora 31. openrocket built from source
.ork file for replication purposes in zip file

[bugfix.zip](https://github.com/openrocket/openrocket/files/3883074/bugfix.zip)

**Comment by teyrana** [comment]
@Ross04 Thank you for including the rocket file-- that's awesome :) !

Can you confirm which version of OR this is?  15.03, I assume? 

This is likely a dup of issue: #525 , and fixed in: #533 .  But it's hard to tell without further information.

**Comment by Ross04** [comment]
Unable to confirm fixed, (for some reason it's not compiling for me now) .

> openrocket built from source
There is your OR version. I'll probably close this issue now since I am using your appimage most of the time now.
