### ISSUE TITLE
Instructions to build from terminal

### ISSUE THREAD

**Issue by Houkime** [openrocket/openrocket#562]
https://github.com/openrocket/openrocket/issues/340 points to http://wiki.openrocket.info/Developer%27s_Guide as a source for building instructions, but it is needlessly convoluted and tied to IDE (which i don't use).

On the other side, build.xml is just an Apache Ant build file.  
Actual build_from_terminal instructions are extremely simple:

#### Unix-like systems (Linux / BSD / MacOS /...)

* Install [Apache Ant](https://en.wikipedia.org/wiki/Apache_Ant) (e.g. `sudo pacman -S ant` for Arch Linux)
* Clone and build:
 ```
git clone https://github.com/openrocket/openrocket
cd openrocket
ant
```
* Run the .jar with `java -jar swing/build/jar/OpenRocket.jar` or copy it wherever you need

______________________________________
I am not sure about my exact wording and whether to include git and JDK itself in the required packages, but even like that it will have some value if added to README.md i think.
Works on my Arch Linux (while downloaded .jar doesn't btw).

About Windows I cannot provide instructions though since i don't have it.

**Comment by itshanney** [comment]
Note: You will need to ensure that you have JDK 8 and not newer. #347 is the issue that will deliver support for newer versions of Java, but that's not complete yet. In the meantime, ensure Java 8 is your JDK being used.

Your instructions are in essence correct. This is the basic procedure, assuming Linux, as you mentioned:
1. Install JDK 8. OpenJDK 8 is probably the most popular here.
2. Install Apache Ant and add to your PATH.
3. Git clone the code as you have done.
4. cd into openrocket folder
5. I would advise to start in core folder to test your setup
6. ant build

Wrapping that all up into a set of commands that can be used, give this a try. Sorry I don't use Arch Linux, but you can "translate" to your distro.

`
sudo apt-get install openjdk-8-jdk ant git
mkdir -p ~/Code
cd ~/Code
git clone https://github.com/openrocket/openrocket
cd openrocket/core
ant build
`

**Comment by teyrana** [comment]
@Houkime @itshanney 

Friendly reminder:  Both of you have a the ability to edit the wiki pages. (if not, let me know-- that'd be a bug)

And this is exactly the sort of thing that would be useful to have documented there, and for the same effort as posting it here :)

**Comment by teyrana** [comment]
As a starting point, I've copied over the comments here to a page: 

https://github.com/openrocket/openrocket/wiki/Instructions-to-build-from-terminal

Feel free to correct it, as you see fit, and if I've screwed up the editing, or misrepresented anyone, I apologize in advance!

**Comment by itshanney** [comment]
Closing issue as wiki document has been updated and exists as a guide.

https://github.com/openrocket/openrocket/wiki/Instructions-to-build-from-terminal
