### ISSUE TITLE
Calculates Incorrect Cp on split-fin rockets

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#600]
### Reproduction: 

Open the following in current development branch (`unstable`):
[simple_split_fins.ork.zip](https://github.com/openrocket/openrocket/files/4365711/simple_split_fins.ork.zip)

### Expected 
Same as in 15.03, or the equivalent 4-fin FinSet
Cp.x = 50.5 cm 

### Actual
Cp.x = -32.7 cm

**Comment by JoePfeiffer** [comment]
-32.7?  Wow.  I'm still plugging through the BaroowmanCalculator which includes both that code and the friction code; when I get the PR finished for the friction code I can look at this if you'd like.

**Comment by teyrana** [comment]
@JoePfeiffer 

Actually I have a PR that you can look at, if you have the time /grin
(#601)

I've definitely fixed this *particular* issue (#600) but I'm not sure that the rest of the associated code works the way we want.
