### ISSUE TITLE
tube fins don't display -- 2d / side-views

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#605]

**Comment by teyrana** [comment]
@itshanney 

In another thread, you said:
> Also, ignore the Fix 2D TubeFin rendering (will clean up the commit later) - as I was simply fixing the rendering for my own tests. I know @teyrana raised a bug with little detail, so I assume a patch is coming.

Nope, I have no patch in the works.  And if you have one, it's welcome!
(Assuming that it's independent from those other changes of course ;)

**Comment by wolsen** [comment]
@teyrana that was me actually. I'll revisit that one in a bit
