### ISSUE TITLE
Large CPU usage in unstable branch

### ISSUE THREAD

**Issue by itshanney** [openrocket/openrocket#615]
When running the latest build from unstable, there is a very high bit of CPU usage. I hooked up a profiler to try and see what the culprit is and the attached screenshots show the top consumers of CPU. 

It appears to be something related to the rendering engine on screen. @teyrana @wolsen have any ideas?

![Screen Shot 2020-04-02 at 19 42 12](https://user-images.githubusercontent.com/454090/78318837-a2d9be80-751a-11ea-9eac-6aa447a1c8ca.png)
![Screen Shot 2020-04-02 at 19 42 48](https://user-images.githubusercontent.com/454090/78318843-a66d4580-751a-11ea-95c1-09391d3d9bec.png)
![Screen Shot 2020-04-02 at 19 43 19](https://user-images.githubusercontent.com/454090/78318848-a9683600-751a-11ea-8abc-73c8dd1ec1e6.png)

**Comment by itshanney** [comment]
Found the culprit. It's from this chunk of code starting on line 364 in ScaleScrollPane.java.  It's continually drawing the ticks and calling the drawTick method.

```java
for (Tick t : ticks) {
    int position = toPx(t.value);
    drawTick(g2, position, t);
}
```

**Comment by teyrana** [comment]
well it's running within the outer 'paintComponent` method...  which is intended to only be called when something changes.

**Comment by wolsen** [comment]
@itshanney Ah good find. Looking at the code, I think that the ScaleScrollPane.Ruler.paintComponent() method is causing this. In that code, one of the first things it does is invoke updateSize() which in turn calls revalidate() and repaint(). AIUI, this will cause the underlying graphics libraries mark the component as dirty. The paintComponent method will continue to execute, but the component is marked as dirty which will then retrigger an invocation to the paintComponent... which in turn calls updateSize() and we are then on the merry-go-round of painting those rulers super frequently.

**Comment by wolsen** [comment]
Here's a [test build](https://www.dropbox.com/s/im0no05u8ytlpil/OpenRocket-fix-615-high-cpu.jar?dl=0) with the changes included for anyone who wants to test. See if this resolves the high cpu usage or if we need to chase some further activity. It looks promising on my machine.

@itshanney @neilweinstock - can you guys give this a go?

**Comment by neilweinstock** [comment]
Thanks, I'll give it a test tomorrow and get back to you.

**Comment by neilweinstock** [comment]
Looks good on MacOS 10.14.


  *   Neil

________________________________
