### ISSUE TITLE
Motor parameter search with empty motor characteristic causes null pointer exception

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#620]
When a motor is loaded from a user motor file (so not from the serialized motor database) some of its fields -- notably the caseInfo field -- are null.  If a motor search ends up doing a string compare against such a motor, a null pointer exception is raised

**Comment by teyrana** [comment]
@JoePfeiffer  
I merged #622 ... can we close this issue?

**Comment by JoePfeiffer** [comment]
Fixed by #622
