### ISSUE TITLE
Scaling rocket doesn't scale radial distance of pods

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#638]
Scaling seems to forget to scale the radial distance of pods.  Here's a design, before scaling:
![image](https://user-images.githubusercontent.com/243872/80716269-71c2be80-8ac5-11ea-824d-f08df3cae132.png)

Here it is after scaling 400%:
![image](https://user-images.githubusercontent.com/243872/80716361-8737e880-8ac5-11ea-9a2f-d198bd5cb478.png)

Tested on the latest unstable, based on commit 1c7171e.

**Comment by teyrana** [comment]
Fix submitted at #662
