### ISSUE TITLE
Change  calculation method of "getPreviousSymmetricComponent"

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#645]
Triggered by undesired behavior of the "auto Radius" check box on a trailing Transition component.
The component should refer to the previous component _in-line_, and ignore those in attached pods.

**Comment by teyrana** [comment]
## Example:

![mre](https://user-images.githubusercontent.com/5686825/80869207-10d5ea80-8c6d-11ea-82e8-576371e695fd.png)

In this rocket, we have a Tail Cone ("Transition" Component), which has it's forward radius set to auto.    In this case, the tail cone thinks it's "previous" component is the body tube in the pods, instead of the body tube it _actually_ follows.

The expected behavior would be to match radius with the centerline body tube.

**Comment by teyrana** [comment]
(although, just to acknowledge, in the picture above, this *does* look like an expansion rocket nozzle)

**Comment by neilweinstock** [comment]
Good find!
