### ISSUE TITLE
Error in calculating CP with phantom body tubes:

### ISSUE THREAD

**Issue by teyrana** [openrocket/openrocket#648]
CG is sometimes shown off-axis in 3D Finished view.  See attached design.

Related to #641, but this issue is for CP calculations.

Side view:
![image](https://user-images.githubusercontent.com/243872/80773963-89cc2980-8b29-11ea-9318-8037c9a6b1ad.png)

3D Finished view:
![image](https://user-images.githubusercontent.com/243872/80773980-994b7280-8b29-11ea-9125-ec32e62001d5.png)

Tested on latest unstable build.

[cg_render_bug.ork.zip](https://github.com/openrocket/openrocket/files/4562127/cg_render_bug.ork.zip)

If the pod-fins are offset *past* the end of their parent bodies (Offset via BOTTOM: x > 0) ... CP is NaN.

If the pod-fins are offset *past* the end of their parent bodies (Offset via BOTTOM: x > 0) ... CP  is reasonably.

**Comment by neilweinstock** [comment]
Here's a design I cooked up yesterday that shows the CP off-axis.
![image](https://user-images.githubusercontent.com/243872/80971611-07728c80-8deb-11ea-8c48-f6c21907a900.png)
[retro_lander.ork.zip](https://github.com/openrocket/openrocket/files/4574958/retro_lander.ork.zip)

**Comment by JoePfeiffer** [comment]
These CP bugs are like roaches, aren't they...

> If the pod-fins are offset _past_ the end of their parent bodies (Offset via BOTTOM: x > 0) ... CP is NaN.
> 
> If the pod-fins are offset _past_ the end of their parent bodies (Offset via BOTTOM: x > 0) ... CP is reasonably.

These look like you're describing the same case?

**Comment by teyrana** [comment]
*sigh* yea.  There *is* a lot of them.
