### ISSUE TITLE
CP is still off-center if pods.

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#654]
In Neil's 3fnc test rockets, CP is still shown off-center in 3fnc-take2-pods.ork.  On-center in 3fnc-take2.ork, however.

**Comment by JoePfeiffer** [comment]
Just clarified the title -- the display isn't the problem (in fact, was masking the problem).

**Comment by JoePfeiffer** [comment]
Ah.  The CP code for FinSets recognizes when there are three or more fins in the set, and (because they're evenly distributed around the axis) pins CP Y and Z to 0.  This doesn't work when there are pods, since there may be only a single fin on the pod, even though the pods are evenly distributed.

Need to look more closely at the moment calculations...

**Comment by teyrana** [comment]
We've merged #654, so I suppose this is due for re-validation.

**Comment by teyrana** [comment]
@JoePfeiffer I'm assumed you're referencing #568?

**Comment by teyrana** [comment]
I just ran the 3fnc files referenced above through our `unstable` branch, and the CP is on-axis.  
It looks like this was resolved by PR #657.

Closing as resolved.

**Comment by JoePfeiffer** [comment]
I wasn't specifically referencing any other issue in particular, though the examples in #568 are a good test case.  Yes, issue is resolved.
