### ISSUE TITLE
railbuttons don't rotate in 2D view

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#656]
With the attached design, when I display in 2D and rotate the rocket the railbutton remains vertical as it moves around the body tube.  In 3D views, it rotates appropriately.
[railbutton-doesn't-rotate.ork.zip](https://github.com/openrocket/openrocket/files/4589104/railbutton-doesn.t-rotate.ork.zip)

**Comment by teyrana** [comment]
## At 0°
![button-render-00d](https://user-images.githubusercontent.com/5686825/81430744-f5b42080-912d-11ea-8891-f5c020e4344e.png)

## At 90°
![button-render-90d](https://user-images.githubusercontent.com/5686825/81430745-f8167a80-912d-11ea-8c24-300ca6f1e722.png)

**Comment by JoePfeiffer** [comment]
At 90 it should look like a disk (just as fins are shown in an orthographic view).  Also, at a 180 rotation the button is shown inside the body tube.
![button-inside-tube](https://user-images.githubusercontent.com/3065196/81449430-77f81100-913d-11ea-814d-da0ce6f5b507.png)

**Comment by teyrana** [comment]
see #660
