### ISSUE TITLE
OpenRocket 15.03 unable to launch through Java version 8 latest. Please help!!

### ISSUE THREAD

**Issue by ApoorvSom** [openrocket/openrocket#667]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000, pid=7560, tid=0x00002510
#
# JRE version: Java(TM) SE Runtime Environment (8.0_251-b08) (build 1.8.0_251-b08)
# Java VM: Java HotSpot(TM) Client VM (25.251-b08 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  0x00000000
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by neilweinstock** [comment]
Apoorv got it working using a packaged installer.  Shall we close this?

**Comment by teyrana** [comment]
well, thanks to whoever helped Apoorv?

**Comment by teyrana** [comment]
Do we know what the inciting problem is?

**Comment by neilweinstock** [comment]
He found my packaged installer, presumably from TRF.

Don’t know what the problem was. I just didn’t think we were going to be trying to chase down java problems on 15.03 at this point.

________________________________

**Comment by teyrana** [comment]
Okay, well glad it got solved, then.

**Comment by airqualityanthony** [comment]
What was the solution here? I'm having the same issue.
