### ISSUE TITLE
simulation results in rocket design pane don't match results in flight simulations tab

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#671]
In the attached rocket, the Altitude in the rocket design pane is significantly different from the value shown in the Flight Simulations tab (Max velocity and Max acceleration are also different, though not by as much).

Rocket design pane:
![designpane](https://user-images.githubusercontent.com/3065196/82165279-b09c9680-9871-11ea-8d9d-1b67fda190cf.png)

Simulation tab:
![simulationtab](https://user-images.githubusercontent.com/3065196/82165333-e2adf880-9871-11ea-9c11-64a2c0e998e9.png)

[Rocket Double Stage Constant Diameter.ork.zip](https://github.com/openrocket/openrocket/files/4641514/Rocket.Double.Stage.Constant.Diameter.ork.zip)

**Comment by neilweinstock** [comment]
Is this one fixed?  Should it be closed?

**Comment by JoePfeiffer** [comment]
Not fully -- I got distracted, but am back on it.
