### ISSUE TITLE
Bug report of OR in Dell machine with Windows 10 

### ISSUE THREAD

**Issue by LuisaMirelle** [openrocket/openrocket#692]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadDirectory(MotorDatabaseLoader.java:124)
	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:69)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)

---------- Thread information ----------
Thread[DatabaseLoadingThread,1,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: C:\Users\luisa\AppData\Local\OpenRocket\app\OpenRocket-15.03.jar
JOGL version: 2.1.5
Current default locale: en
System properties:
  app.preferences.id=net/sf/openrocket/startup
  awt.toolkit=sun.awt.windows.WToolkit
  file.encoding=Cp1252
  file.encoding.pkg=sun.io
  file.separator=\
  java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
  java.awt.printerjob=sun.awt.windows.WPrinterJob
  java.class.path=C:\Users\luisa\AppData\Local\OpenRocket\app\OpenRocket-15.03.jar
  java.class.version=52.0
  java.endorsed.dirs=C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\endorsed
  java.ext.dirs=C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
  java.home=C:\Users\luisa\AppData\Local\OpenRocket\runtime
  java.io.tmpdir=C:\Users\luisa\AppData\Local\Temp\
  java.launcher.path=C:\Users\luisa\AppData\Local\OpenRocket
  java.library.path=C:\Users\luisa\AppData\Local\OpenRocket\app;C:\Users\luisa\AppData\Local\OpenRocket
  java.runtime.name=Java(TM) SE Runtime Environment
  java.runtime.version=1.8.0_111-b14
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=1.8
  java.vendor=Oracle Corporation
  java.vendor.url=http://java.oracle.com/
  java.vendor.url.bug=http://bugreport.sun.com/bugreport/
  java.version=1.8.0_111
  java.vm.info=mixed mode
  java.vm.name=Java HotSpot(TM) 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=1.8
  java.vm.vendor=Oracle Corporation
  java.vm.version=25.111-b14
  line.separator=\u000d\u000a
  os.arch=amd64
  os.name=Windows 10
  os.version=10.0
  path.separator=;
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.class.path=C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\resources.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\rt.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\sunrsasign.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\jsse.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\jce.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\charsets.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\lib\jfr.jar;C:\Users\luisa\AppData\Local\OpenRocket\runtime\classes
  sun.boot.library.path=C:\Users\luisa\AppData\Local\OpenRocket\runtime\bin
  sun.cpu.endian=little
  sun.cpu.isalist=amd64
  sun.desktop=windows
  sun.io.unicode.encoding=UnicodeLittle
  sun.jnu.encoding=Cp1252
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=
  user.country=BR
  user.dir=C:\Users\luisa\AppData\Local\OpenRocket\app
  user.home=C:\Users\luisa
  user.language=pt
  user.name=luisa
  user.script=
  user.timezone=America/Cayenne
  user.variant=
---------- Error log ----------
   1      0.000 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0.000 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0.088 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0.176 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0.205 INFO   (SwingStartup.java:133) Registering exception handler
   6      0.210 INFO   (SwingStartup.java:139) Loading databases
   7      1.912 INFO   (TranslatorProvider.java:46) Setting user-selected locale en
   8      1.949 INFO   (TranslatorProvider.java:61) Set up translation for locale en, debug.currentFile=messages.properties
   9      1.953 INFO   (ComponentPresetDatabaseLoader.java:51) Loading component presets from datafiles/presets
  10      1.956 INFO   (MotorDatabaseLoader.java:55) Starting reading serialized motor database
  11      1.957 INFO   (SwingStartup.java:151) Starting update check
  12      1.959 INFO   (SwingStartup.java:160) Setting best LAF
  14      2.382 WARN   (UpdateInfoRetriever.java:184) Unknown server response code: 404
  18      2.815 INFO   (SwingStartup.java:172) Opening main application window
  19      2.839 INFO   (BasicFrame.java:1518) New action initiated
  20      2.856 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.rocketcomponent.Configuration@7c9e727d, current number of listeners is 1
  22      2.889 INFO   (OpenRocketDocument.java:414) Clearing undo history of net.sf.openrocket.document.OpenRocketDocument@35b064d3
  23      2.891 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.document.OpenRocketDocument@35b064d3, current number of listeners is 2
  25      3.216 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.SimulationPanel$22@2b435b4, current number of listeners is 3
  28      3.491 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.RocketActions$2@5b04f79d, current number of listeners is 4
  31      3.708 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.componenttree.ComponentTreeModel@4ca631ab, current number of listeners is 5
  32      4.201 INFO   (MotorDatabaseLoader.java:61) Ending reading serialized motor database, motorCount=1721
  33      4.201 INFO   (MotorDatabaseLoader.java:64) Starting reading user-defined motors
  39      4.436 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.MotorConfigurationPanel$6@18d975f9, current number of listeners is 6
  40      4.460 INFO   (BlockingMotorDatabaseProvider.java:65) Motor database not loaded yet, displaying dialog
  41      4.497 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[DatabaseLoadingThread,1,main]
   > java.lang.IllegalArgumentException: MALFORMED
   > 	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
   > 	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
   > 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
   > 	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
   > 	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
   > 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDirectory(MotorDatabaseLoader.java:124)
   > 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:69)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
  42      4.499 STDERR (SwingExceptionHandler.java:49) java.lang.IllegalArgumentException: MALFORMED
  43      4.499 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
  44      4.499 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:300)
  45      4.499 STDERR (SwingExceptionHandler.java:49) 	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:122)
  46      4.499 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.file.motor.ZipFileMotorLoader.load(ZipFileMotorLoader.java:56)
  47      4.499 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.file.motor.GeneralMotorLoader.load(GeneralMotorLoader.java:36)
  48      4.507 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDirectory(MotorDatabaseLoader.java:124)
  49      4.507 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.MotorDatabaseLoader.loadDatabase(MotorDatabaseLoader.java:69)
  50      4.507 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
  51      4.507 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
  52      4.507 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
  53      4.507 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
  54      4.548 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 248      0.000 DEBUG  (-) ===== 208 DEBUG lines removed =====
 248    202.760 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1940
 249    203.782 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1950
 250    204.795 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1960
 251    205.805 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1970
 252    206.816 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1980
 253    207.826 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=1990
 254    208.854 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2000
 255    209.864 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2010
 256    210.871 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2020
 257    211.887 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2030
 258    212.898 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2040
 259    213.910 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2050
 260    214.916 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2060
 261    215.933 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2070
 262    216.949 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2080
 263    217.957 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2090
 264    218.968 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2100
 265    219.980 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2110
 266    220.998 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2120
 267    222.060 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2130
 268    223.100 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2140
 269    224.138 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2150
 270    225.158 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2160
 271    226.173 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2170
 272    227.185 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2180
 273    228.200 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2190
 274    229.230 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2200
 275    230.292 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2210
 276    231.301 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2220
 277    232.314 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2230
 278    233.324 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2240
 279    234.335 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2250
 280    235.344 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2260
 281    236.360 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2270
 282    237.375 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2280
 283    238.383 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2290
 284    239.392 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2300
 285    240.402 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2310
 286    241.415 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2320
 287    242.424 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2330
 288    243.436 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2340
 289    244.464 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2350
 290    245.474 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2360
 291    246.544 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2370
 292    247.569 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2380
 293    248.580 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2390
 294    249.590 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2400
 295    250.652 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2410
 296    251.660 DEBUG  (BlockingMotorDatabaseProvider.java:79) Database not loaded, count=2420
 297    251.945 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 298    251.949 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by wolsen** [comment]
It looks like the error is occurring when loading local ThrustCurve files. I can't tell which file in particular is causing the problems. Can you try moving the local ThrustCurve files to a different location and starting up OpenRocket to help confirm this is the case?

**Comment by wolsen** [comment]
From rocketryforum discussion:

@LuisaMirelle , I was looking at your bug report and it looks as though the error is occurring when loading your local motor database files. The problem appears to happen when reading in some of the local thrustcurves. So a couple of questions for you:
To confirm, do you have local thrustcurve files? I'm not a Windows guy, but I believe it will be in one of the following for your system. You can also just search for the ThrustCurves folder:
C:\Users\luisa\OpenRocket\ThrustCurves
C:\Users\luisa\AppData\Local\OpenRocket\ThrustCurves
Can you move the local thrustcurve files to another location and try to start up OpenRocket?
Have you recently added new thrustcurve files? I can't tell which one in particular is causing the problem
I'll also comment on the bug report.

**Comment by wolsen** [comment]
User seems to have resolved the issue [per the forum](https://www.rocketryforum.com/threads/openrocket-packaged-installers-for-windows-and-mac-to-solve-all-your-java-problems.143540/post-2019518). Closing this for now. Please re-open if you encounter this again.
