### ISSUE TITLE
Side view jittering (badly) while trying to "fit"

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#696]
See attached videos (sorry they are .mov format, that's what the screen recorder produced).

In the first (jitters1.mov), the rocket opened up into a size window where the side view oscillated rapidly between two sizes.

In the second (jitters2.mov), I show resizing the window downwards, and the side view oscillates as I do it.  If I stop in the right spot, it goes into self-oscillation.

Also attached is the rocket file that causes this (for whatever reason, probably just luck).

[jitters.zip](https://github.com/openrocket/openrocket/files/4915943/jitters.zip)
[blackfish_golden_sunset.ork.zip](https://github.com/openrocket/openrocket/files/4915956/blackfish_golden_sunset.ork.zip)

This is on a Mac running Mojave, using Daniel's latest build for PR #686

**Comment by teyrana** [comment]
Reproduced, on a Windows 10 Machine, on mainline 'unstable' branch.

Note that it only happens in 'auto-zoom'.  This can be worked around by explicitly setting the zoom level.
