### ISSUE TITLE
Feature request: Photo Studio should remember settings

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#697]
I use the Photo Studio quite a bit.  The default settings are pretty bad, and so usually I have to spend some time adjust everything to look good.  If I close the Photo Studio window, then everything is lost and I have to start over next time.  This is maddening.

It would be extremely useful if the Photo Studio could remember it's settings, preferably in the ORK file for each design.

Frankly, the Photo Studio settings panel could use an overhaul, but this one change would make it a lot less frustrating to use.

**Comment by hcraigmiller** [comment]
The only anomaly that I noticed is that the default "smoke" opacity is now "4000" instead of "40." Otherwise, seems to work well in all respects.

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]
