### ISSUE TITLE
Add back the "Rocket Optimization" feature

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#701]
"Rocket Optimization" was dropped out of the unstable branch at some time in the past.  Should be added back in before next release.

**Comment by teyrana** [comment]
Where is this "Optimization" option?

**Comment by neilweinstock** [comment]
Sounds like you've answered your own question, but anyway:
![image](https://user-images.githubusercontent.com/243872/88460397-0db45a00-ce6a-11ea-9d7b-7237fe71cb95.png)
