### ISSUE TITLE
Two repeatable crashers working with transitions (update: Java 14 only)

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#710]
This is repeatable on the last few builds I am working with here on MacOS.  I'm guessing they're related so including both here.  If they're not then this can be split into two issues.

To recreate, scenario 1:
1) Open the "Simple model rocket" example.
2) Select "Body Tube"
3) Add a transition
4) Click "Close" button on transition editing dialog.
5) Click the "Delete" button.
This reliably creates the crash in attached file "transition_crash_1.txt".
[transition_crash_1.txt](https://github.com/openrocket/openrocket/files/4978916/transition_crash_1.txt)

Scenario 2:
1) Open the "Simple model rocket" example.
2) Select "Body Tube"
3) Add a transition
4) Select the "Aft Diameter" field
5) Type in a new number, I usually just use "1"
6) Hit TAB
The reliably creates the crash in attached file "transition_crash_2.txt"
[transition_crash_2.txt](https://github.com/openrocket/openrocket/files/4978915/transition_crash_2.txt)

**Comment by wolsen** [comment]
Hmm, these are both SIGABRT in Java threads (Java 14)

**Comment by neilweinstock** [comment]
Yes indeed, it appears this is a Java 14 problem.  Does not reproduce on Java 11.

Do we even want to track this or should I just close it?

**Comment by hcraigmiller** [comment]
Where we will now be looking at JAVA 17 LTS compatibility, I recommend closing this issue.

**Comment by SiboVG** [comment]
This issue did not reproduce in Java 17, will therefore close this issue
