### ISSUE TITLE
Bug Report -- Motor Dimension Units Not Carried Over to Motor Section without Exiting all Instances of OR

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#724]
After opening the example "simple model rocket," change the motor dimension preference from the existing (old) unit to a different (new) unit of measure. Then, go to the select a rocket motor screen, it still displays the old unit not the new unit of measure on the slide bars (the text above the diameter bar does change). The select a rocket motor screen will not display the new unit or measure on the bars until all instances of OR are closed and OR is reopened (if even 1 instance of OR is left open, the change will not take effect).

![Motor Dim](https://user-images.githubusercontent.com/68821492/88861537-061aeb00-d1b3-11ea-81f3-dc3cd66cab7e.png)

**Comment by teyrana** [comment]
## Breadcrumbs

1. defined at: https://github.com/openrocket/openrocket/blob/917503149c3040fdcbf2b441f23b96162f0267f3/swing/src/net/sf/openrocket/gui/dialogs/motor/thrustcurve/MotorFilterPanel.java#L218
