### ISSUE TITLE
UI: Object configuration dialogs have gotten larger

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#727]
I just noticed that the object configuration dialogs have gotten somewhat larger in the new builds due to expanded spacing around the header and footer:
![image](https://user-images.githubusercontent.com/243872/88954151-e8f42400-d267-11ea-8123-94ac45ec8408.png)

This is not a major issue but to me it is better the old way.  The extra spacing does not (IMHO) enhance usability, it just makes the dialogs take up more space on the screen.

**Comment by teyrana** [comment]
Hmmm, I don't remember anyone explicitly setting this.

Which dialogs are you seeing it on?

**Comment by neilweinstock** [comment]
I think it's all of the component configuration dialogs.

**Comment by teyrana** [comment]
So, to be clear, you haven't seen it in dialogs _besides_ the Component Configuration ones?

**Comment by teyrana** [comment]
looks like it was a side effect of:
 https://github.com/openrocket/openrocket/issues/424
