### ISSUE TITLE
Rail Button Instance Separation Resets to Default Distance When Saved and Reopened

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#740]
Using the simple model rocket, delete the launch lug and create multiple rail button instances, change the instance separation, save and reopen. The instance separation between multiple rail buttons resets to the default distance when saved and reopened. The number of instances does not seem to change the outcome.
![01 Rail Button Multiple-2 Instance Distance Default](https://user-images.githubusercontent.com/68821492/89742052-544dab00-da4b-11ea-99b2-767777094a07.png)
![02 Rail Button Multiple-2 Instance Distance Changed](https://user-images.githubusercontent.com/68821492/89742056-6d565c00-da4b-11ea-8a2b-fcf5bdaf689d.png)
![03 Rail Button Multiple-2 Instance Distance Changed Saved-Reopened](https://user-images.githubusercontent.com/68821492/89742059-75160080-da4b-11ea-9979-1a75de03af25.png)

**Comment by teyrana** [comment]
breadcrumbs:
1. confirmed that the distance is a load issue (save seems to work as expected).
