### ISSUE TITLE
Rail Buttons Do Not Display on Pod Body Tubes

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#741]
Rail buttons that display on the main body tube disappear when moved to a pod set body tube. A change in the CG shows the move as expected, but the CP does not change. 

[Rail Button.Pod Set.No Display.zip](https://github.com/openrocket/openrocket/files/5048488/Rail.Button.Pod.Set.No.Display.zip)

**Comment by hcraigmiller** [comment]
Correction, the rail buttons were just out of view; the display did not reduce to show the rail buttons that were out of visual range.

**Comment by teyrana** [comment]
1.  Like launch lugs, rail buttons are not aerodynamic, and will not affect CP.

2. What do you mean by "display reduce”?   Auto zoom?

**Comment by hcraigmiller** [comment]
It did not auto zoom out to show the rail buttons.

**Comment by teyrana** [comment]
Dude... how big are your rail buttons ?!
(Mostly rhetorical)

**Comment by hcraigmiller** [comment]
Just looking for program functionality, not actual designing a rocket. I did find an irregularity in function, when comparing what happens with launch lugs and rail buttons, when moved from the main body tube to a pod body tube, a launch lug stays on the body tube, when you do the same with rail buttons, the buttons are some distance from the pod body tube.

![Rail Button Launch Lug Main Body Tube](https://user-images.githubusercontent.com/68821492/89742904-f2913f00-da52-11ea-9eb2-2fd074215d80.png)
![Rail Button Launch Lug Pod Body Tube](https://user-images.githubusercontent.com/68821492/89742907-f755f300-da52-11ea-8c3a-7aaaf9189310.png)

**Comment by teyrana** [comment]
## Breadcrumbs
1. Reproduce
2. Observed on side views AND rear views
