### ISSUE TITLE
Feature request: add "fit" option in zoom selector in fin editor

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#743]
In the main design view, there's a "fit" option at the bottom of the zoom selector.  It would be nice to have one in the fin editor as well, now that the zoom-to-fit functionality is nicely implemented.

Frankly, I'd prefer seeing the "fit" option at the top of the list instead of the bottom, but I'll take it either way.

**Comment by teyrana** [comment]
... is it not?  Haha
Yea, that'd make sense!

**Comment by neilweinstock** [comment]
I see it in the latest unstable.  I dunno if I missed it before or what, but it's definitely there now (and works! :)) so I'm closing this.
