### ISSUE TITLE
Crazy fin CP calculation (seems like a numerical error)

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#746]
Found this in 15.03, it persists in the current unstable.  This one took me quite a while to isolate.  It bit me badly on a rocket I'm building right now.

In the following set of four screenshots, I've edited the Y value of the second to last point on the fin by .001" each time (value shown in the magnifier).  Look at how the CP bounces around crazy from those tiny insignificant changes.  In addition to being way larger CP variations than would be justified, the movement isn't even monotonic.  This suggests to me a numerical error of some sort.

The trigger for the problem might be the spikes on the fins.  In any case, the numbers should not behave this way.

Here's the screenshot(s):
![image](https://user-images.githubusercontent.com/243872/90303517-8b252600-de7c-11ea-8baa-aade80fb93c1.png)

Here's the design:
[crazy_cp.ork.zip](https://github.com/openrocket/openrocket/files/5078013/crazy_cp.ork.zip)

**Comment by JoePfeiffer** [comment]
Ouch!  Yes, that's got to be a bug....  after a brief look, seems like something is going on with the midchord angle.

**Comment by neilweinstock** [comment]
That's a good one, isn't it? :)

I've played around with the spikes a fair bit, and can't establish a clear connection.  But without the spikes things seem to calm down, so they're involved somehow.

**Comment by JoePfeiffer** [comment]
It was the presence of a nearly-horizontal line in the fin.  When the fin was split up into "slices" to calculate its geometry, the calculation of the intersection between the line and the bounds of a slice were far, far outside the bounds of the fin itself.

**Comment by neilweinstock** [comment]
Interesting!  Got a fix?

**Comment by wcravens** [comment]
https://www.amazon.com/Chaos-Making-Science-James-Gleick/dp/0143113453 :-D

Wes
