### ISSUE TITLE
Inconsistent terminology used for angular/radial component positioning

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#751]
Launch lugs use "Radial position" and rail buttons use "Angular position." Mass components and inner tubes use radial position, but pods use "Angle." Should the positioning be standardized to either angular or radial positioning?

**Comment by neilweinstock** [comment]
Yes, should be standardized.  I'm not sure what the preferred term should be.

Also, fin sets simply use "Angle", although *maybe* it's a different enough thing to justify a different term, not sure.

Inner tubes have their own separate tab for "Radial Position", and inside that tab they have "Radial Direction" which is yet another term for the same thing.  It's debatable whether that should be a separate tab at all, but either way consistency in terminology would be good.

**Comment by teyrana** [comment]
Since I'm not seeing any replies, I'm unifying the labels to "Rotation".  This matches LaunchLugs and RailButtons to the Fin Config Dialogs.

**Comment by neilweinstock** [comment]
That seems good to me. 👍

________________________________
