### ISSUE TITLE
Addition of launch lug causes length error in multi-stage rockets

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#756]
Using a stripped version of Neil's 3-stage rocket, when you add a launch lug to a subsequent stage, that stage length changes to the length of that stage plus all upper stages combined. 
[Talos Terrier Recruit.Stripped.zip](https://github.com/openrocket/openrocket/files/5111725/Talos.Terrier.Recruit.Stripped.zip)

As shown below, adding a rail button to Stage 2 does not change the stage length, but adding a launch lug to Stage 2 changes the Stage 2 length to the total length of Stage 1 plus Stage 2.

![Stage Length](https://user-images.githubusercontent.com/68821492/90944388-439a1f00-e3d3-11ea-864a-7a417c4fa980.png)

The same thing happens if you, instead, add a launch lug to Stage 3, the Stage 3 length changes to the total length of all three stages.

**Comment by teyrana** [comment]
## Notes
- [ ] .1. Implement BoundingBox interface on Railbutton
- [ ] .2. Implement BoundingBox interface on LaunchLug
- [ ] .3. Implement BoundingBox interface on CenteringRing
- [ ] .4. Implement BoundingBox interface on InnerTube
- [ ] .5. Implement aerodynamics on RailButton
