### ISSUE TITLE
Mass components Do not render correctly - ignore radial position, radial angle

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#758]
Tried to radially line up two components, one named "Quick link [RADIAL POSITION ERROR]" the other named "Eye bolt body [RADIAL POSITION CORRECT]." As the names indicate, the latter can be positioned correctly using the Radial position tab and entering the Radial distance and direction. However, the Quick link (mass component) cannot be radially positioned visually, the Radial distance and direction do not change the visual display. Although the Quick link is a Recovery hardware type, the mass component type does not seem to change the outcome.

[LOC.T-Loc.Rev.01.zip](https://github.com/openrocket/openrocket/files/5126995/LOC.T-Loc.Rev.01.zip)

**Comment by teyrana** [comment]
Notes:
1. The ... Mass Component doesn't display it's Type-name-text correctly
2. The Mass Components aren't rendered correctly.
3. The _actual_ position seems to change, as observed by the C.M. moving.
