### ISSUE TITLE
Motor configuration changes when saved and reopened (specific to Aerotech G80)

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#761]
This may be specific to the Aerotech 29mm G80 motor. When a configuration containing this motor is saved, it changes to a G78 when reopened. I tried a number of different configurations, but this is the only motor that kept changing.

![Motor Selection Change After Save](https://user-images.githubusercontent.com/68821492/91256759-09a38280-e71d-11ea-86ae-56b4153022db.png)

On a side note, new configurations are not always created in the same order (such as the beginning or the end of the existing list).  How are new configurations ordered?

**Comment by teyrana** [comment]
@hcraigmiller 
Please post the file for debugging

Even the "wrong" one, as it will save a lot of time to reproduce the issue

**Comment by hcraigmiller** [comment]
Design file is attached:
[LOC.T-Loc.Error.Motor.G80.zip](https://github.com/openrocket/openrocket/files/5405243/LOC.T-Loc.Error.Motor.G80.zip)

Open the design file, and select Motors and Configuration.
![Error Motor Selection G80](https://user-images.githubusercontent.com/68821492/96520770-9dc52e00-1224-11eb-8505-a1c0a3da8c9c.png)

**Comment by JoePfeiffer** [comment]
Confirmed.  Hmmm....

**Comment by JoePfeiffer** [comment]
Hash collision!  Turns out both motors have the same "digest" (effectively a hash), and there's no check for a collision.  Working on it...
