### ISSUE TITLE
Recovery device opened while motor running warning even though deployment is set to apogee

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#762]
If recovery is set to deploy at apogee on the Recovery tab, but the motor ejection delay is set to greater than the simulated optimum delay, the simulation displays a “Recovery device opened while motor still running” warning. 

![Ejection Motor Running](https://user-images.githubusercontent.com/68821492/91367731-188d4200-e7bc-11ea-9e9c-295cc0564d1c.png)

Shouldn't the deploy at apogee setting on the Recovery tab disable this warning?

[MDRM.Fighter.Rev.01.zip](https://github.com/openrocket/openrocket/files/5133194/MDRM.Fighter.Rev.01.zip)

**Comment by JoePfeiffer** [comment]
I wouldn't say the warning should be disabled, but I'll agree that looking at the simulation plot it didn't happen in this case, so the warning shouldn't have gotten set.  Hmmm
