### ISSUE TITLE
Selection of deployment configuration for one motor on recovery tab opens the config menu for a different motor 

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#763]
Open the attached OR design file.
[MDRM.Fighter.Rev.02.zip](https://github.com/openrocket/openrocket/files/5133223/MDRM.Fighter.Rev.02.zip)

Go to the Motors & Configurations tab and click on the Recovery tab. On the Recovery tab, select the Main Parachute, Apogee setting for the H115 motor (either double-click on the word "Apogee" or single-click on the word "Apogee" and click the "Select deployment" button). The Select Deployment Configuration window shows that the recovery configuration for the H115 motor is being modified. Click OK or cancel to exit.

Now, select the Main Parachute, Apogee setting for the G138 motor. The Select Deployment Configuration window shows that _the recovery configuration for the **H115** motor is still being modified_.  Change deployment to first ejection charge of the stage then click OK, and it confirms that the recovery configuration for the H115 motor, not the G138 motor, was modified.

![Recovery Wrong Motor](https://user-images.githubusercontent.com/68821492/91369448-a66b2c00-e7c0-11ea-87f0-a01a20a266f8.png)

Even if you go straight from opening the design file to selecting the Main Parachute, Apogee setting for the G138 motor. The Select Deployment Configuration window will show that the recovery configuration for the **H115** motor is being modified.

FYI, may be related, new motor configurations just seem to be ordered without any consistency, sometimes place first in order, sometimes last, and sometimes in the middle of other existing configurations.

**Comment by JoePfeiffer** [comment]
The underlying issue is the selected configuration isn't being kept in sync between the Motors tab, Recovery tab, Stages tab, and the main rocket display window. When selecting a motor it uses the configuration selected in the pane so it isn't as noticeable; when selecting recovery options it's really noticeable since the configuration selected in the main display window determines which configuration is changed, which is not expected.

15.03 had this right...

**Comment by hcraigmiller** [comment]
May be related to #771 and/or #845.

**Comment by JoePfeiffer** [comment]
I *think* they're separate issues.  But I'll check.

**Comment by SiboVG** [comment]
From the first looks, it seems that the pop-up window uses the motor that is selected in the flight configuration. Selecting G138-5 in flight configuration makes the G138-5 to be edited in the deployment configuration, in both cases, both when selecting the G138-5 and H115-14 in the Recovery window. Will look into fixing it.

**Comment by hcraigmiller** [comment]
Your observation appears correct. In fact, if you select "Flight configuration: No Motors" then you cannot "override" the selected recovery configuration for any selection (the change is rejected); you can only change a configuration by using the "Change all configuration using the default deployment event" selection, changing all recovery configurations, not just the one you selected.

**Comment by SiboVG** [comment]
I might have found a possible solution for it by passing the FlightConfigurationId to the DeploymentSelectionDialog constructor. The ID is passed in selectDeployment from RecoveryConfigurationPanel, which in turn is extracted from the currently selected item in the recovery table. The current implementation took the FlightConfigurationId from the rocket flight configuration, but I changed that to be the ID of the configuration selected in the recovery table. Will do a pull request as soon as possible, but after editing these changes, it worked perfectly on my version.

**Comment by hcraigmiller** [comment]
Uploading a test .jar file may be helpful for testing and verification purposes.

**Comment by hcraigmiller** [comment]
This issue was fixed by PR #943.

**Comment by JoePfeiffer** [comment]
#942 was merged, not #943.  Did that also fix this issue?

**Comment by hcraigmiller** [comment]
Yes it did.
