### ISSUE TITLE
Component CG override result is inconsistent between Stage 1 and other stages

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#775]
Using post merge pull request #769 from teyrana/fix/755/cg-error download.  See also Issues #774 and #776 

Open attached design file:
[Staged Tubes.Analysis.CG-4.MO-1.ZeroOverride.Ver.01.zip](https://github.com/openrocket/openrocket/files/5178924/Staged.Tubes.Analysis.CG-4.MO-1.ZeroOverride.Ver.01.zip)

All component mass overrides are set to zero, and component CG overrides are set to 4, 12, and 20; component CG overrides are still measuring from the tip of Stage 1.

Looking at the stages individually, Stage 1 results in a CG of “NA” while Stage 2 and Stage 3 show a CG of 12, and 20, respectively. The Stage 1 result should be 4 to be consistent.

Also, when the stages are shown together, Stage 1 is ignored.

![Screen Shot ZeroMass Set 01](https://user-images.githubusercontent.com/68821492/92315669-e212ac80-ef9d-11ea-9814-fa876cbe93d7.png)

Although I used the component mass overrides, you get the same result without the component mass overrides checked.

**Comment by teyrana** [comment]
PR #769 appears to have fixed the CM.x override for _stages_. 
This issue is about CMx overrides on other components, including body tubes.
