### ISSUE TITLE
Rocket mass does not change when motor is installed

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#786]
If you create a new design, or open a design that does not have a motor installed when saved, when a motor is installed the upper left corner of the display window does not change to add "Mass with motors..." below "Mass with no motors..." But, if you save a design with the motor installed, it does. Also, in the latter, if you uninstall all motors, it keeps both lines of text, both showing the same mass.

**Comment by teyrana** [comment]
- [ ] update window when a motor mount is added
- [ ] update window when a motor mount is removed
- [ ] update window -- motor mass -- on _any_ motor change

**Comment by hcraigmiller** [comment]
Fixed.
