### ISSUE TITLE
Display smaller in current than 15.03

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#788]
I am editing this issue to reflect the 12/03/2020 merge as a number of issues that appear in the side view drawings have been corrected.

There is a significant difference in the 3D functionality between 15.03 and the current unstable; the current unstable is not recognizing the system display settings in the same way the 15.03 does. Using the sample Apocalypse rocket, you can see the problem.

![Sample 01](https://user-images.githubusercontent.com/68821492/101812900-dc62c080-3ad0-11eb-8ca1-fbd9dcd8b5c5.png)
![Sample 02](https://user-images.githubusercontent.com/68821492/101812914-e4226500-3ad0-11eb-84a8-15652c4bb211.png)

See also #719. 

Even lowering the screen resolution, the current unstable 3D Finished view is smaller than in 15.03.

![Sample 03](https://user-images.githubusercontent.com/68821492/101813955-4334a980-3ad2-11eb-86ee-2225008d84e3.png)

In the current unstable, the off-screen rendering also has an effect on size and the placement of the CG and CP markers.

![Sample 04](https://user-images.githubusercontent.com/68821492/101815346-4466d600-3ad4-11eb-9139-96fcf1786124.png)

Although not recognizing the system display settings for 3D functions is not otherwise affecting program functionality, when the Beta is release this bug will likely trigger a host of reports.

See also, #790

**Comment by wolsen** [comment]
The problem is that when setting up the view for the RocketFigure in 3d, the view size is doubling the span of the Y axes for the bounds required. This is likely legacy code, since the new bounds information takes this accurately into account and the doubling is no longer needed.

**Comment by wolsen** [comment]
> The problem is that when setting up the view for the RocketFigure in 3d, the view size is doubling the span of the Y axes for the bounds required. This is likely legacy code, since the new bounds information takes this accurately into account and the doubling is no longer needed.

Note that this only applies to the scaling of the rocket figure displayed, not the scaling of the 3d viewport itself (which is #719)
