### ISSUE TITLE
Vague and inaccurate diagnostic when motor file doesn't exist in specified format

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#807]
Several of the motor files at thrustcurve.org are failing to download (the vast majority are succeeding).  The only diagnostic is a message similar to " [java] 	Error downloading RockSim for motorID=782".  Some hint as to what's wrong is needed...

**Comment by hcraigmiller** [comment]
Perhaps a conversation with John Coker on TRF would be helpful.
![ThrustCurve](https://user-images.githubusercontent.com/68821492/98140503-5cff2300-1e7a-11eb-9053-b218c9dd93f6.PNG)

**Comment by JoePfeiffer** [comment]
The error message turns out to be a red herring -- in the case where there is no data for the motor in the specified download format (ie RASP or RockSim), attempting to put null data in the list of curves for the motor throws an error.  Actually harmless, but alarming and misleading.
