### ISSUE TITLE
Feature Request: Option to display stability as a percentage of rocket length

### ISSUE THREAD

**Issue by neutronium95** [openrocket/openrocket#822]
Calibers of stability are a nice rule of thumb for most normal rocket designs, but they tend to break down when working with especially thin or fat rockets. Some people instead prefer to think of stability in terms of percentage of body length, aiming for around 10-15%. It's kind of annoying to have to calculate that from the CG CP distance all the time.

**Comment by JoePfeiffer** [comment]
This seems like something we might want to make possible as we consider making the rocket information panel configurable (#802)

**Comment by hcraigmiller** [comment]
This issue has been fixed by way of PR #921; this issue should be closed.
