### ISSUE TITLE
Launch failure in macOS Big Sur

### ISSUE THREAD

**Issue by kenbiba** [openrocket/openrocket#827]
Just won't launch.

**Comment by JoePfeiffer** [comment]
Assuming you're trying to launch 15.03, it requires an antique version of Java.  You can find a prepacked installer for MacOS that includes the needed version at https://github.com/openrocket/openrocket/releases/download/release-15.03/OpenRocket-15.03.dmg

**Comment by kenbiba** [comment]
Sadly ... it does not launch.

**Comment by JoePfeiffer** [comment]
That's with the dmg, not the jar file? We'll see if anyone else has any ideas....

**Comment by kenbiba** [comment]
Sadly yes.   Just tried again.   At first it complained about Java.  Now it is just silent and does nothing.

Perhaps you can open this issue again.

**Comment by jimmiedave** [comment]
It's possible that MacOS gatekeeper is preventing unsigned code from running - but there's usually a dialog that comes along with that.

Can you describe what the install process was like as you installed from the DMG - you probably would've gotten a dialog that says "this file was downloaded from the web - do you want to open it?"

Then there may have been other administrator dialogs, or other complaints from the system. It'd be helpful to know what they were.

Are you an administrator on the system? (if you're the only person who's ever used it, and it's not managed by a business, yes, you probably are).

**Comment by jimmiedave** [comment]
You may also be able to go into Security and Privacy (in System Preferences) and find a place to set an unsigned application to run - but I don't see such a place on my Catalina system.

**Comment by kenbiba** [comment]
Hmmmm .... fixed it.

I removed the old one first.  And emptied trash.  Then reinstalled from the source.

This time it explicitly asked for authentication - requiring me to option-click on the first open and allow it to open.

It launched.   For the moment it seems OK.

Thanks for responding.

**Comment by JoePfeiffer** [comment]
Don't know what went wrong the first time... but glad it's OK now.
