### ISSUE TITLE
Mass objects shown in wrong position in side view

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#828]
Mass objects are shown in side view in the wrong position.  This *only* affects the side view.  See attached screenshot.
![image](https://user-images.githubusercontent.com/243872/99968995-df874e00-2d67-11eb-8abd-47b27f388222.png)
Note that the CG is shown in the same location in old OR and new OR, so it seems to be purely a rendering error.

**Comment by hcraigmiller** [comment]
See also Issue #785;may be the same or a related issue.

**Comment by neilweinstock** [comment]
Yes, probably a duplicate, but I'll leave it open just in case.
