### ISSUE TITLE
Freeform fin shape editor grid color should be light blue with darker blue index (see 15.03)

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#836]
In 15.03, the grid in the freeform fin set editor was light blue with a darker blue index line. In the current unstable, the grid is light gray with a darker gray index line. With a monochrome grid and fin display screen, it can sometimes be difficult to distinguish a fin line from the grid lines when the two are parallel.

The 15.03 light blue grid index line in the freeform fin set editor was much easier to see (distinguish from the fin lines), with a darker shade of the same color for the 1" index lines.

**Comment by neilweinstock** [comment]
I would just pick a better color, like the the old blue.  This doesn't need to be a user setting.
