### ISSUE TITLE
Freeform fin shape editor - fin lines should be a different color than the grid lines

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#838]
In the freeform fin set editor, It would be helpful if the fin lines were a different color than the grid, perhaps blue (or user selectable).

**Comment by neilweinstock** [comment]
This seems redundant to #836.  Once the grid color is changed, the fin lines will no longer be the same color as the grid lines, problem solved.

**Comment by hcraigmiller** [comment]
See comments of @neilweinstock in Issue #836.
