### ISSUE TITLE
Add more stage separation options

### ISSUE THREAD

**Issue by neutronium95** [openrocket/openrocket#852]
Some rockets come down in multiple segments, for example a nosecone that comes down on it's own parachute. This can be approximated by putting the nose and the associated parachute in a separate stage, but there isn't a good way to have them separate at apogee besides adjusting it to separate at a certain time in flight. Adding stage separation options for apogee and at a certain altitude during descent would make simulating complicated recovery systems with multiple sections much easier.

**Comment by RemingtonHolder** [comment]
I believe this is implemented correct?

**Comment by JoePfeiffer** [comment]
No, these options have not been added yet.  Definitely a good idea for the future, though.
