### ISSUE TITLE
3D display not rendering properly with display scaling (Windows 10)

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#854]
Although the 3D display after the recent merge is much better, it is still different than version 15.03.

![Differences Compare](https://user-images.githubusercontent.com/68821492/102699943-c609e280-41fd-11eb-872c-14fa54dce502.png)

In viewing what was intended, I looked back at the "_after_" screen shot in Issue #847 where the display appeared the same as Version 15.03, but the recent merge is not under Windows 10.

**Comment by hcraigmiller** [comment]
With regard to no 3D display on my Dell Inspiron with a Samsung 32" monitor, the following is the display information:

![Display Samsung Details All](https://user-images.githubusercontent.com/68821492/102707508-799bc280-4250-11eb-926b-02cc155eb7f6.png)

And, the comparison between the current unstable and 15.03 is this:

![Display Samsung Recommended 100 A Simple Rocket Both Versions](https://user-images.githubusercontent.com/68821492/102707626-810f9b80-4251-11eb-9526-097f25dbee46.png)

I have checked everything I know how to, no joy. I even uninstalled Java 11.0.8 and installed Java 11.0.9, still no joy.

Somehow Version 15.03 is getting it right, and the current unstable not so much. I hope this is helpful.

**Comment by wolsen** [comment]
So I think we're ultimately mixing a bunch of issues into the same report here. Various versions of this appear to have been reported in #720 and others. We should try to avoid mixing issues. As I see it, this particular issue is primarily about the scaling of the extra bits beyond just the rocket (altitude, motor selection, CG/CP carets).

I do not have a Windows computer so I will likely need some help debug and troubleshoot this. I have loaded Windows 10 inside a virtual machine but it does not have opengl support so I get no rendering of the 3d views.

**Comment by wolsen** [comment]
@hcraigmiller can you check the latest in unstable and report back on what works, what doesn't? I'm hoping the overlay bits (of text and carets) are resolved as well - but haven't been able to recreate these myself.

**Comment by hcraigmiller** [comment]
No change in any of the foregoing... should any of the above be spit off into individual issues?

**Comment by wolsen** [comment]
Let's split the two issues. I'll relabel this one for 3D renderings in Hi DPI scaling. Please raise a new issue for the lack of 3D renderings on your Samsung display.

**Comment by wolsen** [comment]
Okay I think I have this one figured out - but would like you to give it a test @hcraigmiller. I'll send you a jar file to test.
