### ISSUE TITLE
Adjust all freeform fin points color to be red (selected point color to be double red)

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#856]
See final comments of @neilweinstock in Issue #848.

![Fin Points](https://user-images.githubusercontent.com/68821492/102707938-1449d080-4254-11eb-9723-510a21390a83.png)

**Comment by wolsen** [comment]
So I'm not sure why it needs to be red other than "this is how it was in 15.03". It's a minor change, but the question is does this need to change? The grid lines I could easily understand as it was difficult to discern them.

**Comment by hcraigmiller** [comment]
Need... no. I believe that you could classify it as one of those "good, better, best" issues where a minor change has a benefit to a user. This was a carry-over issue mentioned by @neilweinstock in Issue #848.

**Comment by neilweinstock** [comment]
Having the points be a different color simply makes them easier to see.
The old color choices were good and effective.

It's not a big deal, though; the grid color was much more important from a
usability standpoint.

**Comment by wolsen** [comment]
> Having the points be a different color simply makes them easier to see. The old color choices were good and effective. It's not a big deal, though; the grid color was much more important from a usability standpoint.

This is the right reason I think - usability. Will change
