### ISSUE TITLE
Mass component radial displacement not shown in 3D view

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#859]
Side view:
![image](https://user-images.githubusercontent.com/243872/102902534-1f138980-443d-11eb-9206-7a6431dec7d1.png)

3D view:
![image](https://user-images.githubusercontent.com/243872/102902562-29358800-443d-11eb-9912-8112087c7950.png)

**Comment by hcraigmiller** [comment]
This issue is confirmed in Window 10 as to all components on the mass row, parachutes, streamers, and mass components of every mass type.

**Comment by neilweinstock** [comment]
Ah, interesting.  My guess is that recovery stuff is rarely positioned off-axis, so never noticed before.  There are good reasons to move mass components off center, though.

**Comment by hcraigmiller** [comment]
Radial offset is fixed as to all components on the mass row, except a "shock cord"; _the shock cord component is the only mass component that does not have a radial position tab_. 

The lack of a shock cord radial position tab may need to be a new issue.

**Comment by neilweinstock** [comment]
I don’t think lack of radial offset on shock cord is an issue.  No one is asking for it.
________________________________

**Comment by hcraigmiller** [comment]
Radial offset of shock cords is commonly done in complex high power rockets. Even though this is of minor significance, I mention it primarily because it is my general belief that all components of the same class should have similar options. Just my view.

**Comment by neilweinstock** [comment]
Fair enough. Doesn’t seem high priority, but a reasonable thing to do.
________________________________

**Comment by SiboVG** [comment]
@neilweinstock  This issue was fixed in #957 and merged into unstable, so the issue can be closed.

**Comment by neilweinstock** [comment]
Right you are.  Closing...
