### ISSUE TITLE
Confirm/Update "Bug report" transmission to location

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#860]
When a user makes a "Bug report" within OpenRocket, the location to which the report is being transmitted should be confirmed/updated.

**Comment by jimmiedave** [comment]
Testing on MacOS Catalina 10.15.7, with the Little Snitch network monitor up, upon submission of the report, I see no network activity (no attempt, no communication, no blocking) and an alert is raised:

_"OpenRocket was unable to send the bug report:
Connect Exception: Host is down (connect failed)

Please send the report manually to openrocket-bugs@lists.sourceforge.net"_

**NOTE:** this behavior differs from 15.03 on the same platform. That older version would raise an alert with"

_"IOException: Server responded with code 404, expecting 202"_

**Comment by neilbalch** [comment]
Hrm, I'm potentially interested in patching this. Should this somehow hook into a GitHub API for the issues tracker, if one exists? Or should it just direct people to the form to create a new issue and instruct them to copy/paste the bug report text?
