### ISSUE TITLE
Photo Studio: "Orbit" background shows up as black

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#861]
In both unstable at this writing, and in 15.03, choosing the "Orbit" background (this file in the jar: /datafiles/sky/space.jpg) results in a black background, behind the rendered rocket.

Testing on MacOS Catalina 10.15.7, on a 2020 16" MacBook Pro (Intel) with AMD Radeon Pro 5300M GPU.

Steps to repro:

Open example model "A simple model rocket" (or any other, I believe)
Open Photo Studio
Select "Environment" tab
From "Sky Image" droplist, select "Orbit"

Expected result:
Model renders over Orbit image

Actual result:
Model renders over black background.

**Comment by hcraigmiller** [comment]
Screen shot Windows 10, current unstable.

![Photo Studio Orbit](https://user-images.githubusercontent.com/68821492/102957988-bfdf6480-4490-11eb-9467-c7efba7d4f5c.png)

Screen shot Windows 10, Version 15,03.

![Photo Studio Orbit 15 03](https://user-images.githubusercontent.com/68821492/102958143-1f3d7480-4491-11eb-8994-a0c2b23313db.png)

What operating system is creating the issue?

**Comment by jimmiedave** [comment]
As noted above: MacOS Catalina 10.15.7

![Screen Shot 2020-12-22 at 11 22 37 PM](https://user-images.githubusercontent.com/35353530/102959342-338f6a80-44ad-11eb-8438-fbf7bc938813.png)
The other textures work fine. BTW, they appear to be various panos, where the Orbit shot does not.

![Screen Shot 2020-12-22 at 11 22 51 PM](https://user-images.githubusercontent.com/35353530/102959375-4b66ee80-44ad-11eb-94bf-ebc72918eff6.png)
Only difference here is that I've switched to the "Orbit" image.

I've tried a wide variety of monitor settings, thinking that maybe my 4K display ate too much VRAM or something, or that Apple's various 2X HiDPI resolutions might interfere. Nope. Get the same results at 640x480, same results on internal laptop monitor as external 4K.

**Comment by jimmiedave** [comment]
After a little investigation, all the textures split on power-of-2 boundaries, except Orbit, which is 1025x1024. I edited it in an image editor to a 1024 square, and it loads fine. Someone needs to trim the image (my trim was a rough experiment) and place it in the JAR, and this will work again.

**Comment by wolsen** [comment]
Odd. I don't see the problem in Ubuntu either. Must be limited to MacOS. If cropping the image to 1024x1024 square is all it takes, that's not much.

**Comment by neilweinstock** [comment]
Interesting, I have no problem with this in Mojave... on 15.03.  On the latest unstable, Photo Studio is still completely non-functional for me (permanent beach-ball). :(

**Comment by jimmiedave** [comment]
Do you have Intel graphics, or a proper GPU? Could make the difference.



DC

On December 27, 2020 8:03:58 PM EST, Neil Weinstock <notifications@github.com> wrote:
>Interesting, I have no problem with this in Mojave... on 15.03.  On the
>latest unstable, Photo Studio is still completely non-functional for me
>(permanent beach-ball). :(
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrocket/openrocket/issues/861#issuecomment-751539838

David Cain
sblkSoAR@jimmiedave.com
KM4NHQ
NAR L2 #100727
Eggfinder GPS 917MHz, ID3
2020 SoAR VP

**Comment by jimmiedave** [comment]
Do you have Intel graphics, or a proper GPU? That could make the difference in both cases.

DC

**Comment by neilweinstock** [comment]
I have a 2013 iMac with NVIDIA GeForce GT 750M 1 GB.

Photo Studio worked for me on the unstable branch until I migrated my hard drive from my internal Fusion drive to an external SSD.  Since then... nothing.  OR is the only program that I have identified as being affected.  No idea how to fix.

**Comment by jimmiedave** [comment]
Hmm. AMD/Nvidia difference? Driver problem?

Weird.

DC

On December 27, 2020 8:16:08 PM EST, Neil Weinstock <notifications@github.com> wrote:
>I have a 2013 iMac with NVIDIA GeForce GT 750M 1 GB.
>
>Photo Studio worked for me on the unstable branch until I migrated my
>hard drive from my internal Fusion drive to an external SSD.  Since
>then... nothing.  OR is the only program that I have identified as
>being affected.  No idea how to fix.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openrocket/openrocket/issues/861#issuecomment-751541472

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
