### ISSUE TITLE
Guided tours reference four other tours which are not supplied.

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#863]
Both the included guided tours reference other guided tours (by link, and text) that are not supplied. 

Missing:
"Viewing options" tour, linked from Introduction
"Simulating a flight" tour, linked from Introduction
"Preferences" tour, linked from Creating a simple rocket design
"defining motors" tour, linked from Creating a simple rocket design

Clicking links for these tours raises a dialog: "Sorry, the selected tour has not yet been written."

**Comment by SiboVG** [comment]
Fixed in #1433 and #1434
