### ISSUE TITLE
Fin tab length changes are referenced only to the top of the parent component

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#868]
Rather than referencing the change in length from the selected relative to position, the change is always referenced to the top of the parent component. The design file used is a Simple model rocket.

![00 Automatic](https://user-images.githubusercontent.com/68821492/103076214-0f518d80-4582-11eb-88ae-a53f3175d7ab.png)

Although only the trapezoidal fin has been used above, the same issue exists for all fin types, and for both fins on body tubes and fins on transitions.

**Comment by JoePfeiffer** [comment]
I think I know what I did on this one.  Unfortunately I'm not likely to be able to look at it in detail before the New Year.
