### ISSUE TITLE
RASAero import

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#875]
It would be good to be able to import (and export, though I see that as less important) designs in RASAero's format.

**Comment by hcraigmiller** [comment]
After the RASAero II data structure to the current unstable, I believe that it would be appropriate to split this one issue into two issues, a new feature to export an OpenRocket design in the RASAero II file format, and a separate new issue to import RASAero II designs into OpenRocket.

&bull; As to the export new feature, the RASAero II file format is very similar to that of the current unstable, though the variable names are different, and distances are measured in inches, not meters. It appears that all that is needed is a translator that (1) changes the variable names, (2) corrects the numerical values, if needed, and (3) removes excess data fields.

&bull; As to the import new feature, although RASAero II features 8 different fin cross-sections compared to the 3 in OpenRocket, in most other design features RASAero II lacks the component parameters that OpenRocket requires; for example, RASAero does not "position" rail buttons on the body tube, it simply puts 2 buttons on the body tube according to its own internal spacing parameters. This import feature, if even possible, will be much more complex than the export feature.

**Comment by JoePfeiffer** [comment]
Breaking it up into two issues seems very reasonable to me, not just because of the difficulties you mention but because the import and export code will be pretty completely separate.

But it's not something I want to think about until after final release of current unstable.
