### ISSUE TITLE
Transparency does not display correctly

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#878]
@ChrisMickelson (I think) added support for transparency a while back.  I am fairly certain it worked correctly in the past., which is to say that the alpha value was properly reflected in the object appearance in 3D views.  No longer, at least on my Mac running Mojave: now, any alpha value other than 255 displays exactly the same, e.g.:

Color = 0,0,0, 255
![image](https://user-images.githubusercontent.com/243872/104794760-cc956680-5777-11eb-9932-6fe105de3c96.png)

Color = 0,0,0, 254
![image](https://user-images.githubusercontent.com/243872/104794768-da4aec00-5777-11eb-88e7-b901e29b8053.png)

Color = 0,0,0, 0
![image](https://user-images.githubusercontent.com/243872/104794774-eafb6200-5777-11eb-9fe1-a11e1f1c1a86.png)

**Comment by ChrisMickelson** [comment]
Thanks Neil, I'll definitely take a look at that. I must have a sixth sense for these things - I have been out of the scene for years and then I get a feeling I should check how OR is doing. I might have to reorient myself to the current state of the project as it seems to have had some serious work done, which is inspiring to see.

**Comment by neilweinstock** [comment]
Hey, there you are. :)

I feel certain it used to work correctly, I recall tweaking the alpha channel to get some transparent fins to look just right in a past design.  Definitely misbehaving now, at least on my Mac; haven't been able to confirm on Windows.

**Comment by wolsen** [comment]
It took me awhile to confirm on Linux, because I wasn't even aware that there was a alpha/transparency option in the color chooser. Apparently, the Java Swing library's JColorChooser is still missing the transparency selector in the GTK (default) look and feel.

**Comment by neilweinstock** [comment]
I was also going to file an issue that we should copy how Rocksim handles transparency: a setting in the "Appearance" tab, along with "color" and "shine".  Having it available only as an alpha channel value inside the color picker is bad.  I realize that it was the easiest way to get it implemented, but from a user standpoint it's far from ideal.
