### ISSUE TITLE
Changes to the color picker should be reflected in real time

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#879]
When making changes to the color of a component, the 3D view is only updated after you close the color picker.  This is highly frustrating if you're experimenting.  The 3D view should be updated as changes are made in the picker, or at least within a second or two.

**Comment by SiboVG** [comment]
Normally fixed this issue, see #944

**Comment by neilweinstock** [comment]
Thank you thank you thank you
________________________________
