### ISSUE TITLE
Square fins Cd too high on model imported from RocketSim

### ISSUE THREAD

**Issue by soupwizard** [openrocket/openrocket#88]
Report from The Rocketry Forum, Kevin has been communicating with them, adding issue here to track.  http://www.rocketryforum.com/showthread.php?53242-Open-Rocket-sim-on-LPR-1-2-altitude-of-Rocksim

That thread has links to both the openrocket imported version of the model, and the source rocksim files.

**Comment by dkingsley** [comment]
I recommend this issue be close. Near the end of the reference TRF thread there is some flight data compared to OR and RS. OR is closer to the flight data than RS.

**Comment by neilweinstock** [comment]
Closing.
