### ISSUE TITLE
RockSim coversion error: Distance of fin relative to base/bottom reversed

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#881]
When RockSim measures a distance from the bottom of the component, distances toward the tip (to the left) have positive and distances toward the bottom (to the right) have negative values. In OpenRocket, the reverse is true. OpenRocket correctly inverses the distance for centering rings relative to the base/bottom of the component during conversion...

![Ring Placement](https://user-images.githubusercontent.com/68821492/104868465-45233100-58f8-11eb-8488-7bec282b7cf2.png)

But, during conversion, OpenRocket fails to inverse the distance for fins relative to the base/bottom of the component...

![Fin Placement](https://user-images.githubusercontent.com/68821492/104868679-f033ea80-58f8-11eb-8375-589816112f54.png)

This error results in the fin placement being reversed when relative to the base/bottom of the component.

**Comment by hcraigmiller** [comment]
As to this issue, OpenRocket properly converts to RockSim.

**Comment by jonnypjohnston** [comment]
I attached a screenshot of the imported file.

I opened the file in Rocksim, saved it out to a different file. Imported that file into OpenRocket.

![openrocket-import-rocksim-file](https://user-images.githubusercontent.com/3137489/119283188-3fbd5680-bc0a-11eb-91e7-a9ec3638dea3.png)
