### ISSUE TITLE
"Show Details" tab on motor selection panel hides "Compatible Cases" data after switching to a DMS

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#885]
Clicking through various motors with the "Show Details" pane up, in particular, looking for case compatibility (I'm prepping for a launch in a week), I click on an H73, which is an RMS reload, and I can see its case name and compatibility. I click on the next motor with my current filtering, an H100, which is a DMS. I click back to H73, everything's the same. I click back to the H100 and then back to the H73 again, and the panel has changed its width and the Case info had been truncated to an ellipsis, and the Compatible Cases info has disappeared (without visible truncation).

I then click on the H100 again and back to the H73 and the compatible case info reappears (and the pane changes to the previous width)

This looks related to the panel layout, but there's no adjustment possible to widen the Show Details pane manually - it stays the width it is when I resize the window to full screen, and there's nothing to grab and drag the pane wider.

Seems like a minor problem, but it makes it really difficult to quickly bop down the list looking for reloads for the cases I own. (a nice future feature would be to filter by compatible case).

Using Unstable
MacOS Catalina 10.15.7, 2020 16in MacBook Pro
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

<img width="448" alt="Normal" src="https://user-images.githubusercontent.com/35353530/106373442-7dd6f780-6347-11eb-90ac-f3ed0858263a.png">
<img width="396" alt="Broken" src="https://user-images.githubusercontent.com/35353530/106373443-80395180-6347-11eb-873a-0a9d49b2b43f.png">

**Comment by hcraigmiller** [comment]
Post 02/23/2021 merges, this error does not appear using Windows 10. I went back and forth 50+ times between the H100 (DMS) and the H73 (Case) and the window size did not change, nor did I lose the H73 case information. I also tried switching between an assortment of other motors up 20+ times each, both DMS and Case, and SU and Case types, and the window size did not change, nor did I lose the case information on case type motors.

**Comment by jimmiedave** [comment]
Same behavior with latest pull from unstable 2/23/2021. Same Mac as above.

Switched to adoptOpenJDK11 in the IDE (and the IntelliJ IDE console/log/whatever indicates this is what's being used this run):

https://youtu.be/jsTyCxU83UQ

**Comment by jimmiedave** [comment]
Just confirmed very similar, probably identical, behavior on Ubuntu 20.04.2 LTS, running on AMD Ryzen 3400G, 64-bit Linux.
for test clicks used G69 and G71R.

**Comment by jimmiedave** [comment]
In fiddling with 15.03 on Windows 7, I noted that while there are also no resizability controls in either 15.03 or unstable, the panels are never resized/re-layed-out in 15.03. It's possible that the re-sizing in unstable makes the difference old to new. Confirmed that on MacOS 15.03, no resize/layout of panels either.

**Comment by JoePfeiffer** [comment]
I'm also seeing similar behavior with latest unstable under Debian Linux, with Java version openjdk 15.0.2 2021-01-19

But... no case information at all in the panel in 15.03?

**Comment by jimmiedave** [comment]
git history shows that Kevin Ruland branched in 12/2015, added case info, merged back in 10/10/2016. So that change brings in CaseInfo, and probably the reformatting - apparently that dialog got refactored in the process.

MotorInformationPanel.java is what I'm looking at.

**Comment by jimmiedave** [comment]
Think I may have it: simple width of the JPanel is enough to prevent reformatting and remove this problem.

In MotorInformationPanel.java, line 219:

changing:

`			this.add(layer, "width 300:300:, height 180:180:, grow, spanx");`

to

`			this.add(layer, "width 400:400:, height 180:180:, grow, spanx");`

is enough to prevent line-breaks and rewrapping on the longest enums listed in CaseInfo.java - at least on my Mac.

Do I need some kind of permission to checkout, change, ask for test, merge back?

I'm a complete noob at collaborative projects with git, and have only really done Hello World with Java (though I code in a number of languages, know Python, have exposure to C, old 8-bit CPU assembly, lots of others)

**Comment by JoePfeiffer** [comment]
If we can find a way to strictly make the size depend on contents, it would be preferable.  It turns out that if we invalidate() the MotorInformationPanel when we update it, it will redraw and fit the contents.  I'm looking at tidying up the compatible cases display as well; PR will be incoming.

git is indeed a strange new world, and I expect to spend a long, long time getting used to git with github's enhancements.

That said, it requires no particular permissions to clone a repository (the closest thing in git to checking it out), create a new branch in your clone, or file a request that your new branch be merged back in to the main line (called filing a pull request).  Actually merging it in is the one thing that requires permissions.
