### ISSUE TITLE
Motor data: 29/40-120 casing shows up in modern reloads as 29/40

### ISSUE THREAD

**Issue by jimmiedave** [openrocket/openrocket#888]
Note the case descriptions for G53, G76, G64 and G138. These are all for the 29/40-120 case (I buy and use all of these regularly). The case shows up as 29/40. The outdated reloads below (see prior bug on filtering, whence came this image) show up with the proper designation.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/35353530/106373951-985f9f80-634c-11eb-8540-811ecb65183a.png">

Using Unstable
MacOS Catalina 10.15.7, 2020 16in MacBook Pro
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

**Comment by wolsen** [comment]
Looks like there must have been an error in the Thrustcurve.org data (I'm guessing maybe?). Just need to update the thrustcurves with the serialize-motors task in the core/build.xml file.

**Comment by JoePfeiffer** [comment]
This is probably a a real bug (not just requiring a database refresh).  I've been refreshing it pretty frequently, and I'm seeing the reported behavior. Coincidentally, I was just getting back to the motor stuff...

**Comment by JoePfeiffer** [comment]
I apologize, you are correct.
