### ISSUE TITLE
OpenRocket Jar will not launch

### ISSUE THREAD

**Issue by roguextech** [openrocket/openrocket#911]
Ubuntu 20.04
IntelliJ IDEA Community latest version
OpenJava JDK 11 -using
OpenJava JDK 13
Default JRE

Opened project, set JDK to 11, build. Copied jar to desktop. Checked the execute file in the file properties dialog.

Will not run. I've done this a few times before and had no issues.

When I run the project within IDEA, there is a message "failed to load Canberra-gtk-module".

I have reinstalled Ubuntu several times over the past week for other reasons. I always install IntelliJ just for OpenRocket-unstable purposes. This is the first time this has happened.

I can not figure out what is wrong. I have searched high and low using both Google and Bing...

**Comment by JoePfeiffer** [comment]
Presumably you have installed the libcanberra-gtk-module package?  On my Debian machine it's 

ii  libcanberra-gtk-module:amd64 0.30-7       amd64        translates GTK+ widgets signals to event sounds

**Comment by roguextech** [comment]
Well, I never installed it before and IntelliJ always built without issue.

I would copy the jar to the desktop and she'd run just dandy. I'll install the lib when I get home and report back. About an hourish...

**Comment by roguextech** [comment]
Installed the library via:

sudo apt install -y libcanberra-gtk-module-0.30-7

Rebuilt the jar, deleted the old jar, copied the new jar, checked the execute in the file properties dialog, still not running. WTF. I know it is something I did. LOL

I think I am going to delete the src, download a fresh copy ad start over. Just for the heck of it...

**Comment by JoePfeiffer** [comment]
Will it run outside IntelliJ using java -jar?  This is the point at which I start doing things like
strace java -jar .../OpenRocket.jar >& log
and looking for strings in the trace...

**Comment by roguextech** [comment]
I did that earlier and there was an error. Related to my java installation. Which of course I did not make a copy of. I was having other issues related to Jupyter and reset my Ubuntu notebook.

I will do that again and make notes if it fails...

**Comment by roguextech** [comment]
Joe,

See the attached log files. I copied and pasted your CLI example in -01, and just typed it in -02...

[log-01.txt](https://github.com/openrocket/openrocket/files/6251550/log-01.txt)
[log-02.txt](https://github.com/openrocket/openrocket/files/6251552/log-02.txt)

**Comment by roguextech** [comment]
I reset my Ubuntu notebook. I am thinking that when I did the ole "sudo apt autoremove" yesterday morning after another reset, that it deleted what ever libraries OpenRocket was looking for.

She is running just fine today. Attached is a screenshot...

![Screenshot from 2021-04-03 12-25-07](https://user-images.githubusercontent.com/55761077/113484789-2c96d180-9478-11eb-8d01-249eeec39479.png)

**Comment by JoePfeiffer** [comment]
Glad to hear it!   I had actually forgotten a critical option in that shell command, a -f so it would follow forks.  So for the benefit of somebody reading this some time in the future, it should have been
strace -f java -jar .../OpenRocket.jar >& log
But what I'm finding really weird is when I run OR on my Debian box, there's no sign of libcanberra!  So I'm just going to be happy the problem has gone away....

**Comment by roguextech** [comment]
Noted. Sorry abou that one. However, I do know now not to autoremove extra misc libs...

**Comment by JoePfeiffer** [comment]
Not a problem.
