### ISSUE TITLE
Wrong encoding for CSV export

### ISSUE THREAD

**Issue by Condzi** [openrocket/openrocket#912]
When exporting to CSV, units have question marks instead of actual unit. Please, add a possibility to select a proper encoding (so user can select if he/she wants to have questionmarks or actual units, in unicode or utf-8 or something).
The problem: (should be m/s^2)
![image](https://user-images.githubusercontent.com/15295570/114418079-74bd9e80-9bb2-11eb-92b6-fe98d9321820.png)

**Comment by neilbalch** [comment]
Heyo! I'm interested in patching this issue, but I can only seem to reproduce the issue with a plain text editor. _(I tested with VSCode)_ In OR 15.03 on Windows 10 with JRE 1.8.0, Excel reads the CSV in "properly" with the squared character. Could you describe what your computer setup is and what kind of unit representation/format you'd like to see?

![image](https://user-images.githubusercontent.com/3847882/117757760-8c01a300-b1d5-11eb-9f4e-1cdbdfe08e1d.png)

![image](https://user-images.githubusercontent.com/3847882/117757927-d7b44c80-b1d5-11eb-8de2-3b6dc9248165.png)

**Comment by Condzi** [comment]
Hello! Thanks for answering.
Unfortunately, I couldn't get it to work with Excel:
![image](https://user-images.githubusercontent.com/15295570/117767216-eb40d100-b230-11eb-8aae-af105926a43a.png)
I'm on Windows 10 Pro with following language settings:
![image](https://user-images.githubusercontent.com/15295570/117767333-14f9f800-b231-11eb-969c-3090c66ec552.png)
OR 15.03, Java:
![image](https://user-images.githubusercontent.com/15295570/117767550-60140b00-b231-11eb-98b5-9728b99464cb.png)
I tried Arial and Consolas fonts, but I still only see the `?`. 
Could you send me the CSV file you're using? Just to see if that's OR issue, or if the issue is on my part. Here's mine (exported from simple rocket example, or something like that)
[csv_files_issue.zip](https://github.com/openrocket/openrocket/files/6456923/csv_files_issue.zip)
> Could you describe what your computer setup is and what kind of unit representation/format you'd like to see?

I would love to see something parser-friendly, maybe just like an additional option when exporting. For example, instead `Lateral acceleration (m/s²)` (which is locale dependent, IIRC), just `ACC_LATERAL METERS_PER_SECOND_SQUARED`. This way the parsing would be easier, I wouldn't have to care about different languages, and I would have just clear structure of `value unit;value unit; value_unit`.

**Comment by neilbalch** [comment]
Curious! This is the one I exported from my machine:
[test.zip](https://github.com/openrocket/openrocket/files/6457106/test.zip)

Manually rename it to `test.csv` before opening; GitHub will only let me upload it if it's a `.zip`, lol.

**Comment by neilbalch** [comment]
Also, does this one render properly for you?
[test-unicode..zip](https://github.com/openrocket/openrocket/files/6457226/test-unicode.zip)

I manually replaced all of the "squared" characters with the [corresponding unicode superscript](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) character. I also replaced the degree sign in one of the header items. If this works, I'll try to get a patch PR out soon. _(when my school midterms cool down, lol)_

Also, I noticed that  there are some literal `?` unit designations for a couple of columns at the end: `...Stability margin calibers (?),Mach number (?),Reynolds number (?)...`. Maybe worth investigating whether these are indeed unit-less scalar values or if they do have designations to be added. 🤷‍♂️

**Comment by neilbalch** [comment]
> 
> 
> Backing up a step, we've pretty much stopped developing for 15.03 -- all our efforts now are devoted to getting the new release out the door. Are you able to check whether the problem still exists in the current unstable source tree?

Excel reads the header line created by the current unstable branch correctly, just like in 15.03, but VSCode sees the "unicode symbol not found" question mark character. i.e. the issue remains in the current codebase.

**Comment by neilbalch** [comment]
> 
> 
> Here's how the `test.csv` from the first comment looks like (different characters than in my file? weird):
> ![image](https://user-images.githubusercontent.com/15295570/117777962-6c05ca00-b23d-11eb-9535-a73de5eba4d3.png)
> But opening it with `Windows 1252` encoding (suggested by VS code` looks correct:
> 
> ![image](https://user-images.githubusercontent.com/15295570/117779438-f8fd5300-b23e-11eb-8beb-e9a15a973344.png)
> Just to clarify -- opening my own file (directly after exporting to .csv, without opening it in Excel first) still gives `?` instead `²`.
> 
> `test-unicode.csv` looks good in VS Code:
> ![image](https://user-images.githubusercontent.com/15295570/117778283-c30b9f00-b23d-11eb-9019-da1c3564ee60.png)
> Excel fails to recognize the encoding, I guess:
> ![image](https://user-images.githubusercontent.com/15295570/117778527-05cd7700-b23e-11eb-94d0-98ce55a4815e.png)
> I think that `?` means a scalar value, since it appears next to coefficients for me. Maybe `scalar` instead `?` would be more fitting there.

Hrm, interesting. I'm actually quite surprised that Excel doesn't read the regular unicode character properly... I'm encouraged by VSCode understanding it, though.

As for the unit-less scalars, I'm in favor of changing them from `?` to `N/A` to indicate that they have no units. This is assuming that the parenthetical unit specification is a mandatory part of the header line template. I haven't found the relevant code yet, so IDK.
