### ISSUE TITLE
Bug: Fin tabs move when scaling the rocket

### ISSUE THREAD

**Issue by raketenolli** [openrocket/openrocket#925]
If a fin (I tried trapezoid and freeform) has a fin tab that is offset relative to the "center of the parent component" (which, observing the placement of the tab, is probably not even the right wording – at least in the German translation – because it's relative to the fin root), and then the rocket is scaled to e.g. 200 % its original size, the fin tab moves relative to the fin root by a significant amount:
![fin-tab-moves](https://user-images.githubusercontent.com/14631918/118392963-a657d880-b63c-11eb-86c6-2d5ad3eab456.png)

I would expect the tab to remain where it was relative to the fin root, with the offset adequately scaled.

**Comment by hcraigmiller** [comment]
See also, bugs #865 and #868, and new feature request #829.

**Comment by hcraigmiller** [comment]
This issue, Issue #925, resolved with the fix of Issue #868. This issue should be closed.
