### ISSUE TITLE
Motor selection dialog responsive layout issues

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#926]
When the motor selection dialog is minimum size:
![image](https://user-images.githubusercontent.com/243872/118981950-ed014780-b948-11eb-83c5-0f965f0fa26c.png)

When the dialog is made taller:
![image](https://user-images.githubusercontent.com/243872/118982124-1ae68c00-b949-11eb-8edf-7ebd56041ebd.png)

Note that the "Select thrust curve" and "Ejection charge delay" pickers and the motor list are have spread apart from each other.  The way this should work is that those three elements remain close together (as in the first screenshot), and all addition window height is consumed by making the motor list are taller.  That is, it should look more like this:
![image](https://user-images.githubusercontent.com/243872/118983400-63527980-b94a-11eb-8636-6f1676bd6720.png)

Similarly, the Manufacturer list stops expanding after a while and the entire right column moves down from the top.  It seems to me like right column should stay in place (top-justified), and the Manufacturer list area should expand to consume all additional space.

**Comment by hcraigmiller** [comment]
The following issues relate to the "Select a rocket motor" tab: #877 and #627.
