### ISSUE TITLE
Auto-run simulations does not correctly run loaded motor

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#927]
![Motor Simulation Loaded Motor Text](https://user-images.githubusercontent.com/68821492/119280850-125fb100-bbe8-11eb-9c44-bacacab3ddd6.png)

[Pike XL.Madcow.zip](https://github.com/openrocket/openrocket/files/6529132/Pike.XL.Madcow.zip)

May be related to issues: #771 and #915.

**Comment by SiboVG** [comment]
Might be fixed with #952

**Comment by neilweinstock** [comment]
@hcraigmiller can you check on this with Sibo's latest in PR #952?  I suspect it's all part of the same thing.

**Comment by hcraigmiller** [comment]
See comment in PR #952.
