### ISSUE TITLE
Bug: Launch lug distance to a reference point does not change when the reference point is changed

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#928]
Launch lug components **DO NOT** correctly calculate the component distance to a changed reference point (the distance to a reference point does not change when the reference point is changed).

_I will post specific screenshots and files to show the errors._

* Conversions from Trapezoidal and Elliptical to Freeform fins _may not be_ consistent with the original fin. More testing will be done and further specifics posted.

**Comment by hcraigmiller** [comment]
LAUNCH LUGS:
Using the _A simple model rocket_ example file, the distance between the launch lug component and a reference point does not change when the reference point is changed.

![TipNosecone LaunchLug](https://user-images.githubusercontent.com/68821492/119424673-c03b9000-bcba-11eb-95b2-9e90b6eeb6c0.png)

**Comment by neilbalch** [comment]
I'm not sure I follow... The render appears to show the correct position in all frames, but the numerical position in the configuration dialog shows `0` for them all. Is the latter the issue at play here in your report?

**Comment by hcraigmiller** [comment]
If you were to use a 10" long tube and place a 1" long launch lug in the center of the tube, the reference from the middle would be 0", from the top would be 4.5", and from the bottom would be -4.5". As the screenshots above show, as you move from the middle to any other reference point, the distance does not change. In other words, no matter what reference point you select, the _Middle of the parent component_  is always the actual reference point from which the component distance is calculated and displayed.

**Comment by hcraigmiller** [comment]
CONVERSIONS TO FREEFORM FINS
Conversions from Trapezoidal and Elliptical to Freeform fins are not consistent with the original fin dimensions at very small length values, values of > .004".  While this is a bug, it is inconceivable that it would ever be an actual issue in real life. My only concern is that it may evidence a procedural or computational error that goes beyond this manifestation.

**Comment by neilbalch** [comment]
I think this is probably due to a separate issue? Not sure, but it sounds distinct from the original position reference bug.

**Comment by hcraigmiller** [comment]
If you are referring to the conversion to freeform fins, I agree. I will be separating it out to a new issue for future resolution or simply an FYI in case something related is also found.

**Comment by SiboVG** [comment]
See #946, this might have fixed it.
