### ISSUE TITLE
Hi-DPI problem in 3D display on Mac

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#929]
This may or may not also be a problem on Windows or Linux, hopefully someone else can confirm.  Tested on a pretty recent Unstable build.

Here's the "simple model rocket" in side view on a Retina display:
![image](https://user-images.githubusercontent.com/243872/119427883-e290d600-bcd9-11eb-8b8d-07cf9010b6da.png)
Looks good.

Here's the 3D finished view:
![image](https://user-images.githubusercontent.com/243872/119427999-1c61dc80-bcda-11eb-9394-6cc09eb96b9e.png)
Problems.  The design info in the four corners is behaving as if it doesn't know about hi-DPI display, and the CG/CP markers are off in la-la land.

**Comment by hcraigmiller** [comment]
May be related to issues #864, #854, #720, and #719.

**Comment by wolsen** [comment]
@neilweinstock any chance you can test with the PR from https://github.com/openrocket/openrocket/pull/866 ?

**Comment by neilweinstock** [comment]
Just tried it, looks good!

**Comment by wolsen** [comment]
This was was fixed with merge for PR #866
