### ISSUE TITLE
3D Part Selection Broken with commit 7015d861

### ISSUE THREAD

**Issue by wolsen** [openrocket/openrocket#937]
The switch to GLJPanel + FBO Caps with commit 7015d861 breaks part selection in the 3d model.

This part of the patch should be reverted.

**Comment by hcraigmiller** [comment]
In Windows 10 with Java version 11.0.9 2020-10-20 LTS, selecting a part using the tree highlight the part on the 3d model, and a left click anywhere in the 3d display window (on or off the model) deselects a selected part. You cannot select a part by left-clicking the part in the 3d window.
