### ISSUE TITLE
Artifacts in 3D Finished view on Mac

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#965]
Running latest unstable on an M1 Mac, Big Sur.

Here's what the "Apocalypse" sample rocket looks like in 3D finished view:
![artifacts](https://user-images.githubusercontent.com/243872/123721896-40728980-d855-11eb-8066-70662057d84e.png)

Note the areas in the red boxes.  In each case an inner coupler or shoulder is showing through and causing artifacts.  These do not appear in 15.03.

**Comment by hcraigmiller** [comment]
Current unstable.

![Apocalypse 6_28_2021 6_45_28 PM](https://user-images.githubusercontent.com/68821492/123724424-2af36480-d841-11eb-8d81-316573d64bd2.png)
![Apocalypse 6_28_2021 6_46_54 PM](https://user-images.githubusercontent.com/68821492/123724510-524a3180-d841-11eb-925b-ada5dd67ae82.png)

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]

**Comment by neilweinstock** [comment]
I can no longer reproduce this on the latest unstable builds.

Since I'm the only on who ever saw it in the first place, I'm just going to close it now.
