### ISSUE TITLE
Bad highlight colors on Mac

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#968]
This problem was present in 15.03, never got around to reporting it.  Currently running on an M1 Mac on Big Sur.

Certain UI elements are colored with a very dark highlight color, rendering the contained black text unreadable.  E.g.:
![image](https://user-images.githubusercontent.com/243872/123879325-c0a8f580-d90e-11eb-8838-b6d805dbb3a1.png)

Same on the delete confirmation dialog:
![image](https://user-images.githubusercontent.com/243872/123879721-6f4d3600-d90f-11eb-900c-a4a8cacd4ec0.png)

There may be others; these are the ones I was able to find quickly.

Elsewhere in the OS, when UI elements are highlighted with this color, the text is set to white to make it readable.

**Comment by SiboVG** [comment]
Can confirm this problem on Macbook Air 2015, on Big Sur.

**Comment by hcraigmiller** [comment]
Compare...

![Text](https://user-images.githubusercontent.com/68821492/123906228-a0863000-d928-11eb-9f20-bd65723c4156.png)

[OS Windows 10 Pro service pack 120.2212.2020.0 with Java version 11.0.9 2020-10-20 LTS]
