### ISSUE TITLE
How to run OpenRocket unit tests using Ant via the Terminal?

### ISSUE THREAD

**Issue by phao5814** [openrocket/openrocket#985]
The [Wiki](https://github.com/openrocket/openrocket/wiki/Instructions-to-Build-from-Terminal) does a great job explaining how to build OpenRocket via `ant`; however, unfortunately, it doesn't really contain any information on running unit tests via the terminal.

Unfortunately, my current experience with running Ant unit tests for both the `master` and `unstable` branch is problematic as follows:

When I run the following command in my terminal to run the unit tests in the `core` module:

`ant unittest-core`

I get the following failed tests:

```
    [junit] Testcase: testExpressions took 0.001 sec
    [junit] Testsuite: net.sf.openrocket.simulation.extension.impl.TestScriptingUtil
    [junit] Tests run: 7, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.017 sec
    [junit]
    [junit] Testcase: testGetLanguages took 0.005 sec
    [junit] 	FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit] 	at net.sf.openrocket.simulation.extension.impl.TestScriptingUtil.testGetLanguages(TestScriptingUtil.java:41)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit]
    [junit] Testcase: testClearTrustedScripts took 0.002 sec
    [junit] Testcase: testHash took 0.002 sec
    [junit] Testcase: testSetTrustedScript took 0.002 sec
    [junit] Testcase: testGetLanguage took 0.001 sec
    [junit] 	FAILED
    [junit] expected:<JavaScript> but was:<null>
    [junit] junit.framework.AssertionFailedError: expected:<JavaScript> but was:<null>
    [junit] 	at net.sf.openrocket.simulation.extension.impl.TestScriptingUtil.testGetLanguage(TestScriptingUtil.java:32)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
Below is the HTML output for everyone's convenience:
![image](https://user-images.githubusercontent.com/23574714/126271425-38f67f57-a769-4a6d-b0ae-6a3eb6126bfa.png)

However, when I go to the `TestScriptingUtil` class to run the unit test via the GUI in Intellij, the tests pass with no issues as shown below:

![image](https://user-images.githubusercontent.com/23574714/126271705-9c97ce4e-557a-4f6c-8c36-21736b8b6c2e.png)

Furthermore, if I run the `unittest-core` Ant job via the Intellij GUI, the tests also pass without a hitch:

![image](https://user-images.githubusercontent.com/23574714/126271875-1ed3166d-0169-46ef-9458-18b723da2988.png)

I've set my Intelliji Java version to 11 as shown below:

![image](https://user-images.githubusercontent.com/23574714/126272027-a95d3bf2-336f-490c-abbf-aba3d773c9b9.png)

I have a hunch that the reason why the unit tests are failing is down to a mismatch in the version of Java used by Ant in the CLI and the version of Java used by Ant when called by Intellij. Another piece of evidence that points to this hypothesis is that the two failing tests seem to be related to the fact that the Java runtime Ant is running in the terminal does not support JavaScript scripting (but the Intellij Java runtime does support JavaScript).

I've tried various things by modifying the `core/build.xml` file to force Ant to use my Java 11's `javac` as per StackOverflow posts like [this one](https://stackoverflow.com/a/11551770/7489488). However, I haven't been able to find a fix. This is probably down to my inexperience with Ant; however, there could be a chance there is another problem thats causing this.

Nonetheless, I was hoping someone could help me get to the bottom of this. The issue should be fairly easy to replicate.

1. Clone OpenRocket repo.
2. Checkout either `unstable` or `master` branch.
2. Install Ant - I'm using version 1.10.11.
3. Run `ant unittest-core`.

If this is a known issue and there is a known fix, this might be worth documenting in the Wiki. I'm happy to write something up once I can figure out what the problem is.

**Comment by SiboVG** [comment]
The error in the unit tests is fixed in #1507. I also updated the [wiki documentation](https://github.com/openrocket/openrocket/wiki/Instructions-for-running-unit-tests) on running unit tests.
