### ISSUE TITLE
Bad modal dialog button colors on Mac

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#988]
On the Mac, the default button in modal system dialogs is shown with black text on dark background:
![image](https://user-images.githubusercontent.com/243872/128189541-7ad9a424-2673-4cb1-8c00-c05a45d9dd02.png)

This is the last remnant of #968, the rest of which was fixed.

**Comment by SiboVG** [comment]
Fixed with the introduction of the FlatLaf LAF (I can't find the PR for it, but I pushed the code for it a couple of months ago).

**Comment by neilweinstock** [comment]
Hooray! :)
