### ISSUE TITLE
Bug: Photo Studio flame and spark Effect no longer display correctly in Windows 10 Pro

### ISSUE THREAD

**Issue by hcraigmiller** [openrocket/openrocket#997]
Beginning with OpenRocket-954-jkl1.jar dated 07/02/2021, and post 07/11/2021 merge, the Photo Studio flame and spark effects no longer display correctly in Windows 10 Pro.
![0000 Photo Studio Flame](https://user-images.githubusercontent.com/68821492/130323615-1e5f329e-3fa4-4d45-99c4-ca46342359ee.png)

A similar error may be what is causing the smoke effect not to function as well (see Issue #874).

**Comment by SiboVG** [comment]
So the issues are related to #967? Do you also have an idea of a merge date after which #874 started showing up?

**Comment by hcraigmiller** [comment]
I don't. My records only go back to the 11/03/2020 merge and it existed from and after that date, but I don't know if it existed before that date.

**Comment by hcraigmiller** [comment]
This bug occurs **only if there is more than one stage**, even if the other stages have no components, **and then only if the motor is NOT in the upper most stage**. 

For example:
   1. If Upper Stage then Motor Stage then Flame is a glow not a flame.
   2. If Motor Stage then Lower Stage the Flame is a flame not a glow.
  
Regardless of how may stages there are, there must be a motor in the upper stage for the Flame to be a flame instead of a glow. **This is the opposite of what it should be**; if the lowest stage has a motor, the Flame should be a flame, not a glow.

The non-functional smoke issue is separate and unrelated.

**Comment by SiboVG** [comment]
> This bug occurs only if there is more than one stage, even if the other stages have no components, and then only if the motor is NOT in the upper most stage.

Aha! At last I am able to recreate this issue. Indeed, I tested it with 'A simple model rocket' and with 'Three-staged rocket'. The former displays the flame and sparks, the latter not. If you look closely at the image, you see that the smoke of 'Three-staged rocket' starts somewhere in the middle of the rocket. If you also increase the aspect ratio of the flame, eventually it pokes out of the bottom of the rocket.
<img width="1724" alt="Screenshot 2022-01-11 at 21 20 55" src="https://user-images.githubusercontent.com/11031519/149015679-6d64e662-29bc-46fd-9b09-1ee013b31779.png">

So the starting point of the smoke, flame and sparks is not at the right motor.
